/* The milestone-2 scene from C, on the kaya bindings: kaya_wire.h
 * (generated by kaya-bindgen from kaya::spec) carries the packers and
 * the occurrence parser; what remains here is the scene declaration and
 * the logic answering occurrences. The main thread enters kaya_run()
 * and becomes the core's UI thread; a pthread is the app thread.
 *
 * Built and run by the Linux container suite (tools/linux/run-suites.sh),
 * where a plain cc and the shared library are both at hand; add
 * -I bindings/c alongside -I crates/kaya/include. */

#include <kaya.h>
#include <kaya_wire.h>

#include <pthread.h>
#include <stdio.h>

/* Guest-allocated ids, counted from 1 per space. */
#define SIG_STATUS 1
#define SIG_EXTRAS 2
#define W_COLUMN 1
#define W_STEP 2
#define W_STATUS 3
#define W_WHEN 4
#define W_FOR_GROUPS 5
#define C_GROUPS 1
#define C_ITEMS 2
#define N_BANNER 1
#define N_GROUP_COL 2
#define N_GROUP_NAME 3
#define N_ITEMS_FOR 4
#define N_ITEM_ROW 5
#define N_ITEM_TEXT 6
#define N_REMOVE 7

static void build_scene(void) {
    uint8_t buf[2048];
    KayaTx tx = {buf, 0};

    kaya_tx_create_signal(&tx, SIG_STATUS, kaya_str("step 0"));
    kaya_tx_create_signal(&tx, SIG_EXTRAS, kaya_bool(0));
    kaya_tx_create_widget(&tx, W_COLUMN, KAYA_KIND_COLUMN);
    kaya_tx_create_widget(&tx, W_STEP, KAYA_KIND_BUTTON);
    kaya_tx_set_text(&tx, W_STEP, "step");
    kaya_tx_create_widget(&tx, W_STATUS, KAYA_KIND_LABEL);
    kaya_tx_bind_text(&tx, W_STATUS, SIG_STATUS);

    /* When(extras): a banner label. The scope brackets the blueprint. */
    kaya_tx_create_when(&tx, W_WHEN, SIG_EXTRAS);
    kaya_tx_create_widget(&tx, N_BANNER, KAYA_KIND_LABEL);
    kaya_tx_set_text(&tx, N_BANNER, "extras on");
    kaya_tx_template_end(&tx);

    /* For over groups, nesting a For over items. */
    kaya_tx_create_collection(&tx, C_GROUPS,
                              (KayaVariantSchema[]){{(uint32_t[]){KAYA_VALUE_STR}, 1}}, 1);
    kaya_tx_create_for(&tx, W_FOR_GROUPS, C_GROUPS);
    kaya_tx_create_widget(&tx, N_GROUP_COL, KAYA_KIND_COLUMN);
    kaya_tx_create_widget(&tx, N_GROUP_NAME, KAYA_KIND_LABEL);
    kaya_tx_bind_text_element(&tx, N_GROUP_NAME, 0, 0);
    kaya_tx_add_child(&tx, N_GROUP_COL, N_GROUP_NAME);
    kaya_tx_create_collection(&tx, C_ITEMS,
                              (KayaVariantSchema[]){{(uint32_t[]){KAYA_VALUE_STR}, 1}}, 1);
    kaya_tx_create_for(&tx, N_ITEMS_FOR, C_ITEMS);
    kaya_tx_create_widget(&tx, N_ITEM_ROW, KAYA_KIND_COLUMN);
    kaya_tx_create_widget(&tx, N_ITEM_TEXT, KAYA_KIND_LABEL);
    kaya_tx_bind_text_element(&tx, N_ITEM_TEXT, 0, 0);
    kaya_tx_create_widget(&tx, N_REMOVE, KAYA_KIND_BUTTON);
    kaya_tx_set_text(&tx, N_REMOVE, "remove");
    kaya_tx_add_child(&tx, N_ITEM_ROW, N_ITEM_TEXT);
    kaya_tx_add_child(&tx, N_ITEM_ROW, N_REMOVE);
    kaya_tx_template_end(&tx);
    kaya_tx_add_child(&tx, N_GROUP_COL, N_ITEMS_FOR);
    kaya_tx_template_end(&tx);

    kaya_tx_add_child(&tx, W_COLUMN, W_STEP);
    kaya_tx_add_child(&tx, W_COLUMN, W_STATUS);
    kaya_tx_add_child(&tx, W_COLUMN, W_WHEN);
    kaya_tx_add_child(&tx, W_COLUMN, W_FOR_GROUPS);
    kaya_tx_mount(&tx, 0, W_COLUMN); /* window 0: the default */

    kaya_submit(tx.buf, tx.len);
}

static void *app(void *arg) {
    (void)arg;
    build_scene();
    unsigned steps = 0;
    /* C takes the function floor by decision: no binding-owned model,
     * so the app keeps its own item counts alongside the deltas it
     * sends — hand-rolled bookkeeping is C's idiom. */
    unsigned items_in[2] = {0, 0}; /* [0]: g1, [1]: g2 */
    uint8_t rec[256];
    for (;;) {
        size_t size = kaya_next_occurrence(rec, sizeof rec);
        if (size == 0)
            break; /* shutdown */
        uint64_t id;
        KayaVal keys[2];
        uint32_t n_keys;
        if (!kaya_parse_click(rec, &id, keys, 2, &n_keys))
            continue;
        if (n_keys == 0 && id == W_STEP) {
            steps += 1;
            uint8_t buf[1024];
            KayaTx tx = {buf, 0};
            KayaVal g1 = kaya_str("g1");
            KayaVal g2 = kaya_str("g2");
            if (steps == 1) {
                kaya_tx_collection_insert(&tx, C_GROUPS, 0, 0, kaya_str("g1"), 0,
                                          (KayaVal[]){kaya_str("Work")}, 1);
                kaya_tx_collection_insert(&tx, C_ITEMS, &g1, 1, kaya_str("a"), 0,
                                          (KayaVal[]){kaya_str("send report")}, 1);
                kaya_tx_collection_insert(&tx, C_ITEMS, &g1, 1, kaya_str("b"), 0,
                                          (KayaVal[]){kaya_str("buy milk")}, 1);
                items_in[0] = 2;
            } else if (steps == 2) {
                kaya_tx_collection_insert(&tx, C_GROUPS, 0, 0, kaya_str("g2"), 0,
                                          (KayaVal[]){kaya_str("Home")}, 1);
                kaya_tx_collection_insert(&tx, C_ITEMS, &g2, 1, kaya_str("a"), 0,
                                          (KayaVal[]){kaya_str("water plants")}, 1);
                kaya_tx_collection_update(&tx, C_GROUPS, 0, 0, kaya_str("g1"), 0,
                                          (KayaVal[]){kaya_str("Office")}, 1);
                items_in[1] = 1;
            }
            char status[32];
            snprintf(status, sizeof status, "step %u", steps);
            kaya_tx_write_signal(&tx, SIG_EXTRAS, kaya_bool(steps == 1));
            kaya_tx_write_signal(&tx, SIG_STATUS, kaya_str(status));
            kaya_submit(tx.buf, tx.len);
        } else if (n_keys == 2 && id == N_REMOVE) {
            uint8_t buf[512];
            KayaTx tx = {buf, 0};
            kaya_tx_collection_remove(&tx, C_ITEMS, &keys[0], 1, keys[1]);
            unsigned *left = &items_in[keys[0].s_len == 2 && keys[0].s[1] == '2'];
            *left -= 1;
            char status[160];
            snprintf(status, sizeof status, "removed %.*s/%.*s, %u left",
                     keys[0].s_len, keys[0].s, keys[1].s_len, keys[1].s, *left);
            kaya_tx_write_signal(&tx, SIG_STATUS, kaya_str(status));
            kaya_submit(tx.buf, tx.len);
        }
    }
    return NULL;
}

int main(void) {
    /* The stale-artifact guard: this guest compiled against one spec
     * revision; the loaded library must speak the same one. */
    if (kaya_spec_hash() != KAYA_SPEC_HASH) {
        fprintf(stderr, "kaya: library/binding spec mismatch — rebuild both\n");
        return 1;
    }
    pthread_t app_thread;
    pthread_create(&app_thread, NULL, app, NULL);
    return kaya_run(); /* takes over the main thread until the app exits */
}
