// kaya wire vocabulary. Generated by kaya-bindgen from kaya::spec — do not edit.
//
// Records are {u32 size, u16 kind, u16 flags}, body, padded to 8,
// little-endian. Values accept Boolean, Long, Double, String, and
// BlobHandle, mapped to the kaya value types; keys in paths likewise.
package dev.kaya;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;

public final class KayaWire {
    /** SPEC_HASH: the protocol fingerprint; the runtime asserts the loaded core agrees. */
    public static final long SPEC_HASH = 0xecc906b893ee37aeL;

    public static final int VALUE_BOOL = 1;
    public static final int VALUE_I64 = 2;
    public static final int VALUE_F64 = 3;
    public static final int VALUE_STR = 4;
    public static final int VALUE_BLOB = 5;
    public static final int KIND_COLUMN = 1;
    public static final int KIND_BUTTON = 2;
    public static final int KIND_LABEL = 3;
    public static final int KIND_ENTRY = 4;
    public static final int KIND_ROW = 5;
    public static final int KIND_CHECKBOX = 6;
    public static final int KIND_SLIDER = 7;
    public static final int KIND_IMAGE = 8;
    public static final int PROP_TEXT = 1;
    public static final int PROP_CHECKED = 2;
    public static final int PROP_VALUE = 3;
    public static final int PROP_MIN = 4;
    public static final int PROP_MAX = 5;
    public static final int PROP_SOURCE = 6;
    public static final int PROP_GROW = 7;
    public static final int PROP_SPACING = 8;
    public static final int PROP_ALIGN = 9;
    public static final int WPROP_TITLE = 1;
    public static final int WPROP_WIDTH = 2;
    public static final int WPROP_HEIGHT = 3;
    public static final int WPROP_VETO_CLOSE = 4;
    public static final int ALIGN_START = 0;
    public static final int ALIGN_CENTER = 1;
    public static final int ALIGN_END = 2;
    public static final int ALIGN_STRETCH = 3;
    public static final int ALIGN_BASELINE = 4;
    public static final int SOURCE_CONST = 0;
    public static final int SOURCE_SIGNAL = 1;
    public static final int SOURCE_ELEMENT = 2;
    public static final int OCCURRENCE_PAD = 0;
    public static final int OCCURRENCE_BUTTON_CLICKED = 1;
    public static final int OCCURRENCE_TEXT_CHANGED = 2;
    public static final int OCCURRENCE_TOGGLED = 3;
    public static final int OCCURRENCE_VALUE_CHANGED = 4;
    public static final int COMMAND_CLEAR = 1;
    public static final int COMMAND_FOCUS = 2;
    public static final short TX_KIND_CREATE_SIGNAL = 1;
    public static final short TX_KIND_WRITE_SIGNAL = 2;
    public static final short TX_KIND_CREATE_WIDGET = 3;
    public static final short TX_KIND_SET_PROPERTY = 4;
    public static final short TX_KIND_ADD_CHILD = 5;
    public static final short TX_KIND_MOUNT = 6;
    public static final short TX_KIND_CREATE_COLLECTION = 7;
    public static final short TX_KIND_COLLECTION_INSERT = 8;
    public static final short TX_KIND_COLLECTION_UPDATE = 9;
    public static final short TX_KIND_COLLECTION_REMOVE = 10;
    public static final short TX_KIND_CREATE_FOR = 11;
    public static final short TX_KIND_CREATE_WHEN = 12;
    public static final short TX_KIND_TEMPLATE_END = 13;
    public static final short TX_KIND_COLLECTION_MOVE = 15;
    public static final short TX_KIND_COLLECTION_UPDATE_FIELD = 14;
    public static final short TX_KIND_VARIANT_CASE = 16;
    public static final short TX_KIND_WIDGET_COMMAND = 17;
    public static final short TX_KIND_SET_WINDOW_PROP = 18;
    public static final short TX_KIND_CREATE_WINDOW = 19;
    public static final short TX_KIND_DESTROY_WINDOW = 20;
    public static final short APPLY_KIND_CREATE = 1;
    public static final short APPLY_KIND_SET_PROP = 2;
    public static final short APPLY_KIND_ADD_CHILD = 3;
    public static final short APPLY_KIND_MOUNT = 4;
    public static final short APPLY_KIND_MOVE_CHILD = 6;
    public static final short APPLY_KIND_DESTROY = 5;
    public static final short APPLY_KIND_COMMAND = 7;
    public static final short APPLY_KIND_SET_WINDOW_PROP = 8;
    public static final short APPLY_KIND_CREATE_WINDOW = 9;
    public static final short APPLY_KIND_DESTROY_WINDOW = 10;
    public static final short OCC_KIND_BUTTON_CLICKED = 1;
    public static final short OCC_KIND_TEXT_CHANGED = 2;
    public static final short OCC_KIND_TOGGLED = 3;
    public static final short OCC_KIND_VALUE_CHANGED = 4;
    public static final short OCC_KIND_CLOSE_REQUESTED = 5;
    public static final short OCC_KIND_WINDOW_CLOSED = 6;

    /** A blob value: the u64 handle from kaya_blob_register, consumed
     * by the next submit; the bytes never ride the record stream. */
    public static final class BlobHandle {
        public final long handle;

        public BlobHandle(long handle) {
            this.handle = handle;
        }
    }

    private static ByteBuffer begin(short kind) {
        ByteBuffer b = ByteBuffer.allocate(4096).order(ByteOrder.LITTLE_ENDIAN);
        b.putInt(0).putShort(kind).putShort((short) 0);
        return b;
    }

    private static byte[] finish(ByteBuffer b) {
        while (b.position() % 8 != 0) b.put((byte) 0);
        b.putInt(0, b.position());
        byte[] out = new byte[b.position()];
        b.flip();
        b.get(out);
        return out;
    }

    // Values self-pad to 8: they concatenate inside record bodies.
    private static void encodeValue(ByteBuffer b, Object v) {
        if (v instanceof Boolean) {
            b.putInt(VALUE_BOOL).putInt(1).put((byte) (((Boolean) v) ? 1 : 0));
        } else if (v instanceof Integer) {
            b.putInt(VALUE_I64).putInt(8).putLong((Integer) v);
        } else if (v instanceof Long) {
            b.putInt(VALUE_I64).putInt(8).putLong((Long) v);
        } else if (v instanceof Double) {
            b.putInt(VALUE_F64).putInt(8).putDouble((Double) v);
        } else if (v instanceof String) {
            byte[] utf8 = ((String) v).getBytes(StandardCharsets.UTF_8);
            b.putInt(VALUE_STR).putInt(utf8.length).put(utf8);
        } else if (v instanceof BlobHandle) {
            b.putInt(VALUE_BLOB).putInt(8).putLong(((BlobHandle) v).handle);
        } else {
            throw new IllegalArgumentException(
                    "kaya: value must be Boolean, Long, Double, String, or BlobHandle");
        }
        while (b.position() % 8 != 0) b.put((byte) 0);
    }

    // A counted value sequence — a key path or a record:
    // {u32 count, u32 reserved, count values}.
    private static void encodeValues(ByteBuffer b, Object[] vals) {
        int n = vals == null ? 0 : vals.length;
        b.putInt(n).putInt(0);
        for (int i = 0; i < n; i++) encodeValue(b, vals[i]);
    }

    // A collection schema: {u32 count, u32 reserved, count VALUE_* tags},
    // padded to 8.
    private static void encodeVariantSchemas(ByteBuffer b, int[][] variants) {
        b.putInt(variants.length).putInt(0);
        for (int[] schema : variants) {
            b.putInt(schema.length);
            for (int t : schema) b.putInt(t);
        }
        while (b.position() % 8 != 0) b.put((byte) 0);
    }

    /** Create a signal holding `initial`. */
    public static byte[] txCreateSignal(long signalId, Object initial) {
        ByteBuffer b = begin(TX_KIND_CREATE_SIGNAL);
        b.putLong(signalId);
        encodeValue(b, initial);
        return finish(b);
    }

    /** Replace a signal's value; keep-latest per batch. */
    public static byte[] txWriteSignal(long signalId, Object value) {
        ByteBuffer b = begin(TX_KIND_WRITE_SIGNAL);
        b.putLong(signalId);
        encodeValue(b, value);
        return finish(b);
    }

    /** Create a live widget, or declare a template node inside a scope. */
    public static byte[] txCreateWidget(long widgetId, int kind) {
        ByteBuffer b = begin(TX_KIND_CREATE_WIDGET);
        b.putLong(widgetId);
        b.putInt(kind);
        b.putInt(0);
        return finish(b);
    }

    /** Append `child` to `parent` (same zone only). */
    public static byte[] txAddChild(long parent, long child) {
        ByteBuffer b = begin(TX_KIND_ADD_CHILD);
        b.putLong(parent);
        b.putLong(child);
        return finish(b);
    }

    /** Mount a root into a window (0 = the default window). */
    public static byte[] txMount(long window, long root) {
        ByteBuffer b = begin(TX_KIND_MOUNT);
        b.putLong(window);
        b.putLong(root);
        return finish(b);
    }

    /** Declare a collection and its schema: one ordered field-type list per variant of the element sum. A record collection is the one-variant case and a scalar collection the one-variant one-field case. Variants are indices; names never travel. A blueprint when inside a template. */
    public static byte[] txCreateCollection(long collectionId, int[][] variants) {
        ByteBuffer b = begin(TX_KIND_CREATE_COLLECTION);
        b.putLong(collectionId);
        encodeVariantSchemas(b, variants);
        return finish(b);
    }

    /** Insert an entry into the instance at `path`; the fields match `variant`'s schema positionally. Stamps a copy from that variant's case. */
    public static byte[] txCollectionInsert(long collectionId, Object[] path, Object key, int variant, Object[] fields) {
        ByteBuffer b = begin(TX_KIND_COLLECTION_INSERT);
        b.putLong(collectionId);
        encodeValues(b, path);
        encodeValue(b, key);
        b.putInt(variant);
        b.putInt(0);
        encodeValues(b, fields);
        return finish(b);
    }

    /** Replace an entry's record; every element binding follows. A different `variant` than the entry's current one tears down its stamped copy and restamps from the new variant's case, in place. */
    public static byte[] txCollectionUpdate(long collectionId, Object[] path, Object key, int variant, Object[] fields) {
        ByteBuffer b = begin(TX_KIND_COLLECTION_UPDATE);
        b.putLong(collectionId);
        encodeValues(b, path);
        encodeValue(b, key);
        b.putInt(variant);
        b.putInt(0);
        encodeValues(b, fields);
        return finish(b);
    }

    /** Remove an entry; its stamped copy tears down. */
    public static byte[] txCollectionRemove(long collectionId, Object[] path, Object key) {
        ByteBuffer b = begin(TX_KIND_COLLECTION_REMOVE);
        b.putLong(collectionId);
        encodeValues(b, path);
        encodeValue(b, key);
        return finish(b);
    }

    /** A For over a collection; opens a template scope until template_end. */
    public static byte[] txCreateFor(long id, long collectionId) {
        ByteBuffer b = begin(TX_KIND_CREATE_FOR);
        b.putLong(id);
        b.putLong(collectionId);
        return finish(b);
    }

    /** A When over a Bool signal; opens a template scope until template_end. */
    public static byte[] txCreateWhen(long id, long signalId) {
        ByteBuffer b = begin(TX_KIND_CREATE_WHEN);
        b.putLong(id);
        b.putLong(signalId);
        return finish(b);
    }

    /** Close the innermost template scope. */
    public static byte[] txTemplateEnd() {
        ByteBuffer b = begin(TX_KIND_TEMPLATE_END);
        return finish(b);
    }

    /** Move an entry so it sits before the entry whose key is the one value in `before`, or to the end when `before` is empty. Keys, never indices: order is data, and indices would race the very deltas that change them. */
    public static byte[] txCollectionMove(long collectionId, Object[] path, Object key, Object[] before) {
        ByteBuffer b = begin(TX_KIND_COLLECTION_MOVE);
        b.putLong(collectionId);
        encodeValues(b, path);
        encodeValue(b, key);
        encodeValues(b, before);
        return finish(b);
    }

    /** Set one field of an entry's record; only bindings on that field re-resolve. `variant` is the discriminant the guest witnessed in the match that produced this write — the scene asserts it against the entry's stored variant, so a drifted model fails loudly; it never changes a constructor (update does). */
    public static byte[] txCollectionUpdateField(long collectionId, Object[] path, Object key, int field, int variant, Object value) {
        ByteBuffer b = begin(TX_KIND_COLLECTION_UPDATE_FIELD);
        b.putLong(collectionId);
        encodeValues(b, path);
        encodeValue(b, key);
        b.putInt(field);
        b.putInt(variant);
        encodeValue(b, value);
        return finish(b);
    }

    /** Inside a For over a sum: the records that follow (until the next variant_case or template_end) are the blueprint for this variant. Cases must be total at template_end; an empty case renders a constructor as nothing, explicitly. */
    public static byte[] txVariantCase(int variant) {
        ByteBuffer b = begin(TX_KIND_VARIANT_CASE);
        b.putInt(variant);
        b.putInt(0);
        return finish(b);
    }

    /** A one-shot command aimed at a live widget: momentary, fire-and-forget, never state at rest — the app's sanctioned crossing into widget-owned state (clear, focus). The widget answers through its normal occurrence path; nothing is recorded and nothing replays on rebuild. The command enum is the closed vocabulary; each verb is admitted by a real artifact, per the escalation policy. */
    public static byte[] txWidgetCommand(long widgetId, int command) {
        ByteBuffer b = begin(TX_KIND_WIDGET_COMMAND);
        b.putLong(widgetId);
        b.putInt(command);
        b.putInt(0);
        return finish(b);
    }

    /** Create an auxiliary window (capability-gated: a host without KAYA_CAP_AUX_WINDOWS rejects it at the root). Materializes hidden; mounting a root presents it. Ids are guest-allocated, below the internal bit; 0 is the primary and always exists. */
    public static byte[] txCreateWindow(long windowId) {
        ByteBuffer b = begin(TX_KIND_CREATE_WINDOW);
        b.putLong(windowId);
        return finish(b);
    }

    /** Close and forget an auxiliary window: the native window and its views are released wholesale, and the scene forgets the mounted tree (widget ids are never reused, so stale entries are inert). The primary is not destroyable: the process owns it. */
    public static byte[] txDestroyWindow(long windowId) {
        ByteBuffer b = begin(TX_KIND_DESTROY_WINDOW);
        b.putLong(windowId);
        return finish(b);
    }

    /** set_property with a constant text value. */
    public static byte[] txSetText(long widgetId, String text) {
        ByteBuffer b = begin(TX_KIND_SET_PROPERTY);
        b.putLong(widgetId).putInt(PROP_TEXT).putInt(SOURCE_CONST);
        encodeValue(b, text);
        return finish(b);
    }

    /** set_property with a signal-bound text value. */
    public static byte[] txBindText(long widgetId, long signalId) {
        ByteBuffer b = begin(TX_KIND_SET_PROPERTY);
        b.putLong(widgetId).putInt(PROP_TEXT).putInt(SOURCE_SIGNAL).putLong(signalId);
        return finish(b);
    }

    /** set_property bound to one field of the element of the enclosing For. */
    public static byte[] txBindTextElement(long widgetId, int level, int field) {
        ByteBuffer b = begin(TX_KIND_SET_PROPERTY);
        b.putLong(widgetId).putInt(PROP_TEXT).putInt(SOURCE_ELEMENT)
                .putInt(level).putInt(field);
        return finish(b);
    }

    /** set_property with a constant checked value. */
    public static byte[] txSetChecked(long widgetId, boolean checked) {
        ByteBuffer b = begin(TX_KIND_SET_PROPERTY);
        b.putLong(widgetId).putInt(PROP_CHECKED).putInt(SOURCE_CONST);
        encodeValue(b, checked);
        return finish(b);
    }

    /** set_property with a signal-bound checked value. */
    public static byte[] txBindChecked(long widgetId, long signalId) {
        ByteBuffer b = begin(TX_KIND_SET_PROPERTY);
        b.putLong(widgetId).putInt(PROP_CHECKED).putInt(SOURCE_SIGNAL).putLong(signalId);
        return finish(b);
    }

    /** set_property bound to one field of the element of the enclosing For. */
    public static byte[] txBindCheckedElement(long widgetId, int level, int field) {
        ByteBuffer b = begin(TX_KIND_SET_PROPERTY);
        b.putLong(widgetId).putInt(PROP_CHECKED).putInt(SOURCE_ELEMENT)
                .putInt(level).putInt(field);
        return finish(b);
    }

    /** set_property with a constant value value. */
    public static byte[] txSetValue(long widgetId, double value) {
        ByteBuffer b = begin(TX_KIND_SET_PROPERTY);
        b.putLong(widgetId).putInt(PROP_VALUE).putInt(SOURCE_CONST);
        encodeValue(b, value);
        return finish(b);
    }

    /** set_property with a signal-bound value value. */
    public static byte[] txBindValue(long widgetId, long signalId) {
        ByteBuffer b = begin(TX_KIND_SET_PROPERTY);
        b.putLong(widgetId).putInt(PROP_VALUE).putInt(SOURCE_SIGNAL).putLong(signalId);
        return finish(b);
    }

    /** set_property bound to one field of the element of the enclosing For. */
    public static byte[] txBindValueElement(long widgetId, int level, int field) {
        ByteBuffer b = begin(TX_KIND_SET_PROPERTY);
        b.putLong(widgetId).putInt(PROP_VALUE).putInt(SOURCE_ELEMENT)
                .putInt(level).putInt(field);
        return finish(b);
    }

    /** set_property with a constant min value. */
    public static byte[] txSetMin(long widgetId, double min) {
        ByteBuffer b = begin(TX_KIND_SET_PROPERTY);
        b.putLong(widgetId).putInt(PROP_MIN).putInt(SOURCE_CONST);
        encodeValue(b, min);
        return finish(b);
    }

    /** set_property with a signal-bound min value. */
    public static byte[] txBindMin(long widgetId, long signalId) {
        ByteBuffer b = begin(TX_KIND_SET_PROPERTY);
        b.putLong(widgetId).putInt(PROP_MIN).putInt(SOURCE_SIGNAL).putLong(signalId);
        return finish(b);
    }

    /** set_property bound to one field of the element of the enclosing For. */
    public static byte[] txBindMinElement(long widgetId, int level, int field) {
        ByteBuffer b = begin(TX_KIND_SET_PROPERTY);
        b.putLong(widgetId).putInt(PROP_MIN).putInt(SOURCE_ELEMENT)
                .putInt(level).putInt(field);
        return finish(b);
    }

    /** set_property with a constant max value. */
    public static byte[] txSetMax(long widgetId, double max) {
        ByteBuffer b = begin(TX_KIND_SET_PROPERTY);
        b.putLong(widgetId).putInt(PROP_MAX).putInt(SOURCE_CONST);
        encodeValue(b, max);
        return finish(b);
    }

    /** set_property with a signal-bound max value. */
    public static byte[] txBindMax(long widgetId, long signalId) {
        ByteBuffer b = begin(TX_KIND_SET_PROPERTY);
        b.putLong(widgetId).putInt(PROP_MAX).putInt(SOURCE_SIGNAL).putLong(signalId);
        return finish(b);
    }

    /** set_property bound to one field of the element of the enclosing For. */
    public static byte[] txBindMaxElement(long widgetId, int level, int field) {
        ByteBuffer b = begin(TX_KIND_SET_PROPERTY);
        b.putLong(widgetId).putInt(PROP_MAX).putInt(SOURCE_ELEMENT)
                .putInt(level).putInt(field);
        return finish(b);
    }

    /** set_property with a constant source value. */
    public static byte[] txSetSource(long widgetId, long handle) {
        ByteBuffer b = begin(TX_KIND_SET_PROPERTY);
        b.putLong(widgetId).putInt(PROP_SOURCE).putInt(SOURCE_CONST);
        encodeValue(b, new BlobHandle(handle));
        return finish(b);
    }

    /** set_property with a signal-bound source value. */
    public static byte[] txBindSource(long widgetId, long signalId) {
        ByteBuffer b = begin(TX_KIND_SET_PROPERTY);
        b.putLong(widgetId).putInt(PROP_SOURCE).putInt(SOURCE_SIGNAL).putLong(signalId);
        return finish(b);
    }

    /** set_property bound to one field of the element of the enclosing For. */
    public static byte[] txBindSourceElement(long widgetId, int level, int field) {
        ByteBuffer b = begin(TX_KIND_SET_PROPERTY);
        b.putLong(widgetId).putInt(PROP_SOURCE).putInt(SOURCE_ELEMENT)
                .putInt(level).putInt(field);
        return finish(b);
    }

    /** set_property with a constant grow value. */
    public static byte[] txSetGrow(long widgetId, double grow) {
        ByteBuffer b = begin(TX_KIND_SET_PROPERTY);
        b.putLong(widgetId).putInt(PROP_GROW).putInt(SOURCE_CONST);
        encodeValue(b, grow);
        return finish(b);
    }

    /** set_property with a signal-bound grow value. */
    public static byte[] txBindGrow(long widgetId, long signalId) {
        ByteBuffer b = begin(TX_KIND_SET_PROPERTY);
        b.putLong(widgetId).putInt(PROP_GROW).putInt(SOURCE_SIGNAL).putLong(signalId);
        return finish(b);
    }

    /** set_property bound to one field of the element of the enclosing For. */
    public static byte[] txBindGrowElement(long widgetId, int level, int field) {
        ByteBuffer b = begin(TX_KIND_SET_PROPERTY);
        b.putLong(widgetId).putInt(PROP_GROW).putInt(SOURCE_ELEMENT)
                .putInt(level).putInt(field);
        return finish(b);
    }

    /** set_property with a constant spacing value. */
    public static byte[] txSetSpacing(long widgetId, double spacing) {
        ByteBuffer b = begin(TX_KIND_SET_PROPERTY);
        b.putLong(widgetId).putInt(PROP_SPACING).putInt(SOURCE_CONST);
        encodeValue(b, spacing);
        return finish(b);
    }

    /** set_property with a signal-bound spacing value. */
    public static byte[] txBindSpacing(long widgetId, long signalId) {
        ByteBuffer b = begin(TX_KIND_SET_PROPERTY);
        b.putLong(widgetId).putInt(PROP_SPACING).putInt(SOURCE_SIGNAL).putLong(signalId);
        return finish(b);
    }

    /** set_property bound to one field of the element of the enclosing For. */
    public static byte[] txBindSpacingElement(long widgetId, int level, int field) {
        ByteBuffer b = begin(TX_KIND_SET_PROPERTY);
        b.putLong(widgetId).putInt(PROP_SPACING).putInt(SOURCE_ELEMENT)
                .putInt(level).putInt(field);
        return finish(b);
    }

    /** set_property with a constant align value. */
    public static byte[] txSetAlign(long widgetId, long align) {
        ByteBuffer b = begin(TX_KIND_SET_PROPERTY);
        b.putLong(widgetId).putInt(PROP_ALIGN).putInt(SOURCE_CONST);
        encodeValue(b, align);
        return finish(b);
    }

    /** set_property with a signal-bound align value. */
    public static byte[] txBindAlign(long widgetId, long signalId) {
        ByteBuffer b = begin(TX_KIND_SET_PROPERTY);
        b.putLong(widgetId).putInt(PROP_ALIGN).putInt(SOURCE_SIGNAL).putLong(signalId);
        return finish(b);
    }

    /** set_property bound to one field of the element of the enclosing For. */
    public static byte[] txBindAlignElement(long widgetId, int level, int field) {
        ByteBuffer b = begin(TX_KIND_SET_PROPERTY);
        b.putLong(widgetId).putInt(PROP_ALIGN).putInt(SOURCE_ELEMENT)
                .putInt(level).putInt(field);
        return finish(b);
    }

    /** set_window_prop with a constant title value (window 0, the primary surface). */
    public static byte[] txSetWindowTitle(long window, String title) {
        ByteBuffer b = begin(TX_KIND_SET_WINDOW_PROP);
        b.putLong(window).putInt(WPROP_TITLE).putInt(SOURCE_CONST);
        encodeValue(b, title);
        return finish(b);
    }

    /** set_window_prop with a signal-bound title value (window 0, the primary surface). */
    public static byte[] txBindWindowTitle(long window, long signalId) {
        ByteBuffer b = begin(TX_KIND_SET_WINDOW_PROP);
        b.putLong(window).putInt(WPROP_TITLE).putInt(SOURCE_SIGNAL).putLong(signalId);
        return finish(b);
    }

    /** set_window_prop with a constant width value (window 0, the primary surface). */
    public static byte[] txSetWindowWidth(long window, double width) {
        ByteBuffer b = begin(TX_KIND_SET_WINDOW_PROP);
        b.putLong(window).putInt(WPROP_WIDTH).putInt(SOURCE_CONST);
        encodeValue(b, width);
        return finish(b);
    }

    /** set_window_prop with a signal-bound width value (window 0, the primary surface). */
    public static byte[] txBindWindowWidth(long window, long signalId) {
        ByteBuffer b = begin(TX_KIND_SET_WINDOW_PROP);
        b.putLong(window).putInt(WPROP_WIDTH).putInt(SOURCE_SIGNAL).putLong(signalId);
        return finish(b);
    }

    /** set_window_prop with a constant height value (window 0, the primary surface). */
    public static byte[] txSetWindowHeight(long window, double height) {
        ByteBuffer b = begin(TX_KIND_SET_WINDOW_PROP);
        b.putLong(window).putInt(WPROP_HEIGHT).putInt(SOURCE_CONST);
        encodeValue(b, height);
        return finish(b);
    }

    /** set_window_prop with a signal-bound height value (window 0, the primary surface). */
    public static byte[] txBindWindowHeight(long window, long signalId) {
        ByteBuffer b = begin(TX_KIND_SET_WINDOW_PROP);
        b.putLong(window).putInt(WPROP_HEIGHT).putInt(SOURCE_SIGNAL).putLong(signalId);
        return finish(b);
    }

    /** set_window_prop with a constant veto_close value (window 0, the primary surface). */
    public static byte[] txSetWindowVetoClose(long window, boolean vetoClose) {
        ByteBuffer b = begin(TX_KIND_SET_WINDOW_PROP);
        b.putLong(window).putInt(WPROP_VETO_CLOSE).putInt(SOURCE_CONST);
        encodeValue(b, vetoClose);
        return finish(b);
    }

    /** set_window_prop with a signal-bound veto_close value (window 0, the primary surface). */
    public static byte[] txBindWindowVetoClose(long window, long signalId) {
        ByteBuffer b = begin(TX_KIND_SET_WINDOW_PROP);
        b.putLong(window).putInt(WPROP_VETO_CLOSE).putInt(SOURCE_SIGNAL).putLong(signalId);
        return finish(b);
    }

    /** Concatenate packed records into one transaction. */
    public static byte[] tx(byte[]... records) {
        int len = 0;
        for (byte[] r : records) len += r.length;
        byte[] out = new byte[len];
        int at = 0;
        for (byte[] r : records) {
            System.arraycopy(r, 0, out, at, r.length);
            at += r.length;
        }
        return out;
    }

    /** A parsed occurrence: the kind, the id, the copy's key path
     * (empty when id is a widget id; otherwise id is a template
     * node id), and the payload — the entry's new text (String)
     * for TEXT_CHANGED, the checkbox's new state (Boolean) for
     * TOGGLED, the slider's new value (Double) for VALUE_CHANGED,
     * null for clicks. */
    public static final class Occ {
        public final short kind;
        public final long id;
        public final List<Object> keys;
        public final Object payload;

        Occ(short kind, long id, List<Object> keys, Object payload) {
            this.kind = kind;
            this.id = id;
            this.keys = keys;
            this.payload = payload;
        }
    }

    /** Decode one occurrence record (header included); null for pad
     * or unknown kinds. */
    public static Occ parseOccurrence(byte[] rec) {
        ByteBuffer b = ByteBuffer.wrap(rec).order(ByteOrder.LITTLE_ENDIAN);
        short kind = b.getShort(4);
        if (kind != OCC_KIND_BUTTON_CLICKED && kind != OCC_KIND_TEXT_CHANGED && kind != OCC_KIND_TOGGLED && kind != OCC_KIND_VALUE_CHANGED && kind != OCC_KIND_CLOSE_REQUESTED && kind != OCC_KIND_WINDOW_CLOSED) {
            return null;
        }
        long id = b.getLong(8);
        int pathLen = b.getInt(16);
        List<Object> keys = new ArrayList<>();
        int at = 24;
        for (int i = 0; i < pathLen; i++) {
            int vtype = b.getInt(at);
            int vlen = b.getInt(at + 4);
            switch (vtype) {
                case VALUE_BOOL: keys.add(rec[at + 8] != 0); break;
                case VALUE_I64: keys.add(b.getLong(at + 8)); break;
                case VALUE_F64: keys.add(b.getDouble(at + 8)); break;
                default:
                    keys.add(new String(rec, at + 8, vlen, StandardCharsets.UTF_8));
            }
            at += 8 + ((vlen + 7) & ~7);
        }
        Object payload = null;
        if (kind == OCC_KIND_TEXT_CHANGED || kind == OCC_KIND_TOGGLED || kind == OCC_KIND_VALUE_CHANGED) {
            int ptype = b.getInt(at);
            int plen = b.getInt(at + 4);
            switch (ptype) {
                case VALUE_BOOL: payload = rec[at + 8] != 0; break;
                case VALUE_I64: payload = b.getLong(at + 8); break;
                case VALUE_F64: payload = b.getDouble(at + 8); break;
                default:
                    payload = new String(rec, at + 8, plen, StandardCharsets.UTF_8);
            }
        }
        return new Occ(kind, id, keys, payload);
    }

    private KayaWire() {}
}
