// kaya wire vocabulary. Generated by kaya-bindgen from kaya::spec — do not edit.
//
// Records are {u32 size, u16 kind, u16 flags}, body, padded to 8,
// little-endian. Values accept Go bool, int64, float64, string, and
// BlobHandle, mapped to the kaya value types; keys in paths likewise.
package kaya

import (
	"encoding/binary"
	"math"
)

const (
	// SpecHash: the protocol fingerprint; the runtime asserts the loaded core agrees.
	SpecHash uint64 = 0xecc906b893ee37ae

	ValueBool = 1
	ValueI64 = 2
	ValueF64 = 3
	ValueStr = 4
	ValueBlob = 5
	KindColumn = 1
	KindButton = 2
	KindLabel = 3
	KindEntry = 4
	KindRow = 5
	KindCheckbox = 6
	KindSlider = 7
	KindImage = 8
	PropText = 1
	PropChecked = 2
	PropValue = 3
	PropMin = 4
	PropMax = 5
	PropSource = 6
	PropGrow = 7
	PropSpacing = 8
	PropAlign = 9
	WpropTitle = 1
	WpropWidth = 2
	WpropHeight = 3
	WpropVetoClose = 4
	AlignStart = 0
	AlignCenter = 1
	AlignEnd = 2
	AlignStretch = 3
	AlignBaseline = 4
	SourceConst = 0
	SourceSignal = 1
	SourceElement = 2
	OccurrencePad = 0
	OccurrenceButtonClicked = 1
	OccurrenceTextChanged = 2
	OccurrenceToggled = 3
	OccurrenceValueChanged = 4
	CommandClear = 1
	CommandFocus = 2
	txCreateSignal = 1
	txWriteSignal = 2
	txCreateWidget = 3
	txSetProperty = 4
	txAddChild = 5
	txMount = 6
	txCreateCollection = 7
	txCollectionInsert = 8
	txCollectionUpdate = 9
	txCollectionRemove = 10
	txCreateFor = 11
	txCreateWhen = 12
	txTemplateEnd = 13
	txCollectionMove = 15
	txCollectionUpdateField = 14
	txVariantCase = 16
	txWidgetCommand = 17
	txSetWindowProp = 18
	txCreateWindow = 19
	txDestroyWindow = 20
	applyCreate = 1
	applySetProp = 2
	applyAddChild = 3
	applyMount = 4
	applyMoveChild = 6
	applyDestroy = 5
	applyCommand = 7
	applySetWindowProp = 8
	applyCreateWindow = 9
	applyDestroyWindow = 10
	occButtonClicked = 1
	occTextChanged = 2
	occToggled = 3
	occValueChanged = 4
	occCloseRequested = 5
	occWindowClosed = 6
)

func pad8(b []byte) []byte {
	for len(b)%8 != 0 {
		b = append(b, 0)
	}
	return b
}

// BlobHandle marks a u64 handle from kaya_blob_register as a blob
// value, consumed by the next submit; the bytes never ride the
// record stream.
type BlobHandle uint64

// encodeValue appends one kaya value; values self-pad to 8 because
// they concatenate inside record bodies.
func encodeValue(b []byte, v any) []byte {
	switch x := v.(type) {
	case bool:
		b = binary.LittleEndian.AppendUint32(b, ValueBool)
		b = binary.LittleEndian.AppendUint32(b, 1)
		if x {
			b = append(b, 1)
		} else {
			b = append(b, 0)
		}
	case int:
		return encodeValue(b, int64(x))
	case int64:
		b = binary.LittleEndian.AppendUint32(b, ValueI64)
		b = binary.LittleEndian.AppendUint32(b, 8)
		b = binary.LittleEndian.AppendUint64(b, uint64(x))
	case float64:
		b = binary.LittleEndian.AppendUint32(b, ValueF64)
		b = binary.LittleEndian.AppendUint32(b, 8)
		b = binary.LittleEndian.AppendUint64(b, math.Float64bits(x))
	case string:
		b = binary.LittleEndian.AppendUint32(b, ValueStr)
		b = binary.LittleEndian.AppendUint32(b, uint32(len(x)))
		b = append(b, x...)
	case BlobHandle:
		b = binary.LittleEndian.AppendUint32(b, ValueBlob)
		b = binary.LittleEndian.AppendUint32(b, 8)
		b = binary.LittleEndian.AppendUint64(b, uint64(x))
	default:
		panic("kaya: value must be bool, int64, float64, string, or BlobHandle")
	}
	return pad8(b)
}

// encodeValues appends a counted value sequence — a key path or a
// record: {u32 count, u32 reserved, count values}.
func encodeValues(b []byte, vals []any) []byte {
	b = binary.LittleEndian.AppendUint32(b, uint32(len(vals)))
	b = binary.LittleEndian.AppendUint32(b, 0)
	for _, v := range vals {
		b = encodeValue(b, v)
	}
	return b
}

// encodeVariantSchemas appends a collection's element sum: {u32
// variant_count, u32 reserved, per variant: u32 field_count,
// field_count Value* tags}, padded to 8. A record collection is
// the one-variant case.
func encodeVariantSchemas(b []byte, variants [][]uint32) []byte {
	b = binary.LittleEndian.AppendUint32(b, uint32(len(variants)))
	b = binary.LittleEndian.AppendUint32(b, 0)
	for _, schema := range variants {
		b = binary.LittleEndian.AppendUint32(b, uint32(len(schema)))
		for _, t := range schema {
			b = binary.LittleEndian.AppendUint32(b, t)
		}
	}
	for len(b)%8 != 0 {
		b = append(b, 0)
	}
	return b
}

func beginRecord(kind uint16) []byte {
	b := make([]byte, 0, 64)
	b = append(b, 0, 0, 0, 0)
	b = binary.LittleEndian.AppendUint16(b, kind)
	return append(b, 0, 0)
}

func endRecord(b []byte) []byte {
	b = pad8(b)
	binary.LittleEndian.PutUint32(b, uint32(len(b)))
	return b
}

// TxCreateSignal: Create a signal holding `initial`.
func TxCreateSignal(signalId uint64, initial any) []byte {
	b := beginRecord(txCreateSignal)
	b = binary.LittleEndian.AppendUint64(b, signalId)
	b = encodeValue(b, initial)
	return endRecord(b)
}

// TxWriteSignal: Replace a signal's value; keep-latest per batch.
func TxWriteSignal(signalId uint64, value any) []byte {
	b := beginRecord(txWriteSignal)
	b = binary.LittleEndian.AppendUint64(b, signalId)
	b = encodeValue(b, value)
	return endRecord(b)
}

// TxCreateWidget: Create a live widget, or declare a template node inside a scope.
func TxCreateWidget(widgetId uint64, kind uint32) []byte {
	b := beginRecord(txCreateWidget)
	b = binary.LittleEndian.AppendUint64(b, widgetId)
	b = binary.LittleEndian.AppendUint32(b, kind)
	b = binary.LittleEndian.AppendUint32(b, 0)
	return endRecord(b)
}

// TxAddChild: Append `child` to `parent` (same zone only).
func TxAddChild(parent uint64, child uint64) []byte {
	b := beginRecord(txAddChild)
	b = binary.LittleEndian.AppendUint64(b, parent)
	b = binary.LittleEndian.AppendUint64(b, child)
	return endRecord(b)
}

// TxMount: Mount a root into a window (0 = the default window).
func TxMount(window uint64, root uint64) []byte {
	b := beginRecord(txMount)
	b = binary.LittleEndian.AppendUint64(b, window)
	b = binary.LittleEndian.AppendUint64(b, root)
	return endRecord(b)
}

// TxCreateCollection: Declare a collection and its schema: one ordered field-type list per variant of the element sum. A record collection is the one-variant case and a scalar collection the one-variant one-field case. Variants are indices; names never travel. A blueprint when inside a template.
func TxCreateCollection(collectionId uint64, variants [][]uint32) []byte {
	b := beginRecord(txCreateCollection)
	b = binary.LittleEndian.AppendUint64(b, collectionId)
	b = encodeVariantSchemas(b, variants)
	return endRecord(b)
}

// TxCollectionInsert: Insert an entry into the instance at `path`; the fields match `variant`'s schema positionally. Stamps a copy from that variant's case.
func TxCollectionInsert(collectionId uint64, path []any, key any, variant uint32, fields []any) []byte {
	b := beginRecord(txCollectionInsert)
	b = binary.LittleEndian.AppendUint64(b, collectionId)
	b = encodeValues(b, path)
	b = encodeValue(b, key)
	b = binary.LittleEndian.AppendUint32(b, variant)
	b = binary.LittleEndian.AppendUint32(b, 0)
	b = encodeValues(b, fields)
	return endRecord(b)
}

// TxCollectionUpdate: Replace an entry's record; every element binding follows. A different `variant` than the entry's current one tears down its stamped copy and restamps from the new variant's case, in place.
func TxCollectionUpdate(collectionId uint64, path []any, key any, variant uint32, fields []any) []byte {
	b := beginRecord(txCollectionUpdate)
	b = binary.LittleEndian.AppendUint64(b, collectionId)
	b = encodeValues(b, path)
	b = encodeValue(b, key)
	b = binary.LittleEndian.AppendUint32(b, variant)
	b = binary.LittleEndian.AppendUint32(b, 0)
	b = encodeValues(b, fields)
	return endRecord(b)
}

// TxCollectionRemove: Remove an entry; its stamped copy tears down.
func TxCollectionRemove(collectionId uint64, path []any, key any) []byte {
	b := beginRecord(txCollectionRemove)
	b = binary.LittleEndian.AppendUint64(b, collectionId)
	b = encodeValues(b, path)
	b = encodeValue(b, key)
	return endRecord(b)
}

// TxCreateFor: A For over a collection; opens a template scope until template_end.
func TxCreateFor(id uint64, collectionId uint64) []byte {
	b := beginRecord(txCreateFor)
	b = binary.LittleEndian.AppendUint64(b, id)
	b = binary.LittleEndian.AppendUint64(b, collectionId)
	return endRecord(b)
}

// TxCreateWhen: A When over a Bool signal; opens a template scope until template_end.
func TxCreateWhen(id uint64, signalId uint64) []byte {
	b := beginRecord(txCreateWhen)
	b = binary.LittleEndian.AppendUint64(b, id)
	b = binary.LittleEndian.AppendUint64(b, signalId)
	return endRecord(b)
}

// TxTemplateEnd: Close the innermost template scope.
func TxTemplateEnd() []byte {
	b := beginRecord(txTemplateEnd)
	return endRecord(b)
}

// TxCollectionMove: Move an entry so it sits before the entry whose key is the one value in `before`, or to the end when `before` is empty. Keys, never indices: order is data, and indices would race the very deltas that change them.
func TxCollectionMove(collectionId uint64, path []any, key any, before []any) []byte {
	b := beginRecord(txCollectionMove)
	b = binary.LittleEndian.AppendUint64(b, collectionId)
	b = encodeValues(b, path)
	b = encodeValue(b, key)
	b = encodeValues(b, before)
	return endRecord(b)
}

// TxCollectionUpdateField: Set one field of an entry's record; only bindings on that field re-resolve. `variant` is the discriminant the guest witnessed in the match that produced this write — the scene asserts it against the entry's stored variant, so a drifted model fails loudly; it never changes a constructor (update does).
func TxCollectionUpdateField(collectionId uint64, path []any, key any, field uint32, variant uint32, value any) []byte {
	b := beginRecord(txCollectionUpdateField)
	b = binary.LittleEndian.AppendUint64(b, collectionId)
	b = encodeValues(b, path)
	b = encodeValue(b, key)
	b = binary.LittleEndian.AppendUint32(b, field)
	b = binary.LittleEndian.AppendUint32(b, variant)
	b = encodeValue(b, value)
	return endRecord(b)
}

// TxVariantCase: Inside a For over a sum: the records that follow (until the next variant_case or template_end) are the blueprint for this variant. Cases must be total at template_end; an empty case renders a constructor as nothing, explicitly.
func TxVariantCase(variant uint32) []byte {
	b := beginRecord(txVariantCase)
	b = binary.LittleEndian.AppendUint32(b, variant)
	b = binary.LittleEndian.AppendUint32(b, 0)
	return endRecord(b)
}

// TxWidgetCommand: A one-shot command aimed at a live widget: momentary, fire-and-forget, never state at rest — the app's sanctioned crossing into widget-owned state (clear, focus). The widget answers through its normal occurrence path; nothing is recorded and nothing replays on rebuild. The command enum is the closed vocabulary; each verb is admitted by a real artifact, per the escalation policy.
func TxWidgetCommand(widgetId uint64, command uint32) []byte {
	b := beginRecord(txWidgetCommand)
	b = binary.LittleEndian.AppendUint64(b, widgetId)
	b = binary.LittleEndian.AppendUint32(b, command)
	b = binary.LittleEndian.AppendUint32(b, 0)
	return endRecord(b)
}

// TxCreateWindow: Create an auxiliary window (capability-gated: a host without KAYA_CAP_AUX_WINDOWS rejects it at the root). Materializes hidden; mounting a root presents it. Ids are guest-allocated, below the internal bit; 0 is the primary and always exists.
func TxCreateWindow(windowId uint64) []byte {
	b := beginRecord(txCreateWindow)
	b = binary.LittleEndian.AppendUint64(b, windowId)
	return endRecord(b)
}

// TxDestroyWindow: Close and forget an auxiliary window: the native window and its views are released wholesale, and the scene forgets the mounted tree (widget ids are never reused, so stale entries are inert). The primary is not destroyable: the process owns it.
func TxDestroyWindow(windowId uint64) []byte {
	b := beginRecord(txDestroyWindow)
	b = binary.LittleEndian.AppendUint64(b, windowId)
	return endRecord(b)
}

// TxSetText: set_property with a constant text value.
func TxSetText(widgetID uint64, text string) []byte {
	b := beginRecord(txSetProperty)
	b = binary.LittleEndian.AppendUint64(b, widgetID)
	b = binary.LittleEndian.AppendUint32(b, PropText)
	b = binary.LittleEndian.AppendUint32(b, SourceConst)
	b = encodeValue(b, text)
	return endRecord(b)
}

// TxBindText: set_property with a signal-bound text value.
func TxBindText(widgetID uint64, signalID uint64) []byte {
	b := beginRecord(txSetProperty)
	b = binary.LittleEndian.AppendUint64(b, widgetID)
	b = binary.LittleEndian.AppendUint32(b, PropText)
	b = binary.LittleEndian.AppendUint32(b, SourceSignal)
	b = binary.LittleEndian.AppendUint64(b, signalID)
	return endRecord(b)
}

// TxBindTextElement: set_property bound to one field of the element of the
// enclosing For, `level` Fors up (0 = nearest).
func TxBindTextElement(widgetID uint64, level uint32, field uint32) []byte {
	b := beginRecord(txSetProperty)
	b = binary.LittleEndian.AppendUint64(b, widgetID)
	b = binary.LittleEndian.AppendUint32(b, PropText)
	b = binary.LittleEndian.AppendUint32(b, SourceElement)
	b = binary.LittleEndian.AppendUint32(b, level)
	b = binary.LittleEndian.AppendUint32(b, field)
	return endRecord(b)
}

// TxSetChecked: set_property with a constant checked value.
func TxSetChecked(widgetID uint64, checked bool) []byte {
	b := beginRecord(txSetProperty)
	b = binary.LittleEndian.AppendUint64(b, widgetID)
	b = binary.LittleEndian.AppendUint32(b, PropChecked)
	b = binary.LittleEndian.AppendUint32(b, SourceConst)
	b = encodeValue(b, checked)
	return endRecord(b)
}

// TxBindChecked: set_property with a signal-bound checked value.
func TxBindChecked(widgetID uint64, signalID uint64) []byte {
	b := beginRecord(txSetProperty)
	b = binary.LittleEndian.AppendUint64(b, widgetID)
	b = binary.LittleEndian.AppendUint32(b, PropChecked)
	b = binary.LittleEndian.AppendUint32(b, SourceSignal)
	b = binary.LittleEndian.AppendUint64(b, signalID)
	return endRecord(b)
}

// TxBindCheckedElement: set_property bound to one field of the element of the
// enclosing For, `level` Fors up (0 = nearest).
func TxBindCheckedElement(widgetID uint64, level uint32, field uint32) []byte {
	b := beginRecord(txSetProperty)
	b = binary.LittleEndian.AppendUint64(b, widgetID)
	b = binary.LittleEndian.AppendUint32(b, PropChecked)
	b = binary.LittleEndian.AppendUint32(b, SourceElement)
	b = binary.LittleEndian.AppendUint32(b, level)
	b = binary.LittleEndian.AppendUint32(b, field)
	return endRecord(b)
}

// TxSetValue: set_property with a constant value value.
func TxSetValue(widgetID uint64, value float64) []byte {
	b := beginRecord(txSetProperty)
	b = binary.LittleEndian.AppendUint64(b, widgetID)
	b = binary.LittleEndian.AppendUint32(b, PropValue)
	b = binary.LittleEndian.AppendUint32(b, SourceConst)
	b = encodeValue(b, value)
	return endRecord(b)
}

// TxBindValue: set_property with a signal-bound value value.
func TxBindValue(widgetID uint64, signalID uint64) []byte {
	b := beginRecord(txSetProperty)
	b = binary.LittleEndian.AppendUint64(b, widgetID)
	b = binary.LittleEndian.AppendUint32(b, PropValue)
	b = binary.LittleEndian.AppendUint32(b, SourceSignal)
	b = binary.LittleEndian.AppendUint64(b, signalID)
	return endRecord(b)
}

// TxBindValueElement: set_property bound to one field of the element of the
// enclosing For, `level` Fors up (0 = nearest).
func TxBindValueElement(widgetID uint64, level uint32, field uint32) []byte {
	b := beginRecord(txSetProperty)
	b = binary.LittleEndian.AppendUint64(b, widgetID)
	b = binary.LittleEndian.AppendUint32(b, PropValue)
	b = binary.LittleEndian.AppendUint32(b, SourceElement)
	b = binary.LittleEndian.AppendUint32(b, level)
	b = binary.LittleEndian.AppendUint32(b, field)
	return endRecord(b)
}

// TxSetMin: set_property with a constant min value.
func TxSetMin(widgetID uint64, min float64) []byte {
	b := beginRecord(txSetProperty)
	b = binary.LittleEndian.AppendUint64(b, widgetID)
	b = binary.LittleEndian.AppendUint32(b, PropMin)
	b = binary.LittleEndian.AppendUint32(b, SourceConst)
	b = encodeValue(b, min)
	return endRecord(b)
}

// TxBindMin: set_property with a signal-bound min value.
func TxBindMin(widgetID uint64, signalID uint64) []byte {
	b := beginRecord(txSetProperty)
	b = binary.LittleEndian.AppendUint64(b, widgetID)
	b = binary.LittleEndian.AppendUint32(b, PropMin)
	b = binary.LittleEndian.AppendUint32(b, SourceSignal)
	b = binary.LittleEndian.AppendUint64(b, signalID)
	return endRecord(b)
}

// TxBindMinElement: set_property bound to one field of the element of the
// enclosing For, `level` Fors up (0 = nearest).
func TxBindMinElement(widgetID uint64, level uint32, field uint32) []byte {
	b := beginRecord(txSetProperty)
	b = binary.LittleEndian.AppendUint64(b, widgetID)
	b = binary.LittleEndian.AppendUint32(b, PropMin)
	b = binary.LittleEndian.AppendUint32(b, SourceElement)
	b = binary.LittleEndian.AppendUint32(b, level)
	b = binary.LittleEndian.AppendUint32(b, field)
	return endRecord(b)
}

// TxSetMax: set_property with a constant max value.
func TxSetMax(widgetID uint64, max float64) []byte {
	b := beginRecord(txSetProperty)
	b = binary.LittleEndian.AppendUint64(b, widgetID)
	b = binary.LittleEndian.AppendUint32(b, PropMax)
	b = binary.LittleEndian.AppendUint32(b, SourceConst)
	b = encodeValue(b, max)
	return endRecord(b)
}

// TxBindMax: set_property with a signal-bound max value.
func TxBindMax(widgetID uint64, signalID uint64) []byte {
	b := beginRecord(txSetProperty)
	b = binary.LittleEndian.AppendUint64(b, widgetID)
	b = binary.LittleEndian.AppendUint32(b, PropMax)
	b = binary.LittleEndian.AppendUint32(b, SourceSignal)
	b = binary.LittleEndian.AppendUint64(b, signalID)
	return endRecord(b)
}

// TxBindMaxElement: set_property bound to one field of the element of the
// enclosing For, `level` Fors up (0 = nearest).
func TxBindMaxElement(widgetID uint64, level uint32, field uint32) []byte {
	b := beginRecord(txSetProperty)
	b = binary.LittleEndian.AppendUint64(b, widgetID)
	b = binary.LittleEndian.AppendUint32(b, PropMax)
	b = binary.LittleEndian.AppendUint32(b, SourceElement)
	b = binary.LittleEndian.AppendUint32(b, level)
	b = binary.LittleEndian.AppendUint32(b, field)
	return endRecord(b)
}

// TxSetSource: set_property with a constant source value.
func TxSetSource(widgetID uint64, handle uint64) []byte {
	b := beginRecord(txSetProperty)
	b = binary.LittleEndian.AppendUint64(b, widgetID)
	b = binary.LittleEndian.AppendUint32(b, PropSource)
	b = binary.LittleEndian.AppendUint32(b, SourceConst)
	b = encodeValue(b, BlobHandle(handle))
	return endRecord(b)
}

// TxBindSource: set_property with a signal-bound source value.
func TxBindSource(widgetID uint64, signalID uint64) []byte {
	b := beginRecord(txSetProperty)
	b = binary.LittleEndian.AppendUint64(b, widgetID)
	b = binary.LittleEndian.AppendUint32(b, PropSource)
	b = binary.LittleEndian.AppendUint32(b, SourceSignal)
	b = binary.LittleEndian.AppendUint64(b, signalID)
	return endRecord(b)
}

// TxBindSourceElement: set_property bound to one field of the element of the
// enclosing For, `level` Fors up (0 = nearest).
func TxBindSourceElement(widgetID uint64, level uint32, field uint32) []byte {
	b := beginRecord(txSetProperty)
	b = binary.LittleEndian.AppendUint64(b, widgetID)
	b = binary.LittleEndian.AppendUint32(b, PropSource)
	b = binary.LittleEndian.AppendUint32(b, SourceElement)
	b = binary.LittleEndian.AppendUint32(b, level)
	b = binary.LittleEndian.AppendUint32(b, field)
	return endRecord(b)
}

// TxSetGrow: set_property with a constant grow value.
func TxSetGrow(widgetID uint64, grow float64) []byte {
	b := beginRecord(txSetProperty)
	b = binary.LittleEndian.AppendUint64(b, widgetID)
	b = binary.LittleEndian.AppendUint32(b, PropGrow)
	b = binary.LittleEndian.AppendUint32(b, SourceConst)
	b = encodeValue(b, grow)
	return endRecord(b)
}

// TxBindGrow: set_property with a signal-bound grow value.
func TxBindGrow(widgetID uint64, signalID uint64) []byte {
	b := beginRecord(txSetProperty)
	b = binary.LittleEndian.AppendUint64(b, widgetID)
	b = binary.LittleEndian.AppendUint32(b, PropGrow)
	b = binary.LittleEndian.AppendUint32(b, SourceSignal)
	b = binary.LittleEndian.AppendUint64(b, signalID)
	return endRecord(b)
}

// TxBindGrowElement: set_property bound to one field of the element of the
// enclosing For, `level` Fors up (0 = nearest).
func TxBindGrowElement(widgetID uint64, level uint32, field uint32) []byte {
	b := beginRecord(txSetProperty)
	b = binary.LittleEndian.AppendUint64(b, widgetID)
	b = binary.LittleEndian.AppendUint32(b, PropGrow)
	b = binary.LittleEndian.AppendUint32(b, SourceElement)
	b = binary.LittleEndian.AppendUint32(b, level)
	b = binary.LittleEndian.AppendUint32(b, field)
	return endRecord(b)
}

// TxSetSpacing: set_property with a constant spacing value.
func TxSetSpacing(widgetID uint64, spacing float64) []byte {
	b := beginRecord(txSetProperty)
	b = binary.LittleEndian.AppendUint64(b, widgetID)
	b = binary.LittleEndian.AppendUint32(b, PropSpacing)
	b = binary.LittleEndian.AppendUint32(b, SourceConst)
	b = encodeValue(b, spacing)
	return endRecord(b)
}

// TxBindSpacing: set_property with a signal-bound spacing value.
func TxBindSpacing(widgetID uint64, signalID uint64) []byte {
	b := beginRecord(txSetProperty)
	b = binary.LittleEndian.AppendUint64(b, widgetID)
	b = binary.LittleEndian.AppendUint32(b, PropSpacing)
	b = binary.LittleEndian.AppendUint32(b, SourceSignal)
	b = binary.LittleEndian.AppendUint64(b, signalID)
	return endRecord(b)
}

// TxBindSpacingElement: set_property bound to one field of the element of the
// enclosing For, `level` Fors up (0 = nearest).
func TxBindSpacingElement(widgetID uint64, level uint32, field uint32) []byte {
	b := beginRecord(txSetProperty)
	b = binary.LittleEndian.AppendUint64(b, widgetID)
	b = binary.LittleEndian.AppendUint32(b, PropSpacing)
	b = binary.LittleEndian.AppendUint32(b, SourceElement)
	b = binary.LittleEndian.AppendUint32(b, level)
	b = binary.LittleEndian.AppendUint32(b, field)
	return endRecord(b)
}

// TxSetAlign: set_property with a constant align value.
func TxSetAlign(widgetID uint64, align int64) []byte {
	b := beginRecord(txSetProperty)
	b = binary.LittleEndian.AppendUint64(b, widgetID)
	b = binary.LittleEndian.AppendUint32(b, PropAlign)
	b = binary.LittleEndian.AppendUint32(b, SourceConst)
	b = encodeValue(b, align)
	return endRecord(b)
}

// TxBindAlign: set_property with a signal-bound align value.
func TxBindAlign(widgetID uint64, signalID uint64) []byte {
	b := beginRecord(txSetProperty)
	b = binary.LittleEndian.AppendUint64(b, widgetID)
	b = binary.LittleEndian.AppendUint32(b, PropAlign)
	b = binary.LittleEndian.AppendUint32(b, SourceSignal)
	b = binary.LittleEndian.AppendUint64(b, signalID)
	return endRecord(b)
}

// TxBindAlignElement: set_property bound to one field of the element of the
// enclosing For, `level` Fors up (0 = nearest).
func TxBindAlignElement(widgetID uint64, level uint32, field uint32) []byte {
	b := beginRecord(txSetProperty)
	b = binary.LittleEndian.AppendUint64(b, widgetID)
	b = binary.LittleEndian.AppendUint32(b, PropAlign)
	b = binary.LittleEndian.AppendUint32(b, SourceElement)
	b = binary.LittleEndian.AppendUint32(b, level)
	b = binary.LittleEndian.AppendUint32(b, field)
	return endRecord(b)
}

// TxSetWindowTitle: set_window_prop with a constant title value (window 0, the primary surface).
func TxSetWindowTitle(window uint64, title string) []byte {
	b := beginRecord(txSetWindowProp)
	b = binary.LittleEndian.AppendUint64(b, window)
	b = binary.LittleEndian.AppendUint32(b, WpropTitle)
	b = binary.LittleEndian.AppendUint32(b, SourceConst)
	b = encodeValue(b, title)
	return endRecord(b)
}

// TxBindWindowTitle: set_window_prop with a signal-bound title value (window 0, the primary surface).
func TxBindWindowTitle(window uint64, signalID uint64) []byte {
	b := beginRecord(txSetWindowProp)
	b = binary.LittleEndian.AppendUint64(b, window)
	b = binary.LittleEndian.AppendUint32(b, WpropTitle)
	b = binary.LittleEndian.AppendUint32(b, SourceSignal)
	b = binary.LittleEndian.AppendUint64(b, signalID)
	return endRecord(b)
}

// TxSetWindowWidth: set_window_prop with a constant width value (window 0, the primary surface).
func TxSetWindowWidth(window uint64, width float64) []byte {
	b := beginRecord(txSetWindowProp)
	b = binary.LittleEndian.AppendUint64(b, window)
	b = binary.LittleEndian.AppendUint32(b, WpropWidth)
	b = binary.LittleEndian.AppendUint32(b, SourceConst)
	b = encodeValue(b, width)
	return endRecord(b)
}

// TxBindWindowWidth: set_window_prop with a signal-bound width value (window 0, the primary surface).
func TxBindWindowWidth(window uint64, signalID uint64) []byte {
	b := beginRecord(txSetWindowProp)
	b = binary.LittleEndian.AppendUint64(b, window)
	b = binary.LittleEndian.AppendUint32(b, WpropWidth)
	b = binary.LittleEndian.AppendUint32(b, SourceSignal)
	b = binary.LittleEndian.AppendUint64(b, signalID)
	return endRecord(b)
}

// TxSetWindowHeight: set_window_prop with a constant height value (window 0, the primary surface).
func TxSetWindowHeight(window uint64, height float64) []byte {
	b := beginRecord(txSetWindowProp)
	b = binary.LittleEndian.AppendUint64(b, window)
	b = binary.LittleEndian.AppendUint32(b, WpropHeight)
	b = binary.LittleEndian.AppendUint32(b, SourceConst)
	b = encodeValue(b, height)
	return endRecord(b)
}

// TxBindWindowHeight: set_window_prop with a signal-bound height value (window 0, the primary surface).
func TxBindWindowHeight(window uint64, signalID uint64) []byte {
	b := beginRecord(txSetWindowProp)
	b = binary.LittleEndian.AppendUint64(b, window)
	b = binary.LittleEndian.AppendUint32(b, WpropHeight)
	b = binary.LittleEndian.AppendUint32(b, SourceSignal)
	b = binary.LittleEndian.AppendUint64(b, signalID)
	return endRecord(b)
}

// TxSetWindowVetoClose: set_window_prop with a constant veto_close value (window 0, the primary surface).
func TxSetWindowVetoClose(window uint64, vetoClose bool) []byte {
	b := beginRecord(txSetWindowProp)
	b = binary.LittleEndian.AppendUint64(b, window)
	b = binary.LittleEndian.AppendUint32(b, WpropVetoClose)
	b = binary.LittleEndian.AppendUint32(b, SourceConst)
	b = encodeValue(b, vetoClose)
	return endRecord(b)
}

// TxBindWindowVetoClose: set_window_prop with a signal-bound veto_close value (window 0, the primary surface).
func TxBindWindowVetoClose(window uint64, signalID uint64) []byte {
	b := beginRecord(txSetWindowProp)
	b = binary.LittleEndian.AppendUint64(b, window)
	b = binary.LittleEndian.AppendUint32(b, WpropVetoClose)
	b = binary.LittleEndian.AppendUint32(b, SourceSignal)
	b = binary.LittleEndian.AppendUint64(b, signalID)
	return endRecord(b)
}

// ParseOccurrence decodes one occurrence record (header included).
// keys is nil when id is a widget id; otherwise id is a template
// node id and keys is the copy's key path, outermost first. payload
// is the entry's new text (string) for occTextChanged, the
// checkbox's new state (bool) for occToggled, the slider's new
// value (float64) for occValueChanged, nil for clicks. ok is
// false for pad/unknown records.
func ParseOccurrence(rec []byte) (kind uint16, id uint64, keys []any, payload any, ok bool) {
	kind = binary.LittleEndian.Uint16(rec[4:])
	if kind != occButtonClicked && kind != occTextChanged && kind != occToggled && kind != occValueChanged && kind != occCloseRequested && kind != occWindowClosed {
		return 0, 0, nil, nil, false
	}
	id = binary.LittleEndian.Uint64(rec[8:])
	pathLen := binary.LittleEndian.Uint32(rec[16:])
	at := 24
	for i := uint32(0); i < pathLen; i++ {
		vtype := binary.LittleEndian.Uint32(rec[at:])
		vlen := int(binary.LittleEndian.Uint32(rec[at+4:]))
		payload := rec[at+8 : at+8+vlen]
		switch vtype {
		case ValueBool:
			keys = append(keys, payload[0] != 0)
		case ValueI64:
			keys = append(keys, int64(binary.LittleEndian.Uint64(payload)))
		case ValueF64:
			keys = append(keys, math.Float64frombits(binary.LittleEndian.Uint64(payload)))
		default:
			keys = append(keys, string(payload))
		}
		at += 8 + (vlen+7)&^7
	}
	if kind == occTextChanged || kind == occToggled || kind == occValueChanged {
		vtype := binary.LittleEndian.Uint32(rec[at:])
		vlen := int(binary.LittleEndian.Uint32(rec[at+4:]))
		switch vtype {
		case ValueBool:
			payload = rec[at+8] != 0
		case ValueI64:
			payload = int64(binary.LittleEndian.Uint64(rec[at+8:]))
		case ValueF64:
			payload = math.Float64frombits(binary.LittleEndian.Uint64(rec[at+8:]))
		default:
			payload = string(rec[at+8 : at+8+vlen])
		}
	}
	return kind, id, keys, payload, true
}
