// kaya wire vocabulary. Generated by kaya-bindgen from kaya::spec — do not edit.
//
// Records are {u32 size, u16 kind, u16 flags}, body, padded to 8,
// little-endian. Constants come from kaya.h via the bridging header.

import Foundation

enum KayaValue: Equatable {
    case bool(Bool)
    case i64(Int64)
    case f64(Double)
    case str(String)
}

/// A transaction under construction: packed records accumulate in
/// `bytes`; submit with kaya_submit.
struct KayaTx {
    var bytes = Data()

    mutating func u16(_ v: UInt16) {
        withUnsafeBytes(of: v.littleEndian) { bytes.append(contentsOf: $0) }
    }

    mutating func u32(_ v: UInt32) {
        withUnsafeBytes(of: v.littleEndian) { bytes.append(contentsOf: $0) }
    }

    mutating func u64(_ v: UInt64) {
        withUnsafeBytes(of: v.littleEndian) { bytes.append(contentsOf: $0) }
    }

    mutating func pad() {
        while bytes.count % 8 != 0 { bytes.append(0) }
    }

    /// Values self-pad to 8: they concatenate inside record bodies.
    mutating func value(_ v: KayaValue) {
        switch v {
        case .bool(let x):
            u32(UInt32(KAYA_VALUE_BOOL))
            u32(1)
            bytes.append(x ? 1 : 0)
        case .i64(let x):
            u32(UInt32(KAYA_VALUE_I64))
            u32(8)
            u64(UInt64(bitPattern: x))
        case .f64(let x):
            u32(UInt32(KAYA_VALUE_F64))
            u32(8)
            u64(x.bitPattern)
        case .str(let x):
            let utf8 = Array(x.utf8)
            u32(UInt32(KAYA_VALUE_STR))
            u32(UInt32(utf8.count))
            bytes.append(contentsOf: utf8)
        }
        pad()
    }

    /// A key path: {u32 count, u32 reserved, count values}.
    mutating func path(_ keys: [KayaValue]) {
        u32(UInt32(keys.count))
        u32(0)
        for key in keys { value(key) }
    }

    mutating func begin(_ kind: UInt16) -> Int {
        let start = bytes.count
        u32(0)
        u16(kind)
        u16(0)
        return start
    }

    mutating func end(_ start: Int) {
        pad()
        let size = UInt32(bytes.count - start).littleEndian
        withUnsafeBytes(of: size) {
            bytes.replaceSubrange(start..<start + 4, with: $0)
        }
    }

    /// Create a signal holding `initial`.
    mutating func createSignal(_ signalId: UInt64, _ initial: KayaValue) {
        let start = self.begin(UInt16(KAYA_TX_CREATE_SIGNAL))
        self.u64(signalId)
        self.value(initial)
        self.end(start)
    }

    /// Replace a signal's value; keep-latest per batch.
    mutating func writeSignal(_ signalId: UInt64, _ value: KayaValue) {
        let start = self.begin(UInt16(KAYA_TX_WRITE_SIGNAL))
        self.u64(signalId)
        self.value(value)
        self.end(start)
    }

    /// Create a live widget, or declare a template node inside a scope.
    mutating func createWidget(_ widgetId: UInt64, _ kind: UInt32) {
        let start = self.begin(UInt16(KAYA_TX_CREATE_WIDGET))
        self.u64(widgetId)
        self.u32(kind)
        self.u32(0)
        self.end(start)
    }

    /// Append `child` to `parent` (same zone only).
    mutating func addChild(_ parent: UInt64, _ child: UInt64) {
        let start = self.begin(UInt16(KAYA_TX_ADD_CHILD))
        self.u64(parent)
        self.u64(child)
        self.end(start)
    }

    /// Mount a root into a window (0 = the default window).
    mutating func mount(_ window: UInt64, _ root: UInt64) {
        let start = self.begin(UInt16(KAYA_TX_MOUNT))
        self.u64(window)
        self.u64(root)
        self.end(start)
    }

    /// Declare a collection (a blueprint when inside a template).
    mutating func createCollection(_ collectionId: UInt64) {
        let start = self.begin(UInt16(KAYA_TX_CREATE_COLLECTION))
        self.u64(collectionId)
        self.end(start)
    }

    /// Insert an entry into the instance at `path`; stamps a copy.
    mutating func collectionInsert(_ collectionId: UInt64, _ path: [KayaValue], _ key: KayaValue, _ value: KayaValue) {
        let start = self.begin(UInt16(KAYA_TX_COLLECTION_INSERT))
        self.u64(collectionId)
        self.path(path)
        self.value(key)
        self.value(value)
        self.end(start)
    }

    /// Update an entry's value; element bindings follow.
    mutating func collectionUpdate(_ collectionId: UInt64, _ path: [KayaValue], _ key: KayaValue, _ value: KayaValue) {
        let start = self.begin(UInt16(KAYA_TX_COLLECTION_UPDATE))
        self.u64(collectionId)
        self.path(path)
        self.value(key)
        self.value(value)
        self.end(start)
    }

    /// Remove an entry; its stamped copy tears down.
    mutating func collectionRemove(_ collectionId: UInt64, _ path: [KayaValue], _ key: KayaValue) {
        let start = self.begin(UInt16(KAYA_TX_COLLECTION_REMOVE))
        self.u64(collectionId)
        self.path(path)
        self.value(key)
        self.end(start)
    }

    /// A For over a collection; opens a template scope until template_end.
    mutating func createFor(_ id: UInt64, _ collectionId: UInt64) {
        let start = self.begin(UInt16(KAYA_TX_CREATE_FOR))
        self.u64(id)
        self.u64(collectionId)
        self.end(start)
    }

    /// A When over a Bool signal; opens a template scope until template_end.
    mutating func createWhen(_ id: UInt64, _ signalId: UInt64) {
        let start = self.begin(UInt16(KAYA_TX_CREATE_WHEN))
        self.u64(id)
        self.u64(signalId)
        self.end(start)
    }

    /// Close the innermost template scope.
    mutating func templateEnd() {
        let start = self.begin(UInt16(KAYA_TX_TEMPLATE_END))
        self.end(start)
    }

    /// set_property with a constant text value.
    mutating func setText(_ widgetId: UInt64, _ text: String) {
        let start = self.begin(UInt16(KAYA_TX_SET_PROPERTY))
        self.u64(widgetId)
        self.u32(UInt32(KAYA_PROP_TEXT))
        self.u32(UInt32(KAYA_SOURCE_CONST))
        self.value(.str(text))
        self.end(start)
    }

    /// set_property with a signal-bound text value.
    mutating func bindText(_ widgetId: UInt64, _ signalId: UInt64) {
        let start = self.begin(UInt16(KAYA_TX_SET_PROPERTY))
        self.u64(widgetId)
        self.u32(UInt32(KAYA_PROP_TEXT))
        self.u32(UInt32(KAYA_SOURCE_SIGNAL))
        self.u64(signalId)
        self.end(start)
    }

    /// set_property bound to the element of the enclosing For,
    /// `level` Fors up (0 = nearest).
    mutating func bindTextElement(_ widgetId: UInt64, level: UInt32 = 0) {
        let start = self.begin(UInt16(KAYA_TX_SET_PROPERTY))
        self.u64(widgetId)
        self.u32(UInt32(KAYA_PROP_TEXT))
        self.u32(UInt32(KAYA_SOURCE_ELEMENT))
        self.u32(level)
        self.u32(0)
        self.end(start)
    }

    func submit() {
        bytes.withUnsafeBytes { raw in
            kaya_submit(raw.bindMemory(to: UInt8.self).baseAddress, UInt(raw.count))
        }
    }
}

/// Decode one occurrence record (header included); nil for pad or
/// unknown kinds. keys is [] when id is a widget id; otherwise id is
/// a template node id and keys is the copy's key path, outermost
/// first. text is the entry's new content for TEXT_CHANGED, nil for
/// clicks.
func kayaParseOccurrence(_ rec: [UInt8])
    -> (kind: UInt16, id: UInt64, keys: [KayaValue], text: String?)?
{
    rec.withUnsafeBytes { raw in
        let kind = raw.loadUnaligned(fromByteOffset: 4, as: UInt16.self)
        guard kind == UInt16(KAYA_OCCURRENCE_BUTTON_CLICKED)
            || kind == UInt16(KAYA_OCCURRENCE_TEXT_CHANGED)
        else { return nil }
        let id = raw.loadUnaligned(fromByteOffset: 8, as: UInt64.self)
        let pathLen = raw.loadUnaligned(fromByteOffset: 16, as: UInt32.self)
        var keys: [KayaValue] = []
        var at = 24
        for _ in 0..<pathLen {
            let vtype = raw.loadUnaligned(fromByteOffset: at, as: UInt32.self)
            let vlen = Int(raw.loadUnaligned(fromByteOffset: at + 4, as: UInt32.self))
            switch vtype {
            case UInt32(KAYA_VALUE_BOOL):
                keys.append(.bool(raw[at + 8] != 0))
            case UInt32(KAYA_VALUE_I64):
                keys.append(.i64(Int64(bitPattern:
                    raw.loadUnaligned(fromByteOffset: at + 8, as: UInt64.self))))
            case UInt32(KAYA_VALUE_F64):
                keys.append(.f64(Double(bitPattern:
                    raw.loadUnaligned(fromByteOffset: at + 8, as: UInt64.self))))
            default:
                keys.append(.str(String(
                    decoding: raw[(at + 8)..<(at + 8 + vlen)], as: UTF8.self)))
            }
            at += 8 + ((vlen + 7) & ~7)
        }
        var text: String? = nil
        if kind == UInt16(KAYA_OCCURRENCE_TEXT_CHANGED) {
            let vlen = Int(raw.loadUnaligned(fromByteOffset: at + 4, as: UInt32.self))
            text = String(decoding: raw[(at + 8)..<(at + 8 + vlen)], as: UTF8.self)
        }
        return (kind, id, keys, text)
    }
}
