package dev.kaya.milestone2kt;

import dev.kaya.KayaRing;
import dev.kaya.KayaWire;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.MethodHandles;
import java.lang.reflect.Field;

/**
 * The milestone-2 scene from the JVM, on the kaya bindings: KayaWire
 * (generated by kaya-bindgen from kaya::spec) carries the packers and
 * the record parser; what stays here is the scene, the logic answering
 * occurrences, and the direct-tier ring loop — Unsafe fenced access on
 * raw addresses, which is app-side because it is this platform's
 * hand-won recipe (see the git history for the ART findings that shaped
 * it).
 */
final class Milestone2 {
    // Guest-allocated ids, counted from 1 per space.
    private static final long SIG_STATUS = 1;
    private static final long SIG_EXTRAS = 2;
    private static final long W_COLUMN = 1;
    private static final long W_STEP = 2;
    private static final long W_STATUS = 3;
    private static final long W_WHEN = 4;
    private static final long W_GROUPS = 5;
    private static final long C_GROUPS = 1;
    private static final long C_ITEMS = 2;
    private static final long N_BANNER = 1;
    private static final long N_GROUP_COL = 2;
    private static final long N_GROUP_LBL = 3;
    private static final long N_ITEMS_FOR = 4;
    private static final long N_ITEM_ROW = 5;
    private static final long N_ITEM_TEXT = 6;
    private static final long N_REMOVE = 7;

    private static final MethodHandle GET_INT;     // (long) -> int
    private static final MethodHandle GET_BYTE;    // (long) -> byte
    private static final MethodHandle PUT_INT;     // (long, int)
    private static final MethodHandle LOAD_FENCE;  // (): acquire
    private static final MethodHandle STORE_FENCE; // (): release

    static {
        try {
            Class<?> unsafeClass = Class.forName("sun.misc.Unsafe");
            Field theUnsafe = unsafeClass.getDeclaredField("theUnsafe");
            theUnsafe.setAccessible(true);
            Object unsafe = theUnsafe.get(null);
            MethodHandles.Lookup lookup = MethodHandles.lookup();
            GET_INT = lookup.unreflect(unsafeClass.getMethod("getInt", long.class)).bindTo(unsafe);
            GET_BYTE =
                    lookup.unreflect(unsafeClass.getMethod("getByte", long.class)).bindTo(unsafe);
            PUT_INT = lookup
                    .unreflect(unsafeClass.getMethod("putInt", long.class, int.class))
                    .bindTo(unsafe);
            LOAD_FENCE = lookup.unreflect(unsafeClass.getMethod("loadFence")).bindTo(unsafe);
            STORE_FENCE = lookup.unreflect(unsafeClass.getMethod("storeFence")).bindTo(unsafe);
        } catch (ReflectiveOperationException e) {
            throw new ExceptionInInitializerError(e);
        }
    }

    private static void buildScene() {
        KayaRing.submit(KayaWire.tx(
                KayaWire.txCreateSignal(SIG_STATUS, "step 0"),
                KayaWire.txCreateSignal(SIG_EXTRAS, false),
                KayaWire.txCreateWidget(W_COLUMN, KayaWire.KIND_COLUMN),
                KayaWire.txCreateWidget(W_STEP, KayaWire.KIND_BUTTON),
                KayaWire.txSetText(W_STEP, "step"),
                KayaWire.txCreateWidget(W_STATUS, KayaWire.KIND_LABEL),
                KayaWire.txBindText(W_STATUS, SIG_STATUS),
                // When(extras): a banner label.
                KayaWire.txCreateWhen(W_WHEN, SIG_EXTRAS),
                KayaWire.txCreateWidget(N_BANNER, KayaWire.KIND_LABEL),
                KayaWire.txSetText(N_BANNER, "extras on"),
                KayaWire.txTemplateEnd(),
                // For over groups, nesting a For over items.
                KayaWire.txCreateCollection(C_GROUPS),
                KayaWire.txCreateFor(W_GROUPS, C_GROUPS),
                KayaWire.txCreateWidget(N_GROUP_COL, KayaWire.KIND_COLUMN),
                KayaWire.txCreateWidget(N_GROUP_LBL, KayaWire.KIND_LABEL),
                KayaWire.txBindTextElement(N_GROUP_LBL, 0),
                KayaWire.txAddChild(N_GROUP_COL, N_GROUP_LBL),
                KayaWire.txCreateCollection(C_ITEMS),
                KayaWire.txCreateFor(N_ITEMS_FOR, C_ITEMS),
                KayaWire.txCreateWidget(N_ITEM_ROW, KayaWire.KIND_COLUMN),
                KayaWire.txCreateWidget(N_ITEM_TEXT, KayaWire.KIND_LABEL),
                KayaWire.txBindTextElement(N_ITEM_TEXT, 0),
                KayaWire.txCreateWidget(N_REMOVE, KayaWire.KIND_BUTTON),
                KayaWire.txSetText(N_REMOVE, "remove"),
                KayaWire.txAddChild(N_ITEM_ROW, N_ITEM_TEXT),
                KayaWire.txAddChild(N_ITEM_ROW, N_REMOVE),
                KayaWire.txTemplateEnd(),
                KayaWire.txAddChild(N_GROUP_COL, N_ITEMS_FOR),
                KayaWire.txTemplateEnd(),
                KayaWire.txAddChild(W_COLUMN, W_STEP),
                KayaWire.txAddChild(W_COLUMN, W_STATUS),
                KayaWire.txAddChild(W_COLUMN, W_WHEN),
                KayaWire.txAddChild(W_COLUMN, W_GROUPS),
                KayaWire.txMount(0, W_COLUMN))); // window 0: the default
    }

    static void app() {
        try {
            run();
        } catch (Throwable t) {
            // invokeExact declares Throwable; nothing here throws in practice.
            throw new RuntimeException(t);
        }
    }

    private static void run() throws Throwable {
        buildScene();

        long data = KayaRing.dataAddress();
        long headAddr = KayaRing.headAddress();
        long tailAddr = KayaRing.tailAddress();
        int mask = KayaRing.capacity() - 1;

        int steps = 0;
        int h = (int) GET_INT.invokeExact(headAddr);
        while (true) {
            int t = (int) GET_INT.invokeExact(tailAddr);
            LOAD_FENCE.invokeExact(); // acquire: record reads cannot move above the tail load
            if (h == t) {
                if (!KayaRing.waitOccurrences()) {
                    return; // shutdown
                }
                continue;
            }
            long at = data + (h & mask);
            int size = (int) GET_INT.invokeExact(at);
            byte[] rec = new byte[size];
            for (int i = 0; i < size; i++) {
                rec[i] = (byte) GET_BYTE.invokeExact(at + i);
            }
            h += size;
            STORE_FENCE.invokeExact(); // release: record reads complete before the hand-back
            PUT_INT.invokeExact(headAddr, h);

            KayaWire.Click click = KayaWire.parseClick(rec);
            if (click == null) {
                continue;
            }
            if (click.keys.isEmpty() && click.id == W_STEP) {
                steps++;
                byte[] changes;
                if (steps == 1) {
                    changes = KayaWire.tx(
                            KayaWire.txCollectionInsert(C_GROUPS, null, "g1", "Work"),
                            KayaWire.txCollectionInsert(
                                    C_ITEMS, new Object[] {"g1"}, "a", "send report"),
                            KayaWire.txCollectionInsert(
                                    C_ITEMS, new Object[] {"g1"}, "b", "buy milk"));
                } else if (steps == 2) {
                    changes = KayaWire.tx(
                            KayaWire.txCollectionInsert(C_GROUPS, null, "g2", "Home"),
                            KayaWire.txCollectionInsert(
                                    C_ITEMS, new Object[] {"g2"}, "a", "water plants"),
                            KayaWire.txCollectionUpdate(C_GROUPS, null, "g1", "Office"));
                } else {
                    changes = new byte[0];
                }
                KayaRing.submit(KayaWire.tx(
                        changes,
                        KayaWire.txWriteSignal(SIG_EXTRAS, steps == 1),
                        KayaWire.txWriteSignal(SIG_STATUS, "step " + steps)));
            } else if (click.keys.size() == 2 && click.id == N_REMOVE) {
                String group = (String) click.keys.get(0);
                String item = (String) click.keys.get(1);
                KayaRing.submit(KayaWire.tx(
                        KayaWire.txCollectionRemove(C_ITEMS, new Object[] {group}, item),
                        KayaWire.txWriteSignal(SIG_STATUS, "removed " + group + "/" + item)));
            }
        }
    }

    private Milestone2() {}
}
