//! C emitter: a header of static inline packers over a caller-owned
//! buffer, plus the occurrence parser. C has no namespaces, so every
//! identifier wears the kaya_ prefix and the validator carries the
//! whole collision load. Constants are not emitted here — cbindgen
//! already puts KAYA_TX_*/KAYA_KIND_*/... in kaya.h, which this header
//! includes.

use kaya::spec::{FieldTy, ProtocolSpec};

use crate::{Ctx, prop_variants, record_params};

/// C keywords plus this header's own identifiers.
pub const RESERVED: &[&str] = &[
    "auto", "break", "case", "char", "const", "continue", "default", "do", "double", "else",
    "enum", "extern", "float", "for", "goto", "if", "inline", "int", "long", "register",
    "restrict", "return", "short", "signed", "sizeof", "static", "struct", "switch", "typedef",
    "union", "unsigned", "void", "volatile", "while",
];

pub fn emit(spec: &ProtocolSpec) -> String {
    let mut c = Ctx { out: String::new() };
    c.line("/* kaya wire vocabulary. Generated by kaya-bindgen from kaya::spec — do not edit.");
    c.line(" *");
    c.line(" * Static inline packers over a caller-owned KayaTx buffer, and the");
    c.line(" * occurrence parser. Records are {u32 size, u16 kind, u16 flags}, body,");
    c.line(" * padded to 8, little-endian; constants come from kaya.h. */");
    c.line("");
    c.line("#ifndef KAYA_WIRE_H");
    c.line("#define KAYA_WIRE_H");
    c.line("");
    c.line("#include <kaya.h>");
    c.line("#include <string.h>");
    c.line("");
    c.line("/* A transaction under construction. The caller owns the storage and");
    c.line(" * submits with kaya_submit(tx.buf, tx.len); overflow is the caller's");
    c.line(" * to size against (records fail loudly core-side, never silently). */");
    c.line("typedef struct {");
    c.line("    uint8_t *buf;");
    c.line("    size_t len;");
    c.line("} KayaTx;");
    c.line("");
    c.line("/* A scalar for keys and values, tagged with a KAYA_VALUE_* type.");
    c.line(" * For parsed strings, s points into the record buffer (not");
    c.line(" * NUL-terminated); s_len is the byte length. */");
    c.line("typedef struct {");
    c.line("    uint32_t type;");
    c.line("    int64_t i;");
    c.line("    double f;");
    c.line("    const char *s;");
    c.line("    uint32_t s_len;");
    c.line("} KayaVal;");
    c.line("");
    c.line("/* One variant of a collection's element sum: its ordered");
    c.line(" * KAYA_VALUE_* field tags. A record collection declares one. */");
    c.line("typedef struct {");
    c.line("    const uint32_t *tags;");
    c.line("    uint32_t len;");
    c.line("} KayaVariantSchema;");
    c.line("");
    c.line("static inline KayaVal kaya_str(const char *s) {");
    c.line("    KayaVal v = {KAYA_VALUE_STR, 0, 0, s, (uint32_t)strlen(s)};");
    c.line("    return v;");
    c.line("}");
    c.line("");
    c.line("static inline KayaVal kaya_i64(int64_t i) {");
    c.line("    KayaVal v = {KAYA_VALUE_I64, i, 0, 0, 0};");
    c.line("    return v;");
    c.line("}");
    c.line("");
    c.line("static inline KayaVal kaya_f64(double f) {");
    c.line("    KayaVal v = {KAYA_VALUE_F64, 0, f, 0, 0};");
    c.line("    return v;");
    c.line("}");
    c.line("");
    c.line("static inline KayaVal kaya_bool(int b) {");
    c.line("    KayaVal v = {KAYA_VALUE_BOOL, b != 0, 0, 0, 0};");
    c.line("    return v;");
    c.line("}");
    c.line("");
    c.line("/* A blob by its kaya_blob_register handle (riding in i), consumed by");
    c.line(" * the next submit; the bytes never enter the record stream. */");
    c.line("static inline KayaVal kaya_blob(uint64_t handle) {");
    c.line("    KayaVal v = {KAYA_VALUE_BLOB, (int64_t)handle, 0, 0, 0};");
    c.line("    return v;");
    c.line("}");
    c.line("");
    c.line("static inline void kaya_wire_u32(KayaTx *tx, uint32_t v) {");
    c.line("    memcpy(tx->buf + tx->len, &v, 4);");
    c.line("    tx->len += 4;");
    c.line("}");
    c.line("");
    c.line("static inline void kaya_wire_u64(KayaTx *tx, uint64_t v) {");
    c.line("    memcpy(tx->buf + tx->len, &v, 8);");
    c.line("    tx->len += 8;");
    c.line("}");
    c.line("");
    c.line("static inline void kaya_wire_pad(KayaTx *tx) {");
    c.line("    while (tx->len % 8 != 0)");
    c.line("        tx->buf[tx->len++] = 0;");
    c.line("}");
    c.line("");
    c.line("/* Values are self-padded to 8: they concatenate inside bodies. */");
    c.line("static inline void kaya_wire_value(KayaTx *tx, KayaVal v) {");
    c.line("    kaya_wire_u32(tx, v.type);");
    c.line("    switch (v.type) {");
    c.line("    case KAYA_VALUE_BOOL:");
    c.line("        kaya_wire_u32(tx, 1);");
    c.line("        tx->buf[tx->len++] = (uint8_t)v.i;");
    c.line("        break;");
    c.line("    case KAYA_VALUE_I64:");
    c.line("    case KAYA_VALUE_BLOB: /* the u64 handle rides in i */");
    c.line("        kaya_wire_u32(tx, 8);");
    c.line("        memcpy(tx->buf + tx->len, &v.i, 8);");
    c.line("        tx->len += 8;");
    c.line("        break;");
    c.line("    case KAYA_VALUE_F64:");
    c.line("        kaya_wire_u32(tx, 8);");
    c.line("        memcpy(tx->buf + tx->len, &v.f, 8);");
    c.line("        tx->len += 8;");
    c.line("        break;");
    c.line("    default:");
    c.line("        kaya_wire_u32(tx, v.s_len);");
    c.line("        memcpy(tx->buf + tx->len, v.s, v.s_len);");
    c.line("        tx->len += v.s_len;");
    c.line("    }");
    c.line("    kaya_wire_pad(tx);");
    c.line("}");
    c.line("");
    c.line("/* A counted value sequence — a key path or a record: {u32 count,");
    c.line(" * u32 reserved, count values}. */");
    c.line("static inline void kaya_wire_values(KayaTx *tx, const KayaVal *vals, uint32_t n) {");
    c.line("    kaya_wire_u32(tx, n);");
    c.line("    kaya_wire_u32(tx, 0);");
    c.line("    for (uint32_t i = 0; i < n; i++)");
    c.line("        kaya_wire_value(tx, vals[i]);");
    c.line("}");
    c.line("");
    c.line("/* A collection schema: {u32 count, u32 reserved, count KAYA_VALUE_*");
    c.line(" * tags}, padded to 8. */");
    c.line("static inline void kaya_wire_variant_schemas(KayaTx *tx, const KayaVariantSchema *variants, uint32_t n) {");
    c.line("    kaya_wire_u32(tx, n);");
    c.line("    kaya_wire_u32(tx, 0);");
    c.line("    for (uint32_t i = 0; i < n; i++) {");
    c.line("        kaya_wire_u32(tx, variants[i].len);");
    c.line("        for (uint32_t j = 0; j < variants[i].len; j++)");
    c.line("            kaya_wire_u32(tx, variants[i].tags[j]);");
    c.line("    }");
    c.line("    kaya_wire_pad(tx);");
    c.line("}");
    c.line("");
    c.line("static inline size_t kaya_wire_begin(KayaTx *tx, uint16_t kind) {");
    c.line("    size_t start = tx->len;");
    c.line("    memset(tx->buf + tx->len, 0, 8);");
    c.line("    memcpy(tx->buf + tx->len + 4, &kind, 2);");
    c.line("    tx->len += 8;");
    c.line("    return start;");
    c.line("}");
    c.line("");
    c.line("static inline void kaya_wire_end(KayaTx *tx, size_t start) {");
    c.line("    kaya_wire_pad(tx);");
    c.line("    uint32_t size = (uint32_t)(tx->len - start);");
    c.line("    memcpy(tx->buf + start, &size, 4);");
    c.line("}");

    c.line(&format!("/* KAYA_SPEC_HASH: {}. */", "the protocol fingerprint; the runtime asserts the loaded core agrees"));
    c.line(&format!("#define KAYA_SPEC_HASH 0x{:016x}ULL", crate::spec_hash()));
    c.line("");
    for r in spec.tx {
        if r.name == "set_property" {
            continue;
        }
        let params = record_params(r);
        let mut sig: Vec<String> = vec!["KayaTx *tx".into()];
        for f in &params {
            sig.push(match f.ty {
                FieldTy::U32 => format!("uint32_t {}", f.name),
                FieldTy::U64 => format!("uint64_t {}", f.name),
                FieldTy::Value => format!("KayaVal {}", f.name),
                FieldTy::Values => format!("const KayaVal *{}, uint32_t {}_len", f.name, f.name),
                FieldTy::VariantSchemas => {
                    format!("const KayaVariantSchema *{}, uint32_t {}_len", f.name, f.name)
                }
            });
        }
        c.line("");
        c.line(&format!("/* {} */", r.doc.replace('\n', " ")));
        c.line(&format!(
            "static inline void kaya_tx_{}({}) {{",
            r.name,
            sig.join(", ")
        ));
        c.line(&format!(
            "    size_t start = kaya_wire_begin(tx, KAYA_TX_{});",
            r.name.to_uppercase()
        ));
        for f in r.fields {
            c.line(&match f.ty {
                FieldTy::U32 if f.name == "reserved" => "    kaya_wire_u32(tx, 0);".into(),
                FieldTy::U32 => format!("    kaya_wire_u32(tx, {});", f.name),
                FieldTy::U64 => format!("    kaya_wire_u64(tx, {});", f.name),
                FieldTy::Value => format!("    kaya_wire_value(tx, {});", f.name),
                FieldTy::Values => {
                    format!("    kaya_wire_values(tx, {}, {}_len);", f.name, f.name)
                }
                FieldTy::VariantSchemas => {
                    format!("    kaya_wire_variant_schemas(tx, {}, {}_len);", f.name, f.name)
                }
            });
        }
        c.line("    kaya_wire_end(tx, start);");
        c.line("}");
    }

    // The set_property arms, one trio per property: spec-driven so new
    // props reach every binding without emitter edits. The constant arm
    // takes a KayaVal; strings stay the common case via kaya_str.
    for (prop, _, kind) in prop_variants(spec) {
        let up = prop.to_uppercase();
        // Blob setters take the u64 kaya_blob_register handle (see
        // kaya_blob), so the parameter says so.
        let (ty, ctor, param) = match kind {
            crate::PropKind::Str => ("const char *", "kaya_str", *prop),
            crate::PropKind::Bool => ("int ", "kaya_bool", *prop),
            crate::PropKind::F64 => ("double ", "kaya_f64", *prop),
            crate::PropKind::Blob => ("uint64_t ", "kaya_blob", "handle"),
            // Enum props ride I64; the KAYA_<ENUM>_* constants are the
            // domain, generated above from the spec enum.
            crate::PropKind::Enum(_) => ("int64_t ", "kaya_i64", *prop),
        };
        c.line("");
        c.line(&format!("/* set_property with a constant {prop} value. */"));
        c.line(&format!("static inline void kaya_tx_set_{prop}(KayaTx *tx, uint64_t widget_id, {ty}{param}) {{"));
        c.line("    size_t start = kaya_wire_begin(tx, KAYA_TX_SET_PROPERTY);");
        c.line("    kaya_wire_u64(tx, widget_id);");
        c.line(&format!("    kaya_wire_u32(tx, KAYA_PROP_{up});"));
        c.line("    kaya_wire_u32(tx, KAYA_SOURCE_CONST);");
        c.line(&format!("    kaya_wire_value(tx, {ctor}({param}));"));
        c.line("    kaya_wire_end(tx, start);");
        c.line("}");
        c.line("");
        c.line(&format!("/* set_property with a signal-bound {prop} value. */"));
        c.line(&format!("static inline void kaya_tx_bind_{prop}(KayaTx *tx, uint64_t widget_id, uint64_t signal_id) {{"));
        c.line("    size_t start = kaya_wire_begin(tx, KAYA_TX_SET_PROPERTY);");
        c.line("    kaya_wire_u64(tx, widget_id);");
        c.line(&format!("    kaya_wire_u32(tx, KAYA_PROP_{up});"));
        c.line("    kaya_wire_u32(tx, KAYA_SOURCE_SIGNAL);");
        c.line("    kaya_wire_u64(tx, signal_id);");
        c.line("    kaya_wire_end(tx, start);");
        c.line("}");
        c.line("");
        c.line("/* set_property bound to one field of the element of the enclosing");
        c.line(" * For, `level` Fors up (field 0 for a scalar collection). */");
        c.line(&format!("static inline void kaya_tx_bind_{prop}_element(KayaTx *tx, uint64_t widget_id, uint32_t level, uint32_t field) {{"));
        c.line("    size_t start = kaya_wire_begin(tx, KAYA_TX_SET_PROPERTY);");
        c.line("    kaya_wire_u64(tx, widget_id);");
        c.line(&format!("    kaya_wire_u32(tx, KAYA_PROP_{up});"));
        c.line("    kaya_wire_u32(tx, KAYA_SOURCE_ELEMENT);");
        c.line("    kaya_wire_u32(tx, level);");
        c.line("    kaya_wire_u32(tx, field);");
        c.line("    kaya_wire_end(tx, start);");
        c.line("}");
    }
    c.line("");
    c.line("/* Decode one value at `at`; returns the next offset. */");
    c.line("static inline size_t kaya_parse_value(const uint8_t *buf, size_t at, KayaVal *out) {");
    c.line("    memcpy(&out->type, buf + at, 4);");
    c.line("    uint32_t len;");
    c.line("    memcpy(&len, buf + at + 4, 4);");
    c.line("    out->i = 0;");
    c.line("    out->f = 0;");
    c.line("    out->s = 0;");
    c.line("    out->s_len = 0;");
    c.line("    switch (out->type) {");
    c.line("    case KAYA_VALUE_BOOL:");
    c.line("        out->i = buf[at + 8];");
    c.line("        break;");
    c.line("    case KAYA_VALUE_I64:");
    c.line("    case KAYA_VALUE_BLOB:");
    c.line("        memcpy(&out->i, buf + at + 8, 8);");
    c.line("        break;");
    c.line("    case KAYA_VALUE_F64:");
    c.line("        memcpy(&out->f, buf + at + 8, 8);");
    c.line("        break;");
    c.line("    default:");
    c.line("        out->s = (const char *)(buf + at + 8);");
    c.line("        out->s_len = len;");
    c.line("    }");
    c.line("    return at + 8 + ((len + 7) & ~7u);");
    c.line("}");
    c.line("");
    c.line("/* Decode one occurrence record (header included). Returns 1 for a");
    c.line(" * click, filling id and up to max_keys of the copy's key path");
    c.line(" * (empty for a click on a guest-created widget); 0 otherwise. */");
    c.line("static inline int kaya_parse_click(const uint8_t *rec, uint64_t *id,");
    c.line("                                   KayaVal *keys, uint32_t max_keys,");
    c.line("                                   uint32_t *n_keys) {");
    c.line("    const KayaRecordButtonClicked *r = (const KayaRecordButtonClicked *)rec;");
    c.line("    if (r->header.kind != KAYA_OCCURRENCE_BUTTON_CLICKED)");
    c.line("        return 0;");
    c.line("    *id = r->id;");
    c.line("    *n_keys = r->path_len;");
    c.line("    size_t at = sizeof(KayaRecordButtonClicked);");
    c.line("    for (uint32_t k = 0; k < r->path_len && k < max_keys; k++)");
    c.line("        at = kaya_parse_value(rec, at, &keys[k]);");
    c.line("    return 1;");
    c.line("}");
    c.line("");
    // One parse helper per payload-carrying occurrence, from the spec's
    // Record::payload — the kind list derives rather than drifts. The
    // payload lands in a KayaVal, kaya_parse_value's generic decode.
    for r in spec.occurrence.iter().filter(|r| r.payload.is_some()) {
        let name = r.name;
        let up = name.to_uppercase();
        let pad = " ".repeat(31 + name.len());
        c.line(&format!(
            "/* Decode a {name} occurrence: same identity head as a click, then"
        ));
        c.line(&format!(
            " * its payload as one {:?} value (strings point into rec). Returns 1",
            r.payload.unwrap()
        ));
        c.line(" * and fills the outputs, or 0 for other kinds. */");
        c.line(&format!(
            "static inline int kaya_parse_{name}(const uint8_t *rec, uint64_t *id,"
        ));
        c.line(&format!("{pad}KayaVal *keys, uint32_t max_keys,"));
        c.line(&format!("{pad}uint32_t *n_keys, KayaVal *payload) {{"));
        c.line("    const KayaRecordButtonClicked *r = (const KayaRecordButtonClicked *)rec;");
        c.line(&format!("    if (r->header.kind != KAYA_OCCURRENCE_{up})"));
        c.line("        return 0;");
        c.line("    *id = r->id;");
        c.line("    *n_keys = r->path_len;");
        c.line("    size_t at = sizeof(KayaRecordButtonClicked);");
        c.line("    for (uint32_t k = 0; k < r->path_len && k < max_keys; k++)");
        c.line("        at = kaya_parse_value(rec, at, &keys[k]);");
        c.line("    kaya_parse_value(rec, at, payload);");
        c.line("    return 1;");
        c.line("}");
        c.line("");
    }
    c.line("#endif /* KAYA_WIRE_H */");
    c.out
}
