//! C# emitter: a static KayaWire class of constants, packers, and the
//! occurrence parser. The class namespaces everything; encoder helpers
//! are private, so shadowing is impossible and the reserved set is
//! keywords plus nothing.

use kaya::spec::{FieldTy, ProtocolSpec, Record};

use crate::{Ctx, prop_variants, record_params, window_prop_variants};

pub const RESERVED: &[&str] = &[
    "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked",
    "class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else",
    "enum", "event", "explicit", "extern", "false", "finally", "fixed", "float", "for",
    "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock",
    "long", "namespace", "new", "null", "object", "operator", "out", "override", "params",
    "private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed", "short",
    "sizeof", "stackalloc", "static", "string", "struct", "switch", "this", "throw", "true",
    "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using", "virtual",
    "void", "volatile", "while",
];

fn pascal(name: &str) -> String {
    name.split('_')
        .map(|w| {
            let mut chars = w.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

fn camel(name: &str) -> String {
    let p = pascal(name);
    let mut chars = p.chars();
    let lowered = match chars.next() {
        Some(first) => first.to_lowercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    };
    // C# keywords are all lowercase, so only camel-cased identifiers can
    // collide; @ makes any keyword a plain identifier ("checked" is a
    // spec prop). This is why csharp is exempt from the reserved-name
    // assert in main.rs.
    if RESERVED.contains(&lowered.as_str()) {
        format!("@{lowered}")
    } else {
        lowered
    }
}

#[cfg(test)]
mod tests {
    use super::camel;

    /// The prop named "checked" must come out escaped, or TxSetChecked
    /// fails to compile in every C# guest (found by the mac suite,
    /// 2026-07-15).
    #[test]
    fn camel_escapes_csharp_keywords() {
        assert_eq!(camel("checked"), "@checked");
        assert_eq!(camel("text"), "text");
    }
}

pub fn emit(spec: &ProtocolSpec) -> String {
    let mut c = Ctx { out: String::new() };
    c.line("// kaya wire vocabulary. Generated by kaya-bindgen from kaya::spec — do not edit.");
    c.line("//");
    c.line("// Records are {u32 size, u16 kind, u16 flags}, body, padded to 8,");
    c.line("// little-endian. Values accept C# bool, long, double, string, and");
    c.line("// BlobHandle, mapped to the kaya value types; keys in paths likewise.");
    c.line("");
    c.line("using System;");
    c.line("using System.Collections.Generic;");
    c.line("using System.IO;");
    c.line("using System.Text;");
    c.line("");
    c.line("static class KayaWire");
    c.line("{");
    c.line(&format!("    // SpecHash: {}.", "the protocol fingerprint; the runtime asserts the loaded core agrees"));
    c.line(&format!("    public const ulong SpecHash = 0x{:016x};", crate::spec_hash()));
    c.line("");
    for e in spec.enums {
        for (name, value) in e.variants {
            c.line(&format!(
                "    public const uint {}{} = {};",
                pascal(e.name),
                pascal(name),
                value
            ));
        }
    }
    for (channel, records) in [("Tx", spec.tx), ("Apply", spec.apply), ("Occ", spec.occurrence)] {
        for r in records {
            c.line(&format!(
                "    public const ushort {channel}Kind{} = {};",
                pascal(r.name),
                r.kind
            ));
        }
    }
    c.line("");
    c.line("    /// A blob value: the u64 handle from kaya_blob_register, consumed");
    c.line("    /// by the next submit; the bytes never ride the record stream.");
    c.line("    public readonly struct BlobHandle");
    c.line("    {");
    c.line("        public readonly ulong Handle;");
    c.line("        public BlobHandle(ulong handle) { Handle = handle; }");
    c.line("    }");
    c.line("");
    c.line("    static void Pad(BinaryWriter w)");
    c.line("    {");
    c.line("        while (w.BaseStream.Position % 8 != 0)");
    c.line("            w.Write((byte)0);");
    c.line("    }");
    c.line("");
    c.line("    // Values self-pad to 8: they concatenate inside record bodies.");
    c.line("    static void EncodeValue(BinaryWriter w, object v)");
    c.line("    {");
    c.line("        switch (v)");
    c.line("        {");
    c.line("            case bool b:");
    c.line("                w.Write(ValueBool); w.Write(1u); w.Write((byte)(b ? 1 : 0));");
    c.line("                break;");
    c.line("            case int i:");
    c.line("                w.Write(ValueI64); w.Write(8u); w.Write((long)i);");
    c.line("                break;");
    c.line("            case long l:");
    c.line("                w.Write(ValueI64); w.Write(8u); w.Write(l);");
    c.line("                break;");
    c.line("            case double d:");
    c.line("                w.Write(ValueF64); w.Write(8u); w.Write(d);");
    c.line("                break;");
    c.line("            case string s:");
    c.line("                byte[] utf8 = Encoding.UTF8.GetBytes(s);");
    c.line("                w.Write(ValueStr); w.Write((uint)utf8.Length); w.Write(utf8);");
    c.line("                break;");
    c.line("            case BlobHandle h:");
    c.line("                w.Write(ValueBlob); w.Write(8u); w.Write(h.Handle);");
    c.line("                break;");
    c.line("            default:");
    c.line("                throw new ArgumentException(\"kaya: value must be bool, long, double, string, or BlobHandle\");");
    c.line("        }");
    c.line("        Pad(w);");
    c.line("    }");
    c.line("");
    c.line("    // A counted value sequence — a key path or a record:");
    c.line("    // {u32 count, u32 reserved, count values}.");
    c.line("    static void EncodeValues(BinaryWriter w, object[] vals)");
    c.line("    {");
    c.line("        w.Write((uint)(vals?.Length ?? 0));");
    c.line("        w.Write(0u);");
    c.line("        foreach (object v in vals ?? Array.Empty<object>())");
    c.line("            EncodeValue(w, v);");
    c.line("    }");
    c.line("");
    c.line("    // A collection schema: {u32 count, u32 reserved, count Value* tags},");
    c.line("    // padded to 8.");
    c.line("    static void EncodeVariantSchemas(BinaryWriter w, uint[][] variants)");
    c.line("    {");
    c.line("        w.Write((uint)variants.Length);");
    c.line("        w.Write(0u);");
    c.line("        foreach (uint[] schema in variants)");
    c.line("        {");
    c.line("            w.Write((uint)schema.Length);");
    c.line("            foreach (uint t in schema)");
    c.line("                w.Write(t);");
    c.line("        }");
    c.line("        Pad(w);");
    c.line("    }");
    c.line("");
    c.line("    static byte[] Finish(MemoryStream stream, BinaryWriter w, ushort kind)");
    c.line("    {");
    c.line("        Pad(w);");
    c.line("        byte[] rec = stream.ToArray();");
    c.line("        BitConverter.GetBytes((uint)rec.Length).CopyTo(rec, 0);");
    c.line("        BitConverter.GetBytes(kind).CopyTo(rec, 4);");
    c.line("        return rec;");
    c.line("    }");
    c.line("");
    c.line("    static BinaryWriter Begin(out MemoryStream stream)");
    c.line("    {");
    c.line("        stream = new MemoryStream();");
    c.line("        var w = new BinaryWriter(stream);");
    c.line("        w.Write(0u); w.Write((ushort)0); w.Write((ushort)0);");
    c.line("        return w;");
    c.line("    }");

    for r in spec.tx {
        if r.name == "set_property" || r.name == "set_window_prop" {
            continue;
        }
        emit_packer(&mut c, r);
    }

    // The set_property arms, one trio per property: spec-driven so new
    // props reach every binding without emitter edits.
    for (prop, _, kind) in prop_variants(spec) {
        let pc = pascal(prop);
        // Blob setters take the u64 kaya_blob_register handle (see
        // BlobHandle), so the parameter says so.
        let (p, ty, expr) = match kind {
            crate::PropKind::Str => (camel(prop), "string", format!("EncodeValue(w, {});", camel(prop))),
            crate::PropKind::Bool => (camel(prop), "bool", format!("EncodeValue(w, {});", camel(prop))),
            crate::PropKind::F64 => (camel(prop), "double", format!("EncodeValue(w, {});", camel(prop))),
            crate::PropKind::Blob => (
                "handle".to_string(),
                "ulong",
                "EncodeValue(w, new BlobHandle(handle));".to_string(),
            ),
            crate::PropKind::Enum(_) => (
                camel(prop),
                "long",
                format!("EncodeValue(w, {});", camel(prop)),
            ),
        };
        c.line("");
        c.line(&format!("    /// set_property with a constant {prop} value."));
        c.line(&format!("    public static byte[] TxSet{pc}(ulong widgetId, {ty} {p})"));
        c.line("    {");
        c.line("        var w = Begin(out var stream);");
        c.line(&format!("        w.Write(widgetId); w.Write(Prop{pc}); w.Write(SourceConst);"));
        c.line(&format!("        {expr}"));
        c.line("        return Finish(stream, w, TxKindSetProperty);");
        c.line("    }");
        c.line("");
        c.line(&format!("    /// set_property with a signal-bound {prop} value."));
        c.line(&format!("    public static byte[] TxBind{pc}(ulong widgetId, ulong signalId)"));
        c.line("    {");
        c.line("        var w = Begin(out var stream);");
        c.line(&format!("        w.Write(widgetId); w.Write(Prop{pc}); w.Write(SourceSignal); w.Write(signalId);"));
        c.line("        return Finish(stream, w, TxKindSetProperty);");
        c.line("    }");
        c.line("");
        c.line("    /// set_property bound to one field of the element of the enclosing For.");
        c.line(&format!("    public static byte[] TxBind{pc}Element(ulong widgetId, uint level = 0, uint field = 0)"));
        c.line("    {");
        c.line("        var w = Begin(out var stream);");
        c.line(&format!("        w.Write(widgetId); w.Write(Prop{pc}); w.Write(SourceElement); w.Write(level); w.Write(field);"));
        c.line("        return Finish(stream, w, TxKindSetProperty);");
        c.line("    }");
    }

    // The window-prop duos (const + signal — element sources are
    // rejected by the wire). Window 0, the primary surface, until aux
    // windows land.
    for (prop, _, kind) in window_prop_variants(spec) {
        let pc = pascal(prop);
        let (p, ty, expr) = match kind {
            crate::PropKind::Str => (camel(prop), "string", format!("EncodeValue(w, {});", camel(prop))),
            crate::PropKind::F64 => (camel(prop), "double", format!("EncodeValue(w, {});", camel(prop))),
            crate::PropKind::Bool => (camel(prop), "bool", format!("EncodeValue(w, {});", camel(prop))),
            other => unreachable!("no window prop carries {other:?}"),
        };
        c.line("");
        c.line(&format!("    /// set_window_prop with a constant {prop} value (window 0, the primary surface)."));
        c.line(&format!("    public static byte[] TxSetWindow{pc}(ulong window, {ty} {p})"));
        c.line("    {");
        c.line("        var w = Begin(out var stream);");
        c.line(&format!("        w.Write(window); w.Write(Wprop{pc}); w.Write(SourceConst);"));
        c.line(&format!("        {expr}"));
        c.line("        return Finish(stream, w, TxKindSetWindowProp);");
        c.line("    }");
        c.line("");
        c.line(&format!("    /// set_window_prop with a signal-bound {prop} value (window 0, the primary surface)."));
        c.line(&format!("    public static byte[] TxBindWindow{pc}(ulong window, ulong signalId)"));
        c.line("    {");
        c.line("        var w = Begin(out var stream);");
        c.line(&format!("        w.Write(window); w.Write(Wprop{pc}); w.Write(SourceSignal); w.Write(signalId);"));
        c.line("        return Finish(stream, w, TxKindSetWindowProp);");
        c.line("    }");
    }
    c.line("");
    c.line("    /// Decode one occurrence record (header included). Returns false");
    c.line("    /// for non-click records. keys is empty for a click on a");
    c.line("    /// guest-created widget (id is a widget id); otherwise id is a");
    c.line("    /// template node id and keys is the copy's key path.");
    c.line("    public static bool ParseOccurrence(");
    c.line("        byte[] rec, out ushort kind, out ulong id, out List<object> keys, out object payload)");
    c.line("    {");
    c.line("        id = 0;");
    c.line("        keys = new List<object>();");
    c.line("        payload = null;");
    c.line("        kind = BitConverter.ToUInt16(rec, 4);");
    let accepted = crate::occurrence_names(spec)
        .iter()
        .map(|n| format!("kind != OccKind{}", pascal(n)))
        .collect::<Vec<_>>()
        .join(" && ");
    c.line(&format!("        if ({accepted})"));
    c.line("            return false;");
    c.line("        id = BitConverter.ToUInt64(rec, 8);");
    c.line("        uint pathLen = BitConverter.ToUInt32(rec, 16);");
    c.line("        int at = 24;");
    c.line("        for (uint i = 0; i < pathLen; i++)");
    c.line("        {");
    c.line("            uint vtype = BitConverter.ToUInt32(rec, at);");
    c.line("            int vlen = BitConverter.ToInt32(rec, at + 4);");
    c.line("            switch (vtype)");
    c.line("            {");
    c.line("                case ValueBool: keys.Add(rec[at + 8] != 0); break;");
    c.line("                case ValueI64: keys.Add(BitConverter.ToInt64(rec, at + 8)); break;");
    c.line("                case ValueF64: keys.Add(BitConverter.ToDouble(rec, at + 8)); break;");
    c.line("                default: keys.Add(Encoding.UTF8.GetString(rec, at + 8, vlen)); break;");
    c.line("            }");
    c.line("            at += 8 + ((vlen + 7) & ~7);");
    c.line("        }");
    let with_payload = crate::payload_occurrence_names(spec)
        .iter()
        .map(|n| format!("kind == OccKind{}", pascal(n)))
        .collect::<Vec<_>>()
        .join(" || ");
    c.line(&format!("        if ({with_payload})"));
    c.line("        {");
    // Type-generic payload decode, same shape as the key loop: no
    // per-kind logic left to drift.
    c.line("            uint ptype = BitConverter.ToUInt32(rec, at);");
    c.line("            int plen = BitConverter.ToInt32(rec, at + 4);");
    c.line("            switch (ptype)");
    c.line("            {");
    c.line("                case ValueBool: payload = rec[at + 8] != 0; break;");
    c.line("                case ValueI64: payload = BitConverter.ToInt64(rec, at + 8); break;");
    c.line("                case ValueF64: payload = BitConverter.ToDouble(rec, at + 8); break;");
    c.line("                default: payload = Encoding.UTF8.GetString(rec, at + 8, plen); break;");
    c.line("            }");
    c.line("        }");
    c.line("        return true;");
    c.line("    }");
    c.line("}");
    c.out
}

fn emit_packer(c: &mut Ctx, r: &Record) {
    let params = record_params(r);
    let mut sig: Vec<String> = Vec::new();
    for f in &params {
        sig.push(match f.ty {
            FieldTy::U32 => format!("uint {}", camel(f.name)),
            FieldTy::U64 => format!("ulong {}", camel(f.name)),
            FieldTy::Value => format!("object {}", camel(f.name)),
            FieldTy::Values => format!("object[] {}", camel(f.name)),
            FieldTy::VariantSchemas => format!("uint[][] {}", camel(f.name)),
        });
    }
    c.line("");
    c.line(&format!("    /// {}", r.doc.replace('\n', " ")));
    c.line(&format!(
        "    public static byte[] Tx{}({})",
        pascal(r.name),
        sig.join(", ")
    ));
    c.line("    {");
    c.line("        var w = Begin(out var stream);");
    for f in r.fields {
        c.line(&match f.ty {
            FieldTy::U32 if f.name == "reserved" => "        w.Write(0u);".into(),
            FieldTy::U32 => format!("        w.Write({});", camel(f.name)),
            FieldTy::U64 => format!("        w.Write({});", camel(f.name)),
            FieldTy::Value => format!("        EncodeValue(w, {});", camel(f.name)),
            FieldTy::Values => format!("        EncodeValues(w, {});", camel(f.name)),
            FieldTy::VariantSchemas => format!("        EncodeVariantSchemas(w, {});", camel(f.name)),
        });
    }
    c.line(&format!(
        "        return Finish(stream, w, TxKind{});",
        pascal(r.name)
    ));
    c.line("    }");
}
