//! Go emitter: the generated half of package kaya (bindings/go). The
//! hand-written runtime (runtime.go, same package) carries cgo, the
//! ring consumer, and Submit/Run; this file is constants and packers.
//! Package scope namespaces everything for consumers; internally,
//! helpers are lowercase (unexported) and generated parameters are
//! locals, so the reserved set is keywords plus the helper names.

use kaya::spec::{FieldTy, ProtocolSpec, Record};

use crate::{Ctx, record_params};

pub const RESERVED: &[&str] = &[
    "encodeValue", "encodePath", "beginRecord", "endRecord", "ParseOccurrence",
    "break", "case", "chan", "const", "continue", "default", "defer", "else", "fallthrough",
    "for", "func", "go", "goto", "if", "import", "interface", "map", "package", "range",
    "return", "select", "struct", "switch", "type", "var",
];

fn camel(name: &str) -> String {
    name.split('_')
        .map(|w| {
            let mut chars = w.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

fn param(name: &str) -> String {
    // Lower camel for parameters; `id` and friends survive as-is.
    let c = camel(name);
    let mut chars = c.chars();
    match chars.next() {
        Some(first) => first.to_lowercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    }
}

pub fn emit(spec: &ProtocolSpec) -> String {
    let mut c = Ctx { out: String::new() };
    c.line("// kaya wire vocabulary. Generated by kaya-bindgen from kaya::spec — do not edit.");
    c.line("//");
    c.line("// Records are {u32 size, u16 kind, u16 flags}, body, padded to 8,");
    c.line("// little-endian. Values accept Go bool, int64, float64, and string,");
    c.line("// mapped to the kaya value types; keys in paths likewise.");
    c.line("package kaya");
    c.line("");
    c.line("import (");
    c.line("\t\"encoding/binary\"");
    c.line("\t\"math\"");
    c.line(")");
    c.line("");
    c.line("const (");
    for e in spec.enums {
        for (name, value) in e.variants {
            c.line(&format!("\t{}{} = {}", camel(e.name), camel(name), value));
        }
    }
    for (channel, records) in [("Tx", spec.tx), ("Apply", spec.apply), ("Occ", spec.occurrence)] {
        for r in records {
            c.line(&format!("\t{}{} = {}", channel.to_lowercase(), camel(r.name), r.kind));
        }
    }
    c.line(")");
    c.line("");
    c.line("func pad8(b []byte) []byte {");
    c.line("\tfor len(b)%8 != 0 {");
    c.line("\t\tb = append(b, 0)");
    c.line("\t}");
    c.line("\treturn b");
    c.line("}");
    c.line("");
    c.line("// encodeValue appends one kaya value; values self-pad to 8 because");
    c.line("// they concatenate inside record bodies.");
    c.line("func encodeValue(b []byte, v any) []byte {");
    c.line("\tswitch x := v.(type) {");
    c.line("\tcase bool:");
    c.line("\t\tb = binary.LittleEndian.AppendUint32(b, ValueBool)");
    c.line("\t\tb = binary.LittleEndian.AppendUint32(b, 1)");
    c.line("\t\tif x {");
    c.line("\t\t\tb = append(b, 1)");
    c.line("\t\t} else {");
    c.line("\t\t\tb = append(b, 0)");
    c.line("\t\t}");
    c.line("\tcase int:");
    c.line("\t\treturn encodeValue(b, int64(x))");
    c.line("\tcase int64:");
    c.line("\t\tb = binary.LittleEndian.AppendUint32(b, ValueI64)");
    c.line("\t\tb = binary.LittleEndian.AppendUint32(b, 8)");
    c.line("\t\tb = binary.LittleEndian.AppendUint64(b, uint64(x))");
    c.line("\tcase float64:");
    c.line("\t\tb = binary.LittleEndian.AppendUint32(b, ValueF64)");
    c.line("\t\tb = binary.LittleEndian.AppendUint32(b, 8)");
    c.line("\t\tb = binary.LittleEndian.AppendUint64(b, math.Float64bits(x))");
    c.line("\tcase string:");
    c.line("\t\tb = binary.LittleEndian.AppendUint32(b, ValueStr)");
    c.line("\t\tb = binary.LittleEndian.AppendUint32(b, uint32(len(x)))");
    c.line("\t\tb = append(b, x...)");
    c.line("\tdefault:");
    c.line("\t\tpanic(\"kaya: value must be bool, int64, float64, or string\")");
    c.line("\t}");
    c.line("\treturn pad8(b)");
    c.line("}");
    c.line("");
    c.line("// encodePath appends a key path: {u32 count, u32 reserved, count values}.");
    c.line("func encodePath(b []byte, keys []any) []byte {");
    c.line("\tb = binary.LittleEndian.AppendUint32(b, uint32(len(keys)))");
    c.line("\tb = binary.LittleEndian.AppendUint32(b, 0)");
    c.line("\tfor _, k := range keys {");
    c.line("\t\tb = encodeValue(b, k)");
    c.line("\t}");
    c.line("\treturn b");
    c.line("}");
    c.line("");
    c.line("func beginRecord(kind uint16) []byte {");
    c.line("\tb := make([]byte, 0, 64)");
    c.line("\tb = append(b, 0, 0, 0, 0)");
    c.line("\tb = binary.LittleEndian.AppendUint16(b, kind)");
    c.line("\treturn append(b, 0, 0)");
    c.line("}");
    c.line("");
    c.line("func endRecord(b []byte) []byte {");
    c.line("\tb = pad8(b)");
    c.line("\tbinary.LittleEndian.PutUint32(b, uint32(len(b)))");
    c.line("\treturn b");
    c.line("}");

    for r in spec.tx {
        if r.name == "set_property" {
            continue;
        }
        emit_packer(&mut c, r);
    }

    c.line("");
    c.line("// TxSetText: set_property with a constant text value.");
    c.line("func TxSetText(widgetID uint64, text string) []byte {");
    c.line("\tb := beginRecord(txSetProperty)");
    c.line("\tb = binary.LittleEndian.AppendUint64(b, widgetID)");
    c.line("\tb = binary.LittleEndian.AppendUint32(b, PropText)");
    c.line("\tb = binary.LittleEndian.AppendUint32(b, SourceConst)");
    c.line("\tb = encodeValue(b, text)");
    c.line("\treturn endRecord(b)");
    c.line("}");
    c.line("");
    c.line("// TxBindText: set_property with a signal-bound text value.");
    c.line("func TxBindText(widgetID uint64, signalID uint64) []byte {");
    c.line("\tb := beginRecord(txSetProperty)");
    c.line("\tb = binary.LittleEndian.AppendUint64(b, widgetID)");
    c.line("\tb = binary.LittleEndian.AppendUint32(b, PropText)");
    c.line("\tb = binary.LittleEndian.AppendUint32(b, SourceSignal)");
    c.line("\tb = binary.LittleEndian.AppendUint64(b, signalID)");
    c.line("\treturn endRecord(b)");
    c.line("}");
    c.line("");
    c.line("// TxBindTextElement: set_property bound to the element of the");
    c.line("// enclosing For, `level` Fors up (0 = nearest).");
    c.line("func TxBindTextElement(widgetID uint64, level uint32) []byte {");
    c.line("\tb := beginRecord(txSetProperty)");
    c.line("\tb = binary.LittleEndian.AppendUint64(b, widgetID)");
    c.line("\tb = binary.LittleEndian.AppendUint32(b, PropText)");
    c.line("\tb = binary.LittleEndian.AppendUint32(b, SourceElement)");
    c.line("\tb = binary.LittleEndian.AppendUint32(b, level)");
    c.line("\tb = binary.LittleEndian.AppendUint32(b, 0)");
    c.line("\treturn endRecord(b)");
    c.line("}");
    c.line("");
    c.line("// ParseOccurrence decodes one occurrence record (header included).");
    c.line("// keys is nil for a click on a guest-created widget (id is a widget");
    c.line("// id); otherwise id is a template node id and keys is the copy's key");
    c.line("// path, outermost first. ok is false for non-click records.");
    c.line("func ParseOccurrence(rec []byte) (id uint64, keys []any, ok bool) {");
    c.line("\tif binary.LittleEndian.Uint16(rec[4:]) != occButtonClicked {");
    c.line("\t\treturn 0, nil, false");
    c.line("\t}");
    c.line("\tid = binary.LittleEndian.Uint64(rec[8:])");
    c.line("\tpathLen := binary.LittleEndian.Uint32(rec[16:])");
    c.line("\tat := 24");
    c.line("\tfor i := uint32(0); i < pathLen; i++ {");
    c.line("\t\tvtype := binary.LittleEndian.Uint32(rec[at:])");
    c.line("\t\tvlen := int(binary.LittleEndian.Uint32(rec[at+4:]))");
    c.line("\t\tpayload := rec[at+8 : at+8+vlen]");
    c.line("\t\tswitch vtype {");
    c.line("\t\tcase ValueBool:");
    c.line("\t\t\tkeys = append(keys, payload[0] != 0)");
    c.line("\t\tcase ValueI64:");
    c.line("\t\t\tkeys = append(keys, int64(binary.LittleEndian.Uint64(payload)))");
    c.line("\t\tcase ValueF64:");
    c.line("\t\t\tkeys = append(keys, math.Float64frombits(binary.LittleEndian.Uint64(payload)))");
    c.line("\t\tdefault:");
    c.line("\t\t\tkeys = append(keys, string(payload))");
    c.line("\t\t}");
    c.line("\t\tat += 8 + (vlen+7)&^7");
    c.line("\t}");
    c.line("\treturn id, keys, true");
    c.line("}");
    c.out
}

fn emit_packer(c: &mut Ctx, r: &Record) {
    let params = record_params(r);
    let mut sig: Vec<String> = Vec::new();
    for f in &params {
        sig.push(match f.ty {
            FieldTy::U32 => format!("{} uint32", param(f.name)),
            FieldTy::U64 => format!("{} uint64", param(f.name)),
            FieldTy::Value => format!("{} any", param(f.name)),
            FieldTy::Path => format!("{} []any", param(f.name)),
        });
    }
    c.line("");
    c.line(&format!("// Tx{}: {}", camel(r.name), r.doc.replace('\n', " ")));
    c.line(&format!(
        "func Tx{}({}) []byte {{",
        camel(r.name),
        sig.join(", ")
    ));
    c.line(&format!("\tb := beginRecord(tx{})", camel(r.name)));
    for f in r.fields {
        c.line(&match f.ty {
            FieldTy::U32 if f.name == "reserved" => {
                "\tb = binary.LittleEndian.AppendUint32(b, 0)".into()
            }
            FieldTy::U32 => format!(
                "\tb = binary.LittleEndian.AppendUint32(b, {})",
                param(f.name)
            ),
            FieldTy::U64 => format!(
                "\tb = binary.LittleEndian.AppendUint64(b, {})",
                param(f.name)
            ),
            FieldTy::Value => format!("\tb = encodeValue(b, {})", param(f.name)),
            FieldTy::Path => format!("\tb = encodePath(b, {})", param(f.name)),
        });
    }
    c.line("\treturn endRecord(b)");
    c.line("}");
}
