//! Go emitter: the generated half of package kaya (bindings/go) —
//! constants and packers. runtime.go, the hand-written half of the same
//! package, carries cgo, the ring consumer, and Submit/Run.

use kaya::spec::{FieldTy, ProtocolSpec, Record};

use crate::{Ctx, is_padding, prop_variants, record_params, window_prop_variants};

pub const RESERVED: &[&str] = &[
    "encodeValue", "encodeValues", "encodeVariantSchemas", "beginRecord", "endRecord", "ParseOccurrence", "BlobHandle",
    "CanonicalizeShortcut", "shortcutNamedKeys",
    "break", "case", "chan", "const", "continue", "default", "defer", "else", "fallthrough",
    "for", "func", "go", "goto", "if", "import", "interface", "map", "package", "range",
    "return", "select", "struct", "switch", "type", "var",
];

fn camel(name: &str) -> String {
    name.split('_')
        .map(|w| {
            let mut chars = w.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

fn param(name: &str) -> String {
    // Lower camel for parameters; `id` and friends survive as-is.
    let c = camel(name);
    let mut chars = c.chars();
    match chars.next() {
        Some(first) => first.to_lowercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    }
}

pub fn emit(spec: &ProtocolSpec) -> String {
    let mut c = Ctx { out: String::new() };
    c.line("// kaya wire vocabulary. Generated by kaya-bindgen from kaya::spec — do not edit.");
    c.line("//");
    c.line("// Records are {u32 size, u16 kind, u16 flags}, body, padded to 8,");
    c.line("// little-endian. Values accept Go bool, int64, float64, string, and");
    c.line("// BlobHandle, mapped to the kaya value types; keys in paths likewise.");
    c.line("package kaya");
    c.line("");
    c.line("import (");
    c.line("\t\"encoding/binary\"");
    c.line("\t\"math\"");
    c.line("\t\"strconv\"");
    c.line("\t\"strings\"");
    c.line(")");
    c.line("");
    c.line("const (");
    c.line("\t// SpecHash: the protocol fingerprint; the runtime asserts the loaded core agrees.");
    c.line(&format!("\tSpecHash uint64 = 0x{:016x}", crate::spec_hash()));
    c.line("");
    for e in spec.enums {
        for (name, value) in e.variants {
            c.line(&format!("\t{}{} = {}", camel(e.name), camel(name), value));
        }
    }
    for (channel, records) in [("Tx", spec.tx), ("Apply", spec.apply), ("Occ", spec.occurrence)] {
        for r in records {
            c.line(&format!("\t{}{} = {}", channel.to_lowercase(), camel(r.name), r.kind));
        }
    }
    c.line(")");
    c.line("");
    c.line("func pad8(b []byte) []byte {");
    c.line("\tfor len(b)%8 != 0 {");
    c.line("\t\tb = append(b, 0)");
    c.line("\t}");
    c.line("\treturn b");
    c.line("}");
    c.line("");
    c.line("// BlobHandle marks a u64 handle from kaya_blob_register as a blob");
    c.line("// value, consumed by the next submit; the bytes never ride the");
    c.line("// record stream.");
    c.line("type BlobHandle uint64");
    c.line("");
    c.line("// encodeValue appends one kaya value; values self-pad to 8 because");
    c.line("// they concatenate inside record bodies.");
    c.line("func encodeValue(b []byte, v any) []byte {");
    c.line("\tswitch x := v.(type) {");
    c.line("\tcase bool:");
    c.line("\t\tb = binary.LittleEndian.AppendUint32(b, ValueBool)");
    c.line("\t\tb = binary.LittleEndian.AppendUint32(b, 1)");
    c.line("\t\tif x {");
    c.line("\t\t\tb = append(b, 1)");
    c.line("\t\t} else {");
    c.line("\t\t\tb = append(b, 0)");
    c.line("\t\t}");
    c.line("\tcase int:");
    c.line("\t\treturn encodeValue(b, int64(x))");
    c.line("\tcase int64:");
    c.line("\t\tb = binary.LittleEndian.AppendUint32(b, ValueI64)");
    c.line("\t\tb = binary.LittleEndian.AppendUint32(b, 8)");
    c.line("\t\tb = binary.LittleEndian.AppendUint64(b, uint64(x))");
    c.line("\tcase float64:");
    c.line("\t\tb = binary.LittleEndian.AppendUint32(b, ValueF64)");
    c.line("\t\tb = binary.LittleEndian.AppendUint32(b, 8)");
    c.line("\t\tb = binary.LittleEndian.AppendUint64(b, math.Float64bits(x))");
    c.line("\tcase string:");
    c.line("\t\tb = binary.LittleEndian.AppendUint32(b, ValueStr)");
    c.line("\t\tb = binary.LittleEndian.AppendUint32(b, uint32(len(x)))");
    c.line("\t\tb = append(b, x...)");
    c.line("\tcase BlobHandle:");
    c.line("\t\tb = binary.LittleEndian.AppendUint32(b, ValueBlob)");
    c.line("\t\tb = binary.LittleEndian.AppendUint32(b, 8)");
    c.line("\t\tb = binary.LittleEndian.AppendUint64(b, uint64(x))");
    c.line("\tdefault:");
    c.line("\t\tpanic(\"kaya: value must be bool, int64, float64, string, or BlobHandle\")");
    c.line("\t}");
    c.line("\treturn pad8(b)");
    c.line("}");
    c.line("");
    c.line("// encodeValues appends a counted value sequence — a key path or a");
    c.line("// record: {u32 count, u32 reserved, count values}.");
    c.line("func encodeValues(b []byte, vals []any) []byte {");
    c.line("\tb = binary.LittleEndian.AppendUint32(b, uint32(len(vals)))");
    c.line("\tb = binary.LittleEndian.AppendUint32(b, 0)");
    c.line("\tfor _, v := range vals {");
    c.line("\t\tb = encodeValue(b, v)");
    c.line("\t}");
    c.line("\treturn b");
    c.line("}");
    c.line("");
    c.line("// encodeVariantSchemas appends a collection's element sum: {u32");
    c.line("// variant_count, u32 reserved, per variant: u32 field_count,");
    c.line("// field_count Value* tags}, padded to 8. A record collection is");
    c.line("// the one-variant case.");
    c.line("func encodeVariantSchemas(b []byte, variants [][]uint32) []byte {");
    c.line("\tb = binary.LittleEndian.AppendUint32(b, uint32(len(variants)))");
    c.line("\tb = binary.LittleEndian.AppendUint32(b, 0)");
    c.line("\tfor _, schema := range variants {");
    c.line("\t\tb = binary.LittleEndian.AppendUint32(b, uint32(len(schema)))");
    c.line("\t\tfor _, t := range schema {");
    c.line("\t\t\tb = binary.LittleEndian.AppendUint32(b, t)");
    c.line("\t\t}");
    c.line("\t}");
    c.line("\tfor len(b)%8 != 0 {");
    c.line("\t\tb = append(b, 0)");
    c.line("\t}");
    c.line("\treturn b");
    c.line("}");
    c.line("");
    c.line("func beginRecord(kind uint16) []byte {");
    c.line("\tb := make([]byte, 0, 64)");
    c.line("\tb = append(b, 0, 0, 0, 0)");
    c.line("\tb = binary.LittleEndian.AppendUint16(b, kind)");
    c.line("\treturn append(b, 0, 0)");
    c.line("}");
    c.line("");
    c.line("func endRecord(b []byte) []byte {");
    c.line("\tb = pad8(b)");
    c.line("\tbinary.LittleEndian.PutUint32(b, uint32(len(b)))");
    c.line("\treturn b");
    c.line("}");

    for r in spec.tx {
        if r.name == "set_property" || r.name == "set_window_prop" {
            continue;
        }
        emit_packer(&mut c, r);
    }

    for (prop, _, kind) in prop_variants(spec) {
        let pc = camel(prop);
        // Blob setters take the u64 kaya_blob_register handle.
        let (p, ty, expr) = match kind {
            crate::PropKind::Str => (param(prop), "string", format!("encodeValue(b, {})", param(prop))),
            crate::PropKind::Bool => (param(prop), "bool", format!("encodeValue(b, {})", param(prop))),
            crate::PropKind::F64 => (param(prop), "float64", format!("encodeValue(b, {})", param(prop))),
            crate::PropKind::Blob => (
                "handle".to_string(),
                "uint64",
                "encodeValue(b, BlobHandle(handle))".to_string(),
            ),
            crate::PropKind::Enum(_) => (
                param(prop),
                "int64",
                format!("encodeValue(b, {})", param(prop)),
            ),
        };
        c.line("");
        c.line(&format!("// TxSet{pc}: set_property with a constant {prop} value."));
        c.line(&format!("func TxSet{pc}(widgetID uint64, {p} {ty}) []byte {{"));
        c.line("\tb := beginRecord(txSetProperty)");
        c.line("\tb = binary.LittleEndian.AppendUint64(b, widgetID)");
        c.line(&format!("\tb = binary.LittleEndian.AppendUint32(b, Prop{pc})"));
        c.line("\tb = binary.LittleEndian.AppendUint32(b, SourceConst)");
        c.line(&format!("\tb = {expr}"));
        c.line("\treturn endRecord(b)");
        c.line("}");
        c.line("");
        c.line(&format!("// TxBind{pc}: set_property with a signal-bound {prop} value."));
        c.line(&format!("func TxBind{pc}(widgetID uint64, signalID uint64) []byte {{"));
        c.line("\tb := beginRecord(txSetProperty)");
        c.line("\tb = binary.LittleEndian.AppendUint64(b, widgetID)");
        c.line(&format!("\tb = binary.LittleEndian.AppendUint32(b, Prop{pc})"));
        c.line("\tb = binary.LittleEndian.AppendUint32(b, SourceSignal)");
        c.line("\tb = binary.LittleEndian.AppendUint64(b, signalID)");
        c.line("\treturn endRecord(b)");
        c.line("}");
        c.line("");
        c.line(&format!("// TxBind{pc}Element: set_property bound to one field of the element of the"));
        c.line("// enclosing For, `level` Fors up (0 = nearest).");
        c.line(&format!("func TxBind{pc}Element(widgetID uint64, level uint32, field uint32) []byte {{"));
        c.line("\tb := beginRecord(txSetProperty)");
        c.line("\tb = binary.LittleEndian.AppendUint64(b, widgetID)");
        c.line(&format!("\tb = binary.LittleEndian.AppendUint32(b, Prop{pc})"));
        c.line("\tb = binary.LittleEndian.AppendUint32(b, SourceElement)");
        c.line("\tb = binary.LittleEndian.AppendUint32(b, level)");
        c.line("\tb = binary.LittleEndian.AppendUint32(b, field)");
        c.line("\treturn endRecord(b)");
        c.line("}");
    }

    // The window-prop duos: element sources are rejected by the wire.
    for (prop, _, kind) in window_prop_variants(spec) {
        let pc = camel(prop);
        let (ty, expr) = match kind {
            crate::PropKind::Str => ("string", format!("encodeValue(b, {})", param(prop))),
            crate::PropKind::F64 => ("float64", format!("encodeValue(b, {})", param(prop))),
            crate::PropKind::Bool => ("bool", format!("encodeValue(b, {})", param(prop))),
            crate::PropKind::Enum(_) => ("int64", format!("encodeValue(b, {})", param(prop))),
            other => unreachable!("no window prop carries {other:?}"),
        };
        let p = param(prop);
        c.line("");
        c.line(&format!("// TxSetWindow{pc}: set_window_prop with a constant {prop} value (window 0, the primary surface)."));
        c.line(&format!("func TxSetWindow{pc}(window uint64, {p} {ty}) []byte {{"));
        c.line("\tb := beginRecord(txSetWindowProp)");
        c.line("\tb = binary.LittleEndian.AppendUint64(b, window)");
        c.line(&format!("\tb = binary.LittleEndian.AppendUint32(b, Wprop{pc})"));
        c.line("\tb = binary.LittleEndian.AppendUint32(b, SourceConst)");
        c.line(&format!("\tb = {expr}"));
        c.line("\treturn endRecord(b)");
        c.line("}");
        c.line("");
        c.line(&format!("// TxBindWindow{pc}: set_window_prop with a signal-bound {prop} value (window 0, the primary surface)."));
        c.line(&format!("func TxBindWindow{pc}(window uint64, signalID uint64) []byte {{"));
        c.line("\tb := beginRecord(txSetWindowProp)");
        c.line("\tb = binary.LittleEndian.AppendUint64(b, window)");
        c.line(&format!("\tb = binary.LittleEndian.AppendUint32(b, Wprop{pc})"));
        c.line("\tb = binary.LittleEndian.AppendUint32(b, SourceSignal)");
        c.line("\tb = binary.LittleEndian.AppendUint64(b, signalID)");
        c.line("\treturn endRecord(b)");
        c.line("}");
    }

    // The entry-prop duos, the window shape on the navigation-entry
    // table (DESIGN.md, Navigation).
    for (prop, _, kind) in crate::entry_prop_variants(spec) {
        let pc = camel(prop);
        let (ty, expr) = match kind {
            crate::PropKind::Str => ("string", format!("encodeValue(b, {})", param(prop))),
            crate::PropKind::Bool => ("bool", format!("encodeValue(b, {})", param(prop))),
            other => unreachable!("no entry prop carries {other:?}"),
        };
        let p = param(prop);
        c.line("");
        c.line(&format!("// TxSetEntry{pc}: set_entry_prop with a constant {prop} value."));
        c.line(&format!("func TxSetEntry{pc}(entry uint64, {p} {ty}) []byte {{"));
        c.line("\tb := beginRecord(txSetEntryProp)");
        c.line("\tb = binary.LittleEndian.AppendUint64(b, entry)");
        c.line(&format!("\tb = binary.LittleEndian.AppendUint32(b, Eprop{pc})"));
        c.line("\tb = binary.LittleEndian.AppendUint32(b, SourceConst)");
        c.line(&format!("\tb = {expr}"));
        c.line("\treturn endRecord(b)");
        c.line("}");
        c.line("");
        c.line(&format!("// TxBindEntry{pc}: set_entry_prop with a signal-bound {prop} value."));
        c.line(&format!("func TxBindEntry{pc}(entry uint64, signalID uint64) []byte {{"));
        c.line("\tb := beginRecord(txSetEntryProp)");
        c.line("\tb = binary.LittleEndian.AppendUint64(b, entry)");
        c.line(&format!("\tb = binary.LittleEndian.AppendUint32(b, Eprop{pc})"));
        c.line("\tb = binary.LittleEndian.AppendUint32(b, SourceSignal)");
        c.line("\tb = binary.LittleEndian.AppendUint64(b, signalID)");
        c.line("\treturn endRecord(b)");
        c.line("}");
    }

    // The section-prop duos; icon rides the blob channel (DESIGN.md,
    // Sections).
    for (prop, _, kind) in crate::section_prop_variants(spec) {
        let pc = camel(prop);
        let (p, ty, expr) = match kind {
            crate::PropKind::Str => (param(prop), "string", format!("encodeValue(b, {})", param(prop))),
            crate::PropKind::Blob => (
                "handle".to_string(),
                "uint64",
                "encodeValue(b, BlobHandle(handle))".to_string(),
            ),
            crate::PropKind::Enum(_) => (param(prop), "int64", format!("encodeValue(b, {})", param(prop))),
            other => unreachable!("no section prop carries {other:?}"),
        };
        c.line("");
        c.line(&format!("// TxSetSection{pc}: set_section_prop with a constant {prop} value."));
        c.line(&format!("func TxSetSection{pc}(section uint64, {p} {ty}) []byte {{"));
        c.line("\tb := beginRecord(txSetSectionProp)");
        c.line("\tb = binary.LittleEndian.AppendUint64(b, section)");
        c.line(&format!("\tb = binary.LittleEndian.AppendUint32(b, Sprop{pc})"));
        c.line("\tb = binary.LittleEndian.AppendUint32(b, SourceConst)");
        c.line(&format!("\tb = {expr}"));
        c.line("\treturn endRecord(b)");
        c.line("}");
        c.line("");
        c.line(&format!("// TxBindSection{pc}: set_section_prop with a signal-bound {prop} value."));
        c.line(&format!("func TxBindSection{pc}(section uint64, signalID uint64) []byte {{"));
        c.line("\tb := beginRecord(txSetSectionProp)");
        c.line("\tb = binary.LittleEndian.AppendUint64(b, section)");
        c.line(&format!("\tb = binary.LittleEndian.AppendUint32(b, Sprop{pc})"));
        c.line("\tb = binary.LittleEndian.AppendUint32(b, SourceSignal)");
        c.line("\tb = binary.LittleEndian.AppendUint64(b, signalID)");
        c.line("\treturn endRecord(b)");
        c.line("}");
    }

    // The one binding-tier shortcut parser (DESIGN.md, Menus): SPELLING
    // only, policy being the core's. TxSetMenuShortcut routes through
    // it, so no call site can bypass canonicalization.
    let named_keys = crate::SHORTCUT_NAMED_KEYS
        .iter()
        .map(|k| format!("\"{k}\": true"))
        .collect::<Vec<_>>()
        .join(", ");
    c.line("");
    c.line(&format!("var shortcutNamedKeys = map[string]bool{{{named_keys}}}"));
    c.line("");
    c.line("// CanonicalizeShortcut canonicalizes a shortcut spelling to the wire");
    c.line("// form: lowercase '+'-joined tokens, modifiers ordered primary,");
    c.line("// shift, alt, then one key (a-z, 0-9, or the closed named set).");
    c.line("// Panics on whitespace, empty tokens, repeated modifiers, aliases");
    c.line("// (ctrl/cmd/option), and unknown or multiple or missing keys. POLICY");
    c.line("// stays at the core, validated on the canonical spelling.");
    c.line("func CanonicalizeShortcut(spelling string) string {");
    c.line("\tif spelling == \"\" {");
    c.line("\t\tpanic(\"kaya: shortcut is empty\")");
    c.line("\t}");
    c.line("\tif strings.ContainsAny(spelling, \" \\t\\n\\v\\f\\r\") {");
    c.line("\t\tpanic(\"kaya: shortcut \" + strconv.Quote(spelling) + \" contains whitespace\")");
    c.line("\t}");
    c.line("\tparts := strings.Split(strings.ToLower(spelling), \"+\")");
    c.line("\tfor _, p := range parts {");
    c.line("\t\tif p == \"\" {");
    c.line("\t\t\tpanic(\"kaya: shortcut \" + strconv.Quote(spelling) + \" has an empty token\")");
    c.line("\t\t}");
    c.line("\t}");
    c.line("\tmods, key := parts[:len(parts)-1], parts[len(parts)-1]");
    c.line("\tvar hasPrimary, hasShift, hasAlt bool");
    c.line("\tfor _, m := range mods {");
    c.line("\t\tvar slot *bool");
    c.line("\t\tswitch m {");
    c.line("\t\tcase \"primary\":");
    c.line("\t\t\tslot = &hasPrimary");
    c.line("\t\tcase \"shift\":");
    c.line("\t\t\tslot = &hasShift");
    c.line("\t\tcase \"alt\":");
    c.line("\t\t\tslot = &hasAlt");
    c.line("\t\tdefault:");
    c.line("\t\t\tpanic(\"kaya: shortcut \" + strconv.Quote(spelling) + \" has an unknown modifier \" + strconv.Quote(m) + \" (the portable modifiers are primary, shift, alt; aliases like ctrl, cmd, and option are not accepted)\")");
    c.line("\t\t}");
    c.line("\t\tif *slot {");
    c.line("\t\t\tpanic(\"kaya: shortcut \" + strconv.Quote(spelling) + \" repeats modifier \" + strconv.Quote(m))");
    c.line("\t\t}");
    c.line("\t\t*slot = true");
    c.line("\t}");
    c.line("\talnum := len(key) == 1 && ((key[0] >= 'a' && key[0] <= 'z') || (key[0] >= '0' && key[0] <= '9'))");
    c.line("\tif !alnum && !shortcutNamedKeys[key] {");
    c.line("\t\tpanic(\"kaya: shortcut \" + strconv.Quote(spelling) + \" key \" + strconv.Quote(key) + \" is outside the floor (one of a-z, 0-9, or the closed named set)\")");
    c.line("\t}");
    c.line("\tout := \"\"");
    c.line("\tif hasPrimary {");
    c.line("\t\tout += \"primary+\"");
    c.line("\t}");
    c.line("\tif hasShift {");
    c.line("\t\tout += \"shift+\"");
    c.line("\t}");
    c.line("\tif hasAlt {");
    c.line("\t\tout += \"alt+\"");
    c.line("\t}");
    c.line("\treturn out + key");
    c.line("}");

    // Signal binders only for the bindable props (SOURCE_SIGNAL on the
    // rest dies at the root).
    for (prop, _, kind) in crate::menu_prop_variants(spec) {
        let pc = camel(prop);
        let (p, ty, expr) = match kind {
            crate::PropKind::Str if *prop == "shortcut" => (
                param(prop),
                "string",
                format!("encodeValue(b, CanonicalizeShortcut({}))", param(prop)),
            ),
            crate::PropKind::Str => (param(prop), "string", format!("encodeValue(b, {})", param(prop))),
            crate::PropKind::Bool => (param(prop), "bool", format!("encodeValue(b, {})", param(prop))),
            crate::PropKind::F64 => (param(prop), "float64", format!("encodeValue(b, {})", param(prop))),
            crate::PropKind::Blob => (
                "handle".to_string(),
                "uint64",
                "encodeValue(b, BlobHandle(handle))".to_string(),
            ),
            crate::PropKind::Enum(_) => (param(prop), "int64", format!("encodeValue(b, {})", param(prop))),
        };
        c.line("");
        if *prop == "shortcut" {
            c.line(&format!("// TxSetMenu{pc}: set_menu_prop with a constant {prop} value, canonicalized"));
            c.line("// here (the one binding-tier shortcut parser — no call site bypasses it).");
        } else {
            c.line(&format!("// TxSetMenu{pc}: set_menu_prop with a constant {prop} value."));
        }
        c.line(&format!("func TxSetMenu{pc}(item uint64, {p} {ty}) []byte {{"));
        c.line("\tb := beginRecord(txSetMenuProp)");
        c.line("\tb = binary.LittleEndian.AppendUint64(b, item)");
        c.line(&format!("\tb = binary.LittleEndian.AppendUint32(b, Mprop{pc})"));
        c.line("\tb = binary.LittleEndian.AppendUint32(b, SourceConst)");
        c.line(&format!("\tb = {expr}"));
        c.line("\treturn endRecord(b)");
        c.line("}");
        if crate::menu_prop_bindable(prop) {
            c.line("");
            c.line(&format!("// TxBindMenu{pc}: set_menu_prop with a signal-bound {prop} value."));
            c.line(&format!("func TxBindMenu{pc}(item uint64, signalID uint64) []byte {{"));
            c.line("\tb := beginRecord(txSetMenuProp)");
            c.line("\tb = binary.LittleEndian.AppendUint64(b, item)");
            c.line(&format!("\tb = binary.LittleEndian.AppendUint32(b, Mprop{pc})"));
            c.line("\tb = binary.LittleEndian.AppendUint32(b, SourceSignal)");
            c.line("\tb = binary.LittleEndian.AppendUint64(b, signalID)");
            c.line("\treturn endRecord(b)");
            c.line("}");
        }
    }
    c.line("");
    // A blob in an OCCURRENCE is a table handle, not the apply
    // channel's batch-local index, and nothing retires one here — so the
    // decoder redeems and releases it, which keeps a handle from ever
    // reaching an app.
    c.line("// ClipValues is one representation as the decoder hands it over:");
    c.line("// the clip kind, and its values with blobs already redeemed to");
    c.line("// bytes. Kind is a SINGLE member of the clip enum and never a mask");
    c.line("// (you offer many and you receive one); 0 with no values is the");
    c.line("// universal empty answer.");
    c.line("type ClipValues struct {");
    c.line("\tKind   uint32");
    c.line("\tValues []any");
    c.line("}");
    c.line("");
    c.line("// parseClip decodes a representation at `at`: the clip kind, then");
    c.line("// its Values block. Blobs are redeemed and RELEASED here.");
    c.line("func parseClip(rec []byte, at int) (ClipValues, int) {");
    c.line("\tclip := ClipValues{Kind: binary.LittleEndian.Uint32(rec[at:])}");
    c.line("\tcount := int(binary.LittleEndian.Uint32(rec[at+8:]))");
    c.line("\tat += 16");
    c.line("\tfor i := 0; i < count; i++ {");
    c.line("\t\tvtype := binary.LittleEndian.Uint32(rec[at:])");
    c.line("\t\tvlen := int(binary.LittleEndian.Uint32(rec[at+4:]))");
    c.line("\t\tbody := rec[at+8 : at+8+vlen]");
    c.line("\t\tswitch vtype {");
    c.line("\t\tcase ValueI64:");
    c.line("\t\t\tclip.Values = append(clip.Values, int64(binary.LittleEndian.Uint64(body)))");
    c.line("\t\tcase ValueBlob:");
    c.line("\t\t\tclip.Values = append(clip.Values, occurrenceBlob(binary.LittleEndian.Uint64(body)))");
    c.line("\t\tdefault:");
    c.line("\t\t\tclip.Values = append(clip.Values, string(body))");
    c.line("\t\t}");
    c.line("\t\tat += 8 + (vlen+7)&^7");
    c.line("\t}");
    c.line("\treturn clip, at");
    c.line("}");
    c.line("");
    // parseClip keeps its own inline copy of this decode.
    if !crate::undo_occurrence_names(spec).is_empty() {
        c.line("// parseValue decodes one wire value at `at` and returns the offset");
        c.line("// after it. Blobs are redeemed and RELEASED here, as parseClip does:");
        c.line("// an occurrence blob is a table handle nothing else retires.");
        c.line("func parseValue(rec []byte, at int) (any, int) {");
        c.line("\tvtype := binary.LittleEndian.Uint32(rec[at:])");
        c.line("\tvlen := int(binary.LittleEndian.Uint32(rec[at+4:]))");
        c.line("\tbody := rec[at+8 : at+8+vlen]");
        c.line("\tvar v any");
        c.line("\tswitch vtype {");
        c.line("\tcase ValueBool:");
        c.line("\t\tv = body[0] != 0");
        c.line("\tcase ValueI64:");
        c.line("\t\tv = int64(binary.LittleEndian.Uint64(body))");
        c.line("\tcase ValueF64:");
        c.line("\t\tv = math.Float64frombits(binary.LittleEndian.Uint64(body))");
        c.line("\tcase ValueBlob:");
        c.line("\t\tv = occurrenceBlob(binary.LittleEndian.Uint64(body))");
        c.line("\tdefault:");
        c.line("\t\tv = string(body)");
        c.line("\t}");
        c.line("\treturn v, at + 8 + (vlen+7)&^7");
        c.line("}");
        c.line("");
    }
    c.line("// ParseOccurrence decodes one occurrence record (header included).");
    c.line("// keys is nil when id is a widget id; otherwise id is a template");
    c.line("// node id and keys is the copy's key path, outermost first. payload");
    c.line("// is the entry's new text (string) for occTextChanged, the");
    c.line("// checkbox's new state (bool) for occToggled, the slider's new");
    c.line("// value (float64) for occValueChanged, nil for clicks. ok is");
    c.line("// false for pad/unknown records.");
    c.line("func ParseOccurrence(rec []byte) (kind uint16, id uint64, keys []any, payload any, ok bool) {");
    c.line("\tkind = binary.LittleEndian.Uint16(rec[4:])");
    let accepted = crate::occurrence_names(spec)
        .iter()
        .map(|n| format!("kind != occ{}", camel(n)))
        .collect::<Vec<_>>()
        .join(" && ");
    c.line(&format!("\tif {accepted} {{"));
    c.line("\t\treturn 0, 0, nil, nil, false");
    c.line("\t}");
    c.line("\tid = binary.LittleEndian.Uint64(rec[8:])");
    c.line("\tif kind == occAlertResult {");
    c.line("\t\t// The alert's one answer: id + u32 choice (AlertChoice*).");
    c.line("\t\treturn kind, id, nil, binary.LittleEndian.Uint32(rec[16:]), true");
    c.line("\t}");
    // The picker's answer is a LIST OF RECORDS, so it needs its own
    // arm: the generic tail would take the file count for a key-path
    // length and start eight bytes early.
    c.line("\tif kind == occFileDialogResult {");
    c.line("\t\t// The picker's answer: id, a count, then three Values");
    c.line("\t\t// per file (handle, name, local_path). EMPTY IS CANCEL.");
    c.line("\t\tcount := int(binary.LittleEndian.Uint32(rec[16:]))");
    c.line("\t\tat := 32 // past id, count, pad, values count, reserved");
    c.line("\t\tfiles := make([]PickedFile, 0, count)");
    c.line("\t\tfor i := 0; i < count; i++ {");
    c.line("\t\t\tvals := [3]any{}");
    c.line("\t\t\tfor j := 0; j < 3; j++ {");
    c.line("\t\t\t\tvtype := binary.LittleEndian.Uint32(rec[at:])");
    c.line("\t\t\t\tvlen := int(binary.LittleEndian.Uint32(rec[at+4:]))");
    c.line("\t\t\t\tbody := rec[at+8 : at+8+vlen]");
    c.line("\t\t\t\tif vtype == ValueI64 {");
    c.line("\t\t\t\t\tvals[j] = int64(binary.LittleEndian.Uint64(body))");
    c.line("\t\t\t\t} else {");
    c.line("\t\t\t\t\tvals[j] = string(body)");
    c.line("\t\t\t\t}");
    c.line("\t\t\t\tat += 8 + (vlen+7)&^7");
    c.line("\t\t\t}");
    c.line("\t\t\thandle, _ := vals[0].(int64)");
    c.line("\t\t\tname, _ := vals[1].(string)");
    c.line("\t\t\tlocalPath, _ := vals[2].(string)");
    c.line("\t\t\tfiles = append(files, PickedFile{");
    c.line("\t\t\t\tHandle: uint64(handle), Name: name, LocalPath: localPath})");
    c.line("\t\t}");
    c.line("\t\treturn kind, id, nil, files, true");
    c.line("\t}");
    // Its own arm: the generic tail would take the CLIP KIND for a path
    // length and read the values header as a key.
    for name in crate::clip_answer_occurrence_names(spec) {
        c.line(&format!("\tif kind == occ{} {{", camel(name)));
        c.line("\t\tclip, _ := parseClip(rec, 16)");
        c.line("\t\treturn kind, id, nil, clip, true");
        c.line("\t}");
    }
    // Four counted runs cut out of one flat Values tail, in the fixed
    // order signals, texts, entries, orders (docs/undo-plan.md D5;
    // wire::undo_body). Its own arm for the file_dialog_result reason —
    // the generic tail would take the SIGNAL COUNT for a key-path
    // length.
    let undo = crate::undo_occurrence_names(spec)
        .iter()
        .map(|n| format!("kind == occ{}", camel(n)))
        .collect::<Vec<_>>()
        .join(" || ");
    if !undo.is_empty() {
        c.line(&format!("\tif {undo} {{"));
        c.line("\t\t// The window is the id; then the four run LENGTHS, the");
        c.line("\t\t// group's label (EMPTY for a typing episode), and one");
        c.line("\t\t// flat values tail the runs cut up in order.");
        c.line("\t\tsignals := int(binary.LittleEndian.Uint32(rec[16:]))");
        c.line("\t\ttexts := int(binary.LittleEndian.Uint32(rec[20:]))");
        c.line("\t\tentries := int(binary.LittleEndian.Uint32(rec[24:]))");
        c.line("\t\torders := int(binary.LittleEndian.Uint32(rec[28:]))");
        c.line("\t\tat := 32");
        c.line("\t\tlabel, at := parseValue(rec, at)");
        c.line("\t\tcount := int(binary.LittleEndian.Uint32(rec[at:]))");
        c.line("\t\tat += 8 // count, reserved");
        c.line("\t\tflat := make([]any, count)");
        c.line("\t\tfor i := range flat {");
        c.line("\t\t\tflat[i], at = parseValue(rec, at)");
        c.line("\t\t}");
        // A truncated or over-long tail is a broken ENCODER: it dies
        // here rather than handing an app half a step.
        c.line("\t\tread := 0");
        c.line("\t\tnext := func(n int) []any {");
        c.line("\t\t\tif read+n > len(flat) {");
        c.line("\t\t\t\tpanic(\"kaya: an undo delta is truncated\")");
        c.line("\t\t\t}");
        c.line("\t\t\tout := flat[read : read+n]");
        c.line("\t\t\tread += n");
        c.line("\t\t\treturn out");
        c.line("\t\t}");
        c.line("\t\tnum := func(v any) int64 {");
        c.line("\t\t\tn, isInt := v.(int64)");
        c.line("\t\t\tif !isInt {");
        c.line("\t\t\t\tpanic(\"kaya: an undo delta wanted an integer\")");
        c.line("\t\t\t}");
        c.line("\t\t\treturn n");
        c.line("\t\t}");
        c.line("\t\tvar delta UndoDelta");
        c.line("\t\tfor i := 0; i < signals; i++ {");
        c.line("\t\t\tpair := next(2)");
        c.line("\t\t\tdelta.Signals = append(delta.Signals,");
        c.line("\t\t\t\tUndoSignal{Signal: uint64(num(pair[0])), Value: pair[1]})");
        c.line("\t\t}");
        // A stamped copy's field is named by (template node, key path);
        // path_len 0 means the id is a live widget id.
        c.line("\t\tfor i := 0; i < texts; i++ {");
        c.line("\t\t\thead := next(3)");
        c.line("\t\t\tsize := int(num(head[0]))");
        c.line("\t\t\tpathLen := int(num(head[2]))");
        c.line("\t\t\tbody := next(size - 3)");
        c.line("\t\t\ttext, _ := body[pathLen].(string)");
        c.line("\t\t\tdelta.Texts = append(delta.Texts, UndoText{");
        c.line("\t\t\t\tID:   uint64(num(head[1])),");
        c.line("\t\t\t\tPath: append([]any(nil), body[:pathLen]...),");
        c.line("\t\t\t\tText: text,");
        c.line("\t\t\t})");
        c.line("\t\t}");
        // Arity-first groups: `size` counts itself, so a reader takes it
        // first and needs no schema.
        c.line("\t\tfor i := 0; i < entries; i++ {");
        c.line("\t\t\t// size, collection, flags (bit 0 = the entry EXISTS),");
        c.line("\t\t\t// variant, path_len — then the path, the key, and the");
        c.line("\t\t\t// record's fields. size counts itself.");
        c.line("\t\t\thead := next(5)");
        c.line("\t\t\tsize := int(num(head[0]))");
        c.line("\t\t\tpathLen := int(num(head[4]))");
        c.line("\t\t\tbody := next(size - 5)");
        c.line("\t\t\tentry := UndoEntry{");
        c.line("\t\t\t\tCollection: uint64(num(head[1])),");
        c.line("\t\t\t\tPath:       append([]any(nil), body[:pathLen]...),");
        c.line("\t\t\t\tKey:        body[pathLen],");
        c.line("\t\t\t\tPresent:    num(head[2]) != 0,");
        c.line("\t\t\t\tVariant:    uint32(num(head[3])),");
        c.line("\t\t\t}");
        c.line("\t\t\tif entry.Present {");
        c.line("\t\t\t\tentry.Record = append([]any(nil), body[pathLen+1:]...)");
        c.line("\t\t\t}");
        c.line("\t\t\tdelta.Entries = append(delta.Entries, entry)");
        c.line("\t\t}");
        c.line("\t\tfor i := 0; i < orders; i++ {");
        c.line("\t\t\thead := next(3)");
        c.line("\t\t\tsize := int(num(head[0]))");
        c.line("\t\t\tpathLen := int(num(head[2]))");
        c.line("\t\t\tbody := next(size - 3)");
        c.line("\t\t\tdelta.Orders = append(delta.Orders, UndoOrder{");
        c.line("\t\t\t\tCollection: uint64(num(head[1])),");
        c.line("\t\t\t\tPath:       append([]any(nil), body[:pathLen]...),");
        c.line("\t\t\t\tKeys:       append([]any(nil), body[pathLen:]...),");
        c.line("\t\t\t})");
        c.line("\t\t}");
        c.line("\t\tif read != len(flat) {");
        c.line("\t\t\tpanic(\"kaya: an undo delta has trailing values\")");
        c.line("\t\t}");
        c.line("\t\tname, _ := label.(string)");
        c.line("\t\treturn kind, id, nil, undoReport{label: name, delta: delta}, true");
        c.line("\t}");
    }
    let id_only = crate::id_only_occurrence_names(spec)
        .iter()
        .map(|n| format!("kind == occ{}", camel(n)))
        .collect::<Vec<_>>()
        .join(" || ");
    c.line(&format!("\tif {id_only} {{"));
    c.line("\t\t// Surface lifecycle records carry the surface id alone —");
    c.line("\t\t// no key path, no payload (derived from the record shapes).");
    c.line("\t\treturn kind, id, nil, nil, true");
    c.line("\t}");
    let id_pair = crate::id_pair_occurrence_names(spec)
        .iter()
        .map(|n| format!("kind == occ{}", camel(n)))
        .collect::<Vec<_>>()
        .join(" || ");
    if !id_pair.is_empty() {
        c.line(&format!("\tif {id_pair} {{"));
        c.line("\t\t// Surface-pair records (window, section): the SECOND id");
        c.line("\t\t// keys the handler; the first rides as the payload.");
        c.line("\t\treturn kind, binary.LittleEndian.Uint64(rec[16:]), nil, id, true");
        c.line("\t}");
    }
    c.line("\tpathLen := binary.LittleEndian.Uint32(rec[16:])");
    c.line("\tat := 24");
    c.line("\tfor i := uint32(0); i < pathLen; i++ {");
    c.line("\t\tvtype := binary.LittleEndian.Uint32(rec[at:])");
    c.line("\t\tvlen := int(binary.LittleEndian.Uint32(rec[at+4:]))");
    c.line("\t\tpayload := rec[at+8 : at+8+vlen]");
    c.line("\t\tswitch vtype {");
    c.line("\t\tcase ValueBool:");
    c.line("\t\t\tkeys = append(keys, payload[0] != 0)");
    c.line("\t\tcase ValueI64:");
    c.line("\t\t\tkeys = append(keys, int64(binary.LittleEndian.Uint64(payload)))");
    c.line("\t\tcase ValueF64:");
    c.line("\t\t\tkeys = append(keys, math.Float64frombits(binary.LittleEndian.Uint64(payload)))");
    c.line("\t\tdefault:");
    c.line("\t\t\tkeys = append(keys, string(payload))");
    c.line("\t\t}");
    c.line("\t\tat += 8 + (vlen+7)&^7");
    c.line("\t}");
    // The u32 slot the tag family calls `reserved` is a real value on
    // these — read from its fixed offset.
    for name in crate::u32_slot_occurrence_names(spec) {
        c.line(&format!("\tif kind == occ{} {{", camel(name)));
        c.line("\t\tpayload = binary.LittleEndian.Uint32(rec[20:])");
        c.line("\t}");
    }
    let with_payload = crate::payload_occurrence_names(spec)
        .iter()
        .map(|n| format!("kind == occ{}", camel(n)))
        .collect::<Vec<_>>()
        .join(" || ");
    c.line(&format!("\tif {with_payload} {{"));
    c.line("\t\tvtype := binary.LittleEndian.Uint32(rec[at:])");
    c.line("\t\tvlen := int(binary.LittleEndian.Uint32(rec[at+4:]))");
    c.line("\t\tswitch vtype {");
    c.line("\t\tcase ValueBool:");
    c.line("\t\t\tpayload = rec[at+8] != 0");
    c.line("\t\tcase ValueI64:");
    c.line("\t\t\tpayload = int64(binary.LittleEndian.Uint64(rec[at+8:]))");
    c.line("\t\tcase ValueF64:");
    c.line("\t\t\tpayload = math.Float64frombits(binary.LittleEndian.Uint64(rec[at+8:]))");
    c.line("\t\tdefault:");
    c.line("\t\t\tpayload = string(rec[at+8 : at+8+vlen])");
    c.line("\t\t}");
    c.line("\t}");
    // A paste rides a click tag VERBATIM, so the key path above is
    // already read and the clip sits after it.
    for name in crate::pasted_occurrence_names(spec) {
        c.line(&format!("\tif kind == occ{} {{", camel(name)));
        c.line("\t\tclip, _ := parseClip(rec, at)");
        c.line("\t\tpayload = clip");
        c.line("\t}");
    }
    // The canvas asks: bare values after the key path with no count in
    // front, read until the record ends (docs/canvas-plan.md §3.2.1).
    let values_tail = crate::values_tail_occurrence_names(spec)
        .iter()
        .map(|n| format!("kind == occ{}", camel(n)))
        .collect::<Vec<_>>()
        .join(" || ");
    if !values_tail.is_empty() {
        c.line(&format!("\tif {values_tail} {{"));
        c.line("\t\t// The canvas asks carry a run of BARE values after the key");
        c.line("\t\t// path — the assigned size, and a tick's frame time — with");
        c.line("\t\t// no count in front, so they are read until the record ends");
        c.line("\t\t// (docs/canvas-plan.md §3.2.1).");
        c.line("\t\tend := int(binary.LittleEndian.Uint32(rec[0:]))");
        c.line("\t\ttail := []any{}");
        c.line("\t\tfor at < end {");
        c.line("\t\t\tvar v any");
        c.line("\t\t\tv, at = parseValue(rec, at)");
        c.line("\t\t\ttail = append(tail, v)");
        c.line("\t\t}");
        c.line("\t\tpayload = tail");
        c.line("\t}");
    }
    c.line("\treturn kind, id, keys, payload, true");
    c.line("}");
    c.out
}

fn emit_packer(c: &mut Ctx, r: &Record) {
    let params = record_params(r);
    let mut sig: Vec<String> = Vec::new();
    for f in &params {
        sig.push(match f.ty {
            FieldTy::U32 => format!("{} uint32", param(f.name)),
            FieldTy::U64 => format!("{} uint64", param(f.name)),
            FieldTy::Value => format!("{} any", param(f.name)),
            FieldTy::Values => format!("{} []any", param(f.name)),
            FieldTy::VariantSchemas => format!("{} [][]uint32", param(f.name)),
        });
    }
    c.line("");
    c.line(&format!("// Tx{}: {}", camel(r.name), r.doc.replace('\n', " ")));
    c.line(&format!(
        "func Tx{}({}) []byte {{",
        camel(r.name),
        sig.join(", ")
    ));
    c.line(&format!("\tb := beginRecord(tx{})", camel(r.name)));
    for f in r.fields {
        c.line(&match f.ty {
            FieldTy::U32 if is_padding(f) => {
                "\tb = binary.LittleEndian.AppendUint32(b, 0)".into()
            }
            FieldTy::U32 => format!(
                "\tb = binary.LittleEndian.AppendUint32(b, {})",
                param(f.name)
            ),
            FieldTy::U64 => format!(
                "\tb = binary.LittleEndian.AppendUint64(b, {})",
                param(f.name)
            ),
            FieldTy::Value => format!("\tb = encodeValue(b, {})", param(f.name)),
            FieldTy::Values => format!("\tb = encodeValues(b, {})", param(f.name)),
            FieldTy::VariantSchemas => format!("\tb = encodeVariantSchemas(b, {})", param(f.name)),
        });
    }
    c.line("\treturn endRecord(b)");
    c.line("}");
}
