//! Go emitter: the generated half of package kaya (bindings/go). The
//! hand-written runtime (runtime.go, same package) carries cgo, the
//! ring consumer, and Submit/Run; this file is constants and packers.
//! Package scope namespaces everything for consumers; internally,
//! helpers are lowercase (unexported) and generated parameters are
//! locals, so the reserved set is keywords plus the helper names.

use kaya::spec::{FieldTy, ProtocolSpec, Record};

use crate::{Ctx, prop_variants, record_params, window_prop_variants};

pub const RESERVED: &[&str] = &[
    "encodeValue", "encodeValues", "encodeVariantSchemas", "beginRecord", "endRecord", "ParseOccurrence", "BlobHandle",
    "break", "case", "chan", "const", "continue", "default", "defer", "else", "fallthrough",
    "for", "func", "go", "goto", "if", "import", "interface", "map", "package", "range",
    "return", "select", "struct", "switch", "type", "var",
];

fn camel(name: &str) -> String {
    name.split('_')
        .map(|w| {
            let mut chars = w.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

fn param(name: &str) -> String {
    // Lower camel for parameters; `id` and friends survive as-is.
    let c = camel(name);
    let mut chars = c.chars();
    match chars.next() {
        Some(first) => first.to_lowercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    }
}

pub fn emit(spec: &ProtocolSpec) -> String {
    let mut c = Ctx { out: String::new() };
    c.line("// kaya wire vocabulary. Generated by kaya-bindgen from kaya::spec — do not edit.");
    c.line("//");
    c.line("// Records are {u32 size, u16 kind, u16 flags}, body, padded to 8,");
    c.line("// little-endian. Values accept Go bool, int64, float64, string, and");
    c.line("// BlobHandle, mapped to the kaya value types; keys in paths likewise.");
    c.line("package kaya");
    c.line("");
    c.line("import (");
    c.line("\t\"encoding/binary\"");
    c.line("\t\"math\"");
    c.line(")");
    c.line("");
    c.line("const (");
    c.line("\t// SpecHash: the protocol fingerprint; the runtime asserts the loaded core agrees.");
    c.line(&format!("\tSpecHash uint64 = 0x{:016x}", crate::spec_hash()));
    c.line("");
    for e in spec.enums {
        for (name, value) in e.variants {
            c.line(&format!("\t{}{} = {}", camel(e.name), camel(name), value));
        }
    }
    for (channel, records) in [("Tx", spec.tx), ("Apply", spec.apply), ("Occ", spec.occurrence)] {
        for r in records {
            c.line(&format!("\t{}{} = {}", channel.to_lowercase(), camel(r.name), r.kind));
        }
    }
    c.line(")");
    c.line("");
    c.line("func pad8(b []byte) []byte {");
    c.line("\tfor len(b)%8 != 0 {");
    c.line("\t\tb = append(b, 0)");
    c.line("\t}");
    c.line("\treturn b");
    c.line("}");
    c.line("");
    c.line("// BlobHandle marks a u64 handle from kaya_blob_register as a blob");
    c.line("// value, consumed by the next submit; the bytes never ride the");
    c.line("// record stream.");
    c.line("type BlobHandle uint64");
    c.line("");
    c.line("// encodeValue appends one kaya value; values self-pad to 8 because");
    c.line("// they concatenate inside record bodies.");
    c.line("func encodeValue(b []byte, v any) []byte {");
    c.line("\tswitch x := v.(type) {");
    c.line("\tcase bool:");
    c.line("\t\tb = binary.LittleEndian.AppendUint32(b, ValueBool)");
    c.line("\t\tb = binary.LittleEndian.AppendUint32(b, 1)");
    c.line("\t\tif x {");
    c.line("\t\t\tb = append(b, 1)");
    c.line("\t\t} else {");
    c.line("\t\t\tb = append(b, 0)");
    c.line("\t\t}");
    c.line("\tcase int:");
    c.line("\t\treturn encodeValue(b, int64(x))");
    c.line("\tcase int64:");
    c.line("\t\tb = binary.LittleEndian.AppendUint32(b, ValueI64)");
    c.line("\t\tb = binary.LittleEndian.AppendUint32(b, 8)");
    c.line("\t\tb = binary.LittleEndian.AppendUint64(b, uint64(x))");
    c.line("\tcase float64:");
    c.line("\t\tb = binary.LittleEndian.AppendUint32(b, ValueF64)");
    c.line("\t\tb = binary.LittleEndian.AppendUint32(b, 8)");
    c.line("\t\tb = binary.LittleEndian.AppendUint64(b, math.Float64bits(x))");
    c.line("\tcase string:");
    c.line("\t\tb = binary.LittleEndian.AppendUint32(b, ValueStr)");
    c.line("\t\tb = binary.LittleEndian.AppendUint32(b, uint32(len(x)))");
    c.line("\t\tb = append(b, x...)");
    c.line("\tcase BlobHandle:");
    c.line("\t\tb = binary.LittleEndian.AppendUint32(b, ValueBlob)");
    c.line("\t\tb = binary.LittleEndian.AppendUint32(b, 8)");
    c.line("\t\tb = binary.LittleEndian.AppendUint64(b, uint64(x))");
    c.line("\tdefault:");
    c.line("\t\tpanic(\"kaya: value must be bool, int64, float64, string, or BlobHandle\")");
    c.line("\t}");
    c.line("\treturn pad8(b)");
    c.line("}");
    c.line("");
    c.line("// encodeValues appends a counted value sequence — a key path or a");
    c.line("// record: {u32 count, u32 reserved, count values}.");
    c.line("func encodeValues(b []byte, vals []any) []byte {");
    c.line("\tb = binary.LittleEndian.AppendUint32(b, uint32(len(vals)))");
    c.line("\tb = binary.LittleEndian.AppendUint32(b, 0)");
    c.line("\tfor _, v := range vals {");
    c.line("\t\tb = encodeValue(b, v)");
    c.line("\t}");
    c.line("\treturn b");
    c.line("}");
    c.line("");
    c.line("// encodeVariantSchemas appends a collection's element sum: {u32");
    c.line("// variant_count, u32 reserved, per variant: u32 field_count,");
    c.line("// field_count Value* tags}, padded to 8. A record collection is");
    c.line("// the one-variant case.");
    c.line("func encodeVariantSchemas(b []byte, variants [][]uint32) []byte {");
    c.line("\tb = binary.LittleEndian.AppendUint32(b, uint32(len(variants)))");
    c.line("\tb = binary.LittleEndian.AppendUint32(b, 0)");
    c.line("\tfor _, schema := range variants {");
    c.line("\t\tb = binary.LittleEndian.AppendUint32(b, uint32(len(schema)))");
    c.line("\t\tfor _, t := range schema {");
    c.line("\t\t\tb = binary.LittleEndian.AppendUint32(b, t)");
    c.line("\t\t}");
    c.line("\t}");
    c.line("\tfor len(b)%8 != 0 {");
    c.line("\t\tb = append(b, 0)");
    c.line("\t}");
    c.line("\treturn b");
    c.line("}");
    c.line("");
    c.line("func beginRecord(kind uint16) []byte {");
    c.line("\tb := make([]byte, 0, 64)");
    c.line("\tb = append(b, 0, 0, 0, 0)");
    c.line("\tb = binary.LittleEndian.AppendUint16(b, kind)");
    c.line("\treturn append(b, 0, 0)");
    c.line("}");
    c.line("");
    c.line("func endRecord(b []byte) []byte {");
    c.line("\tb = pad8(b)");
    c.line("\tbinary.LittleEndian.PutUint32(b, uint32(len(b)))");
    c.line("\treturn b");
    c.line("}");

    for r in spec.tx {
        if r.name == "set_property" || r.name == "set_window_prop" {
            continue;
        }
        emit_packer(&mut c, r);
    }

    // The set_property arms, one trio per property: spec-driven so new
    // props reach every binding without emitter edits.
    for (prop, _, kind) in prop_variants(spec) {
        let pc = camel(prop);
        // Blob setters take the u64 kaya_blob_register handle (see
        // BlobHandle), so the parameter says so.
        let (p, ty, expr) = match kind {
            crate::PropKind::Str => (param(prop), "string", format!("encodeValue(b, {})", param(prop))),
            crate::PropKind::Bool => (param(prop), "bool", format!("encodeValue(b, {})", param(prop))),
            crate::PropKind::F64 => (param(prop), "float64", format!("encodeValue(b, {})", param(prop))),
            crate::PropKind::Blob => (
                "handle".to_string(),
                "uint64",
                "encodeValue(b, BlobHandle(handle))".to_string(),
            ),
            crate::PropKind::Enum(_) => (
                param(prop),
                "int64",
                format!("encodeValue(b, {})", param(prop)),
            ),
        };
        c.line("");
        c.line(&format!("// TxSet{pc}: set_property with a constant {prop} value."));
        c.line(&format!("func TxSet{pc}(widgetID uint64, {p} {ty}) []byte {{"));
        c.line("\tb := beginRecord(txSetProperty)");
        c.line("\tb = binary.LittleEndian.AppendUint64(b, widgetID)");
        c.line(&format!("\tb = binary.LittleEndian.AppendUint32(b, Prop{pc})"));
        c.line("\tb = binary.LittleEndian.AppendUint32(b, SourceConst)");
        c.line(&format!("\tb = {expr}"));
        c.line("\treturn endRecord(b)");
        c.line("}");
        c.line("");
        c.line(&format!("// TxBind{pc}: set_property with a signal-bound {prop} value."));
        c.line(&format!("func TxBind{pc}(widgetID uint64, signalID uint64) []byte {{"));
        c.line("\tb := beginRecord(txSetProperty)");
        c.line("\tb = binary.LittleEndian.AppendUint64(b, widgetID)");
        c.line(&format!("\tb = binary.LittleEndian.AppendUint32(b, Prop{pc})"));
        c.line("\tb = binary.LittleEndian.AppendUint32(b, SourceSignal)");
        c.line("\tb = binary.LittleEndian.AppendUint64(b, signalID)");
        c.line("\treturn endRecord(b)");
        c.line("}");
        c.line("");
        c.line(&format!("// TxBind{pc}Element: set_property bound to one field of the element of the"));
        c.line("// enclosing For, `level` Fors up (0 = nearest).");
        c.line(&format!("func TxBind{pc}Element(widgetID uint64, level uint32, field uint32) []byte {{"));
        c.line("\tb := beginRecord(txSetProperty)");
        c.line("\tb = binary.LittleEndian.AppendUint64(b, widgetID)");
        c.line(&format!("\tb = binary.LittleEndian.AppendUint32(b, Prop{pc})"));
        c.line("\tb = binary.LittleEndian.AppendUint32(b, SourceElement)");
        c.line("\tb = binary.LittleEndian.AppendUint32(b, level)");
        c.line("\tb = binary.LittleEndian.AppendUint32(b, field)");
        c.line("\treturn endRecord(b)");
        c.line("}");
    }

    // The window-prop duos (const + signal — element sources are
    // rejected by the wire). Window 0, the primary surface, until aux
    // windows land.
    for (prop, _, kind) in window_prop_variants(spec) {
        let pc = camel(prop);
        let (ty, expr) = match kind {
            crate::PropKind::Str => ("string", format!("encodeValue(b, {})", param(prop))),
            crate::PropKind::F64 => ("float64", format!("encodeValue(b, {})", param(prop))),
            crate::PropKind::Bool => ("bool", format!("encodeValue(b, {})", param(prop))),
            other => unreachable!("no window prop carries {other:?}"),
        };
        let p = param(prop);
        c.line("");
        c.line(&format!("// TxSetWindow{pc}: set_window_prop with a constant {prop} value (window 0, the primary surface)."));
        c.line(&format!("func TxSetWindow{pc}(window uint64, {p} {ty}) []byte {{"));
        c.line("\tb := beginRecord(txSetWindowProp)");
        c.line("\tb = binary.LittleEndian.AppendUint64(b, window)");
        c.line(&format!("\tb = binary.LittleEndian.AppendUint32(b, Wprop{pc})"));
        c.line("\tb = binary.LittleEndian.AppendUint32(b, SourceConst)");
        c.line(&format!("\tb = {expr}"));
        c.line("\treturn endRecord(b)");
        c.line("}");
        c.line("");
        c.line(&format!("// TxBindWindow{pc}: set_window_prop with a signal-bound {prop} value (window 0, the primary surface)."));
        c.line(&format!("func TxBindWindow{pc}(window uint64, signalID uint64) []byte {{"));
        c.line("\tb := beginRecord(txSetWindowProp)");
        c.line("\tb = binary.LittleEndian.AppendUint64(b, window)");
        c.line(&format!("\tb = binary.LittleEndian.AppendUint32(b, Wprop{pc})"));
        c.line("\tb = binary.LittleEndian.AppendUint32(b, SourceSignal)");
        c.line("\tb = binary.LittleEndian.AppendUint64(b, signalID)");
        c.line("\treturn endRecord(b)");
        c.line("}");
    }
    c.line("");
    c.line("// ParseOccurrence decodes one occurrence record (header included).");
    c.line("// keys is nil when id is a widget id; otherwise id is a template");
    c.line("// node id and keys is the copy's key path, outermost first. payload");
    c.line("// is the entry's new text (string) for occTextChanged, the");
    c.line("// checkbox's new state (bool) for occToggled, the slider's new");
    c.line("// value (float64) for occValueChanged, nil for clicks. ok is");
    c.line("// false for pad/unknown records.");
    c.line("func ParseOccurrence(rec []byte) (kind uint16, id uint64, keys []any, payload any, ok bool) {");
    c.line("\tkind = binary.LittleEndian.Uint16(rec[4:])");
    let accepted = crate::occurrence_names(spec)
        .iter()
        .map(|n| format!("kind != occ{}", camel(n)))
        .collect::<Vec<_>>()
        .join(" && ");
    c.line(&format!("\tif {accepted} {{"));
    c.line("\t\treturn 0, 0, nil, nil, false");
    c.line("\t}");
    c.line("\tid = binary.LittleEndian.Uint64(rec[8:])");
    c.line("\tif kind == occCloseRequested || kind == occWindowClosed {");
    c.line("\t\t// Window lifecycle records carry the window id alone —");
    c.line("\t\t// no key path, no payload.");
    c.line("\t\treturn kind, id, nil, nil, true");
    c.line("\t}");
    c.line("\tpathLen := binary.LittleEndian.Uint32(rec[16:])");
    c.line("\tat := 24");
    c.line("\tfor i := uint32(0); i < pathLen; i++ {");
    c.line("\t\tvtype := binary.LittleEndian.Uint32(rec[at:])");
    c.line("\t\tvlen := int(binary.LittleEndian.Uint32(rec[at+4:]))");
    c.line("\t\tpayload := rec[at+8 : at+8+vlen]");
    c.line("\t\tswitch vtype {");
    c.line("\t\tcase ValueBool:");
    c.line("\t\t\tkeys = append(keys, payload[0] != 0)");
    c.line("\t\tcase ValueI64:");
    c.line("\t\t\tkeys = append(keys, int64(binary.LittleEndian.Uint64(payload)))");
    c.line("\t\tcase ValueF64:");
    c.line("\t\t\tkeys = append(keys, math.Float64frombits(binary.LittleEndian.Uint64(payload)))");
    c.line("\t\tdefault:");
    c.line("\t\t\tkeys = append(keys, string(payload))");
    c.line("\t\t}");
    c.line("\t\tat += 8 + (vlen+7)&^7");
    c.line("\t}");
    let with_payload = crate::payload_occurrence_names(spec)
        .iter()
        .map(|n| format!("kind == occ{}", camel(n)))
        .collect::<Vec<_>>()
        .join(" || ");
    c.line(&format!("\tif {with_payload} {{"));
    c.line("\t\tvtype := binary.LittleEndian.Uint32(rec[at:])");
    c.line("\t\tvlen := int(binary.LittleEndian.Uint32(rec[at+4:]))");
    // Type-generic payload decode, same shape as the key loop: no
    // per-kind logic left to drift.
    c.line("\t\tswitch vtype {");
    c.line("\t\tcase ValueBool:");
    c.line("\t\t\tpayload = rec[at+8] != 0");
    c.line("\t\tcase ValueI64:");
    c.line("\t\t\tpayload = int64(binary.LittleEndian.Uint64(rec[at+8:]))");
    c.line("\t\tcase ValueF64:");
    c.line("\t\t\tpayload = math.Float64frombits(binary.LittleEndian.Uint64(rec[at+8:]))");
    c.line("\t\tdefault:");
    c.line("\t\t\tpayload = string(rec[at+8 : at+8+vlen])");
    c.line("\t\t}");
    c.line("\t}");
    c.line("\treturn kind, id, keys, payload, true");
    c.line("}");
    c.out
}

fn emit_packer(c: &mut Ctx, r: &Record) {
    let params = record_params(r);
    let mut sig: Vec<String> = Vec::new();
    for f in &params {
        sig.push(match f.ty {
            FieldTy::U32 => format!("{} uint32", param(f.name)),
            FieldTy::U64 => format!("{} uint64", param(f.name)),
            FieldTy::Value => format!("{} any", param(f.name)),
            FieldTy::Values => format!("{} []any", param(f.name)),
            FieldTy::VariantSchemas => format!("{} [][]uint32", param(f.name)),
        });
    }
    c.line("");
    c.line(&format!("// Tx{}: {}", camel(r.name), r.doc.replace('\n', " ")));
    c.line(&format!(
        "func Tx{}({}) []byte {{",
        camel(r.name),
        sig.join(", ")
    ));
    c.line(&format!("\tb := beginRecord(tx{})", camel(r.name)));
    for f in r.fields {
        c.line(&match f.ty {
            FieldTy::U32 if f.name == "reserved" => {
                "\tb = binary.LittleEndian.AppendUint32(b, 0)".into()
            }
            FieldTy::U32 => format!(
                "\tb = binary.LittleEndian.AppendUint32(b, {})",
                param(f.name)
            ),
            FieldTy::U64 => format!(
                "\tb = binary.LittleEndian.AppendUint64(b, {})",
                param(f.name)
            ),
            FieldTy::Value => format!("\tb = encodeValue(b, {})", param(f.name)),
            FieldTy::Values => format!("\tb = encodeValues(b, {})", param(f.name)),
            FieldTy::VariantSchemas => format!("\tb = encodeVariantSchemas(b, {})", param(f.name)),
        });
    }
    c.line("\treturn endRecord(b)");
    c.line("}");
}
