//! Haskell emitter: module KayaWire — a Value type, constants, Builder
//! packers, and the occurrence parser (peeks relative to a record
//! pointer). Module scope namespaces everything; parameters are
//! lower-camel locals, so the reserved set is keywords plus the helper
//! names.

use kaya::spec::{FieldTy, ProtocolSpec, Record};

use crate::{Ctx, prop_variants, record_params, window_prop_variants};

pub const RESERVED: &[&str] = &[
    "encodeValue", "encodeValues", "encodeVariantSchemas", "wireRecord", "parseValue", "parseOccurrence",
    "canonicalizeShortcut", "shortcutNamedKeys",
    "case", "class", "data", "default", "deriving", "do", "else", "foreign", "if", "import",
    "in", "infix", "infixl", "infixr", "instance", "let", "module", "newtype", "of", "then",
    "type", "where",
];

fn camel(name: &str) -> String {
    let mut parts = name.split('_');
    let mut out = parts.next().unwrap_or_default().to_string();
    for w in parts {
        let mut chars = w.chars();
        if let Some(first) = chars.next() {
            out.push_str(&first.to_uppercase().collect::<String>());
            out.push_str(chars.as_str());
        }
    }
    out
}

fn pascal(name: &str) -> String {
    let c = camel(name);
    let mut chars = c.chars();
    match chars.next() {
        Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    }
}

pub fn emit(spec: &ProtocolSpec) -> String {
    let mut c = Ctx { out: String::new() };
    c.line("-- kaya wire vocabulary. Generated by kaya-bindgen from kaya::spec — do not edit.");
    c.line("--");
    c.line("-- Records are {u32 size, u16 kind, u16 flags}, body, padded to 8,");
    c.line("-- little-endian; each tx* returns one packed record as a Builder,");
    c.line("-- and a transaction is their concatenation.");
    c.line("module KayaWire where");
    c.line("");
    c.line("import Data.Bits (complement, (.&.))");
    c.line("import qualified Data.ByteString as BS");
    c.line("import Data.ByteString.Builder");
    c.line("import qualified Data.ByteString.Lazy as BL");
    c.line("import Data.Int (Int64)");
    c.line("import Data.Word (Word16, Word32, Word64, Word8)");
    c.line("import Foreign.Marshal.Array (peekArray)");
    c.line("import Foreign.Ptr (Ptr, plusPtr)");
    c.line("import Foreign.Storable (peekByteOff)");
    c.line("import GHC.Float (castDoubleToWord64, castWord64ToDouble)");
    c.line("import Data.Char (chr, toLower)");
    c.line("");
    c.line("-- VBlob carries the u64 handle from kaya_blob_register, consumed by");
    c.line("-- the next submit; the bytes never ride the record stream.");
    c.line("data Value = VBool Bool | VI64 Int64 | VF64 Double | VStr String | VBlob Word64");
    c.line("  deriving (Eq, Show)");
    c.line("");
    c.line(&format!("-- | specHash: {}.", "the protocol fingerprint; the runtime asserts the loaded core agrees"));
    c.line("specHash :: Word64");
    c.line(&format!("specHash = 0x{:016x}", crate::spec_hash()));
    c.line("");
    for e in spec.enums {
        for (name, value) in e.variants {
            // camel the enum name too: a two-word enum (alert_choice)
            // must not leak a snake half into the identifier.
            let ident = format!("{}{}", camel(e.name), pascal(name));
            c.line(&format!("{ident} :: Word32"));
            c.line(&format!("{ident} = {value}"));
        }
    }
    for (channel, records) in [("tx", spec.tx), ("apply", spec.apply), ("occ", spec.occurrence)] {
        for r in records {
            let ident = format!("{channel}Kind{}", pascal(r.name));
            c.line(&format!("{ident} :: Word16"));
            c.line(&format!("{ident} = {}", r.kind));
        }
    }
    c.line("");
    c.line("-- Values self-pad to 8: they concatenate inside record bodies.");
    c.line("encodeValue :: Value -> Builder");
    c.line("encodeValue v = case v of");
    c.line("  VBool x -> word32LE valueBool <> word32LE 1 <> word8 (if x then 1 else 0)");
    c.line("    <> byteString (BS.replicate 7 0)");
    c.line("  VI64 x -> word32LE valueI64 <> word32LE 8 <> int64LE x");
    c.line("  VF64 x -> word32LE valueF64 <> word32LE 8 <> word64LE (castDoubleToWord64 x)");
    c.line("  VStr x ->");
    c.line("    let utf8 = BL.toStrict (toLazyByteString (stringUtf8 x))");
    c.line("        n = BS.length utf8");
    c.line("        padded = (n + 7) .&. complement 7");
    c.line("     in word32LE valueStr <> word32LE (fromIntegral n) <> byteString utf8");
    c.line("          <> byteString (BS.replicate (padded - n) 0)");
    c.line("  VBlob x -> word32LE valueBlob <> word32LE 8 <> word64LE x");
    c.line("");
    c.line("-- A key path: {u32 count, u32 reserved, count values}.");
    c.line("-- | A counted value sequence: a key path or a record.");
    c.line("encodeValues :: [Value] -> Builder");
    c.line("encodeValues vals =");
    c.line("  word32LE (fromIntegral (length vals)) <> word32LE 0 <> foldMap encodeValue vals");
    c.line("");
    c.line("-- | A collection's element sum: per variant, counted value-type tags,");
    c.line("-- padded to 8. A record collection is the one-variant case.");
    c.line("encodeVariantSchemas :: [[Word32]] -> Builder");
    c.line("encodeVariantSchemas variants =");
    c.line("  let one schema = word32LE (fromIntegral (length schema)) <> foldMap word32LE schema");
    c.line("      body = word32LE (fromIntegral (length variants)) <> word32LE 0 <> foldMap one variants");
    c.line("      len = 8 + 4 * (length variants + sum (map length variants))");
    c.line("      padding = (8 - len `mod` 8) `mod` 8");
    c.line("   in body <> byteString (BS.replicate padding 0)");
    c.line("");
    c.line("wireRecord :: Word16 -> Builder -> Builder");
    c.line("wireRecord kind body =");
    c.line("  let bytes = BL.toStrict (toLazyByteString body)");
    c.line("      size = 8 + BS.length bytes");
    c.line("      padded = (size + 7) .&. complement 7");
    c.line("   in word32LE (fromIntegral padded) <> word16LE kind <> word16LE 0");
    c.line("        <> byteString bytes <> byteString (BS.replicate (padded - size) 0)");

    for r in spec.tx {
        if r.name == "set_property" || r.name == "set_window_prop" {
            continue;
        }
        emit_packer(&mut c, r);
    }

    // The set_property arms, one trio per property: spec-driven so new
    // props reach every binding without emitter edits.
    for (prop, _, kind) in prop_variants(spec) {
        let pc = pascal(prop);
        // Blob setters take the u64 kaya_blob_register handle (see
        // VBlob), so the parameter says so.
        let (p, ty, ctor) = match kind {
            crate::PropKind::Str => (camel(prop), "String", "VStr"),
            crate::PropKind::Bool => (camel(prop), "Bool", "VBool"),
            crate::PropKind::F64 => (camel(prop), "Double", "VF64"),
            crate::PropKind::Blob => ("handle".to_string(), "Word64", "VBlob"),
            crate::PropKind::Enum(_) => (camel(prop), "Int64", "VI64"),
        };
        c.line("");
        c.line(&format!("-- set_property with a constant {prop} value."));
        c.line(&format!("txSet{pc} :: Word64 -> {ty} -> Builder"));
        c.line(&format!("txSet{pc} widgetId {p} = wireRecord txKindSetProperty"));
        c.line(&format!("  (word64LE widgetId <> word32LE prop{pc} <> word32LE sourceConst"));
        c.line(&format!("    <> encodeValue ({ctor} {p}))"));
        c.line("");
        c.line(&format!("-- set_property with a signal-bound {prop} value."));
        c.line(&format!("txBind{pc} :: Word64 -> Word64 -> Builder"));
        c.line(&format!("txBind{pc} widgetId signalId = wireRecord txKindSetProperty"));
        c.line(&format!("  (word64LE widgetId <> word32LE prop{pc} <> word32LE sourceSignal"));
        c.line("    <> word64LE signalId)");
        c.line("");
        c.line("-- set_property bound to one field of the element of the enclosing");
        c.line("-- For, `level` Fors up (0 = nearest; field 0 for a scalar).");
        c.line(&format!("txBind{pc}Element :: Word64 -> Word32 -> Word32 -> Builder"));
        c.line(&format!("txBind{pc}Element widgetId level field = wireRecord txKindSetProperty"));
        c.line(&format!("  (word64LE widgetId <> word32LE prop{pc} <> word32LE sourceElement"));
        c.line("    <> word32LE level <> word32LE field)");
    }

    // The window-prop duos (const + signal — element sources are
    // rejected by the wire). Window 0, the primary surface, until aux
    // windows land.
    for (prop, _, kind) in window_prop_variants(spec) {
        let pc = pascal(prop);
        let (p, ty, ctor) = match kind {
            crate::PropKind::Str => (camel(prop), "String", "VStr"),
            crate::PropKind::F64 => (camel(prop), "Double", "VF64"),
            crate::PropKind::Bool => (camel(prop), "Bool", "VBool"),
            crate::PropKind::Enum(_) => (camel(prop), "Int64", "VI64"),
            other => unreachable!("no window prop carries {other:?}"),
        };
        c.line("");
        c.line(&format!("-- set_window_prop with a constant {prop} value (window 0, the primary surface)."));
        c.line(&format!("txSetWindow{pc} :: Word64 -> {ty} -> Builder"));
        c.line(&format!("txSetWindow{pc} window {p} = wireRecord txKindSetWindowProp"));
        c.line(&format!("  (word64LE window <> word32LE wprop{pc} <> word32LE sourceConst"));
        c.line(&format!("    <> encodeValue ({ctor} {p}))"));
        c.line("");
        c.line(&format!("-- set_window_prop with a signal-bound {prop} value (window 0, the primary surface)."));
        c.line(&format!("txBindWindow{pc} :: Word64 -> Word64 -> Builder"));
        c.line(&format!("txBindWindow{pc} window signalId = wireRecord txKindSetWindowProp"));
        c.line(&format!("  (word64LE window <> word32LE wprop{pc} <> word32LE sourceSignal"));
        c.line("    <> word64LE signalId)");
    }

    // The entry-prop duos (const + signal), the window shape on the
    // navigation-entry table (DESIGN.md, Navigation).
    for (prop, _, kind) in crate::entry_prop_variants(spec) {
        let pc = pascal(prop);
        let (p, ty, ctor) = match kind {
            crate::PropKind::Str => (camel(prop), "String", "VStr"),
            crate::PropKind::Bool => (camel(prop), "Bool", "VBool"),
            other => unreachable!("no entry prop carries {other:?}"),
        };
        c.line("");
        c.line(&format!("-- set_entry_prop with a constant {prop} value."));
        c.line(&format!("txSetEntry{pc} :: Word64 -> {ty} -> Builder"));
        c.line(&format!("txSetEntry{pc} entry {p} = wireRecord txKindSetEntryProp"));
        c.line(&format!("  (word64LE entry <> word32LE eprop{pc} <> word32LE sourceConst"));
        c.line(&format!("    <> encodeValue ({ctor} {p}))"));
        c.line("");
        c.line(&format!("-- set_entry_prop with a signal-bound {prop} value."));
        c.line(&format!("txBindEntry{pc} :: Word64 -> Word64 -> Builder"));
        c.line(&format!("txBindEntry{pc} entry signalId = wireRecord txKindSetEntryProp"));
        c.line(&format!("  (word64LE entry <> word32LE eprop{pc} <> word32LE sourceSignal"));
        c.line("    <> word64LE signalId)");
    }

    // The section-prop duos (const + signal), the entry shape on the
    // section table; icon rides the blob channel (DESIGN.md, Sections).
    for (prop, _, kind) in crate::section_prop_variants(spec) {
        let pc = pascal(prop);
        let (p, ty, ctor) = match kind {
            crate::PropKind::Str => (camel(prop), "String", "VStr"),
            crate::PropKind::Blob => ("handle".to_string(), "Word64", "VBlob"),
            other => unreachable!("no section prop carries {other:?}"),
        };
        c.line("");
        c.line(&format!("-- set_section_prop with a constant {prop} value."));
        c.line(&format!("txSetSection{pc} :: Word64 -> {ty} -> Builder"));
        c.line(&format!("txSetSection{pc} section {p} = wireRecord txKindSetSectionProp"));
        c.line(&format!("  (word64LE section <> word32LE sprop{pc} <> word32LE sourceConst"));
        c.line(&format!("    <> encodeValue ({ctor} {p}))"));
        c.line("");
        c.line(&format!("-- set_section_prop with a signal-bound {prop} value."));
        c.line(&format!("txBindSection{pc} :: Word64 -> Word64 -> Builder"));
        c.line(&format!("txBindSection{pc} section signalId = wireRecord txKindSetSectionProp"));
        c.line(&format!("  (word64LE section <> word32LE sprop{pc} <> word32LE sourceSignal"));
        c.line("    <> word64LE signalId)");
    }

    // The one binding-tier shortcut parser (DESIGN.md, Menus): spelling
    // only — policy (escape, shift-only/bare alphanumerics, the
    // reserved floor) is the core's, validated on the canonical form.
    // txSetMenuShortcut routes through it, so no call site can bypass
    // canonicalization (wireRecord materializes the body strictly, so
    // a bad spelling errors at record construction, before submit).
    let named_keys = crate::SHORTCUT_NAMED_KEYS
        .iter()
        .map(|k| format!("\"{k}\""))
        .collect::<Vec<_>>()
        .join(", ");
    c.line("");
    c.line("shortcutNamedKeys :: [String]");
    c.line(&format!("shortcutNamedKeys = [{named_keys}]"));
    c.line("");
    c.line("-- | Canonicalize a shortcut spelling to the wire form: lowercase");
    c.line("-- '+'-joined tokens, modifiers ordered primary, shift, alt, then one");
    c.line("-- key (a-z, 0-9, or the closed named set). Accepts ASCII case");
    c.line("-- variants and any modifier order; errors on whitespace, empty");
    c.line("-- tokens, repeated modifiers, aliases (ctrl/cmd/option), and unknown");
    c.line("-- or multiple or missing keys. POLICY stays at the core: escape,");
    c.line("-- shift-only and bare alphanumerics, and the reserved floor are");
    c.line("-- validated there, on the canonical spelling, never rewritten.");
    c.line("canonicalizeShortcut :: String -> String");
    c.line("canonicalizeShortcut spelling");
    c.line("  | null spelling = error \"kaya: shortcut is empty\"");
    c.line("  | any (`elem` \" \\t\\n\\v\\f\\r\") spelling =");
    c.line("      error (\"kaya: shortcut \\\"\" ++ spelling ++ \"\\\" contains whitespace\")");
    c.line("  | any null parts =");
    c.line("      error (\"kaya: shortcut \\\"\" ++ spelling ++ \"\\\" has an empty token\")");
    c.line("  | otherwise = emitKey (foldl addMod [] (init parts)) (last parts)");
    c.line("  where");
    c.line("    parts = cut (map toLower spelling)");
    c.line("    cut = foldr step [[]]");
    c.line("      where");
    c.line("        step '+' acc = [] : acc");
    c.line("        step ch (t : ts) = (ch : t) : ts");
    c.line("        step ch [] = [[ch]]");
    c.line("    addMod seen m");
    c.line("      | m /= \"primary\" && m /= \"shift\" && m /= \"alt\" =");
    c.line("          error (\"kaya: shortcut \\\"\" ++ spelling ++ \"\\\" has an unknown modifier \\\"\" ++ m");
    c.line("            ++ \"\\\" (the portable modifiers are primary, shift, alt; aliases like ctrl, cmd, and option are not accepted)\")");
    c.line("      | m `elem` seen =");
    c.line("          error (\"kaya: shortcut \\\"\" ++ spelling ++ \"\\\" repeats modifier \\\"\" ++ m ++ \"\\\"\")");
    c.line("      | otherwise = seen ++ [m]");
    c.line("    emitKey seen key");
    c.line("      | not (alnum key) && key `notElem` shortcutNamedKeys =");
    c.line("          error (\"kaya: shortcut \\\"\" ++ spelling ++ \"\\\" key \\\"\" ++ key");
    c.line("            ++ \"\\\" is outside the floor (one of a-z, 0-9, or the closed named set)\")");
    c.line("      | otherwise =");
    c.line("          concat [m ++ \"+\" | m <- [\"primary\", \"shift\", \"alt\"], m `elem` seen] ++ key");
    c.line("    alnum [ch] = (ch >= 'a' && ch <= 'z') || (ch >= '0' && ch <= '9')");
    c.line("    alnum _ = False");

    // The menu-prop setters (const for every prop; signal binders only
    // for the bindable ones — icon/primary/shortcut are const-only and
    // SOURCE_SIGNAL on them dies at the root).
    for (prop, _, kind) in crate::menu_prop_variants(spec) {
        let pc = pascal(prop);
        let (p, ty, ctor_expr) = match kind {
            crate::PropKind::Str if *prop == "shortcut" => (
                camel(prop),
                "String",
                format!("VStr (canonicalizeShortcut {})", camel(prop)),
            ),
            crate::PropKind::Str => (camel(prop), "String", format!("VStr {}", camel(prop))),
            crate::PropKind::Bool => (camel(prop), "Bool", format!("VBool {}", camel(prop))),
            crate::PropKind::F64 => (camel(prop), "Double", format!("VF64 {}", camel(prop))),
            crate::PropKind::Blob => ("handle".to_string(), "Word64", "VBlob handle".to_string()),
            other => unreachable!("no menu prop carries {other:?}"),
        };
        c.line("");
        if *prop == "shortcut" {
            c.line("-- set_menu_prop with a constant shortcut value, canonicalized here");
            c.line("-- (the one binding-tier shortcut parser — no call site bypasses it).");
        } else {
            c.line(&format!("-- set_menu_prop with a constant {prop} value."));
        }
        c.line(&format!("txSetMenu{pc} :: Word64 -> {ty} -> Builder"));
        c.line(&format!("txSetMenu{pc} item {p} = wireRecord txKindSetMenuProp"));
        c.line(&format!("  (word64LE item <> word32LE mprop{pc} <> word32LE sourceConst"));
        c.line(&format!("    <> encodeValue ({ctor_expr}))"));
        if crate::menu_prop_bindable(prop) {
            c.line("");
            c.line(&format!("-- set_menu_prop with a signal-bound {prop} value."));
            c.line(&format!("txBindMenu{pc} :: Word64 -> Word64 -> Builder"));
            c.line(&format!("txBindMenu{pc} item signalId = wireRecord txKindSetMenuProp"));
            c.line(&format!("  (word64LE item <> word32LE mprop{pc} <> word32LE sourceSignal"));
            c.line("    <> word64LE signalId)");
        }
    }
    c.line("");
    c.line("-- Decode one value at offset `at` from the record base; returns the");
    c.line("-- value and the next offset.");
    c.line("parseValue :: Ptr Word8 -> Int -> IO (Value, Int)");
    c.line("parseValue rec at = do");
    c.line("  vtype <- peekByteOff rec at :: IO Word32");
    c.line("  vlen <- peekByteOff rec (at + 4) :: IO Word32");
    c.line("  let next = at + 8 + fromIntegral ((vlen + 7) .&. complement 7)");
    c.line("  v <-");
    c.line("    if vtype == valueBool");
    c.line("      then VBool . (/= (0 :: Word8)) <$> peekByteOff rec (at + 8)");
    c.line("      else");
    c.line("        if vtype == valueI64");
    c.line("          then VI64 <$> peekByteOff rec (at + 8)");
    c.line("          else");
    c.line("            if vtype == valueF64");
    c.line("              then VF64 . castWord64ToDouble <$> peekByteOff rec (at + 8)");
    c.line("              else");
    c.line("                if vtype == valueBlob");
    c.line("                  then VBlob <$> peekByteOff rec (at + 8)");
    c.line("                  else do");
    c.line("                    bytes <- peekArray (fromIntegral vlen)");
    c.line("                      (rec `plusPtr` (at + 8)) :: IO [Word8]");
    c.line("                    return (VStr (map (chr . fromIntegral) bytes))");
    c.line("  return (v, next)");
    c.line("");
    // The occurrence blob table, the third direction. A blob in an
    // OCCURRENCE is a table handle, not the apply channel's batch-local
    // index: this channel has no boundary that retires one, so it is
    // released explicitly. Redeeming inside the decoder is what keeps a
    // handle from ever reaching an app. The redeemer is THREADED AS AN
    // ARGUMENT rather than installed in a global, because KayaRuntime
    // imports this module and never the reverse — Haskell's answer to
    // an effect a module cannot reach on its own.
    c.line("-- | One representation as the decoder hands it over: the clip");
    c.line("-- kind, and its values with blobs already redeemed to bytes. The");
    c.line("-- sum itself is the hand-written tier\'s — this is the taste-free");
    c.line("-- shape the wire carries.");
    c.line("--");
    c.line("-- The kind is a SINGLE member of the clip enum and never a mask");
    c.line("-- (you offer many and you receive one); 0 with no values is the");
    c.line("-- universal empty answer.");
    c.line("data ClipValues = ClipValues");
    c.line("  { clipKind :: !Word32,");
    c.line("    clipValues :: ![ClipPart]");
    c.line("  }");
    c.line("");
    c.line("-- | One value of a representation. Its own type rather than a");
    c.line("-- constructor on Value, because bytes reach a guest ONLY here —");
    c.line("-- nothing else on the occurrence channel has ever carried them.");
    c.line("data ClipPart = CStr String | CI64 Int64 | CBytes BS.ByteString");
    c.line("");
    c.line("-- Decode a representation at `at`: the clip kind, then its Values");
    c.line("-- block. Blobs are redeemed and RELEASED by `redeem` here.");
    c.line("parseClip ::");
    c.line("  (Word64 -> IO BS.ByteString) -> Ptr Word8 -> Int -> IO (ClipValues, Int)");
    c.line("parseClip redeem rec at = do");
    c.line("  kind <- peekByteOff rec at :: IO Word32");
    c.line("  count <- peekByteOff rec (at + 8) :: IO Word32");
    c.line("  let go a 0 acc = return (reverse acc, a)");
    c.line("      go a n acc = do");
    c.line("        (v, next) <- parseValue rec a");
    c.line("        part <- case v of");
    c.line("          VBlob h -> CBytes <$> redeem h");
    c.line("          VI64 i -> return (CI64 i)");
    c.line("          VStr t -> return (CStr t)");
    c.line("          other -> return (CStr (show other))");
    c.line("        go next (n - 1 :: Word32) (part : acc)");
    c.line("  (parts, at') <- go (at + 16) count []");
    c.line("  return (ClipValues kind parts, at')");
    c.line("");
    c.line("-- Decode one occurrence record at `rec` (header included). Just");
    c.line("-- (kind, id, keys, payload) — keys is [] when id is a widget id,");
    c.line("-- else id is a template node id and keys is the copy's key path;");
    c.line("-- payload is Just for text_changed (VStr), toggled (VBool), and");
    c.line("-- value_changed (VF64),");
    c.line("-- Nothing for clicks. Nothing for pad or unknown kinds.");
    c.line("parseOccurrence ::");
    c.line("  (Word64 -> IO BS.ByteString) ->");
    c.line("  Ptr Word8 ->");
    c.line("  IO (Maybe (Word16, Word64, [Value], Maybe Value, Maybe ClipValues))");
    c.line("parseOccurrence redeem rec = do");
    c.line("  kind <- peekByteOff rec 4 :: IO Word16");
    let accepted = crate::occurrence_names(spec)
        .iter()
        .map(|n| format!("kind /= occKind{}", pascal(n)))
        .collect::<Vec<_>>()
        .join(" && ");
    c.line(&format!("  if {accepted}"));
    c.line("    then return Nothing");
    c.line("    else do");
    c.line("      ident <- peekByteOff rec 8 :: IO Word64");
    c.line("      if kind == occKindAlertResult");
    c.line("        then do");
    c.line("          -- The alert's one answer: id + u32 choice (alertChoice*).");
    c.line("          choice <- peekByteOff rec 16 :: IO Word32");
    c.line("          return (Just (kind, ident, [], Just (VI64 (fromIntegral choice)), Nothing))");
    // The picker's answer is a LIST OF RECORDS, and no single Value
    // can carry one — so the three values per file ride the VALUES
    // slot, flattened, and KayaApp regroups them in threes. The
    // generic tail would read that slot as a key path and take the
    // file count as its length, starting eight bytes early.
    c.line("      else if kind == occKindFileDialogResult");
    c.line("        then do");
    c.line("          -- id, a count, then three Values per file (handle,");
    c.line("          -- name, localPath), FLATTENED into the values slot;");
    c.line("          -- the app layer regroups them. EMPTY IS CANCEL.");
    c.line("          count <- peekByteOff rec 16 :: IO Word32");
    c.line("          let readValues 0 _ acc = return (reverse acc)");
    c.line("              readValues n at acc = do");
    c.line("                (v, next) <- parseValue rec at");
    c.line("                readValues (n - 1 :: Int) next (v : acc)");
    c.line("          vals <- readValues (fromIntegral count * 3) 32 []");
    c.line("          return (Just (kind, ident, vals, Nothing, Nothing))");
    for name in crate::clip_answer_occurrence_names(spec) {
        c.line(&format!(
            "      else if kind == occKind{}",
            pascal(name)
        ));
        c.line("        then do");
        c.line("          (clip, _) <- parseClip redeem rec 16");
        c.line("          return (Just (kind, ident, [], Nothing, Just clip))");
    }
    let id_only = crate::id_only_occurrence_names(spec)
        .iter()
        .map(|n| format!("kind == occKind{}", pascal(n)))
        .collect::<Vec<_>>()
        .join(" || ");
    c.line("        -- Surface lifecycle records carry the surface id alone");
    c.line("        -- (derived from the record shapes).");
    c.line(&format!("        else if {id_only}"));
    c.line("          then return (Just (kind, ident, [], Nothing, Nothing))");
    let id_pair = crate::id_pair_occurrence_names(spec)
        .iter()
        .map(|n| format!("kind == occKind{}", pascal(n)))
        .collect::<Vec<_>>()
        .join(" || ");
    if !id_pair.is_empty() {
        c.line("        -- Surface-pair records (window, section): the SECOND id");
        c.line("        -- keys the handler; the first rides as the payload.");
        c.line(&format!("        else if {id_pair}"));
        c.line("          then do");
        c.line("            second <- peekByteOff rec 16 :: IO Word64");
        c.line("            return (Just (kind, second, [], Just (VI64 (fromIntegral ident)), Nothing))");
    }
    c.line("          else do");
    c.line("          pathLen <- peekByteOff rec 16 :: IO Word32");
    c.line("          let go at 0 acc = return (reverse acc, at)");
    c.line("              go at n acc = do");
    c.line("                (v, next) <- parseValue rec at");
    c.line("                go next (n - 1 :: Word32) (v : acc)");
    c.line("          (keys, at') <- go (24 :: Int) pathLen []");
    c.line("          payload <-");
    let with_payload = crate::payload_occurrence_names(spec)
        .iter()
        .map(|n| format!("kind == occKind{}", pascal(n)))
        .collect::<Vec<_>>()
        .join(" || ");
    c.line(&format!("            if {with_payload}"));
    c.line("              then do");
    c.line("                (v, _) <- parseValue rec at'");
    c.line("                return (Just v)");
    c.line("              else return Nothing");
    // A paste rides a click tag VERBATIM, so the key path above is
    // already read and the clip sits after it — the way text_changed's
    // payload does. One record kind, path_len deciding, exactly as a
    // click on a stamped row is one record with a click on a live one.
    {
        let pasted = crate::pasted_occurrence_names(spec)
            .iter()
            .map(|n| format!("kind == occKind{}", pascal(n)))
            .collect::<Vec<_>>()
            .join(" || ");
        if pasted.is_empty() {
            c.line("          let clip = Nothing");
        } else {
            c.line(&format!("          clip <-"));
            c.line(&format!("            if {pasted}"));
            c.line("              then do");
            c.line("                (c, _) <- parseClip redeem rec at'");
            c.line("                return (Just c)");
            c.line("              else return Nothing");
        }
    }
    c.line("          return (Just (kind, ident, keys, payload, clip))");
    c.out
}

fn emit_packer(c: &mut Ctx, r: &Record) {
    let params = record_params(r);
    let mut types: Vec<&str> = Vec::new();
    let mut names: Vec<String> = Vec::new();
    for f in &params {
        types.push(match f.ty {
            FieldTy::U32 => "Word32",
            FieldTy::U64 => "Word64",
            FieldTy::Value => "Value",
            FieldTy::Values => "[Value]",
            FieldTy::VariantSchemas => "[[Word32]]",
        });
        names.push(camel(f.name));
    }
    let mut sig = types.join(" -> ");
    if !sig.is_empty() {
        sig.push_str(" -> ");
    }
    c.line("");
    c.line(&format!("-- {}", r.doc.replace('\n', " ")));
    c.line(&format!("tx{} :: {sig}Builder", pascal(r.name)));
    let mut body: Vec<String> = Vec::new();
    for f in r.fields {
        body.push(match f.ty {
            FieldTy::U32 if f.name == "reserved" => "word32LE 0".into(),
            FieldTy::U32 => format!("word32LE {}", camel(f.name)),
            FieldTy::U64 => format!("word64LE {}", camel(f.name)),
            FieldTy::Value => format!("encodeValue {}", camel(f.name)),
            FieldTy::Values => format!("encodeValues {}", camel(f.name)),
            FieldTy::VariantSchemas => format!("encodeVariantSchemas {}", camel(f.name)),
        });
    }
    let body = if body.is_empty() {
        "mempty".to_string()
    } else {
        body.join(" <> ")
    };
    c.line(&format!(
        "tx{} {}= wireRecord txKind{} ({body})",
        pascal(r.name),
        if names.is_empty() {
            String::new()
        } else {
            names.join(" ") + " "
        },
        pascal(r.name)
    ));
}
