//! Haskell emitter: module KayaWire — a Value type, constants, Builder
//! packers, and the occurrence parser (peeks relative to a record
//! pointer). Module scope namespaces everything; parameters are
//! lower-camel locals, so the reserved set is keywords plus the helper
//! names.

use kaya::spec::{FieldTy, ProtocolSpec, Record};

use crate::{Ctx, prop_variants, record_params};

pub const RESERVED: &[&str] = &[
    "encodeValue", "encodeValues", "encodeTypeTags", "wireRecord", "parseValue", "parseOccurrence",
    "case", "class", "data", "default", "deriving", "do", "else", "foreign", "if", "import",
    "in", "infix", "infixl", "infixr", "instance", "let", "module", "newtype", "of", "then",
    "type", "where",
];

fn camel(name: &str) -> String {
    let mut parts = name.split('_');
    let mut out = parts.next().unwrap_or_default().to_string();
    for w in parts {
        let mut chars = w.chars();
        if let Some(first) = chars.next() {
            out.push_str(&first.to_uppercase().collect::<String>());
            out.push_str(chars.as_str());
        }
    }
    out
}

fn pascal(name: &str) -> String {
    let c = camel(name);
    let mut chars = c.chars();
    match chars.next() {
        Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    }
}

pub fn emit(spec: &ProtocolSpec) -> String {
    let mut c = Ctx { out: String::new() };
    c.line("-- kaya wire vocabulary. Generated by kaya-bindgen from kaya::spec — do not edit.");
    c.line("--");
    c.line("-- Records are {u32 size, u16 kind, u16 flags}, body, padded to 8,");
    c.line("-- little-endian; each tx* returns one packed record as a Builder,");
    c.line("-- and a transaction is their concatenation.");
    c.line("module KayaWire where");
    c.line("");
    c.line("import Data.Bits (complement, (.&.))");
    c.line("import qualified Data.ByteString as BS");
    c.line("import Data.ByteString.Builder");
    c.line("import qualified Data.ByteString.Lazy as BL");
    c.line("import Data.Int (Int64)");
    c.line("import Data.Word (Word16, Word32, Word64, Word8)");
    c.line("import Foreign.Marshal.Array (peekArray)");
    c.line("import Foreign.Ptr (Ptr, plusPtr)");
    c.line("import Foreign.Storable (peekByteOff)");
    c.line("import GHC.Float (castDoubleToWord64, castWord64ToDouble)");
    c.line("import Data.Char (chr)");
    c.line("");
    c.line("data Value = VBool Bool | VI64 Int64 | VF64 Double | VStr String");
    c.line("  deriving (Eq, Show)");
    c.line("");
    c.line(&format!("-- | specHash: {}.", "the protocol fingerprint; the runtime asserts the loaded core agrees"));
    c.line("specHash :: Word64");
    c.line(&format!("specHash = 0x{:016x}", crate::spec_hash()));
    c.line("");
    for e in spec.enums {
        for (name, value) in e.variants {
            let ident = format!("{}{}", e.name, pascal(name));
            c.line(&format!("{ident} :: Word32"));
            c.line(&format!("{ident} = {value}"));
        }
    }
    for (channel, records) in [("tx", spec.tx), ("apply", spec.apply), ("occ", spec.occurrence)] {
        for r in records {
            let ident = format!("{channel}Kind{}", pascal(r.name));
            c.line(&format!("{ident} :: Word16"));
            c.line(&format!("{ident} = {}", r.kind));
        }
    }
    c.line("");
    c.line("-- Values self-pad to 8: they concatenate inside record bodies.");
    c.line("encodeValue :: Value -> Builder");
    c.line("encodeValue v = case v of");
    c.line("  VBool x -> word32LE valueBool <> word32LE 1 <> word8 (if x then 1 else 0)");
    c.line("    <> byteString (BS.replicate 7 0)");
    c.line("  VI64 x -> word32LE valueI64 <> word32LE 8 <> int64LE x");
    c.line("  VF64 x -> word32LE valueF64 <> word32LE 8 <> word64LE (castDoubleToWord64 x)");
    c.line("  VStr x ->");
    c.line("    let utf8 = BL.toStrict (toLazyByteString (stringUtf8 x))");
    c.line("        n = BS.length utf8");
    c.line("        padded = (n + 7) .&. complement 7");
    c.line("     in word32LE valueStr <> word32LE (fromIntegral n) <> byteString utf8");
    c.line("          <> byteString (BS.replicate (padded - n) 0)");
    c.line("");
    c.line("-- A key path: {u32 count, u32 reserved, count values}.");
    c.line("-- | A counted value sequence: a key path or a record.");
    c.line("encodeValues :: [Value] -> Builder");
    c.line("encodeValues vals =");
    c.line("  word32LE (fromIntegral (length vals)) <> word32LE 0 <> foldMap encodeValue vals");
    c.line("");
    c.line("-- | A collection schema: counted value-type tags, padded to 8.");
    c.line("encodeTypeTags :: [Word32] -> Builder");
    c.line("encodeTypeTags tags =");
    c.line("  let body = word32LE (fromIntegral (length tags)) <> word32LE 0 <> foldMap word32LE tags");
    c.line("      len = 8 + 4 * length tags");
    c.line("      padding = (8 - len `mod` 8) `mod` 8");
    c.line("   in body <> byteString (BS.replicate padding 0)");
    c.line("");
    c.line("wireRecord :: Word16 -> Builder -> Builder");
    c.line("wireRecord kind body =");
    c.line("  let bytes = BL.toStrict (toLazyByteString body)");
    c.line("      size = 8 + BS.length bytes");
    c.line("      padded = (size + 7) .&. complement 7");
    c.line("   in word32LE (fromIntegral padded) <> word16LE kind <> word16LE 0");
    c.line("        <> byteString bytes <> byteString (BS.replicate (padded - size) 0)");

    for r in spec.tx {
        if r.name == "set_property" {
            continue;
        }
        emit_packer(&mut c, r);
    }

    // The set_property arms, one trio per property: spec-driven so new
    // props reach every binding without emitter edits.
    for (prop, _, kind) in prop_variants(spec) {
        let p = camel(prop);
        let pc = pascal(prop);
        let (ty, ctor) = match kind {
            crate::PropKind::Str => ("String", "VStr"),
            crate::PropKind::Bool => ("Bool", "VBool"),
            crate::PropKind::F64 => ("Double", "VF64"),
        };
        c.line("");
        c.line(&format!("-- set_property with a constant {prop} value."));
        c.line(&format!("txSet{pc} :: Word64 -> {ty} -> Builder"));
        c.line(&format!("txSet{pc} widgetId {p} = wireRecord txKindSetProperty"));
        c.line(&format!("  (word64LE widgetId <> word32LE prop{pc} <> word32LE sourceConst"));
        c.line(&format!("    <> encodeValue ({ctor} {p}))"));
        c.line("");
        c.line(&format!("-- set_property with a signal-bound {prop} value."));
        c.line(&format!("txBind{pc} :: Word64 -> Word64 -> Builder"));
        c.line(&format!("txBind{pc} widgetId signalId = wireRecord txKindSetProperty"));
        c.line(&format!("  (word64LE widgetId <> word32LE prop{pc} <> word32LE sourceSignal"));
        c.line("    <> word64LE signalId)");
        c.line("");
        c.line("-- set_property bound to one field of the element of the enclosing");
        c.line("-- For, `level` Fors up (0 = nearest; field 0 for a scalar).");
        c.line(&format!("txBind{pc}Element :: Word64 -> Word32 -> Word32 -> Builder"));
        c.line(&format!("txBind{pc}Element widgetId level field = wireRecord txKindSetProperty"));
        c.line(&format!("  (word64LE widgetId <> word32LE prop{pc} <> word32LE sourceElement"));
        c.line("    <> word32LE level <> word32LE field)");
    }
    c.line("");
    c.line("-- Decode one value at offset `at` from the record base; returns the");
    c.line("-- value and the next offset.");
    c.line("parseValue :: Ptr Word8 -> Int -> IO (Value, Int)");
    c.line("parseValue rec at = do");
    c.line("  vtype <- peekByteOff rec at :: IO Word32");
    c.line("  vlen <- peekByteOff rec (at + 4) :: IO Word32");
    c.line("  let next = at + 8 + fromIntegral ((vlen + 7) .&. complement 7)");
    c.line("  v <-");
    c.line("    if vtype == valueBool");
    c.line("      then VBool . (/= (0 :: Word8)) <$> peekByteOff rec (at + 8)");
    c.line("      else");
    c.line("        if vtype == valueI64");
    c.line("          then VI64 <$> peekByteOff rec (at + 8)");
    c.line("          else");
    c.line("            if vtype == valueF64");
    c.line("              then VF64 . castWord64ToDouble <$> peekByteOff rec (at + 8)");
    c.line("              else do");
    c.line("                bytes <- peekArray (fromIntegral vlen)");
    c.line("                  (rec `plusPtr` (at + 8)) :: IO [Word8]");
    c.line("                return (VStr (map (chr . fromIntegral) bytes))");
    c.line("  return (v, next)");
    c.line("");
    c.line("-- Decode one occurrence record at `rec` (header included). Just");
    c.line("-- (kind, id, keys, payload) — keys is [] when id is a widget id,");
    c.line("-- else id is a template node id and keys is the copy's key path;");
    c.line("-- payload is Just for text_changed (VStr), toggled (VBool), and");
    c.line("-- value_changed (VF64),");
    c.line("-- Nothing for clicks. Nothing for pad or unknown kinds.");
    c.line("parseOccurrence :: Ptr Word8 -> IO (Maybe (Word16, Word64, [Value], Maybe Value))");
    c.line("parseOccurrence rec = do");
    c.line("  kind <- peekByteOff rec 4 :: IO Word16");
    let accepted = crate::occurrence_names(spec)
        .iter()
        .map(|n| format!("kind /= occKind{}", pascal(n)))
        .collect::<Vec<_>>()
        .join(" && ");
    c.line(&format!("  if {accepted}"));
    c.line("    then return Nothing");
    c.line("    else do");
    c.line("      ident <- peekByteOff rec 8 :: IO Word64");
    c.line("      pathLen <- peekByteOff rec 16 :: IO Word32");
    c.line("      let go at 0 acc = return (reverse acc, at)");
    c.line("          go at n acc = do");
    c.line("            (v, next) <- parseValue rec at");
    c.line("            go next (n - 1 :: Word32) (v : acc)");
    c.line("      (keys, at') <- go (24 :: Int) pathLen []");
    c.line("      payload <-");
    let with_payload = crate::payload_occurrence_names(spec)
        .iter()
        .map(|n| format!("kind == occKind{}", pascal(n)))
        .collect::<Vec<_>>()
        .join(" || ");
    c.line(&format!("        if {with_payload}"));
    c.line("          then do");
    c.line("            (v, _) <- parseValue rec at'");
    c.line("            return (Just v)");
    c.line("          else return Nothing");
    c.line("      return (Just (kind, ident, keys, payload))");
    c.out
}

fn emit_packer(c: &mut Ctx, r: &Record) {
    let params = record_params(r);
    let mut types: Vec<&str> = Vec::new();
    let mut names: Vec<String> = Vec::new();
    for f in &params {
        types.push(match f.ty {
            FieldTy::U32 => "Word32",
            FieldTy::U64 => "Word64",
            FieldTy::Value => "Value",
            FieldTy::Values => "[Value]",
            FieldTy::TypeTags => "[Word32]",
        });
        names.push(camel(f.name));
    }
    let mut sig = types.join(" -> ");
    if !sig.is_empty() {
        sig.push_str(" -> ");
    }
    c.line("");
    c.line(&format!("-- {}", r.doc.replace('\n', " ")));
    c.line(&format!("tx{} :: {sig}Builder", pascal(r.name)));
    let mut body: Vec<String> = Vec::new();
    for f in r.fields {
        body.push(match f.ty {
            FieldTy::U32 if f.name == "reserved" => "word32LE 0".into(),
            FieldTy::U32 => format!("word32LE {}", camel(f.name)),
            FieldTy::U64 => format!("word64LE {}", camel(f.name)),
            FieldTy::Value => format!("encodeValue {}", camel(f.name)),
            FieldTy::Values => format!("encodeValues {}", camel(f.name)),
            FieldTy::TypeTags => format!("encodeTypeTags {}", camel(f.name)),
        });
    }
    let body = if body.is_empty() {
        "mempty".to_string()
    } else {
        body.join(" <> ")
    };
    c.line(&format!(
        "tx{} {}= wireRecord txKind{} ({body})",
        pascal(r.name),
        if names.is_empty() {
            String::new()
        } else {
            names.join(" ") + " "
        },
        pascal(r.name)
    ));
}
