//! Java emitter: dev.kaya.KayaWire — constants, byte[] packers via
//! ByteBuffer, and the byte[] occurrence parser. The class namespaces
//! everything; encoder helpers are private. The direct-tier ring loop
//! (Unsafe on raw addresses) stays with its consumer — parsing from an
//! address is the runtime's business, but a copied record parses here.

use kaya::spec::{FieldTy, ProtocolSpec, Record};

use crate::{Ctx, prop_variants, record_params};

pub const RESERVED: &[&str] = &[
    "abstract", "assert", "boolean", "break", "byte", "case", "catch", "char", "class", "const",
    "continue", "default", "do", "double", "else", "enum", "extends", "final", "finally",
    "float", "for", "goto", "if", "implements", "import", "instanceof", "int", "interface",
    "long", "native", "new", "package", "private", "protected", "public", "return", "short",
    "static", "strictfp", "super", "switch", "synchronized", "this", "throw", "throws",
    "transient", "try", "void", "volatile", "while",
];

fn pascal(name: &str) -> String {
    name.split('_')
        .map(|w| {
            let mut chars = w.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

fn camel(name: &str) -> String {
    let p = pascal(name);
    let mut chars = p.chars();
    match chars.next() {
        Some(first) => first.to_lowercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    }
}

pub fn emit(spec: &ProtocolSpec) -> String {
    let mut c = Ctx { out: String::new() };
    c.line("// kaya wire vocabulary. Generated by kaya-bindgen from kaya::spec — do not edit.");
    c.line("//");
    c.line("// Records are {u32 size, u16 kind, u16 flags}, body, padded to 8,");
    c.line("// little-endian. Values accept Boolean, Long, Double, and String,");
    c.line("// mapped to the kaya value types; keys in paths likewise.");
    c.line("package dev.kaya;");
    c.line("");
    c.line("import java.nio.ByteBuffer;");
    c.line("import java.nio.ByteOrder;");
    c.line("import java.nio.charset.StandardCharsets;");
    c.line("import java.util.ArrayList;");
    c.line("import java.util.List;");
    c.line("");
    c.line("public final class KayaWire {");
    for e in spec.enums {
        for (name, value) in e.variants {
            c.line(&format!(
                "    public static final int {}_{} = {};",
                e.name.to_uppercase(),
                name.to_uppercase(),
                value
            ));
        }
    }
    for (channel, records) in [("TX", spec.tx), ("APPLY", spec.apply), ("OCC", spec.occurrence)] {
        for r in records {
            c.line(&format!(
                "    public static final short {channel}_KIND_{} = {};",
                r.name.to_uppercase(),
                r.kind
            ));
        }
    }
    c.line("");
    c.line("    private static ByteBuffer begin(short kind) {");
    c.line("        ByteBuffer b = ByteBuffer.allocate(4096).order(ByteOrder.LITTLE_ENDIAN);");
    c.line("        b.putInt(0).putShort(kind).putShort((short) 0);");
    c.line("        return b;");
    c.line("    }");
    c.line("");
    c.line("    private static byte[] finish(ByteBuffer b) {");
    c.line("        while (b.position() % 8 != 0) b.put((byte) 0);");
    c.line("        b.putInt(0, b.position());");
    c.line("        byte[] out = new byte[b.position()];");
    c.line("        b.flip();");
    c.line("        b.get(out);");
    c.line("        return out;");
    c.line("    }");
    c.line("");
    c.line("    // Values self-pad to 8: they concatenate inside record bodies.");
    c.line("    private static void encodeValue(ByteBuffer b, Object v) {");
    c.line("        if (v instanceof Boolean) {");
    c.line("            b.putInt(VALUE_BOOL).putInt(1).put((byte) (((Boolean) v) ? 1 : 0));");
    c.line("        } else if (v instanceof Integer) {");
    c.line("            b.putInt(VALUE_I64).putInt(8).putLong((Integer) v);");
    c.line("        } else if (v instanceof Long) {");
    c.line("            b.putInt(VALUE_I64).putInt(8).putLong((Long) v);");
    c.line("        } else if (v instanceof Double) {");
    c.line("            b.putInt(VALUE_F64).putInt(8).putDouble((Double) v);");
    c.line("        } else if (v instanceof String) {");
    c.line("            byte[] utf8 = ((String) v).getBytes(StandardCharsets.UTF_8);");
    c.line("            b.putInt(VALUE_STR).putInt(utf8.length).put(utf8);");
    c.line("        } else {");
    c.line("            throw new IllegalArgumentException(");
    c.line("                    \"kaya: value must be Boolean, Long, Double, or String\");");
    c.line("        }");
    c.line("        while (b.position() % 8 != 0) b.put((byte) 0);");
    c.line("    }");
    c.line("");
    c.line("    // A key path: {u32 count, u32 reserved, count values}.");
    c.line("    private static void encodePath(ByteBuffer b, Object[] keys) {");
    c.line("        int n = keys == null ? 0 : keys.length;");
    c.line("        b.putInt(n).putInt(0);");
    c.line("        for (int i = 0; i < n; i++) encodeValue(b, keys[i]);");
    c.line("    }");

    for r in spec.tx {
        if r.name == "set_property" {
            continue;
        }
        emit_packer(&mut c, r);
    }

    // The set_property arms, one trio per property: spec-driven so new
    // props reach every binding without emitter edits.
    for (prop, _) in prop_variants(spec) {
        let p = camel(prop);
        let pc = pascal(prop);
        let up = prop.to_uppercase();
        c.line("");
        c.line(&format!("    /** set_property with a constant {prop} value. */"));
        c.line(&format!("    public static byte[] txSet{pc}(long widgetId, String {p}) {{"));
        c.line("        ByteBuffer b = begin(TX_KIND_SET_PROPERTY);");
        c.line(&format!("        b.putLong(widgetId).putInt(PROP_{up}).putInt(SOURCE_CONST);"));
        c.line(&format!("        encodeValue(b, {p});"));
        c.line("        return finish(b);");
        c.line("    }");
        c.line("");
        c.line(&format!("    /** set_property with a signal-bound {prop} value. */"));
        c.line(&format!("    public static byte[] txBind{pc}(long widgetId, long signalId) {{"));
        c.line("        ByteBuffer b = begin(TX_KIND_SET_PROPERTY);");
        c.line(&format!("        b.putLong(widgetId).putInt(PROP_{up}).putInt(SOURCE_SIGNAL).putLong(signalId);"));
        c.line("        return finish(b);");
        c.line("    }");
        c.line("");
        c.line("    /** set_property bound to the element of the enclosing For, `level` Fors up. */");
        c.line(&format!("    public static byte[] txBind{pc}Element(long widgetId, int level) {{"));
        c.line("        ByteBuffer b = begin(TX_KIND_SET_PROPERTY);");
        c.line(&format!("        b.putLong(widgetId).putInt(PROP_{up}).putInt(SOURCE_ELEMENT)"));
        c.line("                .putInt(level).putInt(0);");
        c.line("        return finish(b);");
        c.line("    }");
    }
    c.line("");
    c.line("    /** Concatenate packed records into one transaction. */");
    c.line("    public static byte[] tx(byte[]... records) {");
    c.line("        int len = 0;");
    c.line("        for (byte[] r : records) len += r.length;");
    c.line("        byte[] out = new byte[len];");
    c.line("        int at = 0;");
    c.line("        for (byte[] r : records) {");
    c.line("            System.arraycopy(r, 0, out, at, r.length);");
    c.line("            at += r.length;");
    c.line("        }");
    c.line("        return out;");
    c.line("    }");
    c.line("");
    c.line("    /** A parsed click: the id and the copy's key path (empty for a");
    c.line("     * click on a guest-created widget, where id is a widget id;");
    c.line("     * otherwise id is a template node id). */");
    c.line("    public static final class Click {");
    c.line("        public final long id;");
    c.line("        public final List<Object> keys;");
    c.line("");
    c.line("        Click(long id, List<Object> keys) {");
    c.line("            this.id = id;");
    c.line("            this.keys = keys;");
    c.line("        }");
    c.line("    }");
    c.line("");
    c.line("    /** Decode one occurrence record (header included); null for");
    c.line("     * non-click records. */");
    c.line("    public static Click parseClick(byte[] rec) {");
    c.line("        ByteBuffer b = ByteBuffer.wrap(rec).order(ByteOrder.LITTLE_ENDIAN);");
    c.line("        if (b.getShort(4) != OCC_KIND_BUTTON_CLICKED) return null;");
    c.line("        long id = b.getLong(8);");
    c.line("        int pathLen = b.getInt(16);");
    c.line("        List<Object> keys = new ArrayList<>();");
    c.line("        int at = 24;");
    c.line("        for (int i = 0; i < pathLen; i++) {");
    c.line("            int vtype = b.getInt(at);");
    c.line("            int vlen = b.getInt(at + 4);");
    c.line("            switch (vtype) {");
    c.line("                case VALUE_BOOL: keys.add(rec[at + 8] != 0); break;");
    c.line("                case VALUE_I64: keys.add(b.getLong(at + 8)); break;");
    c.line("                case VALUE_F64: keys.add(b.getDouble(at + 8)); break;");
    c.line("                default:");
    c.line("                    keys.add(new String(rec, at + 8, vlen, StandardCharsets.UTF_8));");
    c.line("            }");
    c.line("            at += 8 + ((vlen + 7) & ~7);");
    c.line("        }");
    c.line("        return new Click(id, keys);");
    c.line("    }");
    c.line("");
    c.line("    private KayaWire() {}");
    c.line("}");
    c.out
}

fn emit_packer(c: &mut Ctx, r: &Record) {
    let params = record_params(r);
    let mut sig: Vec<String> = Vec::new();
    for f in &params {
        sig.push(match f.ty {
            FieldTy::U32 => format!("int {}", camel(f.name)),
            FieldTy::U64 => format!("long {}", camel(f.name)),
            FieldTy::Value => format!("Object {}", camel(f.name)),
            FieldTy::Path => format!("Object[] {}", camel(f.name)),
        });
    }
    c.line("");
    c.line(&format!("    /** {} */", r.doc.replace('\n', " ")));
    c.line(&format!(
        "    public static byte[] tx{}({}) {{",
        pascal(r.name),
        sig.join(", ")
    ));
    c.line(&format!(
        "        ByteBuffer b = begin(TX_KIND_{});",
        r.name.to_uppercase()
    ));
    for f in r.fields {
        c.line(&match f.ty {
            FieldTy::U32 if f.name == "reserved" => "        b.putInt(0);".into(),
            FieldTy::U32 => format!("        b.putInt({});", camel(f.name)),
            FieldTy::U64 => format!("        b.putLong({});", camel(f.name)),
            FieldTy::Value => format!("        encodeValue(b, {});", camel(f.name)),
            FieldTy::Path => format!("        encodePath(b, {});", camel(f.name)),
        });
    }
    c.line("        return finish(b);");
    c.line("    }");
}
