//! Java emitter: dev.kaya.KayaWire — constants, byte[] packers via
//! ByteBuffer, and the byte[] occurrence parser. The class namespaces
//! everything; encoder helpers are private. The direct-tier ring loop
//! (Unsafe on raw addresses) stays with its consumer — parsing from an
//! address is the runtime's business, but a copied record parses here.

use kaya::spec::{FieldTy, ProtocolSpec, Record};

use crate::{Ctx, prop_variants, record_params, window_prop_variants};

pub const RESERVED: &[&str] = &[
    "abstract", "assert", "boolean", "break", "byte", "case", "catch", "char", "class", "const",
    "continue", "default", "do", "double", "else", "enum", "extends", "final", "finally",
    "float", "for", "goto", "if", "implements", "import", "instanceof", "int", "interface",
    "long", "native", "new", "package", "private", "protected", "public", "return", "short",
    "static", "strictfp", "super", "switch", "synchronized", "this", "throw", "throws",
    "transient", "try", "void", "volatile", "while",
];

fn pascal(name: &str) -> String {
    name.split('_')
        .map(|w| {
            let mut chars = w.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

fn camel(name: &str) -> String {
    let p = pascal(name);
    let mut chars = p.chars();
    match chars.next() {
        Some(first) => first.to_lowercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    }
}

pub fn emit(spec: &ProtocolSpec) -> String {
    let mut c = Ctx { out: String::new() };
    c.line("// kaya wire vocabulary. Generated by kaya-bindgen from kaya::spec — do not edit.");
    c.line("//");
    c.line("// Records are {u32 size, u16 kind, u16 flags}, body, padded to 8,");
    c.line("// little-endian. Values accept Boolean, Long, Double, String, and");
    c.line("// BlobHandle, mapped to the kaya value types; keys in paths likewise.");
    c.line("package dev.kaya;");
    c.line("");
    c.line("import java.nio.ByteBuffer;");
    c.line("import java.nio.ByteOrder;");
    c.line("import java.nio.charset.StandardCharsets;");
    c.line("import java.util.ArrayList;");
    c.line("import java.util.List;");
    c.line("");
    c.line("public final class KayaWire {");
    c.line(&format!("    /** SPEC_HASH: {}. */", "the protocol fingerprint; the runtime asserts the loaded core agrees"));
    c.line(&format!("    public static final long SPEC_HASH = 0x{:016x}L;", crate::spec_hash()));
    c.line("");
    for e in spec.enums {
        for (name, value) in e.variants {
            // Java has no unsigned int: a wire u32 above i32::MAX is
            // spelled as its two's-complement value, which is exactly
            // what reading the wire's u32 into a java int yields — so
            // == against the constant stays correct (the alert_choice
            // cancel sentinel is the first such value).
            c.line(&format!(
                "    public static final int {}_{} = {};",
                e.name.to_uppercase(),
                name.to_uppercase(),
                *value as i32
            ));
        }
    }
    for (channel, records) in [("TX", spec.tx), ("APPLY", spec.apply), ("OCC", spec.occurrence)] {
        for r in records {
            c.line(&format!(
                "    public static final short {channel}_KIND_{} = {};",
                r.name.to_uppercase(),
                r.kind
            ));
        }
    }
    c.line("");
    c.line("    /** A blob value: the u64 handle from kaya_blob_register, consumed");
    c.line("     * by the next submit; the bytes never ride the record stream. */");
    c.line("    public static final class BlobHandle {");
    c.line("        public final long handle;");
    c.line("");
    c.line("        public BlobHandle(long handle) {");
    c.line("            this.handle = handle;");
    c.line("        }");
    c.line("    }");
    c.line("");
    c.line("    private static ByteBuffer begin(short kind) {");
    c.line("        ByteBuffer b = ByteBuffer.allocate(4096).order(ByteOrder.LITTLE_ENDIAN);");
    c.line("        b.putInt(0).putShort(kind).putShort((short) 0);");
    c.line("        return b;");
    c.line("    }");
    c.line("");
    c.line("    private static byte[] finish(ByteBuffer b) {");
    c.line("        while (b.position() % 8 != 0) b.put((byte) 0);");
    c.line("        b.putInt(0, b.position());");
    c.line("        byte[] out = new byte[b.position()];");
    c.line("        b.flip();");
    c.line("        b.get(out);");
    c.line("        return out;");
    c.line("    }");
    c.line("");
    c.line("    // Values self-pad to 8: they concatenate inside record bodies.");
    c.line("    private static void encodeValue(ByteBuffer b, Object v) {");
    c.line("        if (v instanceof Boolean) {");
    c.line("            b.putInt(VALUE_BOOL).putInt(1).put((byte) (((Boolean) v) ? 1 : 0));");
    c.line("        } else if (v instanceof Integer) {");
    c.line("            b.putInt(VALUE_I64).putInt(8).putLong((Integer) v);");
    c.line("        } else if (v instanceof Long) {");
    c.line("            b.putInt(VALUE_I64).putInt(8).putLong((Long) v);");
    c.line("        } else if (v instanceof Double) {");
    c.line("            b.putInt(VALUE_F64).putInt(8).putDouble((Double) v);");
    c.line("        } else if (v instanceof String) {");
    c.line("            byte[] utf8 = ((String) v).getBytes(StandardCharsets.UTF_8);");
    c.line("            b.putInt(VALUE_STR).putInt(utf8.length).put(utf8);");
    c.line("        } else if (v instanceof BlobHandle) {");
    c.line("            b.putInt(VALUE_BLOB).putInt(8).putLong(((BlobHandle) v).handle);");
    c.line("        } else {");
    c.line("            throw new IllegalArgumentException(");
    c.line("                    \"kaya: value must be Boolean, Long, Double, String, or BlobHandle\");");
    c.line("        }");
    c.line("        while (b.position() % 8 != 0) b.put((byte) 0);");
    c.line("    }");
    c.line("");
    c.line("    // A counted value sequence — a key path or a record:");
    c.line("    // {u32 count, u32 reserved, count values}.");
    c.line("    private static void encodeValues(ByteBuffer b, Object[] vals) {");
    c.line("        int n = vals == null ? 0 : vals.length;");
    c.line("        b.putInt(n).putInt(0);");
    c.line("        for (int i = 0; i < n; i++) encodeValue(b, vals[i]);");
    c.line("    }");
    c.line("");
    c.line("    // A collection schema: {u32 count, u32 reserved, count VALUE_* tags},");
    c.line("    // padded to 8.");
    c.line("    private static void encodeVariantSchemas(ByteBuffer b, int[][] variants) {");
    c.line("        b.putInt(variants.length).putInt(0);");
    c.line("        for (int[] schema : variants) {");
    c.line("            b.putInt(schema.length);");
    c.line("            for (int t : schema) b.putInt(t);");
    c.line("        }");
    c.line("        while (b.position() % 8 != 0) b.put((byte) 0);");
    c.line("    }");

    for r in spec.tx {
        if r.name == "set_property" || r.name == "set_window_prop" {
            continue;
        }
        emit_packer(&mut c, r);
    }

    // The set_property arms, one trio per property: spec-driven so new
    // props reach every binding without emitter edits.
    for (prop, _, kind) in prop_variants(spec) {
        let pc = pascal(prop);
        let up = prop.to_uppercase();
        // Blob setters take the u64 kaya_blob_register handle (see
        // BlobHandle), so the parameter says so.
        let (p, ty, expr) = match kind {
            crate::PropKind::Str => (camel(prop), "String", format!("encodeValue(b, {});", camel(prop))),
            crate::PropKind::Bool => (camel(prop), "boolean", format!("encodeValue(b, {});", camel(prop))),
            crate::PropKind::F64 => (camel(prop), "double", format!("encodeValue(b, {});", camel(prop))),
            crate::PropKind::Blob => (
                "handle".to_string(),
                "long",
                "encodeValue(b, new BlobHandle(handle));".to_string(),
            ),
            crate::PropKind::Enum(_) => (
                camel(prop),
                "long",
                format!("encodeValue(b, {});", camel(prop)),
            ),
        };
        c.line("");
        c.line(&format!("    /** set_property with a constant {prop} value. */"));
        c.line(&format!("    public static byte[] txSet{pc}(long widgetId, {ty} {p}) {{"));
        c.line("        ByteBuffer b = begin(TX_KIND_SET_PROPERTY);");
        c.line(&format!("        b.putLong(widgetId).putInt(PROP_{up}).putInt(SOURCE_CONST);"));
        c.line(&format!("        {expr}"));
        c.line("        return finish(b);");
        c.line("    }");
        c.line("");
        c.line(&format!("    /** set_property with a signal-bound {prop} value. */"));
        c.line(&format!("    public static byte[] txBind{pc}(long widgetId, long signalId) {{"));
        c.line("        ByteBuffer b = begin(TX_KIND_SET_PROPERTY);");
        c.line(&format!("        b.putLong(widgetId).putInt(PROP_{up}).putInt(SOURCE_SIGNAL).putLong(signalId);"));
        c.line("        return finish(b);");
        c.line("    }");
        c.line("");
        c.line("    /** set_property bound to one field of the element of the enclosing For. */");
        c.line(&format!("    public static byte[] txBind{pc}Element(long widgetId, int level, int field) {{"));
        c.line("        ByteBuffer b = begin(TX_KIND_SET_PROPERTY);");
        c.line(&format!("        b.putLong(widgetId).putInt(PROP_{up}).putInt(SOURCE_ELEMENT)"));
        c.line("                .putInt(level).putInt(field);");
        c.line("        return finish(b);");
        c.line("    }");
    }

    // The window-prop duos (const + signal — element sources are
    // rejected by the wire). Window 0, the primary surface, until aux
    // windows land.
    for (prop, _, kind) in window_prop_variants(spec) {
        let pc = pascal(prop);
        let up = prop.to_uppercase();
        let (p, ty, expr) = match kind {
            crate::PropKind::Str => (camel(prop), "String", format!("encodeValue(b, {});", camel(prop))),
            crate::PropKind::F64 => (camel(prop), "double", format!("encodeValue(b, {});", camel(prop))),
            crate::PropKind::Bool => (camel(prop), "boolean", format!("encodeValue(b, {});", camel(prop))),
            other => unreachable!("no window prop carries {other:?}"),
        };
        c.line("");
        c.line(&format!("    /** set_window_prop with a constant {prop} value (window 0, the primary surface). */"));
        c.line(&format!("    public static byte[] txSetWindow{pc}(long window, {ty} {p}) {{"));
        c.line("        ByteBuffer b = begin(TX_KIND_SET_WINDOW_PROP);");
        c.line(&format!("        b.putLong(window).putInt(WPROP_{up}).putInt(SOURCE_CONST);"));
        c.line(&format!("        {expr}"));
        c.line("        return finish(b);");
        c.line("    }");
        c.line("");
        c.line(&format!("    /** set_window_prop with a signal-bound {prop} value (window 0, the primary surface). */"));
        c.line(&format!("    public static byte[] txBindWindow{pc}(long window, long signalId) {{"));
        c.line("        ByteBuffer b = begin(TX_KIND_SET_WINDOW_PROP);");
        c.line(&format!("        b.putLong(window).putInt(WPROP_{up}).putInt(SOURCE_SIGNAL).putLong(signalId);"));
        c.line("        return finish(b);");
        c.line("    }");
    }

    // The entry-prop duos (const + signal), the window shape on the
    // navigation-entry table (DESIGN.md, Navigation).
    for (prop, _, kind) in crate::entry_prop_variants(spec) {
        let pc = pascal(prop);
        let up = prop.to_uppercase();
        let (p, ty, expr) = match kind {
            crate::PropKind::Str => (camel(prop), "String", format!("encodeValue(b, {});", camel(prop))),
            crate::PropKind::Bool => (camel(prop), "boolean", format!("encodeValue(b, {});", camel(prop))),
            other => unreachable!("no entry prop carries {other:?}"),
        };
        c.line("");
        c.line(&format!("    /** set_entry_prop with a constant {prop} value. */"));
        c.line(&format!("    public static byte[] txSetEntry{pc}(long entry, {ty} {p}) {{"));
        c.line("        ByteBuffer b = begin(TX_KIND_SET_ENTRY_PROP);");
        c.line(&format!("        b.putLong(entry).putInt(EPROP_{up}).putInt(SOURCE_CONST);"));
        c.line(&format!("        {expr}"));
        c.line("        return finish(b);");
        c.line("    }");
        c.line("");
        c.line(&format!("    /** set_entry_prop with a signal-bound {prop} value. */"));
        c.line(&format!("    public static byte[] txBindEntry{pc}(long entry, long signalId) {{"));
        c.line("        ByteBuffer b = begin(TX_KIND_SET_ENTRY_PROP);");
        c.line(&format!("        b.putLong(entry).putInt(EPROP_{up}).putInt(SOURCE_SIGNAL).putLong(signalId);"));
        c.line("        return finish(b);");
        c.line("    }");
    }
    c.line("");
    c.line("    /** Concatenate packed records into one transaction. */");
    c.line("    public static byte[] tx(byte[]... records) {");
    c.line("        int len = 0;");
    c.line("        for (byte[] r : records) len += r.length;");
    c.line("        byte[] out = new byte[len];");
    c.line("        int at = 0;");
    c.line("        for (byte[] r : records) {");
    c.line("            System.arraycopy(r, 0, out, at, r.length);");
    c.line("            at += r.length;");
    c.line("        }");
    c.line("        return out;");
    c.line("    }");
    c.line("");
    c.line("    /** A parsed occurrence: the kind, the id, the copy's key path");
    c.line("     * (empty when id is a widget id; otherwise id is a template");
    c.line("     * node id), and the payload — the entry's new text (String)");
    c.line("     * for TEXT_CHANGED, the checkbox's new state (Boolean) for");
    c.line("     * TOGGLED, the slider's new value (Double) for VALUE_CHANGED,");
    c.line("     * null for clicks. */");
    c.line("    public static final class Occ {");
    c.line("        public final short kind;");
    c.line("        public final long id;");
    c.line("        public final List<Object> keys;");
    c.line("        public final Object payload;");
    c.line("");
    c.line("        Occ(short kind, long id, List<Object> keys, Object payload) {");
    c.line("            this.kind = kind;");
    c.line("            this.id = id;");
    c.line("            this.keys = keys;");
    c.line("            this.payload = payload;");
    c.line("        }");
    c.line("    }");
    c.line("");
    c.line("    /** Decode one occurrence record (header included); null for pad");
    c.line("     * or unknown kinds. */");
    c.line("    public static Occ parseOccurrence(byte[] rec) {");
    c.line("        ByteBuffer b = ByteBuffer.wrap(rec).order(ByteOrder.LITTLE_ENDIAN);");
    c.line("        short kind = b.getShort(4);");
    let accepted = crate::occurrence_names(spec)
        .iter()
        .map(|n| format!("kind != OCC_KIND_{}", n.to_uppercase()))
        .collect::<Vec<_>>()
        .join(" && ");
    c.line(&format!("        if ({accepted}) {{"));
    c.line("            return null;");
    c.line("        }");
    c.line("        long id = b.getLong(8);");
    c.line("        if (kind == OCC_KIND_ALERT_RESULT) {");
    c.line("            // The alert's one answer: id + u32 choice (ALERT_CHOICE_*,");
    c.line("            // the cancel sentinel being -1 in java-int terms).");
    c.line("            return new Occ(kind, id, java.util.List.of(), b.getInt(16));");
    c.line("        }");
    let id_only = crate::id_only_occurrence_names(spec)
        .iter()
        .map(|n| format!("kind == OCC_KIND_{}", n.to_uppercase()))
        .collect::<Vec<_>>()
        .join(" || ");
    c.line("        // Surface lifecycle records carry the surface id alone");
    c.line("        // (derived from the record shapes).");
    c.line(&format!("        if ({id_only}) {{"));
    c.line("            return new Occ(kind, id, java.util.List.of(), null);");
    c.line("        }");
    c.line("        int pathLen = b.getInt(16);");
    c.line("        List<Object> keys = new ArrayList<>();");
    c.line("        int at = 24;");
    c.line("        for (int i = 0; i < pathLen; i++) {");
    c.line("            int vtype = b.getInt(at);");
    c.line("            int vlen = b.getInt(at + 4);");
    c.line("            switch (vtype) {");
    c.line("                case VALUE_BOOL: keys.add(rec[at + 8] != 0); break;");
    c.line("                case VALUE_I64: keys.add(b.getLong(at + 8)); break;");
    c.line("                case VALUE_F64: keys.add(b.getDouble(at + 8)); break;");
    c.line("                default:");
    c.line("                    keys.add(new String(rec, at + 8, vlen, StandardCharsets.UTF_8));");
    c.line("            }");
    c.line("            at += 8 + ((vlen + 7) & ~7);");
    c.line("        }");
    c.line("        Object payload = null;");
    let with_payload = crate::payload_occurrence_names(spec)
        .iter()
        .map(|n| format!("kind == OCC_KIND_{}", n.to_uppercase()))
        .collect::<Vec<_>>()
        .join(" || ");
    c.line(&format!("        if ({with_payload}) {{"));
    // Type-generic payload decode, same shape as the key loop: no
    // per-kind logic left to drift.
    c.line("            int ptype = b.getInt(at);");
    c.line("            int plen = b.getInt(at + 4);");
    c.line("            switch (ptype) {");
    c.line("                case VALUE_BOOL: payload = rec[at + 8] != 0; break;");
    c.line("                case VALUE_I64: payload = b.getLong(at + 8); break;");
    c.line("                case VALUE_F64: payload = b.getDouble(at + 8); break;");
    c.line("                default:");
    c.line("                    payload = new String(rec, at + 8, plen, StandardCharsets.UTF_8);");
    c.line("            }");
    c.line("        }");
    c.line("        return new Occ(kind, id, keys, payload);");
    c.line("    }");
    c.line("");
    c.line("    private KayaWire() {}");
    c.line("}");
    c.out
}

fn emit_packer(c: &mut Ctx, r: &Record) {
    let params = record_params(r);
    let mut sig: Vec<String> = Vec::new();
    for f in &params {
        sig.push(match f.ty {
            FieldTy::U32 => format!("int {}", camel(f.name)),
            FieldTy::U64 => format!("long {}", camel(f.name)),
            FieldTy::Value => format!("Object {}", camel(f.name)),
            FieldTy::Values => format!("Object[] {}", camel(f.name)),
            FieldTy::VariantSchemas => format!("int[][] {}", camel(f.name)),
        });
    }
    c.line("");
    c.line(&format!("    /** {} */", r.doc.replace('\n', " ")));
    c.line(&format!(
        "    public static byte[] tx{}({}) {{",
        pascal(r.name),
        sig.join(", ")
    ));
    c.line(&format!(
        "        ByteBuffer b = begin(TX_KIND_{});",
        r.name.to_uppercase()
    ));
    for f in r.fields {
        c.line(&match f.ty {
            FieldTy::U32 if f.name == "reserved" => "        b.putInt(0);".into(),
            FieldTy::U32 => format!("        b.putInt({});", camel(f.name)),
            FieldTy::U64 => format!("        b.putLong({});", camel(f.name)),
            FieldTy::Value => format!("        encodeValue(b, {});", camel(f.name)),
            FieldTy::Values => format!("        encodeValues(b, {});", camel(f.name)),
            FieldTy::VariantSchemas => format!("        encodeVariantSchemas(b, {});", camel(f.name)),
        });
    }
    c.line("        return finish(b);");
    c.line("    }");
}
