//! Java emitter: dev.kaya.KayaWire — constants, byte[] packers via
//! ByteBuffer, and the byte[] occurrence parser. The class namespaces
//! everything; encoder helpers are private. The direct-tier ring loop
//! (Unsafe on raw addresses) stays with its consumer — parsing from an
//! address is the runtime's business, but a copied record parses here.

use kaya::spec::{FieldTy, ProtocolSpec, Record};

use crate::{Ctx, prop_variants, record_params, window_prop_variants};

pub const RESERVED: &[&str] = &[
    "abstract", "assert", "boolean", "break", "byte", "case", "catch", "char", "class", "const",
    "continue", "default", "do", "double", "else", "enum", "extends", "final", "finally",
    "float", "for", "goto", "if", "implements", "import", "instanceof", "int", "interface",
    "long", "native", "new", "package", "private", "protected", "public", "return", "short",
    "static", "strictfp", "super", "switch", "synchronized", "this", "throw", "throws",
    "transient", "try", "void", "volatile", "while",
];

fn pascal(name: &str) -> String {
    name.split('_')
        .map(|w| {
            let mut chars = w.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

fn camel(name: &str) -> String {
    let p = pascal(name);
    let mut chars = p.chars();
    match chars.next() {
        Some(first) => first.to_lowercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    }
}

pub fn emit(spec: &ProtocolSpec) -> String {
    let mut c = Ctx { out: String::new() };
    c.line("// kaya wire vocabulary. Generated by kaya-bindgen from kaya::spec — do not edit.");
    c.line("//");
    c.line("// Records are {u32 size, u16 kind, u16 flags}, body, padded to 8,");
    c.line("// little-endian. Values accept Boolean, Long, Double, String, and");
    c.line("// BlobHandle, mapped to the kaya value types; keys in paths likewise.");
    c.line("package dev.kaya;");
    c.line("");
    c.line("import java.nio.ByteBuffer;");
    c.line("import java.nio.ByteOrder;");
    c.line("import java.nio.charset.StandardCharsets;");
    c.line("import java.util.ArrayList;");
    c.line("import java.util.List;");
    c.line("");
    c.line("public final class KayaWire {");
    c.line(&format!("    /** SPEC_HASH: {}. */", "the protocol fingerprint; the runtime asserts the loaded core agrees"));
    c.line(&format!("    public static final long SPEC_HASH = 0x{:016x}L;", crate::spec_hash()));
    c.line("");
    for e in spec.enums {
        for (name, value) in e.variants {
            // Java has no unsigned int: a wire u32 above i32::MAX is
            // spelled as its two's-complement value, which is exactly
            // what reading the wire's u32 into a java int yields — so
            // == against the constant stays correct (the alert_choice
            // cancel sentinel is the first such value).
            c.line(&format!(
                "    public static final int {}_{} = {};",
                e.name.to_uppercase(),
                name.to_uppercase(),
                *value as i32
            ));
        }
    }
    for (channel, records) in [("TX", spec.tx), ("APPLY", spec.apply), ("OCC", spec.occurrence)] {
        for r in records {
            c.line(&format!(
                "    public static final short {channel}_KIND_{} = {};",
                r.name.to_uppercase(),
                r.kind
            ));
        }
    }
    c.line("");
    c.line("    /** A blob value: the u64 handle from kaya_blob_register, consumed");
    c.line("     * by the next submit; the bytes never ride the record stream. */");
    c.line("    public static final class BlobHandle {");
    c.line("        public final long handle;");
    c.line("");
    c.line("        public BlobHandle(long handle) {");
    c.line("            this.handle = handle;");
    c.line("        }");
    c.line("    }");
    c.line("");
    c.line("    private static ByteBuffer begin(short kind) {");
    c.line("        ByteBuffer b = ByteBuffer.allocate(4096).order(ByteOrder.LITTLE_ENDIAN);");
    c.line("        b.putInt(0).putShort(kind).putShort((short) 0);");
    c.line("        return b;");
    c.line("    }");
    c.line("");
    c.line("    private static byte[] finish(ByteBuffer b) {");
    c.line("        while (b.position() % 8 != 0) b.put((byte) 0);");
    c.line("        b.putInt(0, b.position());");
    c.line("        byte[] out = new byte[b.position()];");
    c.line("        b.flip();");
    c.line("        b.get(out);");
    c.line("        return out;");
    c.line("    }");
    c.line("");
    c.line("    // Values self-pad to 8: they concatenate inside record bodies.");
    c.line("    private static void encodeValue(ByteBuffer b, Object v) {");
    c.line("        if (v instanceof Boolean) {");
    c.line("            b.putInt(VALUE_BOOL).putInt(1).put((byte) (((Boolean) v) ? 1 : 0));");
    c.line("        } else if (v instanceof Integer) {");
    c.line("            b.putInt(VALUE_I64).putInt(8).putLong((Integer) v);");
    c.line("        } else if (v instanceof Long) {");
    c.line("            b.putInt(VALUE_I64).putInt(8).putLong((Long) v);");
    c.line("        } else if (v instanceof Double) {");
    c.line("            b.putInt(VALUE_F64).putInt(8).putDouble((Double) v);");
    c.line("        } else if (v instanceof String) {");
    c.line("            byte[] utf8 = ((String) v).getBytes(StandardCharsets.UTF_8);");
    c.line("            b.putInt(VALUE_STR).putInt(utf8.length).put(utf8);");
    c.line("        } else if (v instanceof BlobHandle) {");
    c.line("            b.putInt(VALUE_BLOB).putInt(8).putLong(((BlobHandle) v).handle);");
    c.line("        } else {");
    c.line("            throw new IllegalArgumentException(");
    c.line("                    \"kaya: value must be Boolean, Long, Double, String, or BlobHandle\");");
    c.line("        }");
    c.line("        while (b.position() % 8 != 0) b.put((byte) 0);");
    c.line("    }");
    c.line("");
    c.line("    // A counted value sequence — a key path or a record:");
    c.line("    // {u32 count, u32 reserved, count values}.");
    c.line("    private static void encodeValues(ByteBuffer b, Object[] vals) {");
    c.line("        int n = vals == null ? 0 : vals.length;");
    c.line("        b.putInt(n).putInt(0);");
    c.line("        for (int i = 0; i < n; i++) encodeValue(b, vals[i]);");
    c.line("    }");
    c.line("");
    c.line("    // A collection schema: {u32 count, u32 reserved, count VALUE_* tags},");
    c.line("    // padded to 8.");
    c.line("    private static void encodeVariantSchemas(ByteBuffer b, int[][] variants) {");
    c.line("        b.putInt(variants.length).putInt(0);");
    c.line("        for (int[] schema : variants) {");
    c.line("            b.putInt(schema.length);");
    c.line("            for (int t : schema) b.putInt(t);");
    c.line("        }");
    c.line("        while (b.position() % 8 != 0) b.put((byte) 0);");
    c.line("    }");

    for r in spec.tx {
        if r.name == "set_property" || r.name == "set_window_prop" {
            continue;
        }
        emit_packer(&mut c, r);
    }

    // The set_property arms, one trio per property, spec-driven.
    for (prop, _, kind) in prop_variants(spec) {
        let pc = pascal(prop);
        let up = prop.to_uppercase();
        // Blob setters take the u64 kaya_blob_register handle (BlobHandle).
        let (p, ty, expr) = match kind {
            crate::PropKind::Str => (camel(prop), "String", format!("encodeValue(b, {});", camel(prop))),
            crate::PropKind::Bool => (camel(prop), "boolean", format!("encodeValue(b, {});", camel(prop))),
            crate::PropKind::F64 => (camel(prop), "double", format!("encodeValue(b, {});", camel(prop))),
            crate::PropKind::Blob => (
                "handle".to_string(),
                "long",
                "encodeValue(b, new BlobHandle(handle));".to_string(),
            ),
            crate::PropKind::Enum(_) => (
                camel(prop),
                "long",
                format!("encodeValue(b, {});", camel(prop)),
            ),
        };
        c.line("");
        c.line(&format!("    /** set_property with a constant {prop} value. */"));
        c.line(&format!("    public static byte[] txSet{pc}(long widgetId, {ty} {p}) {{"));
        c.line("        ByteBuffer b = begin(TX_KIND_SET_PROPERTY);");
        c.line(&format!("        b.putLong(widgetId).putInt(PROP_{up}).putInt(SOURCE_CONST);"));
        c.line(&format!("        {expr}"));
        c.line("        return finish(b);");
        c.line("    }");
        c.line("");
        c.line(&format!("    /** set_property with a signal-bound {prop} value. */"));
        c.line(&format!("    public static byte[] txBind{pc}(long widgetId, long signalId) {{"));
        c.line("        ByteBuffer b = begin(TX_KIND_SET_PROPERTY);");
        c.line(&format!("        b.putLong(widgetId).putInt(PROP_{up}).putInt(SOURCE_SIGNAL).putLong(signalId);"));
        c.line("        return finish(b);");
        c.line("    }");
        c.line("");
        c.line("    /** set_property bound to one field of the element of the enclosing For. */");
        c.line(&format!("    public static byte[] txBind{pc}Element(long widgetId, int level, int field) {{"));
        c.line("        ByteBuffer b = begin(TX_KIND_SET_PROPERTY);");
        c.line(&format!("        b.putLong(widgetId).putInt(PROP_{up}).putInt(SOURCE_ELEMENT)"));
        c.line("                .putInt(level).putInt(field);");
        c.line("        return finish(b);");
        c.line("    }");
    }

    // The window-prop duos: const + signal, element sources being
    // rejected by the wire.
    for (prop, _, kind) in window_prop_variants(spec) {
        let pc = pascal(prop);
        let up = prop.to_uppercase();
        let (p, ty, expr) = match kind {
            crate::PropKind::Str => (camel(prop), "String", format!("encodeValue(b, {});", camel(prop))),
            crate::PropKind::F64 => (camel(prop), "double", format!("encodeValue(b, {});", camel(prop))),
            crate::PropKind::Bool => (camel(prop), "boolean", format!("encodeValue(b, {});", camel(prop))),
            crate::PropKind::Enum(_) => (
                camel(prop),
                "long",
                format!("encodeValue(b, {});", camel(prop)),
            ),
            other => unreachable!("no window prop carries {other:?}"),
        };
        c.line("");
        c.line(&format!("    /** set_window_prop with a constant {prop} value (window 0, the primary surface). */"));
        c.line(&format!("    public static byte[] txSetWindow{pc}(long window, {ty} {p}) {{"));
        c.line("        ByteBuffer b = begin(TX_KIND_SET_WINDOW_PROP);");
        c.line(&format!("        b.putLong(window).putInt(WPROP_{up}).putInt(SOURCE_CONST);"));
        c.line(&format!("        {expr}"));
        c.line("        return finish(b);");
        c.line("    }");
        c.line("");
        c.line(&format!("    /** set_window_prop with a signal-bound {prop} value (window 0, the primary surface). */"));
        c.line(&format!("    public static byte[] txBindWindow{pc}(long window, long signalId) {{"));
        c.line("        ByteBuffer b = begin(TX_KIND_SET_WINDOW_PROP);");
        c.line(&format!("        b.putLong(window).putInt(WPROP_{up}).putInt(SOURCE_SIGNAL).putLong(signalId);"));
        c.line("        return finish(b);");
        c.line("    }");
    }

    // The entry-prop duos (const + signal), the window shape on the
    // navigation-entry table (DESIGN.md, Navigation).
    for (prop, _, kind) in crate::entry_prop_variants(spec) {
        let pc = pascal(prop);
        let up = prop.to_uppercase();
        let (p, ty, expr) = match kind {
            crate::PropKind::Str => (camel(prop), "String", format!("encodeValue(b, {});", camel(prop))),
            crate::PropKind::Bool => (camel(prop), "boolean", format!("encodeValue(b, {});", camel(prop))),
            other => unreachable!("no entry prop carries {other:?}"),
        };
        c.line("");
        c.line(&format!("    /** set_entry_prop with a constant {prop} value. */"));
        c.line(&format!("    public static byte[] txSetEntry{pc}(long entry, {ty} {p}) {{"));
        c.line("        ByteBuffer b = begin(TX_KIND_SET_ENTRY_PROP);");
        c.line(&format!("        b.putLong(entry).putInt(EPROP_{up}).putInt(SOURCE_CONST);"));
        c.line(&format!("        {expr}"));
        c.line("        return finish(b);");
        c.line("    }");
        c.line("");
        c.line(&format!("    /** set_entry_prop with a signal-bound {prop} value. */"));
        c.line(&format!("    public static byte[] txBindEntry{pc}(long entry, long signalId) {{"));
        c.line("        ByteBuffer b = begin(TX_KIND_SET_ENTRY_PROP);");
        c.line(&format!("        b.putLong(entry).putInt(EPROP_{up}).putInt(SOURCE_SIGNAL).putLong(signalId);"));
        c.line("        return finish(b);");
        c.line("    }");
    }

    // The section-prop duos (const + signal), the entry shape on the
    // section table; icon rides the blob channel (DESIGN.md, Sections).
    for (prop, _, kind) in crate::section_prop_variants(spec) {
        let pc = pascal(prop);
        let up = prop.to_uppercase();
        let (p, ty, expr) = match kind {
            crate::PropKind::Str => (camel(prop), "String", format!("encodeValue(b, {});", camel(prop))),
            crate::PropKind::Blob => (
                "handle".to_string(),
                "long",
                "encodeValue(b, new BlobHandle(handle));".to_string(),
            ),
            crate::PropKind::Enum(_) => (
                camel(prop),
                "long",
                format!("encodeValue(b, {});", camel(prop)),
            ),
            other => unreachable!("no section prop carries {other:?}"),
        };
        c.line("");
        c.line(&format!("    /** set_section_prop with a constant {prop} value. */"));
        c.line(&format!("    public static byte[] txSetSection{pc}(long section, {ty} {p}) {{"));
        c.line("        ByteBuffer b = begin(TX_KIND_SET_SECTION_PROP);");
        c.line(&format!("        b.putLong(section).putInt(SPROP_{up}).putInt(SOURCE_CONST);"));
        c.line(&format!("        {expr}"));
        c.line("        return finish(b);");
        c.line("    }");
        c.line("");
        c.line(&format!("    /** set_section_prop with a signal-bound {prop} value. */"));
        c.line(&format!("    public static byte[] txBindSection{pc}(long section, long signalId) {{"));
        c.line("        ByteBuffer b = begin(TX_KIND_SET_SECTION_PROP);");
        c.line(&format!("        b.putLong(section).putInt(SPROP_{up}).putInt(SOURCE_SIGNAL).putLong(signalId);"));
        c.line("        return finish(b);");
        c.line("    }");
    }

    // The one binding-tier shortcut parser (DESIGN.md, Menus): SPELLING
    // only, policy being the core's and validated on the canonical form.
    // txSetMenuShortcut routes through it, so no call site can bypass
    // canonicalization. Locale.ROOT, deliberately: a default-locale
    // toLowerCase turns "I" into a dotless ı under tr-TR.
    let named_keys = crate::SHORTCUT_NAMED_KEYS
        .iter()
        .map(|k| format!("\"{k}\""))
        .collect::<Vec<_>>()
        .join(", ");
    c.line("");
    c.line("    private static final java.util.Set<String> SHORTCUT_NAMED_KEYS =");
    c.line(&format!("            java.util.Set.of({named_keys});"));
    c.line("");
    c.line("    /** Canonicalize a shortcut spelling to the wire form: lowercase");
    c.line("     * '+'-joined tokens, modifiers ordered primary, shift, alt, then one");
    c.line("     * key (a-z, 0-9, or the closed named set). Accepts ASCII case");
    c.line("     * variants and any modifier order; throws on whitespace, empty");
    c.line("     * tokens, repeated modifiers, aliases (ctrl/cmd/option), and unknown");
    c.line("     * or multiple or missing keys. POLICY stays at the core: escape,");
    c.line("     * shift-only and bare alphanumerics, and the reserved floor are");
    c.line("     * validated there, on the canonical spelling, never rewritten. */");
    c.line("    public static String canonicalizeShortcut(String spelling) {");
    c.line("        if (spelling.isEmpty()) {");
    c.line("            throw new IllegalArgumentException(\"kaya: shortcut is empty\");");
    c.line("        }");
    c.line("        for (int i = 0; i < spelling.length(); i++) {");
    c.line("            char ch = spelling.charAt(i);");
    c.line("            if (ch == ' ' || ch == '\\t' || ch == '\\n' || ch == 0x0b || ch == '\\f' || ch == '\\r') {");
    c.line("                throw new IllegalArgumentException(");
    c.line("                        \"kaya: shortcut \\\"\" + spelling + \"\\\" contains whitespace\");");
    c.line("            }");
    c.line("        }");
    c.line("        // split takes a regex, and -1 keeps trailing empty tokens so");
    c.line("        // \"primary+\" fails as an empty token, never as a silent drop.");
    c.line("        String[] parts = spelling.toLowerCase(java.util.Locale.ROOT).split(\"\\\\+\", -1);");
    c.line("        for (String p : parts) {");
    c.line("            if (p.isEmpty()) {");
    c.line("                throw new IllegalArgumentException(");
    c.line("                        \"kaya: shortcut \\\"\" + spelling + \"\\\" has an empty token\");");
    c.line("            }");
    c.line("        }");
    c.line("        String key = parts[parts.length - 1];");
    c.line("        boolean primary = false, shift = false, alt = false;");
    c.line("        for (int i = 0; i + 1 < parts.length; i++) {");
    c.line("            String m = parts[i];");
    c.line("            boolean repeated;");
    c.line("            if (m.equals(\"primary\")) { repeated = primary; primary = true; }");
    c.line("            else if (m.equals(\"shift\")) { repeated = shift; shift = true; }");
    c.line("            else if (m.equals(\"alt\")) { repeated = alt; alt = true; }");
    c.line("            else {");
    c.line("                throw new IllegalArgumentException(");
    c.line("                        \"kaya: shortcut \\\"\" + spelling + \"\\\" has an unknown modifier \\\"\" + m");
    c.line("                        + \"\\\" (the portable modifiers are primary, shift, alt; aliases like ctrl, cmd, and option are not accepted)\");");
    c.line("            }");
    c.line("            if (repeated) {");
    c.line("                throw new IllegalArgumentException(");
    c.line("                        \"kaya: shortcut \\\"\" + spelling + \"\\\" repeats modifier \\\"\" + m + \"\\\"\");");
    c.line("            }");
    c.line("        }");
    c.line("        boolean alnum = key.length() == 1");
    c.line("                && ((key.charAt(0) >= 'a' && key.charAt(0) <= 'z')");
    c.line("                        || (key.charAt(0) >= '0' && key.charAt(0) <= '9'));");
    c.line("        if (!alnum && !SHORTCUT_NAMED_KEYS.contains(key)) {");
    c.line("            throw new IllegalArgumentException(");
    c.line("                    \"kaya: shortcut \\\"\" + spelling + \"\\\" key \\\"\" + key");
    c.line("                    + \"\\\" is outside the floor (one of a-z, 0-9, or the closed named set)\");");
    c.line("        }");
    c.line("        return (primary ? \"primary+\" : \"\") + (shift ? \"shift+\" : \"\") + (alt ? \"alt+\" : \"\") + key;");
    c.line("    }");

    // The menu-prop setters: a const setter for every prop, signal
    // binders only for the bindable ones (SOURCE_SIGNAL on the rest
    // dies at the root).
    for (prop, _, kind) in crate::menu_prop_variants(spec) {
        let pc = pascal(prop);
        let up = prop.to_uppercase();
        let (p, ty, expr) = match kind {
            crate::PropKind::Str if *prop == "shortcut" => (
                camel(prop),
                "String",
                format!("encodeValue(b, canonicalizeShortcut({}));", camel(prop)),
            ),
            crate::PropKind::Str => (camel(prop), "String", format!("encodeValue(b, {});", camel(prop))),
            crate::PropKind::Bool => (camel(prop), "boolean", format!("encodeValue(b, {});", camel(prop))),
            crate::PropKind::F64 => (camel(prop), "double", format!("encodeValue(b, {});", camel(prop))),
            crate::PropKind::Blob => (
                "handle".to_string(),
                "long",
                "encodeValue(b, new BlobHandle(handle));".to_string(),
            ),
            crate::PropKind::Enum(_) => (
                camel(prop),
                "long",
                format!("encodeValue(b, {});", camel(prop)),
            ),
        };
        c.line("");
        if *prop == "shortcut" {
            c.line("    /** set_menu_prop with a constant shortcut value, canonicalized here");
            c.line("     * (the one binding-tier shortcut parser — no call site bypasses it). */");
        } else {
            c.line(&format!("    /** set_menu_prop with a constant {prop} value. */"));
        }
        c.line(&format!("    public static byte[] txSetMenu{pc}(long item, {ty} {p}) {{"));
        c.line("        ByteBuffer b = begin(TX_KIND_SET_MENU_PROP);");
        c.line(&format!("        b.putLong(item).putInt(MPROP_{up}).putInt(SOURCE_CONST);"));
        c.line(&format!("        {expr}"));
        c.line("        return finish(b);");
        c.line("    }");
        if crate::menu_prop_bindable(prop) {
            c.line("");
            c.line(&format!("    /** set_menu_prop with a signal-bound {prop} value. */"));
            c.line(&format!("    public static byte[] txBindMenu{pc}(long item, long signalId) {{"));
            c.line("        ByteBuffer b = begin(TX_KIND_SET_MENU_PROP);");
            c.line(&format!("        b.putLong(item).putInt(MPROP_{up}).putInt(SOURCE_SIGNAL).putLong(signalId);"));
            c.line("        return finish(b);");
            c.line("    }");
        }
    }
    c.line("");
    c.line("    /** Concatenate packed records into one transaction. */");
    c.line("    public static byte[] tx(byte[]... records) {");
    c.line("        int len = 0;");
    c.line("        for (byte[] r : records) len += r.length;");
    c.line("        byte[] out = new byte[len];");
    c.line("        int at = 0;");
    c.line("        for (byte[] r : records) {");
    c.line("            System.arraycopy(r, 0, out, at, r.length);");
    c.line("            at += r.length;");
    c.line("        }");
    c.line("        return out;");
    c.line("    }");
    c.line("");
    c.line("    /** A parsed occurrence: the kind, the id, the copy's key path");
    c.line("     * (empty when id is a widget id; otherwise id is a template");
    c.line("     * node id), and the payload — the entry's new text (String)");
    c.line("     * for TEXT_CHANGED, the checkbox's new state (Boolean) for");
    c.line("     * TOGGLED, the slider's new value (Double) for VALUE_CHANGED,");
    c.line("     * null for clicks. */");
    c.line("    public static final class Occ {");
    c.line("        public final short kind;");
    c.line("        public final long id;");
    c.line("        public final List<Object> keys;");
    c.line("        public final Object payload;");
    c.line("");
    c.line("        Occ(short kind, long id, List<Object> keys, Object payload) {");
    c.line("            this.kind = kind;");
    c.line("            this.id = id;");
    c.line("            this.keys = keys;");
    c.line("            this.payload = payload;");
    c.line("        }");
    c.line("    }");
    c.line("");
    // The occurrence blob table. A blob in an OCCURRENCE is a table
    // handle, not the apply channel's batch-local index, and nothing
    // retires one here — so the decoder redeems and releases it, which
    // is what keeps a handle from ever reaching an app.
    c.line("    /** One representation as the decoder hands it over: the clip");
    c.line("     * kind, and its values with blobs already redeemed to byte[].");
    c.line("     * The sum itself is the hand-written tier\'s — this is the");
    c.line("     * taste-free shape the wire carries.");
    c.line("     *");
    c.line("     * <p>kind is a SINGLE member of the clip enum and never a mask");
    c.line("     * (you offer many and you receive one); 0 with no values is the");
    c.line("     * universal empty answer. */");
    c.line("    public static final class ClipValues {");
    c.line("        public final int kind;");
    c.line("        public final List<Object> values;");
    c.line("");
    c.line("        ClipValues(int kind, List<Object> values) {");
    c.line("            this.kind = kind;");
    c.line("            this.values = values;");
    c.line("        }");
    c.line("    }");
    c.line("");
    c.line("    /** Decode a representation at {@code at}: the clip kind, then");
    c.line("     * its Values block. Blobs are redeemed and RELEASED here.");
    c.line("     * {@code next[0]} receives the offset past the block. */");
    c.line("    public static ClipValues parseClip(byte[] rec, ByteBuffer b, int at, int[] next) {");
    c.line("        int kind = b.getInt(at);");
    c.line("        int count = b.getInt(at + 8);");
    c.line("        at += 16;");
    c.line("        List<Object> values = new ArrayList<>(count);");
    c.line("        for (int i = 0; i < count; i++) {");
    c.line("            int vtype = b.getInt(at);");
    c.line("            int vlen = b.getInt(at + 4);");
    c.line("            switch (vtype) {");
    c.line("                case VALUE_I64: values.add(b.getLong(at + 8)); break;");
    c.line("                case VALUE_BLOB: values.add(KayaRing.occurrenceBlob(b.getLong(at + 8))); break;");
    c.line("                default:");
    c.line("                    values.add(new String(rec, at + 8, vlen, StandardCharsets.UTF_8));");
    c.line("            }");
    c.line("            at += 8 + ((vlen + 7) & ~7);");
    c.line("        }");
    c.line("        next[0] = at;");
    c.line("        return new ClipValues(kind, values);");
    c.line("    }");
    c.line("");
    // One Value, type-generic, with the offset handed back — the same
    // decode the key loop and the payload switch do inline. Extracted
    // because the undo answer reads an unbounded LIST of them and a
    // fourth copy of the switch is a fourth place for the blob arm to
    // go missing.
    c.line("    /** One Value at {@code next[0]}, which advances past it.");
    c.line("     * Blobs are redeemed and RELEASED here: a handle must never");
    c.line("     * reach an app. */");
    c.line("    public static Object parseValue(byte[] rec, ByteBuffer b, int[] next) {");
    c.line("        int at = next[0];");
    c.line("        int vtype = b.getInt(at);");
    c.line("        int vlen = b.getInt(at + 4);");
    c.line("        next[0] = at + 8 + ((vlen + 7) & ~7);");
    c.line("        switch (vtype) {");
    c.line("            case VALUE_BOOL: return rec[at + 8] != 0;");
    c.line("            case VALUE_I64: return b.getLong(at + 8);");
    c.line("            case VALUE_F64: return b.getDouble(at + 8);");
    c.line("            case VALUE_BLOB: return KayaRing.occurrenceBlob(b.getLong(at + 8));");
    c.line("            default:");
    c.line("                return new String(rec, at + 8, vlen, StandardCharsets.UTF_8);");
    c.line("        }");
    c.line("    }");
    c.line("");
    // The undo answer's taste-free shape, on ClipValues' stance: the
    // decoder cuts the flat tail into its four runs, and the sum-typed
    // surface over it is the hand-written tier's.
    if !crate::undo_occurrence_names(spec).is_empty() {
        c.line("    /** One text field's restored text, named the way the edit");
        c.line("     * that filled it was named: an EMPTY path means {@code id}");
        c.line("     * is a live widget id, and a non-empty one means it is the");
        c.line("     * template node of a stamped copy at that key path. */");
        c.line("    public static final class UndoTextValues {");
        c.line("        public final long id;");
        c.line("        public final List<Object> path;");
        c.line("        public final String text;");
        c.line("");
        c.line("        UndoTextValues(long id, List<Object> path, String text) {");
        c.line("            this.id = id;");
        c.line("            this.path = path;");
        c.line("            this.text = text;");
        c.line("        }");
        c.line("    }");
        c.line("");
        c.line("    /** One collection entry's restored state, as the decoder");
        c.line("     * hands it over. {@code present} false is \"the restored");
        c.line("     * state does not have this entry at all\", and then");
        c.line("     * {@code variant} and {@code fields} are empty. */");
        c.line("    public static final class UndoEntryValues {");
        c.line("        public final long collection;");
        c.line("        public final List<Object> path;");
        c.line("        public final Object key;");
        c.line("        public final boolean present;");
        c.line("        public final int variant;");
        c.line("        public final List<Object> fields;");
        c.line("");
        c.line("        UndoEntryValues(long collection, List<Object> path, Object key,");
        c.line("                boolean present, int variant, List<Object> fields) {");
        c.line("            this.collection = collection;");
        c.line("            this.path = path;");
        c.line("            this.key = key;");
        c.line("            this.present = present;");
        c.line("            this.variant = variant;");
        c.line("            this.fields = fields;");
        c.line("        }");
        c.line("    }");
        c.line("");
        c.line("    /** One collection instance's restored key order — position");
        c.line("     * is the one thing per-entry statements cannot carry. */");
        c.line("    public static final class UndoOrderValues {");
        c.line("        public final long collection;");
        c.line("        public final List<Object> path;");
        c.line("        public final List<Object> keys;");
        c.line("");
        c.line("        UndoOrderValues(long collection, List<Object> path, List<Object> keys) {");
        c.line("            this.collection = collection;");
        c.line("            this.path = path;");
        c.line("            this.keys = keys;");
        c.line("        }");
        c.line("    }");
        c.line("");
        c.line("    /** One undone/redone step as the decoder hands it over: the");
        c.line("     * group's label (EMPTY for a typing episode) and the four");
        c.line("     * counted runs cut out of the flat Values tail. A STATEMENT");
        c.line("     * OF THE RESTORED STATE, never a replay of ops — signals");
        c.line("     * arrive as flattened (id, value) pairs, and the other three");
        c.line("     * runs as arity-first groups. */");
        c.line("    public static final class UndoValues {");
        c.line("        public final String label;");
        c.line("        public final List<Object> signals;");
        c.line("        public final List<UndoTextValues> texts;");
        c.line("        public final List<UndoEntryValues> entries;");
        c.line("        public final List<UndoOrderValues> orders;");
        c.line("");
        c.line("        UndoValues(String label, List<Object> signals, List<UndoTextValues> texts,");
        c.line("                List<UndoEntryValues> entries, List<UndoOrderValues> orders) {");
        c.line("            this.label = label;");
        c.line("            this.signals = signals;");
        c.line("            this.texts = texts;");
        c.line("            this.entries = entries;");
        c.line("            this.orders = orders;");
        c.line("        }");
        c.line("    }");
        c.line("");
    }
    c.line("    /** Decode one occurrence record (header included); null for pad");
    c.line("     * or unknown kinds. */");
    c.line("    public static Occ parseOccurrence(byte[] rec) {");
    c.line("        ByteBuffer b = ByteBuffer.wrap(rec).order(ByteOrder.LITTLE_ENDIAN);");
    c.line("        short kind = b.getShort(4);");
    let accepted = crate::occurrence_names(spec)
        .iter()
        .map(|n| format!("kind != OCC_KIND_{}", n.to_uppercase()))
        .collect::<Vec<_>>()
        .join(" && ");
    c.line(&format!("        if ({accepted}) {{"));
    c.line("            return null;");
    c.line("        }");
    c.line("        long id = b.getLong(8);");
    c.line("        if (kind == OCC_KIND_ALERT_RESULT) {");
    c.line("            // The alert's one answer: id + u32 choice (ALERT_CHOICE_*,");
    c.line("            // the cancel sentinel being -1 in java-int terms).");
    c.line("            return new Occ(kind, id, java.util.List.of(), b.getInt(16));");
    c.line("        }");
    // The picker's answer: the one occurrence whose payload is a LIST
    // OF RECORDS. The generic tail reads a KEY PATH, which would take
    // the file count as a path length and start eight bytes early.
    c.line("        if (kind == OCC_KIND_FILE_DIALOG_RESULT) {");
    c.line("            // id, a count, then three Values per file");
    c.line("            // (handle, name, local_path). EMPTY IS CANCEL.");
    c.line("            int count = b.getInt(16);");
    c.line("            int at = 32; // past id, count, pad, values count, reserved");
    c.line("            java.util.List<KayaApp.PickedFile> files = new java.util.ArrayList<>(count);");
    c.line("            for (int i = 0; i < count; i++) {");
    c.line("                Object[] parts = new Object[3];");
    c.line("                for (int j = 0; j < 3; j++) {");
    c.line("                    int vtype = b.getInt(at);");
    c.line("                    int vlen = b.getInt(at + 4);");
    c.line("                    if (vtype == VALUE_I64) {");
    c.line("                        parts[j] = b.getLong(at + 8);");
    c.line("                    } else {");
    c.line("                        byte[] raw = new byte[vlen];");
    c.line("                        b.position(at + 8);");
    c.line("                        b.get(raw);");
    c.line("                        parts[j] = new String(raw, java.nio.charset.StandardCharsets.UTF_8);");
    c.line("                    }");
    c.line("                    at += 8 + ((vlen + 7) & ~7);");
    c.line("                }");
    c.line("                files.add(new KayaApp.PickedFile(");
    c.line("                        (Long) parts[0], (String) parts[1], (String) parts[2]));");
    c.line("            }");
    c.line("            return new Occ(kind, id, java.util.List.of(), files);");
    c.line("        }");
    // The privileged read's one answer, in its own arm: the generic
    // tail would take the CLIP KIND for a path length, so a text answer
    // would read the values header as a key.
    for name in crate::clip_answer_occurrence_names(spec) {
        c.line(&format!(
            "        if (kind == OCC_KIND_{}) {{",
            name.to_uppercase()
        ));
        c.line("            return new Occ(kind, id, java.util.List.of(),");
        c.line("                    parseClip(rec, b, 16, new int[1]));");
        c.line("        }");
    }
    let id_only = crate::id_only_occurrence_names(spec)
        .iter()
        .map(|n| format!("kind == OCC_KIND_{}", n.to_uppercase()))
        .collect::<Vec<_>>()
        .join(" || ");
    c.line("        // Surface lifecycle records carry the surface id alone");
    c.line("        // (derived from the record shapes).");
    c.line(&format!("        if ({id_only}) {{"));
    c.line("            return new Occ(kind, id, java.util.List.of(), null);");
    c.line("        }");
    let id_pair = crate::id_pair_occurrence_names(spec)
        .iter()
        .map(|n| format!("kind == OCC_KIND_{}", n.to_uppercase()))
        .collect::<Vec<_>>()
        .join(" || ");
    if !id_pair.is_empty() {
        c.line("        // Surface-pair records (window, section): the SECOND id");
        c.line("        // keys the handler; the first rides as the payload.");
        c.line(&format!("        if ({id_pair}) {{"));
        c.line("            return new Occ(kind, b.getLong(16), java.util.List.of(), id);");
        c.line("        }");
    }
    // ONE STEP CAME BACK. Its own arm for the file_dialog_result reason
    // and then some: the body is a window, four RUN LENGTHS, the label,
    // and one flat Values tail the runs cut up (docs/undo-plan.md D5;
    // wire::undo_body). The generic tail below would take `window` for a
    // widget id and the SIGNAL COUNT for a key-path length, then read
    // the label's bytes as keys. The window keys the handler — the
    // ledger is per window — exactly as section_selected's second id
    // does.
    let undo = crate::undo_occurrence_names(spec)
        .iter()
        .map(|n| format!("kind == OCC_KIND_{}", n.to_uppercase()))
        .collect::<Vec<_>>()
        .join(" || ");
    if !undo.is_empty() {
        c.line(&format!("        if ({undo}) {{"));
        c.line("            int signalCount = b.getInt(16);");
        c.line("            int textCount = b.getInt(20);");
        c.line("            int entryCount = b.getInt(24);");
        c.line("            int orderCount = b.getInt(28);");
        c.line("            int[] cursor = { 32 };");
        c.line("            String label = (String) parseValue(rec, b, cursor);");
        c.line("            int flatCount = b.getInt(cursor[0]);");
        c.line("            cursor[0] += 8; // count + reserved");
        c.line("            List<Object> flat = new ArrayList<>(flatCount);");
        c.line("            for (int i = 0; i < flatCount; i++) {");
        c.line("                flat.add(parseValue(rec, b, cursor));");
        c.line("            }");
        c.line("            int taken = 0;");
        c.line("            List<Object> signals = new ArrayList<>(signalCount * 2);");
        c.line("            for (int i = 0; i < signalCount * 2; i++) {");
        c.line("                signals.add(flat.get(taken++));");
        c.line("            }");
        // Arity-first like the two runs below, and for their reason: a
        // stamped copy's field is (template node, key path), which a
        // fixed pair had nowhere to put.
        c.line("            List<UndoTextValues> texts = new ArrayList<>(textCount);");
        c.line("            for (int i = 0; i < textCount; i++) {");
        c.line("                int size = (int) (long) (Long) flat.get(taken);");
        c.line("                long ident = (Long) flat.get(taken + 1);");
        c.line("                int pathLen = (int) (long) (Long) flat.get(taken + 2);");
        c.line("                List<Object> body = new ArrayList<>(");
        c.line("                        flat.subList(taken + 3, taken + size));");
        c.line("                taken += size;");
        c.line("                texts.add(new UndoTextValues(ident,");
        c.line("                        List.copyOf(body.subList(0, pathLen)),");
        c.line("                        (String) body.get(pathLen)));");
        c.line("            }");
        // Arity-first groups: `size` counts itself, so a reader takes it
        // and needs nothing else.
        c.line("            List<UndoEntryValues> entries = new ArrayList<>(entryCount);");
        c.line("            for (int i = 0; i < entryCount; i++) {");
        c.line("                // Arity-first: `size` counts itself, so a reader");
        c.line("                // takes it and needs nothing else.");
        c.line("                int size = (int) (long) (Long) flat.get(taken);");
        c.line("                long coll = (Long) flat.get(taken + 1);");
        c.line("                boolean present = (Long) flat.get(taken + 2) != 0L;");
        c.line("                int variant = (int) (long) (Long) flat.get(taken + 3);");
        c.line("                int pathLen = (int) (long) (Long) flat.get(taken + 4);");
        c.line("                List<Object> body = new ArrayList<>(");
        c.line("                        flat.subList(taken + 5, taken + size));");
        c.line("                taken += size;");
        c.line("                entries.add(new UndoEntryValues(coll,");
        c.line("                        List.copyOf(body.subList(0, pathLen)), body.get(pathLen),");
        c.line("                        present, present ? variant : 0,");
        c.line("                        present ? List.copyOf(body.subList(pathLen + 1, body.size()))");
        c.line("                                : List.of()));");
        c.line("            }");
        c.line("            List<UndoOrderValues> orders = new ArrayList<>(orderCount);");
        c.line("            for (int i = 0; i < orderCount; i++) {");
        c.line("                int size = (int) (long) (Long) flat.get(taken);");
        c.line("                long coll = (Long) flat.get(taken + 1);");
        c.line("                int pathLen = (int) (long) (Long) flat.get(taken + 2);");
        c.line("                List<Object> body = new ArrayList<>(");
        c.line("                        flat.subList(taken + 3, taken + size));");
        c.line("                taken += size;");
        c.line("                orders.add(new UndoOrderValues(coll,");
        c.line("                        List.copyOf(body.subList(0, pathLen)),");
        c.line("                        List.copyOf(body.subList(pathLen, body.size()))));");
        c.line("            }");
        // A truncated or over-long body is a broken ENCODER, not bad
        // input, and it fails here rather than handing the app half a
        // step — the read-in-threes rule the picker already follows.
        c.line("            if (taken != flat.size()) {");
        c.line("                throw new IllegalStateException(");
        c.line("                        \"kaya: undo delta has trailing values\");");
        c.line("            }");
        c.line("            return new Occ(kind, id, java.util.List.of(),");
        c.line("                    new UndoValues(label, signals, texts, entries, orders));");
        c.line("        }");
    }
    c.line("        int pathLen = b.getInt(16);");
    c.line("        List<Object> keys = new ArrayList<>();");
    c.line("        int at = 24;");
    c.line("        for (int i = 0; i < pathLen; i++) {");
    c.line("            int vtype = b.getInt(at);");
    c.line("            int vlen = b.getInt(at + 4);");
    c.line("            switch (vtype) {");
    c.line("                case VALUE_BOOL: keys.add(rec[at + 8] != 0); break;");
    c.line("                case VALUE_I64: keys.add(b.getLong(at + 8)); break;");
    c.line("                case VALUE_F64: keys.add(b.getDouble(at + 8)); break;");
    c.line("                default:");
    c.line("                    keys.add(new String(rec, at + 8, vlen, StandardCharsets.UTF_8));");
    c.line("            }");
    c.line("            at += 8 + ((vlen + 7) & ~7);");
    c.line("        }");
    c.line("        Object payload = null;");
    // The u32 slot the tag family calls `reserved` is a real value on
    // these (sort_requested's column) — read from its fixed offset.
    for name in crate::u32_slot_occurrence_names(spec) {
        c.line(&format!("        if (kind == OCC_KIND_{}) {{", name.to_uppercase()));
        c.line("            payload = b.getInt(20);");
        c.line("        }");
    }
    let with_payload = crate::payload_occurrence_names(spec)
        .iter()
        .map(|n| format!("kind == OCC_KIND_{}", n.to_uppercase()))
        .collect::<Vec<_>>()
        .join(" || ");
    c.line(&format!("        if ({with_payload}) {{"));
    // Type-generic payload decode, same shape as the key loop: no
    // per-kind logic left to drift.
    c.line("            int ptype = b.getInt(at);");
    c.line("            int plen = b.getInt(at + 4);");
    c.line("            switch (ptype) {");
    c.line("                case VALUE_BOOL: payload = rec[at + 8] != 0; break;");
    c.line("                case VALUE_I64: payload = b.getLong(at + 8); break;");
    c.line("                case VALUE_F64: payload = b.getDouble(at + 8); break;");
    c.line("                default:");
    c.line("                    payload = new String(rec, at + 8, plen, StandardCharsets.UTF_8);");
    c.line("            }");
    c.line("        }");
    // A paste rides a click tag VERBATIM, so the key path above is
    // already read and the clip sits after it. One record kind, path_len
    // deciding.
    let pasted = crate::pasted_occurrence_names(spec)
        .iter()
        .map(|n| format!("kind == OCC_KIND_{}", n.to_uppercase()))
        .collect::<Vec<_>>()
        .join(" || ");
    if !pasted.is_empty() {
        c.line(&format!("        if ({pasted}) {{"));
        c.line("            payload = parseClip(rec, b, at, new int[1]);");
        c.line("        }");
    }
    c.line("        return new Occ(kind, id, keys, payload);");
    c.line("    }");
    c.line("");
    c.line("    private KayaWire() {}");
    c.line("}");
    c.out
}

fn emit_packer(c: &mut Ctx, r: &Record) {
    let params = record_params(r);
    let mut sig: Vec<String> = Vec::new();
    for f in &params {
        sig.push(match f.ty {
            FieldTy::U32 => format!("int {}", camel(f.name)),
            FieldTy::U64 => format!("long {}", camel(f.name)),
            FieldTy::Value => format!("Object {}", camel(f.name)),
            FieldTy::Values => format!("Object[] {}", camel(f.name)),
            FieldTy::VariantSchemas => format!("int[][] {}", camel(f.name)),
        });
    }
    c.line("");
    c.line(&format!("    /** {} */", r.doc.replace('\n', " ")));
    c.line(&format!(
        "    public static byte[] tx{}({}) {{",
        pascal(r.name),
        sig.join(", ")
    ));
    c.line(&format!(
        "        ByteBuffer b = begin(TX_KIND_{});",
        r.name.to_uppercase()
    ));
    for f in r.fields {
        c.line(&match f.ty {
            FieldTy::U32 if f.name == "reserved" => "        b.putInt(0);".into(),
            FieldTy::U32 => format!("        b.putInt({});", camel(f.name)),
            FieldTy::U64 => format!("        b.putLong({});", camel(f.name)),
            FieldTy::Value => format!("        encodeValue(b, {});", camel(f.name)),
            FieldTy::Values => format!("        encodeValues(b, {});", camel(f.name)),
            FieldTy::VariantSchemas => format!("        encodeVariantSchemas(b, {});", camel(f.name)),
        });
    }
    c.line("        return finish(b);");
    c.line("    }");
}
