//! TypeScript emitter: one self-contained module of constants, packers,
//! and the occurrence parser — python.rs's shape, spelled for a language
//! with ONE number type. A bare `number` is an F64 on the wire; an I64
//! travels only inside the `I64` wrapper, which the sugar puts on keys
//! and on schema-typed fields (docs/js-plan.md §4).

use kaya::spec::{FieldTy, ProtocolSpec};

use crate::{Ctx, PropKind, is_padding, prop_variants, record_params, window_prop_variants};

/// Names spec identifiers must avoid: this emitter's helpers, plus the
/// JavaScript reserved words a parameter would collide with.
pub const RESERVED: &[&str] = &[
    "enc", "record", "pad", "cat", "u32", "u64", "i64", "f64", "parse_value", "parse_clip",
    "parse_occurrence", "BlobHandle", "I64", "canonicalize_shortcut", "occurrence_blob",
    "install_occurrence_blob", "text_encoder", "text_decoder",
    "arguments", "await", "break", "case", "catch", "class", "const", "continue", "debugger",
    "default", "delete", "do", "else", "enum", "eval", "export", "extends", "false", "finally",
    "for", "function", "if", "implements", "import", "in", "instanceof", "interface", "let",
    "new", "null", "package", "private", "protected", "public", "return", "static", "super",
    "switch", "this", "throw", "true", "try", "typeof", "undefined", "var", "void", "while",
    "with", "yield",
];

fn value_expr(kind: &PropKind, prop: &str) -> (String, &'static str, String) {
    // (parameter name, its TS type, the encoding expression)
    match kind {
        PropKind::Str => (prop.into(), "string", format!("enc.value({prop})")),
        PropKind::Bool => (prop.into(), "boolean", format!("enc.value({prop})")),
        PropKind::F64 => (prop.into(), "number", format!("enc.value({prop})")),
        PropKind::Enum(_) => (prop.into(), "number", format!("enc.value(new I64({prop}))")),
        PropKind::Blob => (
            "handle".into(),
            "number",
            "enc.value(new BlobHandle(handle))".to_string(),
        ),
    }
}

pub fn emit(spec: &ProtocolSpec) -> String {
    let mut c = Ctx { out: String::new() };
    c.line("// kaya wire vocabulary. Generated by kaya-bindgen from kaya::spec — do not edit.");
    c.line("//");
    c.line("// Records are {u32 size, u16 kind, u16 flags}, body, padded to 8, little-endian.");
    c.line("// Values are {u32 type, u32 len, payload padded to 8}; paths are");
    c.line("// {u32 count, u32 reserved, count values}. Keys and values here accept");
    c.line("// boolean, number (an F64), I64, string and BlobHandle, mapped to the");
    c.line("// kaya value types.");
    c.line("");
    c.line("// SPEC_HASH: the protocol fingerprint; the runtime asserts the loaded core agrees.");
    c.line(&format!("export const SPEC_HASH = 0x{:016x}n;", crate::spec_hash()));
    c.line("");
    for e in spec.enums {
        for (name, value) in e.variants {
            c.line(&format!(
                "export const {}_{} = {};",
                e.name.to_uppercase(),
                name.to_uppercase(),
                value
            ));
        }
    }
    c.line("");
    for (channel, records) in [("TX", spec.tx), ("APPLY", spec.apply), ("OCC", spec.occurrence)] {
        for r in records {
            c.line(&format!("export const {channel}_{} = {};", r.name.to_uppercase(), r.kind));
        }
    }
    c.line("");
    c.line("const text_encoder = new TextEncoder();");
    c.line("const text_decoder = new TextDecoder(\"utf-8\", { fatal: true });");
    c.line("");
    c.line("function pad(b: Uint8Array): Uint8Array {");
    c.line("  const rest = (8 - (b.length % 8)) % 8;");
    c.line("  if (rest === 0) return b;");
    c.line("  const out = new Uint8Array(b.length + rest);");
    c.line("  out.set(b);");
    c.line("  return out;");
    c.line("}");
    c.line("");
    c.line("function cat(...parts: Uint8Array[]): Uint8Array {");
    c.line("  let n = 0;");
    c.line("  for (const p of parts) n += p.length;");
    c.line("  const out = new Uint8Array(n);");
    c.line("  let at = 0;");
    c.line("  for (const p of parts) {");
    c.line("    out.set(p, at);");
    c.line("    at += p.length;");
    c.line("  }");
    c.line("  return out;");
    c.line("}");
    c.line("");
    c.line("function u32(v: number): Uint8Array {");
    c.line("  const b = new Uint8Array(4);");
    c.line("  new DataView(b.buffer).setUint32(0, v, true);");
    c.line("  return b;");
    c.line("}");
    c.line("");
    c.line("// Ids and handles are counters below 2^53 (crates/kaya/src/spec.rs,");
    c.line("// MAX_SAFE_INTEGER), so a u64 is two u32 halves and no BigInt.");
    c.line("function u64(v: number): Uint8Array {");
    c.line("  if (!Number.isSafeInteger(v) || v < 0) throw new RangeError(`kaya: ${v} is not a u64 the wire carries`);");
    c.line("  const b = new Uint8Array(8);");
    c.line("  const view = new DataView(b.buffer);");
    c.line("  view.setUint32(0, v % 4294967296, true);");
    c.line("  view.setUint32(4, Math.floor(v / 4294967296), true);");
    c.line("  return b;");
    c.line("}");
    c.line("");
    c.line("function i64(v: number): Uint8Array {");
    c.line("  if (!Number.isSafeInteger(v)) throw new RangeError(`kaya: ${v} is not a safe integer — a kaya integer is a count or a quantity, exact to ±(2^53 − 1); identity rides as strings or opaque tags`);");
    c.line("  const b = new Uint8Array(8);");
    c.line("  new DataView(b.buffer).setBigInt64(0, BigInt(v), true);");
    c.line("  return b;");
    c.line("}");
    c.line("");
    c.line("function f64(v: number): Uint8Array {");
    c.line("  const b = new Uint8Array(8);");
    c.line("  new DataView(b.buffer).setFloat64(0, v, true);");
    c.line("  return b;");
    c.line("}");
    c.line("");
    c.line("/** A blob value at the wire tier: the u64 handle from kaya_blob_register,");
    c.line(" * consumed by the next submit. The bytes never ride the record stream. */");
    c.line("export class BlobHandle {");
    c.line("  readonly handle: number;");
    c.line("  constructor(handle: number) {");
    c.line("    this.handle = handle;");
    c.line("  }");
    c.line("}");
    c.line("");
    c.line("/** An integer on the wire. A bare number is an F64; the sugar wraps keys");
    c.line(" * and schema-typed integer fields in this (docs/js-plan.md §4). */");
    c.line("export class I64 {");
    c.line("  readonly value: number;");
    c.line("  constructor(value: number) {");
    c.line("    if (!Number.isSafeInteger(value)) throw new RangeError(`kaya: ${value} is not a safe integer — a kaya integer is a count or a quantity, exact to ±(2^53 − 1); identity rides as strings or opaque tags`);");
    c.line("    this.value = value;");
    c.line("  }");
    c.line("}");
    c.line("");
    c.line("export type WireValue = boolean | number | string | BlobHandle | I64;");
    c.line("");
    c.line("/** Encoders, namespaced so no generated parameter can shadow them. */");
    c.line("const enc = {");
    c.line("  /** Encode one scalar as a kaya value. */");
    c.line("  value(v: WireValue): Uint8Array {");
    c.line("    if (typeof v === \"boolean\") return pad(cat(u32(VALUE_BOOL), u32(1), new Uint8Array([v ? 1 : 0])));");
    c.line("    if (v instanceof I64) return cat(u32(VALUE_I64), u32(8), i64(v.value));");
    c.line("    if (typeof v === \"number\") return cat(u32(VALUE_F64), u32(8), f64(v));");
    c.line("    if (v instanceof BlobHandle) return cat(u32(VALUE_BLOB), u32(8), u64(v.handle));");
    c.line("    if (typeof v === \"string\") {");
    c.line("      const utf8 = text_encoder.encode(v);");
    c.line("      return pad(cat(u32(VALUE_STR), u32(utf8.length), utf8));");
    c.line("    }");
    c.line("    throw new TypeError(`kaya: ${typeof v} is not a wire value (boolean, number, I64, string, BlobHandle)`);");
    c.line("  },");
    c.line("  /** Encode a counted value sequence: a key path or a record. */");
    c.line("  values(vals: readonly WireValue[]): Uint8Array {");
    c.line("    return cat(u32(vals.length), u32(0), ...vals.map((v) => enc.value(v)));");
    c.line("  },");
    c.line("  /** Encode a collection's element sum: per variant, a counted list of VALUE_* tags. A record collection is the one-variant case. */");
    c.line("  variant_schemas(variants: readonly (readonly number[])[]): Uint8Array {");
    c.line("    const parts = [u32(variants.length), u32(0)];");
    c.line("    for (const schema of variants) {");
    c.line("      parts.push(u32(schema.length));");
    c.line("      for (const t of schema) parts.push(u32(t));");
    c.line("    }");
    c.line("    return pad(cat(...parts));");
    c.line("  },");
    c.line("};");
    c.line("");
    c.line("/** Frame one record. */");
    c.line("export function record(kind: number, body: Uint8Array): Uint8Array {");
    c.line("  body = pad(body);");
    c.line("  const head = new Uint8Array(8);");
    c.line("  const view = new DataView(head.buffer);");
    c.line("  view.setUint32(0, 8 + body.length, true);");
    c.line("  view.setUint16(4, kind, true);");
    c.line("  view.setUint16(6, 0, true);");
    c.line("  return cat(head, body);");
    c.line("}");

    for r in spec.tx {
        if r.name == "set_property" || r.name == "set_window_prop" {
            continue;
        }
        let params = record_params(r);
        let sig: Vec<String> = params
            .iter()
            .map(|f| {
                let ty = match f.ty {
                    FieldTy::U32 | FieldTy::U64 => "number",
                    FieldTy::Value => "WireValue",
                    FieldTy::Values => "readonly WireValue[]",
                    FieldTy::VariantSchemas => "readonly (readonly number[])[]",
                };
                format!("{}: {ty}", f.name)
            })
            .collect();
        c.line("");
        c.line(&format!("/** {} */", r.doc.replace('\n', " ").replace("*/", "* /")));
        c.line(&format!("export function tx_{}({}): Uint8Array {{", r.name, sig.join(", ")));
        let mut parts: Vec<String> = Vec::new();
        for f in r.fields {
            parts.push(match f.ty {
                FieldTy::U32 if is_padding(f) => "u32(0)".into(),
                FieldTy::U32 => format!("u32({})", f.name),
                FieldTy::U64 => format!("u64({})", f.name),
                FieldTy::Value => format!("enc.value({})", f.name),
                FieldTy::Values => format!("enc.values({})", f.name),
                FieldTy::VariantSchemas => format!("enc.variant_schemas({})", f.name),
            });
        }
        let body = if parts.is_empty() {
            "new Uint8Array(0)".to_string()
        } else {
            format!("cat({})", parts.join(", "))
        };
        c.line(&format!("  return record(TX_{}, {body});", r.name.to_uppercase()));
        c.line("}");
    }

    for (prop, _, kind) in prop_variants(spec) {
        let up = prop.to_uppercase();
        let (param, ty, expr) = value_expr(kind, prop);
        c.line("");
        c.line(&format!("/** set_property with a constant {prop} value. */"));
        c.line(&format!("export function tx_set_{prop}(widget_id: number, {param}: {ty}): Uint8Array {{"));
        c.line(&format!("  return record(TX_SET_PROPERTY, cat(u64(widget_id), u32(PROP_{up}), u32(SOURCE_CONST), {expr}));"));
        c.line("}");
        c.line("");
        c.line(&format!("/** set_property with a signal-bound {prop} value. */"));
        c.line(&format!("export function tx_bind_{prop}(widget_id: number, signal_id: number): Uint8Array {{"));
        c.line(&format!("  return record(TX_SET_PROPERTY, cat(u64(widget_id), u32(PROP_{up}), u32(SOURCE_SIGNAL), u64(signal_id)));"));
        c.line("}");
        c.line("");
        c.line(&format!("/** set_property bound to one field of the element of the enclosing For, `level` Fors up. */"));
        c.line(&format!("export function tx_bind_{prop}_element(widget_id: number, level = 0, field = 0): Uint8Array {{"));
        c.line(&format!("  return record(TX_SET_PROPERTY, cat(u64(widget_id), u32(PROP_{up}), u32(SOURCE_ELEMENT), u32(level), u32(field)));"));
        c.line("}");
    }

    // The window-prop duos: element sources are rejected by the wire.
    for (prop, _, kind) in window_prop_variants(spec) {
        let up = prop.to_uppercase();
        let (param, ty, expr) = value_expr(kind, prop);
        assert!(!matches!(kind, PropKind::Blob), "no window prop carries a blob");
        c.line("");
        c.line(&format!("/** set_window_prop with a constant {prop} value; window 0, the primary surface. */"));
        c.line(&format!("export function tx_set_window_{prop}(window: number, {param}: {ty}): Uint8Array {{"));
        c.line(&format!("  return record(TX_SET_WINDOW_PROP, cat(u64(window), u32(WPROP_{up}), u32(SOURCE_CONST), {expr}));"));
        c.line("}");
        c.line("");
        c.line(&format!("/** set_window_prop with a signal-bound {prop} value; window 0, the primary surface. */"));
        c.line(&format!("export function tx_bind_window_{prop}(window: number, signal_id: number): Uint8Array {{"));
        c.line(&format!("  return record(TX_SET_WINDOW_PROP, cat(u64(window), u32(WPROP_{up}), u32(SOURCE_SIGNAL), u64(signal_id)));"));
        c.line("}");
    }

    // The entry-prop duos, the window shape on the navigation-entry
    // table (DESIGN.md, Navigation).
    for (prop, _, kind) in crate::entry_prop_variants(spec) {
        let up = prop.to_uppercase();
        let (param, ty, expr) = value_expr(kind, prop);
        assert!(matches!(kind, PropKind::Str | PropKind::Bool), "no entry prop carries {kind:?}");
        c.line("");
        c.line(&format!("/** set_entry_prop with a constant {prop} value. */"));
        c.line(&format!("export function tx_set_entry_{prop}(entry: number, {param}: {ty}): Uint8Array {{"));
        c.line(&format!("  return record(TX_SET_ENTRY_PROP, cat(u64(entry), u32(EPROP_{up}), u32(SOURCE_CONST), {expr}));"));
        c.line("}");
        c.line("");
        c.line(&format!("/** set_entry_prop with a signal-bound {prop} value. */"));
        c.line(&format!("export function tx_bind_entry_{prop}(entry: number, signal_id: number): Uint8Array {{"));
        c.line(&format!("  return record(TX_SET_ENTRY_PROP, cat(u64(entry), u32(EPROP_{up}), u32(SOURCE_SIGNAL), u64(signal_id)));"));
        c.line("}");
    }

    // The section-prop duos; icon rides the blob channel (DESIGN.md,
    // Sections).
    for (prop, _, kind) in crate::section_prop_variants(spec) {
        let up = prop.to_uppercase();
        let (param, ty, expr) = value_expr(kind, prop);
        assert!(
            matches!(kind, PropKind::Str | PropKind::Blob | PropKind::Enum(_)),
            "no section prop carries {kind:?}"
        );
        c.line("");
        c.line(&format!("/** set_section_prop with a constant {prop} value. */"));
        c.line(&format!("export function tx_set_section_{prop}(section: number, {param}: {ty}): Uint8Array {{"));
        c.line(&format!("  return record(TX_SET_SECTION_PROP, cat(u64(section), u32(SPROP_{up}), u32(SOURCE_CONST), {expr}));"));
        c.line("}");
        c.line("");
        c.line(&format!("/** set_section_prop with a signal-bound {prop} value. */"));
        c.line(&format!("export function tx_bind_section_{prop}(section: number, signal_id: number): Uint8Array {{"));
        c.line(&format!("  return record(TX_SET_SECTION_PROP, cat(u64(section), u32(SPROP_{up}), u32(SOURCE_SIGNAL), u64(signal_id)));"));
        c.line("}");
    }

    // The one binding-tier shortcut parser (DESIGN.md, Menus): SPELLING
    // only, policy being the core's and validated on the canonical form.
    let named_keys = crate::SHORTCUT_NAMED_KEYS
        .iter()
        .map(|k| format!("\"{k}\""))
        .collect::<Vec<_>>()
        .join(", ");
    c.line("");
    c.line(&format!("const SHORTCUT_NAMED_KEYS = new Set([{named_keys}]);"));
    c.line("");
    c.line("/** Canonicalize a shortcut spelling to the wire form: lowercase '+'-joined");
    c.line(" * tokens, modifiers ordered primary, shift, alt, then one key (a-z, 0-9,");
    c.line(" * or the closed named set). Rejects whitespace, empty tokens, repeated");
    c.line(" * modifiers, aliases (ctrl/cmd/option), and unknown or multiple or missing");
    c.line(" * keys. POLICY stays at the core, validated on the canonical spelling. */");
    c.line("export function canonicalize_shortcut(spelling: string): string {");
    c.line("  if (!spelling) throw new Error(\"kaya: shortcut is empty\");");
    c.line("  if (/[ \\t\\n\\v\\f\\r]/.test(spelling)) throw new Error(`kaya: shortcut ${JSON.stringify(spelling)} contains whitespace`);");
    c.line("  const parts = spelling.toLowerCase().split(\"+\");");
    c.line("  if (parts.some((p) => !p)) throw new Error(`kaya: shortcut ${JSON.stringify(spelling)} has an empty token`);");
    c.line("  const mods = parts.slice(0, -1);");
    c.line("  const key = parts[parts.length - 1]!;");
    c.line("  const seen: string[] = [];");
    c.line("  for (const m of mods) {");
    c.line("    if (m !== \"primary\" && m !== \"shift\" && m !== \"alt\") {");
    c.line("      throw new Error(`kaya: shortcut ${JSON.stringify(spelling)} has an unknown modifier ${JSON.stringify(m)} (the portable modifiers are primary, shift, alt; aliases like ctrl, cmd, and option are not accepted)`);");
    c.line("    }");
    c.line("    if (seen.includes(m)) throw new Error(`kaya: shortcut ${JSON.stringify(spelling)} repeats modifier ${JSON.stringify(m)}`);");
    c.line("    seen.push(m);");
    c.line("  }");
    c.line("  const alnum = key.length === 1 && /^[a-z0-9]$/.test(key);");
    c.line("  if (!alnum && !SHORTCUT_NAMED_KEYS.has(key)) {");
    c.line("    throw new Error(`kaya: shortcut ${JSON.stringify(spelling)} key ${JSON.stringify(key)} is outside the floor (one of a-z, 0-9, or the closed named set)`);");
    c.line("  }");
    c.line("  return [...[\"primary\", \"shift\", \"alt\"].filter((m) => seen.includes(m)), key].join(\"+\");");
    c.line("}");

    // Signal binders only for the bindable props.
    for (prop, _, kind) in crate::menu_prop_variants(spec) {
        let up = prop.to_uppercase();
        let (param, ty, expr) = match kind {
            PropKind::Str if *prop == "shortcut" => (
                prop.to_string(),
                "string",
                format!("enc.value(canonicalize_shortcut({prop}))"),
            ),
            other => value_expr(other, prop),
        };
        c.line("");
        c.line(&format!("/** set_menu_prop with a constant {prop} value. */"));
        c.line(&format!("export function tx_set_menu_{prop}(item: number, {param}: {ty}): Uint8Array {{"));
        c.line(&format!("  return record(TX_SET_MENU_PROP, cat(u64(item), u32(MPROP_{up}), u32(SOURCE_CONST), {expr}));"));
        c.line("}");
        if crate::menu_prop_bindable(prop) {
            c.line("");
            c.line(&format!("/** set_menu_prop with a signal-bound {prop} value. */"));
            c.line(&format!("export function tx_bind_menu_{prop}(item: number, signal_id: number): Uint8Array {{"));
            c.line(&format!("  return record(TX_SET_MENU_PROP, cat(u64(item), u32(MPROP_{up}), u32(SOURCE_SIGNAL), u64(signal_id)));"));
            c.line("}");
        }
    }

    c.line("");
    c.line("/** A decoded value: an I64 arrives as a plain number, the root having");
    c.line(" * refused anything past 2^53 before it could get here. */");
    c.line("export type Decoded = boolean | number | string | BlobHandle;");
    c.line("");
    c.line("function read_u32(buf: Uint8Array, at: number): number {");
    c.line("  return new DataView(buf.buffer, buf.byteOffset, buf.byteLength).getUint32(at, true);");
    c.line("}");
    c.line("");
    c.line("function read_u64(buf: Uint8Array, at: number): number {");
    c.line("  const view = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);");
    c.line("  return view.getUint32(at, true) + view.getUint32(at + 4, true) * 4294967296;");
    c.line("}");
    c.line("");
    c.line("/** Decode one value; returns [value, next offset]. */");
    c.line("export function parse_value(buf: Uint8Array, at: number): [Decoded, number] {");
    c.line("  const view = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);");
    c.line("  const vtype = view.getUint32(at, true);");
    c.line("  const vlen = view.getUint32(at + 4, true);");
    c.line("  const end = at + 8 + ((vlen + 7) & ~7);");
    c.line("  if (vtype === VALUE_BOOL) return [buf[at + 8] !== 0, end];");
    c.line("  if (vtype === VALUE_I64) return [Number(view.getBigInt64(at + 8, true)), end];");
    c.line("  if (vtype === VALUE_F64) return [view.getFloat64(at + 8, true), end];");
    c.line("  if (vtype === VALUE_STR) return [text_decoder.decode(buf.subarray(at + 8, at + 8 + vlen)), end];");
    c.line("  if (vtype === VALUE_BLOB) return [new BlobHandle(read_u64(buf, at + 8)), end];");
    c.line("  throw new Error(`unknown value type ${vtype}`);");
    c.line("}");
    c.line("");
    // The occurrence blob table, the third direction (python.rs carries
    // the reasoning): redeemed HERE, in the generated decoder, so no
    // handle ever reaches an app.
    c.line("let occurrence_blob: ((handle: number) => Uint8Array) | null = null;");
    c.line("");
    c.line("/** Redeem-and-release for occurrence blobs, installed by the runtime at");
    c.line(" * load (this module loads no library of its own). */");
    c.line("export function install_occurrence_blob(fn: (handle: number) => Uint8Array): void {");
    c.line("  occurrence_blob = fn;");
    c.line("}");
    c.line("");
    c.line("export type ClipPayload = { clip: number; values: (Decoded | Uint8Array)[] };");
    c.line("");
    c.line("/** Decode one representation: the clip kind, then its values. `clip` is a");
    c.line(" * SINGLE member of the clip enum and never a mask, and 0 with no values is");
    c.line(" * the universal empty answer. Blobs are redeemed to bytes and released here. */");
    c.line("export function parse_clip(buf: Uint8Array, at: number): [ClipPayload, number] {");
    c.line("  const clip = read_u32(buf, at);");
    c.line("  const count = read_u32(buf, at + 8);");
    c.line("  at += 16;");
    c.line("  const values: (Decoded | Uint8Array)[] = [];");
    c.line("  for (let i = 0; i < count; i++) {");
    c.line("    let value: Decoded | Uint8Array;");
    c.line("    [value, at] = parse_value(buf, at);");
    c.line("    if (value instanceof BlobHandle) {");
    c.line("      if (occurrence_blob === null) throw new Error(\"kaya: occurrence blob redemption is not installed\");");
    c.line("      value = occurrence_blob(value.handle);");
    c.line("    }");
    c.line("    values.push(value);");
    c.line("  }");
    c.line("  return [{ clip, values }, at];");
    c.line("}");
    c.line("");
    c.line("export type PickedTriple = [handle: number, name: string, local_path: string];");
    c.line("export type UndoPayload = {");
    c.line("  label: string;");
    c.line("  signals: [id: number, value: Decoded][];");
    c.line("  texts: [id: number, path: Decoded[], text: string][];");
    c.line("  entries: [coll: number, path: Decoded[], key: Decoded, state: [variant: number, fields: Decoded[]] | null][];");
    c.line("  orders: [coll: number, path: Decoded[], keys: Decoded[]][];");
    c.line("};");
    c.line("");
    c.line("/** One decoded occurrence (header included). `id` is null for a kind this");
    c.line(" * vocabulary does not know; `keys` is empty when id is a widget id, else id");
    c.line(" * is a template node id and keys is the copy's key path. */");
    c.line("export type Occurrence = { kind: number; id: number | null; keys: Decoded[]; payload: unknown };");
    c.line("");
    c.line("export function parse_occurrence(buf: Uint8Array): Occurrence {");
    c.line("  const view = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);");
    c.line("  const size = view.getUint32(0, true);");
    c.line("  const kind = view.getUint16(4, true);");
    let accepted = crate::occurrence_names(spec)
        .iter()
        .map(|n| format!("OCC_{}", n.to_uppercase()))
        .collect::<Vec<_>>()
        .join(", ");
    c.line(&format!("  if (![{accepted}].includes(kind)) return {{ kind, id: null, keys: [], payload: null }};"));
    c.line("  if (kind === OCC_ALERT_RESULT) {");
    c.line("    // The alert's one answer: id + u32 choice (ALERT_CHOICE_*).");
    c.line("    return { kind, id: read_u64(buf, 8), keys: [], payload: read_u32(buf, 16) };");
    c.line("  }");
    // The picker's answer: its own arm (python.rs carries the reasoning).
    c.line("  if (kind === OCC_FILE_DIALOG_RESULT) {");
    c.line("    const dialog = read_u64(buf, 8);");
    c.line("    const count = read_u32(buf, 16);");
    c.line("    let at = 32; // past dialog, count, pad, values count, reserved");
    c.line("    const files: PickedTriple[] = [];");
    c.line("    for (let i = 0; i < count; i++) {");
    c.line("      let handle: Decoded, name: Decoded, local_path: Decoded;");
    c.line("      [handle, at] = parse_value(buf, at);");
    c.line("      [name, at] = parse_value(buf, at);");
    c.line("      [local_path, at] = parse_value(buf, at);");
    c.line("      files.push([handle as number, name as string, local_path as string]);");
    c.line("    }");
    c.line("    return { kind, id: dialog, keys: [], payload: files };");
    c.line("  }");
    for name in crate::clip_answer_occurrence_names(spec) {
        c.line(&format!("  if (kind === OCC_{}) {{", name.to_uppercase()));
        c.line("    const request = read_u64(buf, 8);");
        c.line("    const [clip] = parse_clip(buf, 16);");
        c.line("    return { kind, id: request, keys: [], payload: clip };");
        c.line("  }");
    }
    let id_only = crate::id_only_occurrence_names(spec)
        .iter()
        .map(|n| format!("OCC_{}", n.to_uppercase()))
        .collect::<Vec<_>>()
        .join(", ");
    c.line(&format!("  if ([{id_only}].includes(kind)) {{"));
    c.line("    // Surface lifecycle records carry the surface id alone.");
    c.line("    return { kind, id: read_u64(buf, 8), keys: [], payload: null };");
    c.line("  }");
    let id_pair = crate::id_pair_occurrence_names(spec)
        .iter()
        .map(|n| format!("OCC_{}", n.to_uppercase()))
        .collect::<Vec<_>>()
        .join(", ");
    if !id_pair.is_empty() {
        c.line(&format!("  if ([{id_pair}].includes(kind)) {{"));
        c.line("    // Surface-pair records (window, section): the SECOND id keys the");
        c.line("    // handler; the first rides as the payload.");
        c.line("    return { kind, id: read_u64(buf, 16), keys: [], payload: read_u64(buf, 8) };");
        c.line("  }");
    }
    let undo = crate::undo_occurrence_names(spec)
        .iter()
        .map(|n| format!("OCC_{}", n.to_uppercase()))
        .collect::<Vec<_>>()
        .join(", ");
    if !undo.is_empty() {
        c.line(&format!("  if ([{undo}].includes(kind)) {{"));
        c.line("    // One undone/redone step: the window, four run lengths, the group's");
        c.line("    // label, then ONE flat values tail the runs cut up — signals, texts,");
        c.line("    // entries, orders (docs/undo-plan.md D5; wire::undo_body).");
        c.line("    const window = read_u64(buf, 8);");
        c.line("    const n_signals = read_u32(buf, 16);");
        c.line("    const n_texts = read_u32(buf, 20);");
        c.line("    const n_entries = read_u32(buf, 24);");
        c.line("    const n_orders = read_u32(buf, 28);");
        c.line("    let at = 32;");
        c.line("    let label: Decoded;");
        c.line("    [label, at] = parse_value(buf, at);");
        c.line("    const count = read_u32(buf, at);");
        c.line("    at += 8;");
        c.line("    const flat: Decoded[] = [];");
        c.line("    for (let i = 0; i < count; i++) {");
        c.line("      let value: Decoded;");
        c.line("      [value, at] = parse_value(buf, at);");
        c.line("      flat.push(value);");
        c.line("    }");
        c.line("    let i = 0;");
        c.line("    const signals: UndoPayload[\"signals\"] = [];");
        c.line("    for (let n = 0; n < n_signals; n++) {");
        c.line("      signals.push([flat[i] as number, flat[i + 1]!]);");
        c.line("      i += 2;");
        c.line("    }");
        c.line("    // Arity-first groups: `size` counts itself, so a reader takes it and");
        c.line("    // needs nothing else. path_len 0 means the id is a live widget id.");
        c.line("    const texts: UndoPayload[\"texts\"] = [];");
        c.line("    for (let n = 0; n < n_texts; n++) {");
        c.line("      const size = flat[i] as number;");
        c.line("      const ident = flat[i + 1] as number;");
        c.line("      const path_len = flat[i + 2] as number;");
        c.line("      const body = flat.slice(i + 3, i + size);");
        c.line("      i += size;");
        c.line("      texts.push([ident, body.slice(0, path_len), body[path_len] as string]);");
        c.line("    }");
        c.line("    const entries: UndoPayload[\"entries\"] = [];");
        c.line("    for (let n = 0; n < n_entries; n++) {");
        c.line("      const size = flat[i] as number;");
        c.line("      const coll = flat[i + 1] as number;");
        c.line("      const present = flat[i + 2] as number;");
        c.line("      const variant = flat[i + 3] as number;");
        c.line("      const path_len = flat[i + 4] as number;");
        c.line("      const body = flat.slice(i + 5, i + size);");
        c.line("      i += size;");
        c.line("      const state: [number, Decoded[]] | null = present ? [variant, body.slice(path_len + 1)] : null;");
        c.line("      entries.push([coll, body.slice(0, path_len), body[path_len]!, state]);");
        c.line("    }");
        c.line("    const orders: UndoPayload[\"orders\"] = [];");
        c.line("    for (let n = 0; n < n_orders; n++) {");
        c.line("      const size = flat[i] as number;");
        c.line("      const coll = flat[i + 1] as number;");
        c.line("      const path_len = flat[i + 2] as number;");
        c.line("      const body = flat.slice(i + 3, i + size);");
        c.line("      i += size;");
        c.line("      orders.push([coll, body.slice(0, path_len), body.slice(path_len)]);");
        c.line("    }");
        c.line("    // A truncated or over-long body is a broken ENCODER, not bad input.");
        c.line("    if (i !== flat.length) throw new Error(\"kaya: undo delta has trailing values\");");
        c.line("    const payload: UndoPayload = { label: label as string, signals, texts, entries, orders };");
        c.line("    return { kind, id: window, keys: [], payload };");
        c.line("  }");
    }
    c.line("  const ident = read_u64(buf, 8);");
    c.line("  const path_len = read_u32(buf, 16);");
    c.line("  const keys: Decoded[] = [];");
    c.line("  let at = 24;");
    c.line("  for (let i = 0; i < path_len; i++) {");
    c.line("    let key: Decoded;");
    c.line("    [key, at] = parse_value(buf, at);");
    c.line("    keys.push(key);");
    c.line("  }");
    c.line("  let payload: unknown = null;");
    let u32_slot = crate::u32_slot_occurrence_names(spec)
        .iter()
        .map(|n| format!("OCC_{}", n.to_uppercase()))
        .collect::<Vec<_>>()
        .join(", ");
    if !u32_slot.is_empty() {
        c.line("  // The u32 slot the tag family calls `reserved` is a real value on");
        c.line("  // these (sort_requested's column) — read before the generic tail.");
        c.line(&format!("  if ([{u32_slot}].includes(kind)) payload = read_u32(buf, 20);"));
    }
    let with_payload = crate::payload_occurrence_names(spec)
        .iter()
        .map(|n| format!("OCC_{}", n.to_uppercase()))
        .collect::<Vec<_>>()
        .join(", ");
    c.line(&format!("  if ([{with_payload}].includes(kind)) [payload, at] = parse_value(buf, at);"));
    let pasted = crate::pasted_occurrence_names(spec)
        .iter()
        .map(|n| format!("OCC_{}", n.to_uppercase()))
        .collect::<Vec<_>>()
        .join(", ");
    if !pasted.is_empty() {
        c.line("  // A paste rides a click tag VERBATIM, so the key path above is already");
        c.line("  // read and the clip sits after it.");
        c.line(&format!("  if ([{pasted}].includes(kind)) [payload, at] = parse_clip(buf, at);"));
    }
    let values_tail = crate::values_tail_occurrence_names(spec)
        .iter()
        .map(|n| format!("OCC_{}", n.to_uppercase()))
        .collect::<Vec<_>>()
        .join(", ");
    if !values_tail.is_empty() {
        c.line(&format!("  if ([{values_tail}].includes(kind)) {{"));
        c.line("    // The canvas asks carry a run of BARE values after the key path with");
        c.line("    // no count in front, read until the record ends (docs/canvas-plan.md §3.2.1).");
        c.line("    const tail: Decoded[] = [];");
        c.line("    while (at < size) {");
        c.line("      let value: Decoded;");
        c.line("      [value, at] = parse_value(buf, at);");
        c.line("      tail.push(value);");
        c.line("    }");
        c.line("    payload = tail;");
        c.line("  }");
    }
    c.line("  return { kind, id: ident, keys, payload };");
    c.line("}");

    c.out
}
