//! Python emitter: one self-contained module of constants, packers, and
//! the occurrence parser.

use kaya::spec::{FieldTy, ProtocolSpec};

use crate::{Ctx, PropKind, prop_variants, record_params, window_prop_variants};

/// Names spec identifiers must avoid: this emitter's helpers, plus
/// Python's keywords and builtins a parameter would shadow.
pub const RESERVED: &[&str] = &[
    "_enc", "record", "parse_value", "parse_occurrence", "struct", "BlobHandle",
    "canonicalize_shortcut",
    "and", "as", "assert", "async", "await", "break", "class", "continue", "def", "del",
    "elif", "else", "except", "finally", "for", "from", "global", "if", "import", "in",
    "is", "lambda", "nonlocal", "not", "or", "pass", "raise", "return", "try", "while",
    "with", "yield", "type", "bytes", "len", "int", "str", "float", "bool",
];

pub fn emit(spec: &ProtocolSpec) -> String {
    let mut c = Ctx { out: String::new() };
    c.line("\"\"\"kaya wire vocabulary. Generated by kaya-bindgen from kaya::spec — do not edit.");
    c.line("");
    c.line("Records are {u32 size, u16 kind, u16 flags}, body, padded to 8, little-endian.");
    c.line("Values are {u32 type, u32 len, payload padded to 8}; paths are");
    c.line("{u32 count, u32 reserved, count values}. Keys and values here accept");
    c.line("Python bool, int, float, str, and BlobHandle, mapped to the kaya");
    c.line("value types.");
    c.line("\"\"\"");
    c.line("");
    c.line("import struct");
    c.line("");

    c.line(&format!("# SPEC_HASH: {}.", "the protocol fingerprint; the runtime asserts the loaded core agrees"));
    c.line(&format!("SPEC_HASH = 0x{:016x}", crate::spec_hash()));
    c.line("");
    for e in spec.enums {
        for (name, value) in e.variants {
            c.line(&format!(
                "{}_{} = {}",
                e.name.to_uppercase(),
                name.to_uppercase(),
                value
            ));
        }
    }
    c.line("");
    for (channel, records) in [("TX", spec.tx), ("APPLY", spec.apply), ("OCC", spec.occurrence)] {
        for r in records {
            c.line(&format!("{channel}_{} = {}", r.name.to_uppercase(), r.kind));
        }
    }

    c.line("");
    c.line("");
    c.line("def _pad(b):");
    c.line("    return b + b\"\\0\" * (-len(b) % 8)");
    c.line("");
    c.line("");
    c.line("class BlobHandle:");
    c.line("    \"\"\"A blob value at the wire tier: the u64 handle from");
    c.line("    kaya_blob_register, consumed by the next submit. The bytes never");
    c.line("    ride the record stream; the wrapper distinguishes a blob from a");
    c.line("    plain int in the type-dispatched encoders.\"\"\"");
    c.line("");
    c.line("    __slots__ = (\"handle\",)");
    c.line("");
    c.line("    def __init__(self, handle):");
    c.line("        self.handle = handle");
    c.line("");
    c.line("");
    c.line("class _enc:");
    c.line("    \"\"\"Encoders, namespaced so no generated parameter can shadow them.\"\"\"");
    c.line("");
    c.line("    @staticmethod");
    c.line("    def value(v):");
    c.line("        \"\"\"Encode a Python scalar as a kaya value.\"\"\"");
    c.line("        if isinstance(v, bool):");
    c.line("            return _pad(struct.pack(\"<II\", VALUE_BOOL, 1) + bytes([v]))");
    c.line("        if isinstance(v, int):");
    c.line("            return struct.pack(\"<IIq\", VALUE_I64, 8, v)");
    c.line("        if isinstance(v, float):");
    c.line("            return struct.pack(\"<IId\", VALUE_F64, 8, v)");
    c.line("        if isinstance(v, BlobHandle):");
    c.line("            return struct.pack(\"<IIQ\", VALUE_BLOB, 8, v.handle)");
    c.line("        utf8 = v.encode()");
    c.line("        return _pad(struct.pack(\"<II\", VALUE_STR, len(utf8)) + utf8)");
    c.line("");
    c.line("");
    c.line("    @staticmethod");
    c.line("    def values(vals):");
    c.line("        \"\"\"Encode a counted value sequence: a key path or a record.\"\"\"");
    c.line("        return struct.pack(\"<II\", len(vals), 0) + b\"\".join(_enc.value(v) for v in vals)");
    c.line("");
    c.line("");
    c.line("    @staticmethod");
    c.line("    def variant_schemas(variants):");
    c.line("        \"\"\"Encode a collection's element sum: per variant, a counted list of VALUE_* tags. A record collection is the one-variant case.\"\"\"");
    c.line("        body = struct.pack(\"<II\", len(variants), 0)");
    c.line("        for schema in variants:");
    c.line("            body += struct.pack(\"<I\", len(schema)) + b\"\".join(struct.pack(\"<I\", t) for t in schema)");
    c.line("        return _pad(body)");
    c.line("");
    c.line("");
    c.line("def record(kind, body):");
    c.line("    \"\"\"Frame one record.\"\"\"");
    c.line("    body = _pad(body)");
    c.line("    return struct.pack(\"<IHH\", 8 + len(body), kind, 0) + body");
    c.line("");

    // One packer per fixed-layout tx record; set_property gets one
    // helper per source arm.
    for r in spec.tx {
        if r.name == "set_property" || r.name == "set_window_prop" {
            continue;
        }
        let params = record_params(r);
        let names: Vec<String> = params.iter().map(|f| f.name.to_string()).collect();
        c.line("");
        c.line(&format!("def tx_{}({}):", r.name, names.join(", ")));
        c.line(&format!("    \"\"\"{}\"\"\"", r.doc.replace('\n', " ")));
        let mut parts: Vec<String> = Vec::new();
        for f in r.fields {
            parts.push(match f.ty {
                FieldTy::U32 if f.name == "reserved" => "struct.pack(\"<I\", 0)".into(),
                FieldTy::U32 => format!("struct.pack(\"<I\", {})", f.name),
                FieldTy::U64 => format!("struct.pack(\"<Q\", {})", f.name),
                FieldTy::Value => format!("_enc.value({})", f.name),
                FieldTy::Values => format!("_enc.values({})", f.name),
                FieldTy::VariantSchemas => format!("_enc.variant_schemas({})", f.name),
            });
        }
        let body = if parts.is_empty() {
            "b\"\"".to_string()
        } else {
            parts.join(" + ")
        };
        c.line(&format!("    return record(TX_{}, {})", r.name.to_uppercase(), body));
    }

    // The set_property trios, one per property: spec-driven so new
    // props reach every binding without emitter edits. Python's value
    // encoder is type-generic, so PropKind only shapes the docstring.
    for (prop, _, kind) in prop_variants(spec) {
        let up = prop.to_uppercase();
        // Blob setters speak the wire tier: the parameter is the u64
        // handle from kaya_blob_register (see BlobHandle), not bytes.
        let (param, ty, expr) = match kind {
            PropKind::Str => (*prop, "str", format!("_enc.value({prop})")),
            PropKind::Bool => (*prop, "bool", format!("_enc.value({prop})")),
            PropKind::F64 => (*prop, "float", format!("_enc.value({prop})")),
            PropKind::Enum(_) => (*prop, "int", format!("_enc.value(int({prop}))")),
            PropKind::Blob => (
                "handle",
                "a kaya_blob_register handle, consumed by the next submit",
                "_enc.value(BlobHandle(handle))".to_string(),
            ),
        };
        c.line("");
        c.line("");
        c.line(&format!("def tx_set_{prop}(widget_id, {param}):"));
        c.line(&format!("    \"\"\"set_property with a constant {prop} value ({ty}).\"\"\""));
        c.line(&format!("    return record(TX_SET_PROPERTY, struct.pack(\"<QII\", widget_id, PROP_{up}, SOURCE_CONST) + {expr})"));
        c.line("");
        c.line("");
        c.line(&format!("def tx_bind_{prop}(widget_id, signal_id):"));
        c.line(&format!("    \"\"\"set_property with a signal-bound {prop} value.\"\"\""));
        c.line(&format!("    return record(TX_SET_PROPERTY, struct.pack(\"<QIIQ\", widget_id, PROP_{up}, SOURCE_SIGNAL, signal_id))"));
        c.line("");
        c.line("");
        c.line(&format!("def tx_bind_{prop}_element(widget_id, level=0, field=0):"));
        c.line(&format!("    \"\"\"set_property bound to one field of the element of the enclosing For, `level` Fors up.\"\"\""));
        c.line(&format!("    return record(TX_SET_PROPERTY, struct.pack(\"<QIIII\", widget_id, PROP_{up}, SOURCE_ELEMENT, level, field))"));
    }

    // The window-prop duos (const + signal — element sources are
    // rejected by the wire; windows are not collection elements).
    // Window 0, the primary surface, until aux windows land.
    for (prop, _, kind) in window_prop_variants(spec) {
        let up = prop.to_uppercase();
        let (ty, expr) = match kind {
            PropKind::Str => ("str", format!("_enc.value({prop})")),
            PropKind::F64 => ("float", format!("_enc.value({prop})")),
            PropKind::Bool => ("bool", format!("_enc.value({prop})")),
            PropKind::Enum(_) => ("int", format!("_enc.value(int({prop}))")),
            other => unreachable!("no window prop carries {other:?}"),
        };
        c.line("");
        c.line("");
        c.line(&format!("def tx_set_window_{prop}(window, {prop}):"));
        c.line(&format!("    \"\"\"set_window_prop with a constant {prop} value ({ty}); window 0, the primary surface.\"\"\""));
        c.line(&format!("    return record(TX_SET_WINDOW_PROP, struct.pack(\"<QII\", window, WPROP_{up}, SOURCE_CONST) + {expr})"));
        c.line("");
        c.line("");
        c.line(&format!("def tx_bind_window_{prop}(window, signal_id):"));
        c.line(&format!("    \"\"\"set_window_prop with a signal-bound {prop} value; window 0, the primary surface.\"\"\""));
        c.line(&format!("    return record(TX_SET_WINDOW_PROP, struct.pack(\"<QIIQ\", window, WPROP_{up}, SOURCE_SIGNAL, signal_id))"));
    }

    // The entry-prop duos (const + signal), the window shape on the
    // navigation-entry table (DESIGN.md, Navigation).
    for (prop, _, kind) in crate::entry_prop_variants(spec) {
        let up = prop.to_uppercase();
        let (ty, expr) = match kind {
            PropKind::Str => ("str", format!("_enc.value({prop})")),
            PropKind::Bool => ("bool", format!("_enc.value({prop})")),
            other => unreachable!("no entry prop carries {other:?}"),
        };
        c.line("");
        c.line("");
        c.line(&format!("def tx_set_entry_{prop}(entry, {prop}):"));
        c.line(&format!("    \"\"\"set_entry_prop with a constant {prop} value ({ty}).\"\"\""));
        c.line(&format!("    return record(TX_SET_ENTRY_PROP, struct.pack(\"<QII\", entry, EPROP_{up}, SOURCE_CONST) + {expr})"));
        c.line("");
        c.line("");
        c.line(&format!("def tx_bind_entry_{prop}(entry, signal_id):"));
        c.line(&format!("    \"\"\"set_entry_prop with a signal-bound {prop} value.\"\"\""));
        c.line(&format!("    return record(TX_SET_ENTRY_PROP, struct.pack(\"<QIIQ\", entry, EPROP_{up}, SOURCE_SIGNAL, signal_id))"));
    }

    // The section-prop duos (const + signal), the entry shape on the
    // section table; icon rides the blob channel (DESIGN.md, Sections).
    for (prop, _, kind) in crate::section_prop_variants(spec) {
        let up = prop.to_uppercase();
        let (param, ty, expr) = match kind {
            PropKind::Str => (*prop, "str", format!("_enc.value({prop})")),
            PropKind::Blob => (
                "handle",
                "a kaya_blob_register handle, consumed by the next submit",
                "_enc.value(BlobHandle(handle))".to_string(),
            ),
            other => unreachable!("no section prop carries {other:?}"),
        };
        c.line("");
        c.line("");
        c.line(&format!("def tx_set_section_{prop}(section, {param}):"));
        c.line(&format!("    \"\"\"set_section_prop with a constant {prop} value ({ty}).\"\"\""));
        c.line(&format!("    return record(TX_SET_SECTION_PROP, struct.pack(\"<QII\", section, SPROP_{up}, SOURCE_CONST) + {expr})"));
        c.line("");
        c.line("");
        c.line(&format!("def tx_bind_section_{prop}(section, signal_id):"));
        c.line(&format!("    \"\"\"set_section_prop with a signal-bound {prop} value.\"\"\""));
        c.line(&format!("    return record(TX_SET_SECTION_PROP, struct.pack(\"<QIIQ\", section, SPROP_{up}, SOURCE_SIGNAL, signal_id))"));
    }

    // The one binding-tier shortcut parser (DESIGN.md, Menus): spelling
    // only — policy (escape, shift-only/bare alphanumerics, the
    // reserved floor) is the core's, validated on the canonical form.
    // tx_set_menu_shortcut routes through it, so no call site can
    // bypass canonicalization.
    let named_keys = crate::SHORTCUT_NAMED_KEYS
        .iter()
        .map(|k| format!("\"{k}\""))
        .collect::<Vec<_>>()
        .join(", ");
    c.line("");
    c.line("");
    c.line(&format!("_SHORTCUT_NAMED_KEYS = frozenset(({named_keys}))"));
    c.line("");
    c.line("");
    c.line("def canonicalize_shortcut(spelling):");
    c.line("    \"\"\"Canonicalize a shortcut spelling to the wire form: lowercase");
    c.line("    '+'-joined tokens, modifiers ordered primary, shift, alt, then one");
    c.line("    key (a-z, 0-9, or the closed named set). Accepts ASCII case");
    c.line("    variants and any modifier order; rejects whitespace, empty tokens,");
    c.line("    repeated modifiers, aliases (ctrl/cmd/option), and unknown or");
    c.line("    multiple or missing keys. POLICY stays at the core: escape,");
    c.line("    shift-only and bare alphanumerics, and the reserved floor are");
    c.line("    validated there, on the canonical spelling, never rewritten.\"\"\"");
    c.line("    if not spelling:");
    c.line("        raise ValueError(\"kaya: shortcut is empty\")");
    c.line("    if any(ch in spelling for ch in \" \\t\\n\\v\\f\\r\"):");
    c.line("        raise ValueError(f\"kaya: shortcut {spelling!r} contains whitespace\")");
    c.line("    parts = spelling.lower().split(\"+\")");
    c.line("    if any(not p for p in parts):");
    c.line("        raise ValueError(f\"kaya: shortcut {spelling!r} has an empty token\")");
    c.line("    mods, key = parts[:-1], parts[-1]");
    c.line("    seen = []");
    c.line("    for m in mods:");
    c.line("        if m not in (\"primary\", \"shift\", \"alt\"):");
    c.line("            raise ValueError(");
    c.line("                f\"kaya: shortcut {spelling!r} has an unknown modifier {m!r} \"");
    c.line("                \"(the portable modifiers are primary, shift, alt; aliases \"");
    c.line("                \"like ctrl, cmd, and option are not accepted)\")");
    c.line("        if m in seen:");
    c.line("            raise ValueError(f\"kaya: shortcut {spelling!r} repeats modifier {m!r}\")");
    c.line("        seen.append(m)");
    c.line("    alnum = len(key) == 1 and (\"a\" <= key <= \"z\" or \"0\" <= key <= \"9\")");
    c.line("    if not alnum and key not in _SHORTCUT_NAMED_KEYS:");
    c.line("        raise ValueError(");
    c.line("            f\"kaya: shortcut {spelling!r} key {key!r} is outside the floor \"");
    c.line("            \"(one of a-z, 0-9, or the closed named set)\")");
    c.line("    return \"+\".join([m for m in (\"primary\", \"shift\", \"alt\") if m in seen] + [key])");

    // The menu-prop setters (const for every prop; signal binders only
    // for the bindable ones — icon/primary/shortcut are const-only and
    // SOURCE_SIGNAL on them dies at the root).
    for (prop, _, kind) in crate::menu_prop_variants(spec) {
        let up = prop.to_uppercase();
        let (param, ty, expr) = match kind {
            PropKind::Str if *prop == "shortcut" => (
                *prop,
                "str, canonicalized here — the one binding-tier shortcut parser",
                format!("_enc.value(canonicalize_shortcut({prop}))"),
            ),
            PropKind::Str => (*prop, "str", format!("_enc.value({prop})")),
            PropKind::Bool => (*prop, "bool", format!("_enc.value({prop})")),
            PropKind::F64 => (*prop, "float", format!("_enc.value({prop})")),
            PropKind::Blob => (
                "handle",
                "a kaya_blob_register handle, consumed by the next submit",
                "_enc.value(BlobHandle(handle))".to_string(),
            ),
            other => unreachable!("no menu prop carries {other:?}"),
        };
        c.line("");
        c.line("");
        c.line(&format!("def tx_set_menu_{prop}(item, {param}):"));
        c.line(&format!("    \"\"\"set_menu_prop with a constant {prop} value ({ty}).\"\"\""));
        c.line(&format!("    return record(TX_SET_MENU_PROP, struct.pack(\"<QII\", item, MPROP_{up}, SOURCE_CONST) + {expr})"));
        if crate::menu_prop_bindable(prop) {
            c.line("");
            c.line("");
            c.line(&format!("def tx_bind_menu_{prop}(item, signal_id):"));
            c.line(&format!("    \"\"\"set_menu_prop with a signal-bound {prop} value.\"\"\""));
            c.line(&format!("    return record(TX_SET_MENU_PROP, struct.pack(\"<QIIQ\", item, MPROP_{up}, SOURCE_SIGNAL, signal_id))"));
        }
    }
    c.line("");
    c.line("");
    c.line("def parse_value(buf, at):");
    c.line("    \"\"\"Decode one value; returns (python value, next offset).\"\"\"");
    c.line("    vtype, vlen = struct.unpack_from(\"<II\", buf, at)");
    c.line("    payload = buf[at + 8:at + 8 + vlen]");
    c.line("    end = at + 8 + ((vlen + 7) & ~7)");
    c.line("    if vtype == VALUE_BOOL:");
    c.line("        return payload[0] != 0, end");
    c.line("    if vtype == VALUE_I64:");
    c.line("        return struct.unpack(\"<q\", payload)[0], end");
    c.line("    if vtype == VALUE_F64:");
    c.line("        return struct.unpack(\"<d\", payload)[0], end");
    c.line("    if vtype == VALUE_STR:");
    c.line("        return payload.decode(), end");
    c.line("    if vtype == VALUE_BLOB:");
    c.line("        return BlobHandle(struct.unpack(\"<Q\", payload)[0]), end");
    c.line("    raise ValueError(f\"unknown value type {vtype}\")");
    c.line("");
    c.line("");
    // The occurrence blob table, the third direction. A blob in an
    // OCCURRENCE is a table handle, not the apply channel's batch-local
    // index: the occurrence channel has no boundary that retires one
    // (the guest takes records one at a time, and the direct-ring
    // consumers move the head themselves), so it is released
    // explicitly. Redeeming HERE, in the generated decoder, is what
    // keeps a handle from ever reaching an app — a released handle is
    // not something a guest should be able to hold.
    c.line("occurrence_blob = None");
    c.line("\"\"\"Redeem-and-release for occurrence blobs, installed by the runtime");
    c.line("at import (this module loads no library of its own).\"\"\"");
    c.line("");
    c.line("");
    c.line("def parse_clip(buf, at):");
    c.line("    \"\"\"Decode one representation: the clip kind, then its values.");
    c.line("");
    c.line("    Returns (clip, values, next offset). `clip` is a SINGLE member");
    c.line("    of the clip enum and never a mask — you offer many and you");
    c.line("    receive one — and 0 with no values is the universal empty");
    c.line("    answer. Blobs are redeemed to bytes and released here.\"\"\"");
    c.line("    clip, _reserved, count, _pad = struct.unpack_from(\"<IIII\", buf, at)");
    c.line("    at += 16");
    c.line("    values = []");
    c.line("    for _ in range(count):");
    c.line("        value, at = parse_value(buf, at)");
    c.line("        if isinstance(value, BlobHandle):");
    c.line("            value = occurrence_blob(value.handle)");
    c.line("        values.append(value)");
    c.line("    return clip, values, at");
    c.line("");
    c.line("");
    c.line("def parse_occurrence(buf):");
    c.line("    \"\"\"Decode one occurrence record (header included).");
    c.line("");
    c.line("    Returns (kind, id, keys, payload). keys is [] when id is a");
    c.line("    widget id, else id is a template node id and keys is the");
    c.line("    copy's key path. text is the entry's new content for");
    c.line("    OCC_TEXT_CHANGED, the new state for OCC_TOGGLED, the new");
    c.line("    value for OCC_VALUE_CHANGED, None otherwise.");
    // (kind lists below derive from the spec's Record::payload.)
    c.line("    \"\"\"");
    c.line("    _size, kind, _flags = struct.unpack_from(\"<IHH\", buf, 0)");
    let accepted = crate::occurrence_names(spec)
        .iter()
        .map(|n| format!("OCC_{}", n.to_uppercase()))
        .collect::<Vec<_>>()
        .join(", ");
    c.line(&format!("    if kind not in ({accepted}):"));
    c.line("        return kind, None, [], None");
        c.line("    if kind == OCC_ALERT_RESULT:");
    c.line("        # The alert's one answer: id + u32 choice (ALERT_CHOICE_*).");
    c.line("        alert, choice = struct.unpack_from(\"<QI\", buf, 8)");
    c.line("        return kind, alert, [], choice");
    // The picker's answer is the one occurrence whose payload is a
    // LIST OF RECORDS rather than a scalar: dialog id, a count, then
    // three Values per file (handle, name, local_path). The generic
    // tail below reads a KEY PATH, which would take the count as a
    // path length and start reading eight bytes early — decoding a
    // handle as a key and losing the rest. Hence its own arm.
    //
    // EMPTY IS CANCEL, and it arrives here as count 0, so the arm has
    // nothing special to say about it.
    c.line("    if kind == OCC_FILE_DIALOG_RESULT:");
    c.line("        dialog, count = struct.unpack_from(\"<QI\", buf, 8)");
    c.line("        at = 32  # past dialog, count, pad, values count, reserved");
    c.line("        files = []");
    c.line("        for _ in range(count):");
    c.line("            handle, at = parse_value(buf, at)");
    c.line("            name, at = parse_value(buf, at)");
    c.line("            local_path, at = parse_value(buf, at)");
    c.line("            files.append((handle, name, local_path))");
    c.line("        return kind, dialog, [], files");
    // The privileged read's one answer: a request id, then the clip.
    // Its own arm for the file_dialog_result reason and then some — the
    // generic tail would take the CLIP KIND for a path length, so a
    // text answer (clip 1) would read the values header as a key.
    for name in crate::clip_answer_occurrence_names(spec) {
        c.line(&format!("    if kind == OCC_{}:", name.to_uppercase()));
        c.line("        (request,) = struct.unpack_from(\"<Q\", buf, 8)");
        c.line("        clip, values, _at = parse_clip(buf, 16)");
        c.line("        return kind, request, [], (clip, values)");
    }
    let id_only = crate::id_only_occurrence_names(spec)
        .iter()
        .map(|n| format!("OCC_{}", n.to_uppercase()))
        .collect::<Vec<_>>()
        .join(", ");
    c.line(&format!("    if kind in ({id_only}):"));
    c.line("        # Surface lifecycle records carry the surface id alone —");
    c.line("        # no key path, no payload (derived from the record shapes).");
    c.line("        (surface_id,) = struct.unpack_from(\"<Q\", buf, 8)");
    c.line("        return kind, surface_id, [], None");
    let id_pair = crate::id_pair_occurrence_names(spec)
        .iter()
        .map(|n| format!("OCC_{}", n.to_uppercase()))
        .collect::<Vec<_>>()
        .join(", ");
    if !id_pair.is_empty() {
        c.line(&format!("    if kind in ({id_pair},):"));
        c.line("        # Surface-pair records (window, section): the SECOND id");
        c.line("        # keys the handler (they scope to the section); the");
        c.line("        # first rides as the payload.");
        c.line("        window, section = struct.unpack_from(\"<QQ\", buf, 8)");
        c.line("        return kind, section, [], window");
    }
    // ONE STEP CAME BACK. The payload is a STATEMENT OF THE RESTORED
    // STATE rather than a replay of ops: four counted runs cut out of
    // one flat Values tail, in the fixed order signals, texts, entries,
    // orders (docs/undo-plan.md D5; wire::undo_body). Its own arm for
    // the file_dialog_result reason — the generic tail below would take
    // `window` for a widget id and the SIGNAL COUNT for a key-path
    // length, and read the label's bytes as keys.
    let undo = crate::undo_occurrence_names(spec)
        .iter()
        .map(|n| format!("OCC_{}", n.to_uppercase()))
        .collect::<Vec<_>>()
        .join(", ");
    if !undo.is_empty() {
        c.line(&format!("    if kind in ({undo},):"));
        c.line("        # One undone/redone step: the window, four run");
        c.line("        # lengths, the group's label, then ONE flat values");
        c.line("        # tail the runs cut up — signals, texts, entries,");
        c.line("        # orders, in that order. The payload is the whole");
        c.line("        # RESTORED STATE, never a replay of ops.");
        c.line("        window, n_signals, n_texts, n_entries, n_orders = \\");
        c.line("            struct.unpack_from(\"<QIIII\", buf, 8)");
        c.line("        at = 32");
        c.line("        label, at = parse_value(buf, at)");
        c.line("        count, _reserved = struct.unpack_from(\"<II\", buf, at)");
        c.line("        at += 8");
        c.line("        flat = []");
        c.line("        for _ in range(count):");
        c.line("            value, at = parse_value(buf, at)");
        c.line("            flat.append(value)");
        c.line("        i = 0");
        c.line("        signals = []");
        c.line("        for _ in range(n_signals):");
        c.line("            signals.append((flat[i], flat[i + 1]))");
        c.line("            i += 2");
        // ARITY-FIRST LIKE ITS TWO NEIGHBOURS, and for their reason:
        // a stamped copy's field is named by (template node, key path),
        // and a fixed pair had nowhere to put the path. path_len 0 means
        // the id is a live widget id.
        c.line("        texts = []");
        c.line("        for _ in range(n_texts):");
        c.line("            size, ident, path_len = flat[i:i + 3]");
        c.line("            body = flat[i + 3:i + size]");
        c.line("            i += size");
        c.line("            texts.append((ident, tuple(body[:path_len]), body[path_len]))");
        // Arity-first, so each group carries its own size and a reader
        // needs nothing else: 5 fixed values, then the instance path,
        // the key, and the record — `size` counts itself.
        c.line("        entries = []");
        c.line("        # Arity-first groups: `size` counts itself, so a");
        c.line("        # reader takes it and needs nothing else.");
        c.line("        for _ in range(n_entries):");
        c.line("            size, coll, present, variant, path_len = flat[i:i + 5]");
        c.line("            body = flat[i + 5:i + size]");
        c.line("            i += size");
        c.line("            state = (variant, body[path_len + 1:]) if present else None");
        c.line("            entries.append((coll, tuple(body[:path_len]), body[path_len], state))");
        c.line("        orders = []");
        c.line("        for _ in range(n_orders):");
        c.line("            size, coll, path_len = flat[i:i + 3]");
        c.line("            body = flat[i + 3:i + size]");
        c.line("            i += size");
        c.line("            orders.append((coll, tuple(body[:path_len]), body[path_len:]))");
        // A truncated or over-long body is a broken ENCODER, not bad
        // input, and it fails here rather than handing the app half a
        // step (the read-in-threes rule the picker already follows).
        c.line("        if i != len(flat):");
        c.line("            raise ValueError(\"kaya: undo delta has trailing values\")");
        c.line("        return kind, window, [], (label, signals, texts, entries, orders)");
    }
    c.line("    ident, path_len = struct.unpack_from(\"<QI\", buf, 8)");
    c.line("    keys = []");
    c.line("    at = 24");
    c.line("    for _ in range(path_len):");
    c.line("        key, at = parse_value(buf, at)");
    c.line("        keys.append(key)");
    c.line("    payload = None");
    let with_payload = crate::payload_occurrence_names(spec)
        .iter()
        .map(|n| format!("OCC_{}", n.to_uppercase()))
        .collect::<Vec<_>>()
        .join(", ");
    c.line(&format!("    if kind in ({with_payload},):"));
    c.line("        payload, at = parse_value(buf, at)");
    // A paste rides a click tag VERBATIM, so the key path above is
    // already read and the clip sits after it — the way text_changed's
    // payload does. One record kind, path_len deciding, exactly as a
    // click on a stamped row is the same record as one on a live widget.
    let pasted = crate::pasted_occurrence_names(spec)
        .iter()
        .map(|n| format!("OCC_{}", n.to_uppercase()))
        .collect::<Vec<_>>()
        .join(", ");
    if !pasted.is_empty() {
        c.line(&format!("    if kind in ({pasted},):"));
        c.line("        clip, values, at = parse_clip(buf, at)");
        c.line("        payload = (clip, values)");
    }
    c.line("    return kind, ident, keys, payload");

    c.out
}
