//! Swift emitter: a KayaTx struct of mutating packers over a Data
//! buffer, a KayaValue enum, and the occurrence parser. Struct and enum
//! scope namespace everything; the encoder methods live on KayaTx, so
//! parameters cannot shadow them (method calls are self-qualified).
//! Constants come from kaya.h via the bridging header.

use kaya::spec::{FieldTy, ProtocolSpec, Record};

use crate::{Ctx, prop_variants, record_params};

pub const RESERVED: &[&str] = &[
    "associatedtype", "class", "deinit", "enum", "extension", "fileprivate", "func", "import",
    "init", "inout", "internal", "let", "open", "operator", "private", "protocol", "public",
    "rethrows", "static", "struct", "subscript", "typealias", "var", "break", "case",
    "continue", "default", "defer", "do", "else", "fallthrough", "for", "guard", "if", "in",
    "repeat", "return", "switch", "where", "while",
];

fn camel(name: &str) -> String {
    let mut parts = name.split('_');
    let mut out = parts.next().unwrap_or_default().to_string();
    for w in parts {
        let mut chars = w.chars();
        if let Some(first) = chars.next() {
            out.push_str(&first.to_uppercase().collect::<String>());
            out.push_str(chars.as_str());
        }
    }
    out
}

fn pascal(name: &str) -> String {
    let c = camel(name);
    let mut chars = c.chars();
    match chars.next() {
        Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    }
}

pub fn emit(spec: &ProtocolSpec) -> String {
    let mut c = Ctx { out: String::new() };
    c.line("// kaya wire vocabulary. Generated by kaya-bindgen from kaya::spec — do not edit.");
    c.line("//");
    c.line("// Records are {u32 size, u16 kind, u16 flags}, body, padded to 8,");
    c.line("// little-endian. Constants come from kaya.h via the bridging header.");
    c.line("");
    c.line("import Foundation");
    c.line("");
    c.line("enum KayaValue: Equatable {");
    c.line("    case bool(Bool)");
    c.line("    case i64(Int64)");
    c.line("    case f64(Double)");
    c.line("    case str(String)");
    c.line("}");
    c.line("");
    c.line("/// A transaction under construction: packed records accumulate in");
    c.line("/// `bytes`; submit with kaya_submit.");
    c.line("struct KayaTx {");
    c.line("    var bytes = Data()");
    c.line("");
    c.line("    mutating func u16(_ v: UInt16) {");
    c.line("        withUnsafeBytes(of: v.littleEndian) { bytes.append(contentsOf: $0) }");
    c.line("    }");
    c.line("");
    c.line("    mutating func u32(_ v: UInt32) {");
    c.line("        withUnsafeBytes(of: v.littleEndian) { bytes.append(contentsOf: $0) }");
    c.line("    }");
    c.line("");
    c.line("    mutating func u64(_ v: UInt64) {");
    c.line("        withUnsafeBytes(of: v.littleEndian) { bytes.append(contentsOf: $0) }");
    c.line("    }");
    c.line("");
    c.line("    mutating func pad() {");
    c.line("        while bytes.count % 8 != 0 { bytes.append(0) }");
    c.line("    }");
    c.line("");
    c.line("    /// Values self-pad to 8: they concatenate inside record bodies.");
    c.line("    mutating func value(_ v: KayaValue) {");
    c.line("        switch v {");
    c.line("        case .bool(let x):");
    c.line("            u32(UInt32(KAYA_VALUE_BOOL))");
    c.line("            u32(1)");
    c.line("            bytes.append(x ? 1 : 0)");
    c.line("        case .i64(let x):");
    c.line("            u32(UInt32(KAYA_VALUE_I64))");
    c.line("            u32(8)");
    c.line("            u64(UInt64(bitPattern: x))");
    c.line("        case .f64(let x):");
    c.line("            u32(UInt32(KAYA_VALUE_F64))");
    c.line("            u32(8)");
    c.line("            u64(x.bitPattern)");
    c.line("        case .str(let x):");
    c.line("            let utf8 = Array(x.utf8)");
    c.line("            u32(UInt32(KAYA_VALUE_STR))");
    c.line("            u32(UInt32(utf8.count))");
    c.line("            bytes.append(contentsOf: utf8)");
    c.line("        }");
    c.line("        pad()");
    c.line("    }");
    c.line("");
    c.line("    /// A key path: {u32 count, u32 reserved, count values}.");
    c.line("    mutating func path(_ keys: [KayaValue]) {");
    c.line("        u32(UInt32(keys.count))");
    c.line("        u32(0)");
    c.line("        for key in keys { value(key) }");
    c.line("    }");
    c.line("");
    c.line("    mutating func begin(_ kind: UInt16) -> Int {");
    c.line("        let start = bytes.count");
    c.line("        u32(0)");
    c.line("        u16(kind)");
    c.line("        u16(0)");
    c.line("        return start");
    c.line("    }");
    c.line("");
    c.line("    mutating func end(_ start: Int) {");
    c.line("        pad()");
    c.line("        let size = UInt32(bytes.count - start).littleEndian");
    c.line("        withUnsafeBytes(of: size) {");
    c.line("            bytes.replaceSubrange(start..<start + 4, with: $0)");
    c.line("        }");
    c.line("    }");

    for r in spec.tx {
        if r.name == "set_property" {
            continue;
        }
        emit_packer(&mut c, r);
    }

    // The set_property arms, one trio per property: spec-driven so new
    // props reach every binding without emitter edits.
    for (prop, _) in prop_variants(spec) {
        let p = camel(prop);
        let pc = pascal(prop);
        let up = prop.to_uppercase();
        c.line("");
        c.line(&format!("    /// set_property with a constant {prop} value."));
        c.line(&format!("    mutating func set{pc}(_ widgetId: UInt64, _ {p}: String) {{"));
        c.line("        let start = self.begin(UInt16(KAYA_TX_SET_PROPERTY))");
        c.line("        self.u64(widgetId)");
        c.line(&format!("        self.u32(UInt32(KAYA_PROP_{up}))"));
        c.line("        self.u32(UInt32(KAYA_SOURCE_CONST))");
        c.line(&format!("        self.value(.str({p}))"));
        c.line("        self.end(start)");
        c.line("    }");
        c.line("");
        c.line(&format!("    /// set_property with a signal-bound {prop} value."));
        c.line(&format!("    mutating func bind{pc}(_ widgetId: UInt64, _ signalId: UInt64) {{"));
        c.line("        let start = self.begin(UInt16(KAYA_TX_SET_PROPERTY))");
        c.line("        self.u64(widgetId)");
        c.line(&format!("        self.u32(UInt32(KAYA_PROP_{up}))"));
        c.line("        self.u32(UInt32(KAYA_SOURCE_SIGNAL))");
        c.line("        self.u64(signalId)");
        c.line("        self.end(start)");
        c.line("    }");
        c.line("");
        c.line("    /// set_property bound to the element of the enclosing For,");
        c.line("    /// `level` Fors up (0 = nearest).");
        c.line(&format!("    mutating func bind{pc}Element(_ widgetId: UInt64, level: UInt32 = 0) {{"));
        c.line("        let start = self.begin(UInt16(KAYA_TX_SET_PROPERTY))");
        c.line("        self.u64(widgetId)");
        c.line(&format!("        self.u32(UInt32(KAYA_PROP_{up}))"));
        c.line("        self.u32(UInt32(KAYA_SOURCE_ELEMENT))");
        c.line("        self.u32(level)");
        c.line("        self.u32(0)");
        c.line("        self.end(start)");
        c.line("    }");
    }
    c.line("");
    c.line("    func submit() {");
    c.line("        bytes.withUnsafeBytes { raw in");
    c.line("            kaya_submit(raw.bindMemory(to: UInt8.self).baseAddress, UInt(raw.count))");
    c.line("        }");
    c.line("    }");
    c.line("}");
    c.line("");
    c.line("/// Decode one occurrence record (header included); nil for pad or");
    c.line("/// unknown kinds. keys is [] when id is a widget id; otherwise id is");
    c.line("/// a template node id and keys is the copy's key path, outermost");
    c.line("/// first. text is the entry's new content for TEXT_CHANGED, nil for");
    c.line("/// clicks.");
    c.line("func kayaParseOccurrence(_ rec: [UInt8])");
    c.line("    -> (kind: UInt16, id: UInt64, keys: [KayaValue], text: String?)?");
    c.line("{");
    c.line("    rec.withUnsafeBytes { raw in");
    c.line("        let kind = raw.loadUnaligned(fromByteOffset: 4, as: UInt16.self)");
    c.line("        guard kind == UInt16(KAYA_OCCURRENCE_BUTTON_CLICKED)");
    c.line("            || kind == UInt16(KAYA_OCCURRENCE_TEXT_CHANGED)");
    c.line("        else { return nil }");
    c.line("        let id = raw.loadUnaligned(fromByteOffset: 8, as: UInt64.self)");
    c.line("        let pathLen = raw.loadUnaligned(fromByteOffset: 16, as: UInt32.self)");
    c.line("        var keys: [KayaValue] = []");
    c.line("        var at = 24");
    c.line("        for _ in 0..<pathLen {");
    c.line("            let vtype = raw.loadUnaligned(fromByteOffset: at, as: UInt32.self)");
    c.line("            let vlen = Int(raw.loadUnaligned(fromByteOffset: at + 4, as: UInt32.self))");
    c.line("            switch vtype {");
    c.line("            case UInt32(KAYA_VALUE_BOOL):");
    c.line("                keys.append(.bool(raw[at + 8] != 0))");
    c.line("            case UInt32(KAYA_VALUE_I64):");
    c.line("                keys.append(.i64(Int64(bitPattern:");
    c.line("                    raw.loadUnaligned(fromByteOffset: at + 8, as: UInt64.self))))");
    c.line("            case UInt32(KAYA_VALUE_F64):");
    c.line("                keys.append(.f64(Double(bitPattern:");
    c.line("                    raw.loadUnaligned(fromByteOffset: at + 8, as: UInt64.self))))");
    c.line("            default:");
    c.line("                keys.append(.str(String(");
    c.line("                    decoding: raw[(at + 8)..<(at + 8 + vlen)], as: UTF8.self)))");
    c.line("            }");
    c.line("            at += 8 + ((vlen + 7) & ~7)");
    c.line("        }");
    c.line("        var text: String? = nil");
    c.line("        if kind == UInt16(KAYA_OCCURRENCE_TEXT_CHANGED) {");
    c.line("            let vlen = Int(raw.loadUnaligned(fromByteOffset: at + 4, as: UInt32.self))");
    c.line("            text = String(decoding: raw[(at + 8)..<(at + 8 + vlen)], as: UTF8.self)");
    c.line("        }");
    c.line("        return (kind, id, keys, text)");
    c.line("    }");
    c.line("}");
    c.out
}

fn emit_packer(c: &mut Ctx, r: &Record) {
    let params = record_params(r);
    let mut sig: Vec<String> = Vec::new();
    for f in &params {
        sig.push(match f.ty {
            FieldTy::U32 => format!("_ {}: UInt32", camel(f.name)),
            FieldTy::U64 => format!("_ {}: UInt64", camel(f.name)),
            FieldTy::Value => format!("_ {}: KayaValue", camel(f.name)),
            FieldTy::Path => format!("_ {}: [KayaValue]", camel(f.name)),
        });
    }
    c.line("");
    c.line(&format!("    /// {}", r.doc.replace('\n', " ")));
    c.line(&format!(
        "    mutating func {}({}) {{",
        camel(r.name),
        sig.join(", ")
    ));
    c.line(&format!(
        "        let start = self.begin(UInt16(KAYA_TX_{}))",
        r.name.to_uppercase()
    ));
    for f in r.fields {
        c.line(&match f.ty {
            FieldTy::U32 if f.name == "reserved" => "        self.u32(0)".into(),
            FieldTy::U32 => format!("        self.u32({})", camel(f.name)),
            FieldTy::U64 => format!("        self.u64({})", camel(f.name)),
            FieldTy::Value => format!("        self.value({})", camel(f.name)),
            FieldTy::Path => format!("        self.path({})", camel(f.name)),
        });
    }
    c.line("        self.end(start)");
    c.line("    }");
}
