//! Swift emitter: a KayaTx struct of mutating packers over a Data
//! buffer, a KayaValue enum, and the occurrence parser. Struct and enum
//! scope namespace everything; the encoder methods live on KayaTx, so
//! parameters cannot shadow them (method calls are self-qualified).
//! Constants come from kaya.h via the bridging header.

use kaya::spec::{FieldTy, ProtocolSpec, Record};

use crate::{Ctx, is_padding, prop_variants, record_params, window_prop_variants};

pub const RESERVED: &[&str] = &[
    "associatedtype", "class", "deinit", "enum", "extension", "fileprivate", "func", "import",
    "init", "inout", "internal", "let", "open", "operator", "private", "protocol", "public",
    "rethrows", "static", "struct", "subscript", "typealias", "var", "break", "case",
    "continue", "default", "defer", "do", "else", "fallthrough", "for", "guard", "if", "in",
    "repeat", "return", "switch", "where", "while",
    // NOT A KEYWORD — a local this generator EMITS. A record helper
    // opens with `let kayaAt = self.begin(...)`, so a spec field of the
    // same name would be shadowed inside its own helper and the record
    // would carry the buffer offset where the field's value belongs.
    // That is not hypothetical: the field was called `start` for about
    // an hour, and `self.u64(start)` cheerfully wrote the record offset
    // (the C generator had the same local and at least failed to
    // compile). The local is kaya-prefixed so nothing an author writes
    // can reach it, and it is named here so the generator refuses if
    // anyone tries.
    "kayaAt",
];

fn camel(name: &str) -> String {
    let mut parts = name.split('_');
    let mut out = parts.next().unwrap_or_default().to_string();
    for w in parts {
        let mut chars = w.chars();
        if let Some(first) = chars.next() {
            out.push_str(&first.to_uppercase().collect::<String>());
            out.push_str(chars.as_str());
        }
    }
    out
}

fn pascal(name: &str) -> String {
    let c = camel(name);
    let mut chars = c.chars();
    match chars.next() {
        Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    }
}

pub fn emit(spec: &ProtocolSpec) -> String {
    let mut c = Ctx { out: String::new() };
    c.line("// kaya wire vocabulary. Generated by kaya-bindgen from kaya::spec — do not edit.");
    c.line("//");
    c.line("// Records are {u32 size, u16 kind, u16 flags}, body, padded to 8,");
    c.line("// little-endian. Constants come from kaya.h via the bridging header.");
    c.line("");
    c.line("import Foundation");
    c.line("");
    c.line("enum KayaValue: Hashable {");
    c.line("    case bool(Bool)");
    c.line("    case i64(Int64)");
    c.line("    case f64(Double)");
    c.line("    case str(String)");
    c.line("    /// The u64 handle from kaya_blob_register, consumed by the next");
    c.line("    /// submit; the bytes never ride the record stream.");
    c.line("    case blob(UInt64)");
    c.line("}");
    c.line("");
    c.line("/// A transaction under construction: packed records accumulate in");
    c.line("/// `bytes`; submit with kaya_submit.");
    c.line("/// kayaSpecHash: the protocol fingerprint; the runtime asserts the loaded core agrees.");
    c.line(&format!("let kayaSpecHash: UInt64 = 0x{:016x}", crate::spec_hash()));
    c.line("");
    c.line("struct KayaTx {");
    c.line("    var bytes = Data()");
    c.line("");
    c.line("    mutating func u16(_ v: UInt16) {");
    c.line("        withUnsafeBytes(of: v.littleEndian) { bytes.append(contentsOf: $0) }");
    c.line("    }");
    c.line("");
    c.line("    mutating func u32(_ v: UInt32) {");
    c.line("        withUnsafeBytes(of: v.littleEndian) { bytes.append(contentsOf: $0) }");
    c.line("    }");
    c.line("");
    c.line("    mutating func u64(_ v: UInt64) {");
    c.line("        withUnsafeBytes(of: v.littleEndian) { bytes.append(contentsOf: $0) }");
    c.line("    }");
    c.line("");
    c.line("    mutating func pad() {");
    c.line("        while bytes.count % 8 != 0 { bytes.append(0) }");
    c.line("    }");
    c.line("");
    c.line("    /// Values self-pad to 8: they concatenate inside record bodies.");
    c.line("    mutating func value(_ v: KayaValue) {");
    c.line("        switch v {");
    c.line("        case .bool(let x):");
    c.line("            u32(UInt32(KAYA_VALUE_BOOL))");
    c.line("            u32(1)");
    c.line("            bytes.append(x ? 1 : 0)");
    c.line("        case .i64(let x):");
    c.line("            u32(UInt32(KAYA_VALUE_I64))");
    c.line("            u32(8)");
    c.line("            u64(UInt64(bitPattern: x))");
    c.line("        case .f64(let x):");
    c.line("            u32(UInt32(KAYA_VALUE_F64))");
    c.line("            u32(8)");
    c.line("            u64(x.bitPattern)");
    c.line("        case .str(let x):");
    c.line("            let utf8 = Array(x.utf8)");
    c.line("            u32(UInt32(KAYA_VALUE_STR))");
    c.line("            u32(UInt32(utf8.count))");
    c.line("            bytes.append(contentsOf: utf8)");
    c.line("        case .blob(let x):");
    c.line("            u32(UInt32(KAYA_VALUE_BLOB))");
    c.line("            u32(8)");
    c.line("            u64(x)");
    c.line("        }");
    c.line("        pad()");
    c.line("    }");
    c.line("");
    c.line("    /// A key path: {u32 count, u32 reserved, count values}.");
    c.line("    /// A counted value sequence — a key path or a record.");
    c.line("    mutating func values(_ vals: [KayaValue]) {");
    c.line("        u32(UInt32(vals.count))");
    c.line("        u32(0)");
    c.line("        for v in vals { value(v) }");
    c.line("    }");
    c.line("");
    c.line("    /// A collection's element sum: per variant, counted KAYA_VALUE_*");
    c.line("    /// tags, padded to 8. A record collection is the one-variant case.");
    c.line("    mutating func variantSchemas(_ variants: [[UInt32]]) {");
    c.line("        u32(UInt32(variants.count))");
    c.line("        u32(0)");
    c.line("        for schema in variants {");
    c.line("            u32(UInt32(schema.count))");
    c.line("            for t in schema { u32(t) }");
    c.line("        }");
    c.line("        while bytes.count % 8 != 0 { bytes.append(0) }");
    c.line("    }");
    c.line("");
    c.line("    mutating func begin(_ kind: UInt16) -> Int {");
    c.line("        let start = bytes.count");
    c.line("        u32(0)");
    c.line("        u16(kind)");
    c.line("        u16(0)");
    c.line("        return start");
    c.line("    }");
    c.line("");
    c.line("    mutating func end(_ start: Int) {");
    c.line("        pad()");
    c.line("        let size = UInt32(bytes.count - start).littleEndian");
    c.line("        withUnsafeBytes(of: size) {");
    c.line("            bytes.replaceSubrange(start..<start + 4, with: $0)");
    c.line("        }");
    c.line("    }");

    for r in spec.tx {
        if r.name == "set_property" || r.name == "set_window_prop" {
            continue;
        }
        emit_packer(&mut c, r);
    }

    // The set_property arms, one trio per property, spec-driven.
    for (prop, _, kind) in prop_variants(spec) {
        let pc = pascal(prop);
        let up = prop.to_uppercase();
        // Blob setters take the u64 kaya_blob_register handle (KayaValue.blob).
        let (p, ty, ctor) = match kind {
            crate::PropKind::Str => (camel(prop), "String", "str"),
            crate::PropKind::Bool => (camel(prop), "Bool", "bool"),
            crate::PropKind::F64 => (camel(prop), "Double", "f64"),
            crate::PropKind::Blob => ("handle".to_string(), "UInt64", "blob"),
            crate::PropKind::Enum(_) => (camel(prop), "Int64", "i64"),
        };
        c.line("");
        c.line(&format!("    /// set_property with a constant {prop} value."));
        c.line(&format!("    mutating func set{pc}(_ widgetId: UInt64, _ {p}: {ty}) {{"));
        c.line("        let kayaAt = self.begin(UInt16(KAYA_TX_SET_PROPERTY))");
        c.line("        self.u64(widgetId)");
        c.line(&format!("        self.u32(UInt32(KAYA_PROP_{up}))"));
        c.line("        self.u32(UInt32(KAYA_SOURCE_CONST))");
        c.line(&format!("        self.value(.{ctor}({p}))"));
        c.line("        self.end(kayaAt)");
        c.line("    }");
        c.line("");
        c.line(&format!("    /// set_property with a signal-bound {prop} value."));
        c.line(&format!("    mutating func bind{pc}(_ widgetId: UInt64, _ signalId: UInt64) {{"));
        c.line("        let kayaAt = self.begin(UInt16(KAYA_TX_SET_PROPERTY))");
        c.line("        self.u64(widgetId)");
        c.line(&format!("        self.u32(UInt32(KAYA_PROP_{up}))"));
        c.line("        self.u32(UInt32(KAYA_SOURCE_SIGNAL))");
        c.line("        self.u64(signalId)");
        c.line("        self.end(kayaAt)");
        c.line("    }");
        c.line("");
        c.line("    /// set_property bound to one field of the element of the");
        c.line("    /// enclosing For, `level` Fors up (0 = nearest).");
        c.line(&format!("    mutating func bind{pc}Element(_ widgetId: UInt64, level: UInt32 = 0, field: UInt32 = 0) {{"));
        c.line("        let kayaAt = self.begin(UInt16(KAYA_TX_SET_PROPERTY))");
        c.line("        self.u64(widgetId)");
        c.line(&format!("        self.u32(UInt32(KAYA_PROP_{up}))"));
        c.line("        self.u32(UInt32(KAYA_SOURCE_ELEMENT))");
        c.line("        self.u32(level)");
        c.line("        self.u32(field)");
        c.line("        self.end(kayaAt)");
        c.line("    }");
    }

    // The window-prop duos: const + signal, element sources being
    // rejected by the wire.
    for (prop, _, kind) in window_prop_variants(spec) {
        let pc = pascal(prop);
        let up = prop.to_uppercase();
        let (p, ty, ctor) = match kind {
            crate::PropKind::Str => (camel(prop), "String", "str"),
            crate::PropKind::F64 => (camel(prop), "Double", "f64"),
            crate::PropKind::Bool => (camel(prop), "Bool", "bool"),
            crate::PropKind::Enum(_) => (camel(prop), "Int64", "i64"),
            other => unreachable!("no window prop carries {other:?}"),
        };
        c.line("");
        c.line(&format!("    /// set_window_prop with a constant {prop} value (window 0, the primary surface)."));
        c.line(&format!("    mutating func setWindow{pc}(_ window: UInt64, _ {p}: {ty}) {{"));
        c.line("        let kayaAt = self.begin(UInt16(KAYA_TX_SET_WINDOW_PROP))");
        c.line("        self.u64(window)");
        c.line(&format!("        self.u32(UInt32(KAYA_WPROP_{up}))"));
        c.line("        self.u32(UInt32(KAYA_SOURCE_CONST))");
        c.line(&format!("        self.value(.{ctor}({p}))"));
        c.line("        self.end(kayaAt)");
        c.line("    }");
        c.line("");
        c.line(&format!("    /// set_window_prop with a signal-bound {prop} value (window 0, the primary surface)."));
        c.line(&format!("    mutating func bindWindow{pc}(_ window: UInt64, _ signalId: UInt64) {{"));
        c.line("        let kayaAt = self.begin(UInt16(KAYA_TX_SET_WINDOW_PROP))");
        c.line("        self.u64(window)");
        c.line(&format!("        self.u32(UInt32(KAYA_WPROP_{up}))"));
        c.line("        self.u32(UInt32(KAYA_SOURCE_SIGNAL))");
        c.line("        self.u64(signalId)");
        c.line("        self.end(kayaAt)");
        c.line("    }");
    }

    // The entry-prop duos (const + signal), the window shape on the
    // navigation-entry table (DESIGN.md, Navigation).
    for (prop, _, kind) in crate::entry_prop_variants(spec) {
        let pc = pascal(prop);
        let up = prop.to_uppercase();
        let (p, ty, ctor) = match kind {
            crate::PropKind::Str => (camel(prop), "String", "str"),
            crate::PropKind::Bool => (camel(prop), "Bool", "bool"),
            other => unreachable!("no entry prop carries {other:?}"),
        };
        c.line("");
        c.line(&format!("    /// set_entry_prop with a constant {prop} value."));
        c.line(&format!("    mutating func setEntry{pc}(_ entry: UInt64, _ {p}: {ty}) {{"));
        c.line("        let kayaAt = self.begin(UInt16(KAYA_TX_SET_ENTRY_PROP))");
        c.line("        self.u64(entry)");
        c.line(&format!("        self.u32(UInt32(KAYA_EPROP_{up}))"));
        c.line("        self.u32(UInt32(KAYA_SOURCE_CONST))");
        c.line(&format!("        self.value(.{ctor}({p}))"));
        c.line("        self.end(kayaAt)");
        c.line("    }");
        c.line("");
        c.line(&format!("    /// set_entry_prop with a signal-bound {prop} value."));
        c.line(&format!("    mutating func bindEntry{pc}(_ entry: UInt64, _ signalId: UInt64) {{"));
        c.line("        let kayaAt = self.begin(UInt16(KAYA_TX_SET_ENTRY_PROP))");
        c.line("        self.u64(entry)");
        c.line(&format!("        self.u32(UInt32(KAYA_EPROP_{up}))"));
        c.line("        self.u32(UInt32(KAYA_SOURCE_SIGNAL))");
        c.line("        self.u64(signalId)");
        c.line("        self.end(kayaAt)");
        c.line("    }");
    }

    // The section-prop duos (const + signal), the entry shape on the
    // section table; icon rides the blob channel (DESIGN.md, Sections).
    for (prop, _, kind) in crate::section_prop_variants(spec) {
        let pc = pascal(prop);
        let up = prop.to_uppercase();
        let (p, ty, ctor) = match kind {
            crate::PropKind::Str => (camel(prop), "String", "str"),
            crate::PropKind::Blob => ("handle".to_string(), "UInt64", "blob"),
            crate::PropKind::Enum(_) => (camel(prop), "Int64", "i64"),
            other => unreachable!("no section prop carries {other:?}"),
        };
        c.line("");
        c.line(&format!("    /// set_section_prop with a constant {prop} value."));
        c.line(&format!("    mutating func setSection{pc}(_ section: UInt64, _ {p}: {ty}) {{"));
        c.line("        let kayaAt = self.begin(UInt16(KAYA_TX_SET_SECTION_PROP))");
        c.line("        self.u64(section)");
        c.line(&format!("        self.u32(UInt32(KAYA_SPROP_{up}))"));
        c.line("        self.u32(UInt32(KAYA_SOURCE_CONST))");
        c.line(&format!("        self.value(.{ctor}({p}))"));
        c.line("        self.end(kayaAt)");
        c.line("    }");
        c.line("");
        c.line(&format!("    /// set_section_prop with a signal-bound {prop} value."));
        c.line(&format!("    mutating func bindSection{pc}(_ section: UInt64, _ signalId: UInt64) {{"));
        c.line("        let kayaAt = self.begin(UInt16(KAYA_TX_SET_SECTION_PROP))");
        c.line("        self.u64(section)");
        c.line(&format!("        self.u32(UInt32(KAYA_SPROP_{up}))"));
        c.line("        self.u32(UInt32(KAYA_SOURCE_SIGNAL))");
        c.line("        self.u64(signalId)");
        c.line("        self.end(kayaAt)");
        c.line("    }");
    }

    // The menu-prop setters: a const setter for every prop, signal
    // binders only for the bindable ones (SOURCE_SIGNAL on the rest
    // dies at the root). The shortcut setter routes through
    // kayaCanonicalizeShortcut, so no call site can bypass it.
    for (prop, _, kind) in crate::menu_prop_variants(spec) {
        let pc = pascal(prop);
        let up = prop.to_uppercase();
        let (p, ty, expr) = match kind {
            crate::PropKind::Str if *prop == "shortcut" => (
                camel(prop),
                "String",
                format!(".str(kayaCanonicalizeShortcut({}))", camel(prop)),
            ),
            crate::PropKind::Str => (camel(prop), "String", format!(".str({})", camel(prop))),
            crate::PropKind::Bool => (camel(prop), "Bool", format!(".bool({})", camel(prop))),
            crate::PropKind::F64 => (camel(prop), "Double", format!(".f64({})", camel(prop))),
            crate::PropKind::Blob => ("handle".to_string(), "UInt64", ".blob(handle)".to_string()),
            crate::PropKind::Enum(_) => (camel(prop), "Int64", format!(".i64({})", camel(prop))),
        };
        c.line("");
        if *prop == "shortcut" {
            c.line("    /// set_menu_prop with a constant shortcut value, canonicalized here");
            c.line("    /// (the one binding-tier shortcut parser — no call site bypasses it).");
        } else {
            c.line(&format!("    /// set_menu_prop with a constant {prop} value."));
        }
        c.line(&format!("    mutating func setMenu{pc}(_ item: UInt64, _ {p}: {ty}) {{"));
        c.line("        let kayaAt = self.begin(UInt16(KAYA_TX_SET_MENU_PROP))");
        c.line("        self.u64(item)");
        c.line(&format!("        self.u32(UInt32(KAYA_MPROP_{up}))"));
        c.line("        self.u32(UInt32(KAYA_SOURCE_CONST))");
        c.line(&format!("        self.value({expr})"));
        c.line("        self.end(kayaAt)");
        c.line("    }");
        if crate::menu_prop_bindable(prop) {
            c.line("");
            c.line(&format!("    /// set_menu_prop with a signal-bound {prop} value."));
            c.line(&format!("    mutating func bindMenu{pc}(_ item: UInt64, _ signalId: UInt64) {{"));
            c.line("        let kayaAt = self.begin(UInt16(KAYA_TX_SET_MENU_PROP))");
            c.line("        self.u64(item)");
            c.line(&format!("        self.u32(UInt32(KAYA_MPROP_{up}))"));
            c.line("        self.u32(UInt32(KAYA_SOURCE_SIGNAL))");
            c.line("        self.u64(signalId)");
            c.line("        self.end(kayaAt)");
            c.line("    }");
        }
    }
    c.line("");
    c.line("    func submit() {");
    c.line("        bytes.withUnsafeBytes { raw in");
    c.line("            kaya_submit(raw.bindMemory(to: UInt8.self).baseAddress, UInt(raw.count))");
    c.line("        }");
    c.line("    }");
    c.line("}");
    c.line("");
    let named_keys = crate::SHORTCUT_NAMED_KEYS
        .iter()
        .map(|k| format!("\"{k}\""))
        .collect::<Vec<_>>()
        .join(", ");
    c.line(&format!("let kayaShortcutNamedKeys: Set<String> = [{named_keys}]"));
    c.line("");
    c.line("/// The one binding-tier shortcut parser (DESIGN.md, Menus).");
    c.line("/// Canonicalize a shortcut spelling to the wire form: lowercase");
    c.line("/// '+'-joined tokens, modifiers ordered primary, shift, alt, then one");
    c.line("/// key (a-z, 0-9, or the closed named set). Accepts ASCII case");
    c.line("/// variants and any modifier order; traps on whitespace, empty tokens,");
    c.line("/// repeated modifiers, aliases (ctrl/cmd/option), and unknown or");
    c.line("/// multiple or missing keys. POLICY stays at the core: escape,");
    c.line("/// shift-only and bare alphanumerics, and the reserved floor are");
    c.line("/// validated there, on the canonical spelling, never rewritten.");
    c.line("func kayaCanonicalizeShortcut(_ spelling: String) -> String {");
    c.line("    if spelling.isEmpty {");
    c.line("        preconditionFailure(\"kaya: shortcut is empty\")");
    c.line("    }");
    c.line("    for ch in spelling {");
    c.line("        if ch == \" \" || ch == \"\\t\" || ch == \"\\n\" || ch == \"\\u{0B}\" || ch == \"\\u{0C}\" || ch == \"\\r\" {");
    c.line("            preconditionFailure(\"kaya: shortcut \\\"\\(spelling)\\\" contains whitespace\")");
    c.line("        }");
    c.line("    }");
    c.line("    let parts = spelling.lowercased()");
    c.line("        .split(separator: \"+\", omittingEmptySubsequences: false)");
    c.line("        .map(String.init)");
    c.line("    for p in parts where p.isEmpty {");
    c.line("        preconditionFailure(\"kaya: shortcut \\\"\\(spelling)\\\" has an empty token\")");
    c.line("    }");
    c.line("    let key = parts[parts.count - 1]");
    c.line("    var primary = false, shift = false, alt = false");
    c.line("    for m in parts.dropLast() {");
    c.line("        let repeated: Bool");
    c.line("        switch m {");
    c.line("        case \"primary\":");
    c.line("            repeated = primary");
    c.line("            primary = true");
    c.line("        case \"shift\":");
    c.line("            repeated = shift");
    c.line("            shift = true");
    c.line("        case \"alt\":");
    c.line("            repeated = alt");
    c.line("            alt = true");
    c.line("        default:");
    c.line("            preconditionFailure(\"kaya: shortcut \\\"\\(spelling)\\\" has an unknown modifier \\\"\\(m)\\\" (the portable modifiers are primary, shift, alt; aliases like ctrl, cmd, and option are not accepted)\")");
    c.line("        }");
    c.line("        if repeated {");
    c.line("            preconditionFailure(\"kaya: shortcut \\\"\\(spelling)\\\" repeats modifier \\\"\\(m)\\\"\")");
    c.line("        }");
    c.line("    }");
    c.line("    let alnum = key.count == 1 && (key.first!.isASCII && (key.first!.isLowercase || key.first!.isNumber))");
    c.line("    if !alnum && !kayaShortcutNamedKeys.contains(key) {");
    c.line("        preconditionFailure(\"kaya: shortcut \\\"\\(spelling)\\\" key \\\"\\(key)\\\" is outside the floor (one of a-z, 0-9, or the closed named set)\")");
    c.line("    }");
    c.line("    return (primary ? \"primary+\" : \"\") + (shift ? \"shift+\" : \"\") + (alt ? \"alt+\" : \"\") + key");
    c.line("}");
    c.line("");
    // The occurrence blob table. A blob in an OCCURRENCE is a table
    // handle, not the apply channel's batch-local index, and nothing
    // retires one here — so the decoder redeems and releases it, which
    // is what keeps a handle from ever reaching an app.
    c.line("/// One value of a representation. Its own type rather than a case");
    c.line("/// on KayaValue, because bytes reach a guest ONLY here — nothing");
    c.line("/// else on the occurrence channel has ever carried them.");
    c.line("enum KayaClipPart {");
    c.line("    case str(String)");
    c.line("    case i64(Int64)");
    c.line("    case bytes([UInt8])");
    c.line("}");
    c.line("");
    c.line("/// One representation as the decoder hands it over: the clip kind,");
    c.line("/// and its parts with blobs already redeemed. The sum itself is the");
    c.line("/// hand-written tier\'s — this is the taste-free shape the wire");
    c.line("/// carries.");
    c.line("///");
    c.line("/// `kind` is a SINGLE member of the clip enum and never a mask (you");
    c.line("/// offer many and you receive one); 0 with no parts is the universal");
    c.line("/// empty answer.");
    c.line("struct KayaClipValues {");
    c.line("    let kind: UInt32");
    c.line("    let parts: [KayaClipPart]");
    c.line("}");
    c.line("");
    c.line("/// Decode a representation at `at`: the clip kind, then its Values");
    c.line("/// block. Blobs are redeemed and RELEASED here.");
    c.line("func kayaParseClip(_ raw: UnsafeRawBufferPointer, _ at: Int)");
    c.line("    -> (clip: KayaClipValues, next: Int)");
    c.line("{");
    c.line("    let kind = raw.loadUnaligned(fromByteOffset: at, as: UInt32.self)");
    c.line("    let count = Int(raw.loadUnaligned(fromByteOffset: at + 8, as: UInt32.self))");
    c.line("    var at = at + 16");
    c.line("    var parts: [KayaClipPart] = []");
    c.line("    for _ in 0..<count {");
    c.line("        let vtype = raw.loadUnaligned(fromByteOffset: at, as: UInt32.self)");
    c.line("        let vlen = Int(raw.loadUnaligned(fromByteOffset: at + 4, as: UInt32.self))");
    c.line("        switch vtype {");
    c.line("        case UInt32(KAYA_VALUE_I64):");
    c.line("            parts.append(.i64(raw.loadUnaligned(fromByteOffset: at + 8, as: Int64.self)))");
    c.line("        case UInt32(KAYA_VALUE_BLOB):");
    c.line("            let handle = raw.loadUnaligned(fromByteOffset: at + 8, as: UInt64.self)");
    c.line("            var length = 0");
    c.line("            // COPY THEN RELEASE, in that order: the pointer borrows");
    c.line("            // core memory that the release frees.");
    c.line("            if let data = kaya_occurrence_blob(handle, &length) {");
    c.line("                parts.append(.bytes([UInt8](UnsafeBufferPointer(start: data, count: length))))");
    c.line("            } else {");
    c.line("                parts.append(.bytes([]))");
    c.line("            }");
    c.line("            kaya_occurrence_blob_release(handle)");
    c.line("        default:");
    c.line("            parts.append(.str(String(");
    c.line("                decoding: raw[(at + 8)..<(at + 8 + vlen)], as: UTF8.self)))");
    c.line("        }");
    c.line("        at += 8 + ((vlen + 7) & ~7)");
    c.line("    }");
    c.line("    return (KayaClipValues(kind: kind, parts: parts), at)");
    c.line("}");
    c.line("");
    c.line("/// Decode one occurrence record (header included); nil for pad or");
    c.line("/// unknown kinds. keys is [] when id is a widget id; otherwise id is");
    c.line("/// a template node id and keys is the copy's key path, outermost");
    c.line("/// first. payload is the entry's new text for TEXT_CHANGED, the");
    c.line("/// checkbox's new state for TOGGLED, the slider's new value for");
    c.line("/// VALUE_CHANGED, nil for clicks.");
    c.line("func kayaParseOccurrence(_ rec: [UInt8])");
    c.line("    -> (kind: UInt16, id: UInt64, keys: [KayaValue], payload: KayaValue?, files: [KayaPickedFile], clip: KayaClipValues?)?");
    c.line("{");
    c.line("    rec.withUnsafeBytes { raw in");
    c.line("        let kind = raw.loadUnaligned(fromByteOffset: 4, as: UInt16.self)");
    let accepted = crate::occurrence_names(spec)
        .iter()
        .map(|n| format!("kind == UInt16(KAYA_OCCURRENCE_{})", n.to_uppercase()))
        .collect::<Vec<_>>();
    c.line(&format!("        guard {}", accepted[0]));
    for cond in &accepted[1..] {
        c.line(&format!("            || {cond}"));
    }
    c.line("        else { return nil }");
    c.line("        let id = raw.loadUnaligned(fromByteOffset: 8, as: UInt64.self)");
    c.line("        if kind == UInt16(KAYA_OCCURRENCE_ALERT_RESULT) {");
    c.line("            // The alert's one answer: id + u32 choice (ALERT_CHOICE_*).");
    c.line("            let choice = raw.loadUnaligned(fromByteOffset: 16, as: UInt32.self)");
    c.line("            return (kind, id, [], .i64(Int64(choice)), [], nil)");
    c.line("        }");
    // The picker's answer: the one occurrence whose payload is a LIST
    // OF RECORDS, which no single KayaValue can carry — hence the
    // tuple's `files` member. The generic tail reads a KEY PATH, and
    // would take the file count as a path length and start eight bytes
    // early.
    c.line("        if kind == UInt16(KAYA_OCCURRENCE_FILE_DIALOG_RESULT) {");
    c.line("            // id, a count, then three Values per file");
    c.line("            // (handle, name, local_path). EMPTY IS CANCEL.");
    c.line("            let count = Int(raw.loadUnaligned(fromByteOffset: 16, as: UInt32.self))");
    c.line("            var at = 32  // past id, count, pad, values count, reserved");
    c.line("            var files: [KayaPickedFile] = []");
    c.line("            for _ in 0..<count {");
    c.line("                var parts: [KayaValue] = []");
    c.line("                for _ in 0..<3 {");
    c.line("                    let vtype = raw.loadUnaligned(fromByteOffset: at, as: UInt32.self)");
    c.line("                    let vlen = Int(raw.loadUnaligned(fromByteOffset: at + 4, as: UInt32.self))");
    c.line("                    if vtype == UInt32(KAYA_VALUE_I64) {");
    c.line("                        parts.append(.i64(raw.loadUnaligned(fromByteOffset: at + 8, as: Int64.self)))");
    c.line("                    } else {");
    c.line("                        let bytes = (0..<vlen).map { raw[at + 8 + $0] }");
    c.line("                        parts.append(.str(String(decoding: bytes, as: UTF8.self)))");
    c.line("                    }");
    c.line("                    at += 8 + (vlen + 7) & ~7");
    c.line("                }");
    c.line("                guard case .i64(let handle) = parts[0],");
    c.line("                      case .str(let name) = parts[1],");
    c.line("                      case .str(let localPath) = parts[2] else { continue }");
    c.line("                files.append(KayaPickedFile(");
    c.line("                    handle: UInt64(handle), name: name, localPath: localPath))");
    c.line("            }");
    c.line("            return (kind, id, [], nil, files, nil)");
    c.line("        }");
    // The privileged read's one answer, in its own arm: the generic
    // tail would take the CLIP KIND for a path length, so a text answer
    // would read the values header as a key.
    for name in crate::clip_answer_occurrence_names(spec) {
        c.line(&format!(
            "        if kind == UInt16(KAYA_OCCURRENCE_{}) {{",
            name.to_uppercase()
        ));
        c.line("            let (clip, _) = kayaParseClip(raw, 16)");
        c.line("            return (kind, id, [], nil, [], clip)");
        c.line("        }");
    }
    let id_only = crate::id_only_occurrence_names(spec)
        .iter()
        .map(|n| format!("kind == UInt16(KAYA_OCCURRENCE_{})", n.to_uppercase()))
        .collect::<Vec<_>>();
    c.line("        // Surface lifecycle records carry the surface id alone");
    c.line("        // (derived from the record shapes).");
    c.line(&format!("        if {}", id_only[0]));
    for cond in &id_only[1..] {
        c.line(&format!("            || {cond}"));
    }
    c.line("        {");
    c.line("            return (kind, id, [], nil, [], nil)");
    c.line("        }");
    let id_pair = crate::id_pair_occurrence_names(spec)
        .iter()
        .map(|n| format!("kind == UInt16(KAYA_OCCURRENCE_{})", n.to_uppercase()))
        .collect::<Vec<_>>();
    if !id_pair.is_empty() {
        c.line("        // Surface-pair records (window, section): the SECOND id");
        c.line("        // keys the handler; the first rides as the payload.");
        c.line(&format!("        if {}", id_pair[0]));
        for cond in &id_pair[1..] {
            c.line(&format!("            || {cond}"));
        }
        c.line("        {");
        c.line("            let section = raw.loadUnaligned(fromByteOffset: 16, as: UInt64.self)");
        c.line("            return (kind, section, [], .i64(Int64(bitPattern: id)), [], nil)");
        c.line("        }");
    }
    c.line("        let pathLen = raw.loadUnaligned(fromByteOffset: 16, as: UInt32.self)");
    c.line("        var keys: [KayaValue] = []");
    c.line("        var at = 24");
    c.line("        for _ in 0..<pathLen {");
    c.line("            let vtype = raw.loadUnaligned(fromByteOffset: at, as: UInt32.self)");
    c.line("            let vlen = Int(raw.loadUnaligned(fromByteOffset: at + 4, as: UInt32.self))");
    c.line("            switch vtype {");
    c.line("            case UInt32(KAYA_VALUE_BOOL):");
    c.line("                keys.append(.bool(raw[at + 8] != 0))");
    c.line("            case UInt32(KAYA_VALUE_I64):");
    c.line("                keys.append(.i64(Int64(bitPattern:");
    c.line("                    raw.loadUnaligned(fromByteOffset: at + 8, as: UInt64.self))))");
    c.line("            case UInt32(KAYA_VALUE_F64):");
    c.line("                keys.append(.f64(Double(bitPattern:");
    c.line("                    raw.loadUnaligned(fromByteOffset: at + 8, as: UInt64.self))))");
    c.line("            default:");
    c.line("                keys.append(.str(String(");
    c.line("                    decoding: raw[(at + 8)..<(at + 8 + vlen)], as: UTF8.self)))");
    c.line("            }");
    c.line("            at += 8 + ((vlen + 7) & ~7)");
    c.line("        }");
    c.line("        var payload: KayaValue? = nil");
    // The u32 slot the tag family calls `reserved` is a real value on
    // these (sort_requested's column) — read from its fixed offset.
    for name in crate::u32_slot_occurrence_names(spec) {
        c.line(&format!(
            "        if kind == UInt16(KAYA_OCCURRENCE_{}) {{",
            name.to_uppercase()
        ));
        c.line("            payload = .i64(Int64(raw.loadUnaligned(fromByteOffset: 20, as: UInt32.self)))");
        c.line("        }");
    }
    let with_payload = crate::payload_occurrence_names(spec)
        .iter()
        .map(|n| format!("kind == UInt16(KAYA_OCCURRENCE_{})", n.to_uppercase()))
        .collect::<Vec<_>>();
    c.line(&format!("        if {}", with_payload[0]));
    for cond in &with_payload[1..] {
        c.line(&format!("            || {cond}"));
    }
    c.line("        {");
    // Type-generic payload decode, same shape as the key loop: no
    // per-kind logic left to drift.
    c.line("            let ptype = raw.loadUnaligned(fromByteOffset: at, as: UInt32.self)");
    c.line("            let plen = Int(raw.loadUnaligned(fromByteOffset: at + 4, as: UInt32.self))");
    c.line("            switch ptype {");
    c.line("            case UInt32(KAYA_VALUE_BOOL):");
    c.line("                payload = .bool(raw[at + 8] != 0)");
    c.line("            case UInt32(KAYA_VALUE_I64):");
    c.line("                payload = .i64(Int64(bitPattern:");
    c.line("                    raw.loadUnaligned(fromByteOffset: at + 8, as: UInt64.self)))");
    c.line("            case UInt32(KAYA_VALUE_F64):");
    c.line("                payload = .f64(Double(bitPattern:");
    c.line("                    raw.loadUnaligned(fromByteOffset: at + 8, as: UInt64.self)))");
    c.line("            default:");
    c.line("                payload = .str(String(decoding: raw[(at + 8)..<(at + 8 + plen)], as: UTF8.self))");
    c.line("            }");
    c.line("        }");
    // A paste rides a click tag VERBATIM, so the key path above is
    // already read and the clip sits after it. One record kind, path_len
    // deciding.
    c.line("        var clip: KayaClipValues? = nil");
    let pasted = crate::pasted_occurrence_names(spec)
        .iter()
        .map(|n| format!("kind == UInt16(KAYA_OCCURRENCE_{})", n.to_uppercase()))
        .collect::<Vec<_>>();
    if !pasted.is_empty() {
        c.line(&format!("        if {}", pasted[0]));
        for cond in &pasted[1..] {
            c.line(&format!("            || {cond}"));
        }
        c.line("        {");
        c.line("            clip = kayaParseClip(raw, at).clip");
        c.line("        }");
    }
    c.line("        return (kind, id, keys, payload, [], clip)");
    c.line("    }");
    c.line("}");
    c.out
}

fn emit_packer(c: &mut Ctx, r: &Record) {
    let params = record_params(r);
    let mut sig: Vec<String> = Vec::new();
    for f in &params {
        sig.push(match f.ty {
            FieldTy::U32 => format!("_ {}: UInt32", camel(f.name)),
            FieldTy::U64 => format!("_ {}: UInt64", camel(f.name)),
            FieldTy::Value => format!("_ {}: KayaValue", camel(f.name)),
            FieldTy::Values => format!("_ {}: [KayaValue]", camel(f.name)),
            FieldTy::VariantSchemas => format!("_ {}: [[UInt32]]", camel(f.name)),
        });
    }
    c.line("");
    c.line(&format!("    /// {}", r.doc.replace('\n', " ")));
    c.line(&format!(
        "    mutating func {}({}) {{",
        camel(r.name),
        sig.join(", ")
    ));
    c.line(&format!(
        "        let kayaAt = self.begin(UInt16(KAYA_TX_{}))",
        r.name.to_uppercase()
    ));
    for f in r.fields {
        c.line(&match f.ty {
            FieldTy::U32 if is_padding(f) => "        self.u32(0)".into(),
            FieldTy::U32 => format!("        self.u32({})", camel(f.name)),
            FieldTy::U64 => format!("        self.u64({})", camel(f.name)),
            FieldTy::Value => format!("        self.value({})", camel(f.name)),
            FieldTy::Values => format!("        self.values({})", camel(f.name)),
            FieldTy::VariantSchemas => format!("        self.variantSchemas({})", camel(f.name)),
        });
    }
    c.line("        self.end(kayaAt)");
    c.line("    }");
}
