#!/usr/bin/env bash

kaya_flake="$(cd "$(dirname "$0")/../.." && cat flake.nix flake.lock | shasum -a 256 | cut -c1-12)"
if [ "${KAYA_DEV_SHELL:-}" != "$kaya_flake" ]; then
    if [ -z "${KAYA_DEV_SHELL:-}" ]; then
        echo "$0: not inside the dev shell — run this under \`nix develop\`" >&2
    else
        echo "$0: dev shell is stale — the flake changed since it was entered; re-enter \`nix develop\`" >&2
    fi
    exit 1
fi
# Build the SwiftUI backend dylib (macOS): the Swift presentation layer
# plus the kaya_swiftui_run C entry.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"

# shellcheck source=tools/lib/swift-toolchain.sh
source "$ROOT/tools/lib/swift-toolchain.sh"

cargo build --locked --lib
# The Swift dylib below compiles against this library's header and loads
# it at run time; both must come from one tree.
tools/build-id.py --verify target/debug/libkaya.dylib
tools/gen-header.py --check

# The interpreter carries the id of the sources it was compiled from
# (tools/build-id.py): a separate artifact from a separate toolchain, so
# it goes stale separately.
#
# A `public let` survives -O into the dylib's string table (measured
# against a plain let, an @_cdecl and a byte array — all four survive,
# this is the least machinery).
mkdir -p target/swiftui
# ONE BUILDER AT A TIME: the matrix's gate sweep and the mac lane's
# skip path (tools/validate-all.py, 2026-08-20) can both reach here in
# the same second, and two concurrent swiftc runs write one dylib —
# cargo has its own lock, this artifact needs one of its own. mkdir is
# the atomic primitive; a crashed holder's lock dies with the deadline.
LOCK=target/swiftui/.build-lock
waited=0
until mkdir "$LOCK" 2>/dev/null; do
    waited=$((waited + 1))
    if [ "$waited" -gt 300 ]; then
        echo "build-dylib: the build lock $LOCK is stuck after 300s — a dead" >&2
        echo "  builder left it; remove the directory and rerun." >&2
        exit 1
    fi
    sleep 1
done
trap 'rmdir "$LOCK" 2>/dev/null' EXIT
KAYA_SWIFTUI_ID="$(tools/build-id.py swiftui)"
MARKER_SWIFT=target/swiftui/KayaBuildId.swift
cat >"$MARKER_SWIFT" <<EOF
// Generated by tools/swiftui/build-dylib.sh. Do not edit, do not commit.
public let kayaSwiftUIBuildIdMarker = "kaya-build-id:$KAYA_SWIFTUI_ID"
EOF

OUT=target/swiftui/libkaya_swiftui.dylib

# ALREADY FRESH MEANS DONE: when the dylib in place carries this tree's
# own id, a rebuild would produce the same thing — and the matrix's
# concurrent shape (tools/validate-all.py, 2026-08-20) has the gate
# sweep and the mac lane both arriving here while legs are dlopening
# the artifact, so a needless rebuild is not merely slow.
if [ -f "$OUT" ] \
    && tools/build-id.py --verify --component swiftui "$OUT" >/dev/null 2>&1; then
    echo "built $OUT (already carries this tree's id)"
    exit 0
fi

# A FAILED BUILD MUST NOT LEAVE A USABLE ARTIFACT: compile to a scratch
# path; on success the move REPLACES the old dylib atomically (readers
# that mapped it keep their copy, and there is never a moment with no
# dylib on disk — legs dlopen this path while a concurrent sweep
# rebuilds, measured 2026-08-20 when a delete-first shape left a ~30s
# hole and eight legs died in it); on FAILURE the old dylib is deleted,
# which is the guarantee's whole point (docs/traps.md, "A failed build
# must not leave a usable artifact").
#
# -warnings-as-errors is a GUARD, not tidiness: a dropped return value
# is only a warning, and that is how a clipboard seed discarded
# osascript's exit status for the life of the scene (docs/traps.md §
# the swift-typecheck sibling of this flag).
if ! kaya_swiftc \
    -warnings-as-errors \
    -emit-library \
    -import-objc-header crates/kaya/include/kaya.h \
    swift/KayaSwiftUI.swift swift/KayaSwiftUIEntry.swift "$MARKER_SWIFT" \
    -Xlinker -undefined -Xlinker dynamic_lookup \
    -framework AppKit -framework Foundation \
    -o "$OUT.tmp"; then
    rm -f "$OUT.tmp" "$OUT"
    echo "build-dylib: FAILED — no dylib left in place (a stale one would be tested silently)" >&2
    exit 1
fi
mv -f "$OUT.tmp" "$OUT"
# The dylib in place must be the one this run compiled.
tools/build-id.py --verify --component swiftui "$OUT"
echo "built $OUT"
