"""kaya runtime for Python guests: loading, the function floor, and the
occurrence loop. Hand-written; the wire vocabulary next to it
(kaya_wire.py) is generated by kaya-bindgen.

The shape every guest shares: the process main thread enters run() and
becomes the core's UI thread; a Python thread is the app thread,
draining occurrences with next_occurrence() and answering with
submit(). See DESIGN.md for the protocol.
"""

import ctypes
import os
import pathlib
import sys

from kaya_wire import parse_occurrence


def _find_library():
    if lib := os.environ.get("KAYA_LIB"):
        return lib
    name = {"darwin": "libkaya.dylib", "win32": "kaya.dll"}.get(
        sys.platform, "libkaya.so"
    )
    here = pathlib.Path(__file__).resolve().parent
    for base in [here, *here.parents]:
        for candidate in [base / name, base / "target" / "debug" / name]:
            if candidate.exists():
                return str(candidate)
    raise FileNotFoundError(f"{name} not found; build with cargo or set KAYA_LIB")


_lib = ctypes.CDLL(_find_library())
_lib.kaya_next_occurrence.argtypes = [ctypes.c_void_p, ctypes.c_size_t]
_lib.kaya_next_occurrence.restype = ctypes.c_size_t
_lib.kaya_submit.argtypes = [ctypes.c_char_p, ctypes.c_size_t]
_lib.kaya_submit.restype = None
_lib.kaya_run.restype = ctypes.c_int32

_occ_buf = ctypes.create_string_buffer(256)


def submit(*records):
    """Submit one transaction: the concatenation of packed records
    (tx_* results from kaya_wire), applied atomically."""
    tx = b"".join(records)
    _lib.kaya_submit(tx, len(tx))


def next_occurrence():
    """Block for the next click; None when the core has shut down.

    Returns (id, keys): keys is [] for a click on a guest-created widget
    (id is a widget id), else id is a template node id and keys is the
    stamped copy's key path, outermost first.
    """
    while True:
        size = _lib.kaya_next_occurrence(_occ_buf, 256)
        if size == 0:
            return None
        kind, ident, keys = parse_occurrence(_occ_buf.raw)
        if ident is not None:
            return ident, keys


def run():
    """Enter the core on the calling thread (must be the process main
    thread); returns the exit code when the app ends."""
    return _lib.kaya_run()
