package dev.kaya.milestone2kt;

// Code generated by the kaya annotation processor; DO NOT EDIT.
// Regenerate with tools/gen-guests.sh (which also checks freshness).

import dev.kaya.KayaApp;
import dev.kaya.KayaRecords;

/** Item's generated record surface: the collection factory,
 * exact-index field tokens, and a named-setter patch (each set
 * records one update_field — a patch is recorded writes, never a
 * diff). */
final class ItemKaya {
    static KayaRecords.Collection<String, Reorder.Item> collection(KayaApp.Tx tx) {
        return KayaRecords.collectionOf(tx, Reorder.Item.class);
    }

    static final KayaRecords.Field<String> TITLE = KayaRecords.fieldAt(0);

    static Patch patch(KayaApp.Tx tx, KayaRecords.Collection<String, Reorder.Item> c, String key) {
        return new Patch(c.patch(tx, key));
    }

    static final class Patch {
        private final KayaRecords.Patch<String, Reorder.Item> p;

        Patch(KayaRecords.Patch<String, Reorder.Item> p) {
            this.p = p;
        }

        Patch title(String v) {
            p.set(TITLE, v);
            return this;
        }
    }

    private ItemKaya() {}
}
