package dev.kaya.milestone2kt;

// Code generated by the kaya annotation processor; DO NOT EDIT.
// Regenerate with tools/gen-guests.sh (which also checks freshness).

import dev.kaya.KayaApp;
import dev.kaya.KayaSums;
import java.util.function.BiConsumer;

/** Post's generated sum surface: the collection factory and the
 * staged eliminator — each stage offers exactly the next
 * constructor's arm, so totality is a compile error here, and
 * the scene checks it again. */
final class PostKaya {
    static KayaSums.SumCollection<String, Feed.Post> collection(KayaApp.Tx tx) {
        return KayaSums.sumOf(tx, Feed.Post.class, Feed.Note.class, Feed.Todo.class);
    }

    static Stage2 eachSum(KayaApp.Tx tx, KayaSums.SumCollection<String, Feed.Post> c) {
        return new Stage2(tx, c, new KayaSums.Arm[2]);
    }

    static final class Stage2 {
        private final KayaApp.Tx tx;
        private final KayaSums.SumCollection<String, Feed.Post> c;
        private final KayaSums.Arm<String, Feed.Post>[] arms;

        Stage2(KayaApp.Tx tx, KayaSums.SumCollection<String, Feed.Post> c,
                KayaSums.Arm<String, Feed.Post>[] arms) {
            this.tx = tx;
            this.c = c;
            this.arms = arms;
        }

        Stage1 note(BiConsumer<KayaApp.Tpl, KayaSums.Case<String, Feed.Note>> arm) {
            arms[0] = c.arm(Feed.Note.class, arm);
            return new Stage1(tx, c, arms);
        }
    }

    static final class Stage1 {
        private final KayaApp.Tx tx;
        private final KayaSums.SumCollection<String, Feed.Post> c;
        private final KayaSums.Arm<String, Feed.Post>[] arms;

        Stage1(KayaApp.Tx tx, KayaSums.SumCollection<String, Feed.Post> c,
                KayaSums.Arm<String, Feed.Post>[] arms) {
            this.tx = tx;
            this.c = c;
            this.arms = arms;
        }

        KayaApp.Widget todo(BiConsumer<KayaApp.Tpl, KayaSums.Case<String, Feed.Todo>> arm) {
            arms[1] = c.arm(Feed.Todo.class, arm);
            return KayaSums.eachSum(tx, c, arms);
        }
    }

    private PostKaya() {}
}
