// Code generated by kaya-gen; DO NOT EDIT.
// Regenerate with `go generate ./...` (tools/gen-guests.py checks freshness).

package pickers

import (
	"iter"

	kaya "dev.kaya/bindings/go"
)

// TaskCollection declares the record collection; the struct is the
// schema.
func TaskCollection(tx *kaya.Tx) kaya.RecordCollection[string, Task] {
	return kaya.CollectionOf[string, Task](tx)
}

// TaskPatch opens a named-setter patch on one entry; each setter
// records one update_field — a patch is recorded writes, never a
// diff.
func TaskPatch(c kaya.RecordCollection[string, Task], tx *kaya.Tx, key string) taskPatchBuilder {
	return taskPatchBuilder{c.Patch(tx, key)}
}

type taskPatchBuilder struct {
	p kaya.RecordPatch[string, Task]
}

func (p taskPatchBuilder) Name(v string) taskPatchBuilder {
	p.p.Set(func(t *Task) *string { return &t.Name }, v)
	return p
}

func (p taskPatchBuilder) Due(v kaya.Date) taskPatchBuilder {
	p.p.Set(func(t *Task) *kaya.Date { return &t.Due }, v)
	return p
}

// The row surface: one token per wire field, and the template
// constructors that consume them.
type taskRow struct {
	t *kaya.Tpl
	c kaya.RecordCollection[string, Task]
}

func (r taskRow) Name() kaya.Field[string] { return kaya.FieldAt[string](0) }

func (r taskRow) Due() kaya.Field[kaya.Date] { return kaya.FieldAt[kaya.Date](1) }

func (r taskRow) Row(body func()) kaya.Node { return r.t.Row(body) }

func (r taskRow) Column(body func()) kaya.Node { return r.t.Column(body) }

func (r taskRow) Label(f kaya.Field[string]) kaya.Node { return r.c.Label(r.t, f) }

func (r taskRow) Heading(f kaya.Field[string]) kaya.Node { return r.c.Heading(r.t, f) }

func (r taskRow) Caption(f kaya.Field[string]) kaya.Node { return r.c.Caption(r.t, f) }

func (r taskRow) Image(f kaya.Field[[]byte]) kaya.Node { return r.c.Image(r.t, f) }

func (r taskRow) Checkbox(f kaya.Field[bool], onToggle func(*kaya.Tx, string, bool)) kaya.Node {
	return r.c.Checkbox(r.t, f, onToggle)
}

func (r taskRow) DatePicker(f kaya.Field[kaya.Date], onDate func(*kaya.Tx, string, kaya.Date)) kaya.Node {
	return r.c.DatePicker(r.t, f, onDate)
}

func (r taskRow) TimePicker(f kaya.Field[kaya.Time], onTime func(*kaya.Tx, string, kaya.Time)) kaya.Node {
	return r.c.TimePicker(r.t, f, onTime)
}

func (r taskRow) Slider(min, max float64, f kaya.Field[float64], onChange func(*kaya.Tx, string, float64)) kaya.Node {
	return r.c.Slider(r.t, min, max, f, onChange)
}

// The template props: the const flavors write through the recorder,
// the sourced ones through the typed collection, as the constructors
// above do.
func (r taskRow) SetGrow(n kaya.Node, weight float64) { r.t.SetGrow(n, weight) }

func (r taskRow) SetStep(n kaya.Node, step float64) { r.t.SetStep(n, step) }

func (r taskRow) SetTickSpacing(n kaya.Node, spacing float64) { r.t.SetTickSpacing(n, spacing) }

func (r taskRow) SetA11yID(n kaya.Node, id string) { r.t.SetA11yID(n, id) }

func (r taskRow) A11yID(n kaya.Node, f kaya.Field[string]) { r.c.A11yID(r.t, n, f) }

func (r taskRow) SetA11yLabel(n kaya.Node, label string) { r.t.SetA11yLabel(n, label) }

func (r taskRow) A11yLabel(n kaya.Node, f kaya.Field[string]) { r.c.A11yLabel(r.t, n, f) }

func (r taskRow) SetA11yHint(n kaya.Node, hint string) { r.t.SetA11yHint(n, hint) }

func (r taskRow) A11yHint(n kaya.Node, f kaya.Field[string]) { r.c.A11yHint(r.t, n, f) }

func (r taskRow) SetHelp(n kaya.Node, text string) { r.t.SetHelp(n, text) }

func (r taskRow) Help(n kaya.Node, f kaya.Field[string]) { r.c.Help(r.t, n, f) }

func (r taskRow) SetAccepts(n kaya.Node, kinds ...string) { r.t.SetAccepts(n, kinds...) }

func (r taskRow) Draggable(n kaya.Node) kaya.TplDragRef { return r.t.Draggable(n) }

func (r taskRow) SetDropTarget(n kaya.Node, ops ...kaya.Op) { r.t.SetDropTarget(n, ops...) }

func (r taskRow) SetRole(n kaya.Node, role int64) { r.t.SetRole(n, role) }

func (r taskRow) SetInset(n kaya.Node, pad float64) { r.t.SetInset(n, pad) }

// TaskRows opens the record template as a for statement: the For is
// minted here, the chain declares the table, and the loop body runs
// once with the typed row surface (exact-index tokens, no probes);
// stamping is the core's replay.
func TaskRows(tx *kaya.Tx, c kaya.RecordCollection[string, Task]) *taskRowsFor {
	return &taskRowsFor{tx.Rows(c.Collection), c}
}

// The embedded *kaya.Rows carries Widget(); the two chain methods
// are re-spelled only to keep the typed All() reachable through them.
type taskRowsFor struct {
	*kaya.Rows
	c kaya.RecordCollection[string, Task]
}

func (f *taskRowsFor) Columns(titles []string, sort kaya.Sort) *taskRowsFor {
	f.Rows.Columns(titles, sort)
	return f
}

func (f *taskRowsFor) OnSort(fn func(*kaya.Tx, uint32)) *taskRowsFor {
	f.Rows.OnSort(fn)
	return f
}

func (f *taskRowsFor) All() iter.Seq[taskRow] {
	return func(yield func(taskRow) bool) {
		for row := range f.Rows.All() {
			if !yield(taskRow{t: row.Tpl, c: f.c}) {
				return
			}
		}
	}
}
