// Code generated by kaya-csgen; DO NOT EDIT.
// Regenerate with tools/gen-guests.sh (which also checks freshness).

/// <summary>Item's generated record surface: the collection
/// factory, exact-index field tokens, and a named-setter patch
/// (each set records one update_field — a patch is recorded
/// writes, never a diff).</summary>
static class ItemKaya
{
    public static RecordCollection<Item> Collection(Tx tx) =>
        tx.CollectionOf<Item>();

    public static readonly Field<string> Title = KayaRecords.FieldAt<string>(0);

    public static ItemKayaPatch Patch(Tx tx, RecordCollection<Item> c, object key) =>
        new ItemKayaPatch(c.Patch(tx, key));

    /// <summary>The record template: the body runs once, authoring
    /// the blueprint with the typed row surface (exact-index
    /// tokens, no probes); stamping is the core's replay.</summary>
    public static Widget Each(Tx tx, RecordCollection<Item> c,
        System.Action<Tpl, ItemRow> body) =>
        tx.Each(c.Collection, t => body(t, new ItemRow()));
}

/// <summary>The row surface: one token per wire field, and the
/// template constructors that consume them.</summary>
sealed class ItemRow
{
    public readonly Field<string> Title = ItemKaya.Title;

    public Node Label(Tpl t, Field<string> f) => t.Label(f);

    public Node Checkbox(Tpl t, Field<bool> f,
        System.Action<Tx, System.Collections.Generic.List<object>, bool> onToggle = null) =>
        t.Checkbox(f, onToggle);
}

sealed class ItemKayaPatch
{
    readonly RecordPatch<Item> p;

    internal ItemKayaPatch(RecordPatch<Item> p) => this.p = p;

    public ItemKayaPatch Title(string v)
    {
        p.Set(ItemKaya.Title, v);
        return this;
    }
}
