// Code generated by kaya-csgen; DO NOT EDIT.
// Regenerate with tools/gen-guests.py (which also checks freshness).

/// <summary>Task's generated record surface: the collection
/// factory, exact-index field tokens, and a named-setter patch
/// (each set records one update_field — a patch is recorded
/// writes, never a diff).</summary>
static class TaskKaya
{
    public static RecordCollection<Task> Collection(Tx tx) =>
        tx.CollectionOf<Task>();

    public static readonly Field<string> Name = KayaRecords.FieldAt<string>(0);
    public static readonly Field<System.DateOnly> Due = KayaRecords.FieldAt<System.DateOnly>(1);

    public static TaskKayaPatch Patch(Tx tx, RecordCollection<Task> c, object key) =>
        new TaskKayaPatch(c.Patch(tx, key));

    /// <summary>The record template, expression form: the body runs
    /// once, authoring the blueprint with the typed row surface
    /// (exact-index tokens, no probes); stamping is the core's
    /// replay.</summary>
    public static Widget Each(Tx tx, RecordCollection<Task> c,
        System.Action<TaskRow> body) =>
        tx.Each(c.Collection, t => body(new TaskRow(t)));

    /// <summary>The same, for a For opened INSIDE a template body —
    /// the nested table's shape, "for every account, a positions
    /// table". Without it the nested body holds the raw Tpl and
    /// spells its cells with the static tokens rather than the row's
    /// own (docs/deferred.md, the closed C# façade entry).</summary>
    public static Node Each(Tpl t, RecordCollection<Task> c,
        System.Action<TaskRow> body) =>
        t.Each(c.Collection, inner => body(new TaskRow(inner)));

    /// <summary>The foreach form: `foreach (var row in todos.Rows())`
    /// traces the record template — the body runs once, and the
    /// enumerator's Dispose closes the template, so foreach makes the
    /// close structural, even on break.</summary>
    public static TaskRowSeq Rows(this RecordCollection<Task> c) =>
        new TaskRowSeq(c);
}

/// <summary>The row surface: the template handle plus one token per
/// wire field, and the template zone's whole vocabulary aimed at them.
///
/// The forwarders below are the ZONE and not a selection from it. A
/// constructor Tpl has and this does not is reachable through tx.Each
/// and not through `foreach (var row in c.Rows())`, which is a
/// difference no guest should have to know about, and the shape this
/// list drifts into: it named five constructors by hand while the
/// zone named six, and the scene that wanted a per-row entry could
/// not use either, so it opened the For itself and reached for the
/// widget-kind floor (docs/sugar-pass-plan.md S4b).
/// Add here whatever is added to Tpl: the prop setters below are
/// forwarded for the same reason the constructors are.
/// The zone's PLUMBING — Widget, the Bind*Field setters, AddChild —
/// stays off deliberately: a row surface hands out sugar, and its
/// Tpl is private so the floor is reached by opening the For
/// yourself. THE NESTED-FOR VOCABULARY IS NOT PLUMBING and is
/// forwarded — Collection, Each, ForEach, and the Columns that
/// names the Node Each hands back — or a nested table is spellable
/// through tx.Each and not through a row at all. When and
/// ContextMenu are the two still off the list; Java's RowSurface
/// forwards both, and that divergence is recorded in
/// docs/deferred.md rather than blessed here.</summary>
sealed class TaskRow
{
    readonly Tpl t;
    public readonly Field<string> Name = TaskKaya.Name;
    public readonly Field<System.DateOnly> Due = TaskKaya.Due;

    internal TaskRow(Tpl t) => this.t = t;

    public Node Label(string text) => t.Label(text);

    public Node Label(Signal s) => t.Label(s);

    public Node Label(Field<string> f) => t.Label(f);

    public Node Heading(string text) => t.Heading(text);

    public Node Heading(Signal s) => t.Heading(s);

    public Node Heading(Field<string> f) => t.Heading(f);

    public Node Caption(string text) => t.Caption(text);

    public Node Caption(Signal s) => t.Caption(s);

    public Node Caption(Field<string> f) => t.Caption(f);

    public Node Button(string text) => t.Button(text);

    public Node Button(Signal s) => t.Button(s);

    public Node Button(Field<string> f) => t.Button(f);

    public Node Image(byte[] source) => t.Image(source);

    public Node Image(Signal s) => t.Image(s);

    public Node Image(Field<byte[]> f) => t.Image(f);

    public Node Canvas(Viewbox vb, System.Action<Draw> body) => t.Canvas(vb, body);

    public Node Checkbox(Field<bool> f,
        System.Action<Tx, System.Collections.Generic.List<object>, bool> onToggle = null) =>
        t.Checkbox(f, onToggle);

    public Node DatePicker(System.DateOnly value,
        System.Action<Tx, System.Collections.Generic.List<object>, System.DateOnly> onDate = null) =>
        t.DatePicker(value, onDate);

    public Node DatePicker(Signal value,
        System.Action<Tx, System.Collections.Generic.List<object>, System.DateOnly> onDate = null) =>
        t.DatePicker(value, onDate);

    public Node DatePicker(Field<System.DateOnly> f,
        System.Action<Tx, System.Collections.Generic.List<object>, System.DateOnly> onDate = null) =>
        t.DatePicker(f, onDate);

    public Node TimePicker(System.TimeOnly value,
        System.Action<Tx, System.Collections.Generic.List<object>, System.TimeOnly> onTime = null) =>
        t.TimePicker(value, onTime);

    public Node TimePicker(Signal value,
        System.Action<Tx, System.Collections.Generic.List<object>, System.TimeOnly> onTime = null) =>
        t.TimePicker(value, onTime);

    public Node TimePicker(Field<System.TimeOnly> f,
        System.Action<Tx, System.Collections.Generic.List<object>, System.TimeOnly> onTime = null) =>
        t.TimePicker(f, onTime);

    public Node Entry(
        System.Action<Tx, System.Collections.Generic.List<object>, string> onChange = null) =>
        t.Entry(onChange);

    public Node Entry(string text,
        System.Action<Tx, System.Collections.Generic.List<object>, string> onChange = null) =>
        t.Entry(text, onChange);

    public Node Entry(Signal text,
        System.Action<Tx, System.Collections.Generic.List<object>, string> onChange = null) =>
        t.Entry(text, onChange);

    public Node Entry(Field<string> text,
        System.Action<Tx, System.Collections.Generic.List<object>, string> onChange = null) =>
        t.Entry(text, onChange);

    public Node Textarea(
        System.Action<Tx, System.Collections.Generic.List<object>, string> onChange = null) =>
        t.Textarea(onChange);

    public Node Textarea(string text,
        System.Action<Tx, System.Collections.Generic.List<object>, string> onChange = null) =>
        t.Textarea(text, onChange);

    public Node Textarea(Signal text,
        System.Action<Tx, System.Collections.Generic.List<object>, string> onChange = null) =>
        t.Textarea(text, onChange);

    public Node Textarea(Field<string> text,
        System.Action<Tx, System.Collections.Generic.List<object>, string> onChange = null) =>
        t.Textarea(text, onChange);

    public Node Progress(double value) => t.Progress(value);

    public Node Progress(Signal value) => t.Progress(value);

    public Node Progress(Field<double> value) => t.Progress(value);

    public Node ProgressIndeterminate() => t.ProgressIndeterminate();

    public Node Slider(double min, double max, double value, double? step = null, double? tickSpacing = null, System.Action<Tx, System.Collections.Generic.List<object>, double> onChange = null,
        System.Action<Tx, System.Collections.Generic.List<object>, double> onCommit = null) =>
        t.Slider(min, max, value, step, tickSpacing, onChange, onCommit);

    public Node Slider(double min, double max, Signal value, double? step = null, double? tickSpacing = null, System.Action<Tx, System.Collections.Generic.List<object>, double> onChange = null,
        System.Action<Tx, System.Collections.Generic.List<object>, double> onCommit = null) =>
        t.Slider(min, max, value, step, tickSpacing, onChange, onCommit);

    public Node Slider(double min, double max, Field<double> value, double? step = null, double? tickSpacing = null, System.Action<Tx, System.Collections.Generic.List<object>, double> onChange = null,
        System.Action<Tx, System.Collections.Generic.List<object>, double> onCommit = null) =>
        t.Slider(min, max, value, step, tickSpacing, onChange, onCommit);

    public Node Select(string[] options, int selected,
        System.Action<Tx, System.Collections.Generic.List<object>, int> onSelect = null) =>
        t.Select(options, selected, onSelect);

    public Node Select(string[] options, Signal selected,
        System.Action<Tx, System.Collections.Generic.List<object>, int> onSelect = null) =>
        t.Select(options, selected, onSelect);

    public Node Select(string[] options, Field<double> selected,
        System.Action<Tx, System.Collections.Generic.List<object>, int> onSelect = null) =>
        t.Select(options, selected, onSelect);

    public Node Radio(string[] options, int selected,
        System.Action<Tx, System.Collections.Generic.List<object>, int> onSelect = null) =>
        t.Radio(options, selected, onSelect);

    public Node Radio(string[] options, Signal selected,
        System.Action<Tx, System.Collections.Generic.List<object>, int> onSelect = null) =>
        t.Radio(options, selected, onSelect);

    public Node Radio(string[] options, Field<double> selected,
        System.Action<Tx, System.Collections.Generic.List<object>, int> onSelect = null) =>
        t.Radio(options, selected, onSelect);

    public Node Row(System.Action body) => t.Row(body);

    public Node Column(System.Action body) => t.Column(body);

    public Node Scroll(System.Action body) => t.Scroll(body);

    public Node Grid(int columns, System.Action body) => t.Grid(columns, body);

    public Node Labeled(string label, System.Action body) => t.Labeled(label, body);

    public Node Labeled(Signal label, System.Action body) => t.Labeled(label, body);

    public Node Labeled(Field<string> label,
        System.Action body) =>
        t.Labeled(label, body);

    public Node Spacer() => t.Spacer();

    public Collection Collection() => t.Collection();

    public Node Each(Collection c, System.Action<Tpl> body) => t.Each(c, body);

    public Node ForEach(Collection c,
        System.Action<Tpl> body) =>
        t.ForEach(c, body);

    public void Columns(Node n, string[] titles, Sort sort) =>
        t.Columns(n, titles, sort);

    public void SetGrow(Node n, double weight) => t.SetGrow(n, weight);

    public void SetA11yId(Node n, string id) => t.SetA11yId(n, id);

    public void SetA11yId(Node n, Signal s) => t.SetA11yId(n, s);

    public void SetA11yId(Node n, Field<string> f, uint level = 0) =>
        t.SetA11yId(n, f, level);

    public void SetA11yLabel(Node n, string label) => t.SetA11yLabel(n, label);

    public void SetA11yLabel(Node n, Signal s) => t.SetA11yLabel(n, s);

    public void SetA11yLabel(Node n, Field<string> f, uint level = 0) =>
        t.SetA11yLabel(n, f, level);

    public void SetA11yHint(Node n, string hint) => t.SetA11yHint(n, hint);

    public void SetA11yHint(Node n, Signal s) => t.SetA11yHint(n, s);

    public void SetA11yHint(Node n, Field<string> f, uint level = 0) =>
        t.SetA11yHint(n, f, level);

    public void SetHelp(Node n, string text) => t.SetHelp(n, text);

    public void SetHelp(Node n, Signal s) => t.SetHelp(n, s);

    public void SetHelp(Node n, Field<string> f, uint level = 0) =>
        t.SetHelp(n, f, level);

    public void SetAccepts(Node n, params string[] kinds) => t.SetAccepts(n, kinds);

    public TplDragRef Draggable(Node n) => t.Draggable(n);

    public void SetDropTarget(Node n, params Op[] ops) => t.SetDropTarget(n, ops);

    public void SetRole(Node n, Role role) => t.SetRole(n, role);

    public void SetInset(Node n, double pad) => t.SetInset(n, pad);

    public void SetFill(Node n, bool on) => t.SetFill(n, on);

    public void SetColumnsAuto(Node n, double minWidth) =>
        t.SetColumnsAuto(n, minWidth);

    public void SetWrap(Node n, bool on) => t.SetWrap(n, on);
}

/// <summary>The duck-typed enumerable behind Rows(): no IEnumerable,
/// so LINQ never appears on a collection at record time.</summary>
readonly struct TaskRowSeq
{
    readonly RecordCollection<Task> c;

    internal TaskRowSeq(RecordCollection<Task> c) => this.c = c;

    public TaskRowEnumerator GetEnumerator() => new TaskRowEnumerator(c);
}

sealed class TaskRowEnumerator : System.IDisposable
{
    int state;
    System.Action close;
    readonly RecordCollection<Task> c;

    internal TaskRowEnumerator(RecordCollection<Task> c) => this.c = c;

    public TaskRow Current { get; private set; }

    public bool MoveNext()
    {
        if (state != 0)
            return false;
        state = 1;
        var tx = KayaApp.Ambient?.CurrentTx
            ?? throw new System.InvalidOperationException(
                "kaya: Rows() iterates at record time, inside a transaction");
        var (t, done) = tx.BeginRowTrace(c.Collection);
        close = done;
        Current = new TaskRow(t);
        return true;
    }

    public void Dispose()
    {
        close?.Invoke();
        close = null;
    }
}

sealed class TaskKayaPatch
{
    readonly RecordPatch<Task> p;

    internal TaskKayaPatch(RecordPatch<Task> p) => this.p = p;

    public TaskKayaPatch Name(string v)
    {
        p.Set(TaskKaya.Name, v);
        return this;
    }

    public TaskKayaPatch Due(System.DateOnly v)
    {
        p.Set(TaskKaya.Due, v);
        return this;
    }
}
