-- kaya runtime for Haskell guests: loading, the direct-ring occurrence
-- loop, submit, and blob registration. Hand-written; the wire
-- vocabulary next to it
-- (KayaWire.hs) is generated by kaya-bindgen, and kaya_hs_stubs.c
-- carries the two ordered cursor accesses.
--
-- The direct tier: plain peeks on the ring's memory — GHC inlines them
-- to real loads — with ordering carried by the C stubs imported `ccall
-- unsafe` (GHC's own Addr# atomics are the wrong shape; see the stubs'
-- header). Blocking entries are `ccall safe`, releasing the capability
-- while C blocks; the -threaded runtime is required. Link against
-- libkaya at build time; kaya_run must own the process main thread, and
-- GHC's main runs bound to it.
module KayaRuntime (kayaRun, kayaSubmit, pollOccurrence, waitOccurrences, wake, registerBlob, openPicked) where

import Data.Bits ((.&.))
import qualified Data.ByteString as BS
import Data.ByteString.Builder (Builder, toLazyByteString)
import qualified Data.ByteString.Lazy as BL
import Data.ByteString.Unsafe (unsafeUseAsCStringLen)
import Data.IORef (IORef, newIORef, readIORef, writeIORef)
import Data.Int (Int32, Int64)
import Data.Word (Word16, Word32, Word64, Word8)
import Foreign.C.Types (CBool (..), CSize (..))
import Foreign.Marshal.Alloc (alloca, mallocBytes)
import Foreign.Ptr (Ptr, castPtr, plusPtr)
import Foreign.Storable (peek, peekByteOff)
import GHC.IO.Handle.FD (fdToHandle)
import System.IO (Handle)
import System.IO.Unsafe (unsafePerformIO)

import KayaWire (Value, parseOccurrence, specHash)

foreign import ccall safe "kaya_run"
  c_kaya_run :: IO Int32

foreign import ccall safe "kaya_wake"
  c_kaya_wake :: IO ()

foreign import ccall unsafe "kaya_occurrence_ring"
  c_kaya_occurrence_ring :: Ptr () -> IO ()

-- | Redeem a picked handle: the OS handle lands in the first out-param
-- and seekability in the second; 0 is success.
--
-- SAFE, not unsafe: it BLOCKS, and may block for a long time — a cloud
-- provider can download the file before it answers — so the RTS must
-- keep running other threads while it does.
foreign import ccall safe "kaya_open_picked"
  c_kaya_open_picked :: Word64 -> Word32 -> Ptr Int64 -> Ptr Word32 -> IO Int32

foreign import ccall safe "kaya_wait_occurrences"
  c_kaya_wait_occurrences :: IO CBool

foreign import ccall unsafe "kaya_spec_hash"
  c_kaya_spec_hash :: IO Word64

foreign import ccall unsafe "kaya_submit"
  c_kaya_submit :: Ptr Word8 -> CSize -> IO ()

foreign import ccall unsafe "kaya_blob_register"
  c_kaya_blob_register :: Ptr Word8 -> CSize -> IO Word64

-- The ordered cursor accesses; see kaya_hs_stubs.c.
foreign import ccall unsafe "kaya_hs_load_acquire_u32"
  loadAcquireU32 :: Ptr Word32 -> IO Word32

foreign import ccall unsafe "kaya_hs_store_release_u32"
  storeReleaseU32 :: Ptr Word32 -> Word32 -> IO ()

-- | Enter the core on the calling thread (which must be the process
-- main thread); returns the exit code when the app ends.
-- The stale-artifact guard: this binding was generated from one spec
-- revision; the loaded library must speak the same one.
checkSpec :: IO ()
checkSpec = do
  got <- c_kaya_spec_hash
  if got == specHash
    then return ()
    else
      error
        ("kaya: library speaks spec " ++ show got
           ++ ", this binding was generated from " ++ show specHash
           ++ " — rebuild the library or regenerate bindings")

kayaRun :: IO Int32
kayaRun = checkSpec >> c_kaya_run

-- | Submit one transaction: the concatenation of packed records (tx*
-- results from KayaWire), applied atomically.
kayaSubmit :: [Builder] -> IO ()
kayaSubmit records =
  unsafeUseAsCStringLen (BL.toStrict (toLazyByteString (mconcat records))) $
    \(p, len) -> c_kaya_submit (castPtr p) (fromIntegral len)

-- | Register bulk payload bytes (an encoded image) with the core: one
-- copy into core-owned memory, returning the u64 handle. The handle is
-- consumed by the next submit from this guest, referenced or not; the
-- caller's bytes are free to drop the moment this returns.
registerBlob :: BS.ByteString -> IO Word64
registerBlob bytes =
  unsafeUseAsCStringLen bytes $ \(p, len) ->
    c_kaya_blob_register (castPtr p) (fromIntegral len)

data Ring = Ring (Ptr Word8) Word32 (Ptr Word32) (Ptr Word32) Word32

{-# NOINLINE ringRef #-}
ringRef :: IORef (Maybe Ring)
ringRef = unsafePerformIO (newIORef Nothing)

ring :: IO Ring
ring = do
  cached <- readIORef ringRef
  case cached of
    Just r -> return r
    Nothing -> do
      -- KayaRingInfo, as declared in kaya.h:
      -- { u8 *data; u32 capacity; u32 *head; u32 *tail } — offsets
      -- 0/8/16/24.
      info <- mallocBytes 32
      c_kaya_occurrence_ring info
      dat <- peekByteOff info 0 :: IO (Ptr Word8)
      capacity <- peekByteOff info 8 :: IO Word32
      headPtr <- peekByteOff info 16 :: IO (Ptr Word32)
      tailPtr <- peekByteOff info 24 :: IO (Ptr Word32)
      h0 <- loadAcquireU32 headPtr
      let r = Ring dat capacity headPtr tailPtr h0
      writeIORef ringRef (Just r)
      return r

-- | Block for the next occurrence; Nothing when the core has shut
-- down. Keys are [] when the id is a widget id, else the id is a
-- template node id and the keys are the stamped copy's key path,
-- outermost first; the last member is the payload — the entry's new
-- text (a VStr) for text_changed, the checkbox's new state (a VBool)
-- for toggled. Single consumer.
-- Return the app thread from waitOccurrences. Safe from any thread;
-- the binding calls it from KayaApp\'s post, and guests do not name it.
wake :: IO ()
wake = c_kaya_wake

-- Block until there MAY be something to do: a record arrived, or
-- another thread called wake. False once the core has shut down.
-- "May" is the honest word — a wake returns True with the ring still
-- empty, and the caller re-checks both sources, which a drain-then-poll
-- loop does anyway.
waitOccurrences :: IO Bool
waitOccurrences = do
  more <- c_kaya_wait_occurrences
  return (more /= CBool 0)

-- Read the next occurrence if one is ready, WITHOUT blocking; Nothing
-- means the ring is empty right now.
--
-- Polling and waiting are separate actions, rather than one blocking
-- nextOccurrence, because the app thread has a SECOND source of work:
-- actions posted from other threads. A single blocking read would park
-- inside C with no way back out to run them.
pollOccurrence :: IO (Maybe (Word16, Word64, [Value], Maybe Value))
pollOccurrence = do
  Ring dat capacity headPtr tailPtr h <- ring
  let mask = capacity - 1
      loop hh = do
        t <- loadAcquireU32 tailPtr -- acquire: records below are visible
        if hh == t
          then return Nothing -- nothing ready; the caller waits
          else do
            let at = fromIntegral (hh .&. mask)
            size <- peekByteOff dat at :: IO Word32
            parsed <- parseOccurrence (dat `plusPtr` at)
            -- Word32 wraps on its own; hand the space back with release.
            let hh' = hh + size
            storeReleaseU32 headPtr hh'
            cached <- readIORef ringRef
            case cached of
              Just (Ring d c hp tp _) ->
                writeIORef ringRef (Just (Ring d c hp tp hh'))
              Nothing -> return ()
            case parsed of
              Just occ -> return (Just occ)
              Nothing -> loop hh'
  loop h

-- | Redeem a picked handle for a real 'Handle', plus whether it seeks.
--
-- BLOCKS, and may block for a long time, so call it from a thread you
-- chose and post the result back (DESIGN.md, File dialogs).
--
-- THE DESCRIPTOR BECOMES GHC'S: 'fdToHandle' takes it over, so
-- 'hClose' closes it exactly once and the core keeps no claim.
--
-- Seekable rides the OPEN rather than the pick because that is the only
-- place the answer exists: an Android provider may hand back a pipe,
-- and nothing short of opening reveals it.
openPicked :: Word64 -> Word32 -> IO (Handle, Bool)
openPicked handle mode =
  alloca $ \rawPtr -> alloca $ \seekPtr -> do
    rc <- c_kaya_open_picked handle mode rawPtr seekPtr
    if rc /= 0
      then
        ioError
          (userError ("kaya: opening the picked file failed (code " ++ show rc ++ ")"))
      else do
        raw <- peek rawPtr
        seekable <- peek seekPtr
        h <- fdToHandle (fromIntegral raw)
        return (h, seekable /= 0)
