// Code generated by kaya-swift-gen; DO NOT EDIT.
// Regenerate with tools/gen-guests.sh (which also checks freshness).

import Foundation

extension Post: KayaSumElement {
    /// One prototype per constructor, in declaration order — the
    /// one spelling of the constructor order.
    static var prototypes: [Post] {
        [
            .note(text: ""),
            .todo(title: "", done: false),
        ]
    }

    init(variant: UInt32, values: [KayaValue]) {
        switch variant {
        case 0:
            guard case .str(let text) = values[0] else {
                preconditionFailure("kaya: note fields out of order")
            }
            self = .note(text: text)
        case 1:
            guard case .str(let title) = values[0], case .bool(let done) = values[1] else {
                preconditionFailure("kaya: todo fields out of order")
            }
            self = .todo(title: title, done: done)
        default:
            preconditionFailure("kaya: Post has no variant \(variant)")
        }
    }
}

/// note's typed field tokens.
enum PostNoteFields {
    static let text = KayaField<String>(index: 0)
}

/// todo's typed field tokens.
enum PostTodoFields {
    static let title = KayaField<String>(index: 0)
    static let done = KayaField<Bool>(index: 1)
}

/// note's refined arm vocabulary: typed tokens, no label
/// strings.
struct PostNoteArm {
    let t: KayaTpl
    let text = PostNoteFields.text

    func label(_ f: KayaField<String>) -> KayaNodeHandle {
        t.label(f)
    }

    func checkbox(
        _ f: KayaField<Bool>,
        onToggle: ((KayaAppTx, [KayaValue], Bool) -> Void)? = nil
    ) -> KayaNodeHandle {
        t.checkbox(f, onToggle: onToggle)
    }

    func row(@KayaNodeChildren _ children: () -> Void) -> KayaNodeHandle {
        t.row(children)
    }

    func column(@KayaNodeChildren _ children: () -> Void) -> KayaNodeHandle {
        t.column(children)
    }
}

/// todo's refined arm vocabulary: typed tokens, no label
/// strings.
struct PostTodoArm {
    let t: KayaTpl
    let title = PostTodoFields.title
    let done = PostTodoFields.done

    func label(_ f: KayaField<String>) -> KayaNodeHandle {
        t.label(f)
    }

    func checkbox(
        _ f: KayaField<Bool>,
        onToggle: ((KayaAppTx, [KayaValue], Bool) -> Void)? = nil
    ) -> KayaNodeHandle {
        t.checkbox(f, onToggle: onToggle)
    }

    func row(@KayaNodeChildren _ children: () -> Void) -> KayaNodeHandle {
        t.row(children)
    }

    func column(@KayaNodeChildren _ children: () -> Void) -> KayaNodeHandle {
        t.column(children)
    }
}

/// The collection factory: the constructor order lives in the
/// generated prototypes.
func postCollection(_ tx: KayaAppTx) -> KayaSumCollection<Post> {
    tx.sumCollection(of: Post.self)
}

/// The compile-total eliminator: one required labeled parameter
/// per constructor, with the scene checking totality again.
func postEachSum(
    _ tx: KayaAppTx, _ c: KayaSumCollection<Post>,
    note: @escaping (PostNoteArm) -> Void,
    todo: @escaping (PostTodoArm) -> Void
) -> KayaWidget {
    tx.eachSum(
        c,
        arms: [
            c.arm(.note(text: "")) { t, _ in note(PostNoteArm(t: t)) },
            c.arm(.todo(title: "", done: false)) { t, _ in todo(PostTodoArm(t: t)) },
        ])
}

/// postAsNote re-eliminates at call time: the optional is
/// the refinement, fresh at write time — a stale occurrence folds
/// into nil — and each setter's update witnesses note, asserted
/// again by the scene.
func postAsNote(
    _ tx: KayaAppTx, _ c: KayaSumCollection<Post>, _ key: KayaValue
) -> PostNotePatch? {
    guard let current = c.get(tx, key), current.kayaVariant == 0 else {
        return nil
    }
    return PostNotePatch(tx: tx, c: c, key: key)
}

/// note's refined patch: named setters over the witnessed
/// update.
struct PostNotePatch {
    let tx: KayaAppTx
    let c: KayaSumCollection<Post>
    let key: KayaValue

    @discardableResult
    func text(_ v: String) -> PostNotePatch {
        c.updateField(
            tx, key, of: .note(text: ""),
            PostNoteFields.text, .str(v))
        return self
    }
}

/// postAsTodo re-eliminates at call time: the optional is
/// the refinement, fresh at write time — a stale occurrence folds
/// into nil — and each setter's update witnesses todo, asserted
/// again by the scene.
func postAsTodo(
    _ tx: KayaAppTx, _ c: KayaSumCollection<Post>, _ key: KayaValue
) -> PostTodoPatch? {
    guard let current = c.get(tx, key), current.kayaVariant == 1 else {
        return nil
    }
    return PostTodoPatch(tx: tx, c: c, key: key)
}

/// todo's refined patch: named setters over the witnessed
/// update.
struct PostTodoPatch {
    let tx: KayaAppTx
    let c: KayaSumCollection<Post>
    let key: KayaValue

    @discardableResult
    func title(_ v: String) -> PostTodoPatch {
        c.updateField(
            tx, key, of: .todo(title: "", done: false),
            PostTodoFields.title, .str(v))
        return self
    }

    @discardableResult
    func done(_ v: Bool) -> PostTodoPatch {
        c.updateField(
            tx, key, of: .todo(title: "", done: false),
            PostTodoFields.done, .bool(v))
        return self
    }
}
