// Code generated by kaya-swift-gen; DO NOT EDIT.
// Regenerate with tools/gen-guests.py (which also checks freshness).

import Foundation

extension Task: KayaRecord {
    /// The prototype Mirror walks for the schema; every field at
    /// its zero value.
    static let prototype = Task(name: "", due: KayaDate(year: 1970, month: 1, day: 1))

    init(values: [KayaValue]) {
        guard case .str(let name) = values[0], case .i64(let due) = values[1] else {
            preconditionFailure("kaya: Task fields out of order")
        }
        self.init(name: name, due: kayaDate(packed: due))
    }
}

/// Task's typed field tokens.
enum TaskFields {
    static let name = KayaField<String>(index: 0)
    static let due = KayaField<KayaDate>(index: 1)
}

/// The collection factory; the struct is the schema.
func taskCollection(_ tx: KayaAppTx) -> KayaRecordCollection<Task> {
    tx.collection(of: Task.self)
}

/// The row surface: the template handle plus one token per wire
/// field, and the constructors that consume them.
struct TaskRow {
    let t: KayaTpl
    let name = TaskFields.name
    let due = TaskFields.due

    func label(_ f: KayaField<String>) -> KayaNodeHandle {
        t.label(f)
    }

    func image(_ f: KayaField<Data>) -> KayaNodeHandle {
        t.image(f)
    }

    func checkbox(
        _ f: KayaField<Bool>,
        onToggle: ((KayaAppTx, [KayaValue], Bool) -> Void)? = nil
    ) -> KayaNodeHandle {
        t.checkbox(f, onToggle: onToggle)
    }

    func datePicker(
        _ f: KayaField<KayaDate>,
        onDate: ((KayaAppTx, [KayaValue], KayaDate) -> Void)? = nil
    ) -> KayaNodeHandle {
        t.datePicker(f, onDate: onDate)
    }

    func timePicker(
        _ f: KayaField<KayaTime>,
        onTime: ((KayaAppTx, [KayaValue], KayaTime) -> Void)? = nil
    ) -> KayaNodeHandle {
        t.timePicker(f, onTime: onTime)
    }

    func row(@KayaNodeChildren _ children: () -> Void) -> KayaNodeHandle {
        t.row(children)
    }

    func column(@KayaNodeChildren _ children: () -> Void) -> KayaNodeHandle {
        t.column(children)
    }
}

extension KayaRecordCollection where T == Task {
    /// The for-statement form: `for row in tasks.rows { … }`
    /// traces the record template — the body runs once, and the
    /// tracer plants the For in the enclosing container builder.
    var rows: KayaRowTrace<TaskRow> {
        KayaRowTrace(collection: collection) { TaskRow(t: $0) }
    }
}

/// The record template, expression form: the body runs once,
/// authoring the blueprint with the typed row surface; stamping is
/// the core's replay.
func taskEach(
    _ tx: KayaAppTx, _ c: KayaRecordCollection<Task>,
    _ body: @escaping (TaskRow) -> Void
) -> KayaWidget {
    tx.each(c.collection) { t in body(TaskRow(t: t)) }
}
