// Code generated by kaya-swift-gen; DO NOT EDIT.
// Regenerate with tools/gen-guests.py (which also checks freshness).

import Foundation

extension TableItem: KayaRecord {
    /// The prototype Mirror walks for the schema; every field at
    /// its zero value.
    static let prototype = TableItem(name: "", size: "")

    init(values: [KayaValue]) {
        guard case .str(let name) = values[0], case .str(let size) = values[1] else {
            preconditionFailure("kaya: TableItem fields out of order")
        }
        self.init(name: name, size: size)
    }
}

/// TableItem's typed field tokens.
enum TableItemFields {
    static let name = KayaField<String>(index: 0)
    static let size = KayaField<String>(index: 1)
}

/// The collection factory; the struct is the schema.
func tableItemCollection(_ tx: KayaAppTx) -> KayaRecordCollection<TableItem> {
    tx.collection(of: TableItem.self)
}

/// The row surface: the template handle plus one token per wire
/// field, and the constructors that consume them.
struct TableItemRow {
    let t: KayaTpl
    let name = TableItemFields.name
    let size = TableItemFields.size

    func label(_ f: KayaField<String>) -> KayaNodeHandle {
        t.label(f)
    }

    func image(_ f: KayaField<Data>) -> KayaNodeHandle {
        t.image(f)
    }

    func checkbox(
        _ f: KayaField<Bool>,
        onToggle: ((KayaAppTx, [KayaValue], Bool) -> Void)? = nil
    ) -> KayaNodeHandle {
        t.checkbox(f, onToggle: onToggle)
    }

    func datePicker(
        _ f: KayaField<KayaDate>,
        onDate: ((KayaAppTx, [KayaValue], KayaDate) -> Void)? = nil
    ) -> KayaNodeHandle {
        t.datePicker(f, onDate: onDate)
    }

    func timePicker(
        _ f: KayaField<KayaTime>,
        onTime: ((KayaAppTx, [KayaValue], KayaTime) -> Void)? = nil
    ) -> KayaNodeHandle {
        t.timePicker(f, onTime: onTime)
    }

    func row(@KayaNodeChildren _ children: () -> Void) -> KayaNodeHandle {
        t.row(children)
    }

    func column(@KayaNodeChildren _ children: () -> Void) -> KayaNodeHandle {
        t.column(children)
    }
}

extension KayaRecordCollection where T == TableItem {
    /// The for-statement form: `for row in tableItems.rows { … }`
    /// traces the record template — the body runs once, and the
    /// tracer plants the For in the enclosing container builder.
    var rows: KayaRowTrace<TableItemRow> {
        KayaRowTrace(collection: collection) { TableItemRow(t: $0) }
    }
}

/// The record template, expression form: the body runs once,
/// authoring the blueprint with the typed row surface; stamping is
/// the core's replay.
func tableItemEach(
    _ tx: KayaAppTx, _ c: KayaRecordCollection<TableItem>,
    _ body: @escaping (TableItemRow) -> Void
) -> KayaWidget {
    tx.each(c.collection) { t in body(TableItemRow(t: t)) }
}
