(* kaya wire vocabulary. Generated by kaya-bindgen from kaya::spec — do not edit.

   Records are {u32 size, u16 kind, u16 flags}, body, padded to 8,
   little-endian; each tx_* returns one packed record, and a
   transaction is their concatenation. *)

(* Blob carries the u64 handle from kaya_blob_register (as int64),
   consumed by the next submit; the bytes never ride the record
   stream. *)
type value =
  | Bool of bool
  | I64 of int64
  | F64 of float
  | Str of string
  | Blob of int64

(* spec_hash: the protocol fingerprint; the runtime asserts the loaded core agrees. *)
let spec_hash = 0x4d40b317286880f6L

let value_bool = 1
let value_i64 = 2
let value_f64 = 3
let value_str = 4
let value_blob = 5
let kind_column = 1
let kind_button = 2
let kind_label = 3
let kind_entry = 4
let kind_row = 5
let kind_checkbox = 6
let kind_slider = 7
let kind_image = 8
let kind_scroll = 9
let kind_progress = 10
let kind_select = 11
let kind_radio = 12
let kind_grid = 13
let kind_textarea = 14
let prop_text = 1
let prop_checked = 2
let prop_value = 3
let prop_min = 4
let prop_max = 5
let prop_source = 6
let prop_grow = 7
let prop_spacing = 8
let prop_align = 9
let prop_indeterminate = 10
let prop_columns = 11
let prop_a11y_id = 12
let prop_a11y_label = 13
let prop_a11y_hint = 14
let wprop_title = 1
let wprop_width = 2
let wprop_height = 3
let wprop_veto_close = 4
let wprop_sections_presentation = 5
let wprop_list_detail = 6
let eprop_title = 1
let eprop_intercept_back = 2
let sprop_title = 1
let sprop_icon = 2
let menu_kind_menu = 1
let menu_kind_action = 2
let menu_kind_toggle = 3
let menu_kind_radio_group = 4
let menu_kind_radio_option = 5
let menu_kind_separator = 6
let mprop_label = 1
let mprop_enabled = 2
let mprop_checked = 3
let mprop_value = 4
let mprop_icon = 5
let mprop_primary = 6
let mprop_shortcut = 7
let mprop_role = 8
let sections_presentation_auto = 0
let sections_presentation_bar = 1
let sections_presentation_sidebar = 2
let alert_choice_action0 = 0
let alert_choice_action1 = 1
let alert_choice_cancel = 4294967295
let file_mode_read = 0
let file_mode_write = 1
let file_mode_read_write = 2
let align_start = 0
let align_center = 1
let align_end = 2
let align_stretch = 3
let align_baseline = 4
let source_const = 0
let source_signal = 1
let source_element = 2
let occurrence_pad = 0
let occurrence_button_clicked = 1
let occurrence_text_changed = 2
let occurrence_toggled = 3
let occurrence_value_changed = 4
let command_clear = 1
let command_focus = 2
let tx_kind_create_signal = 1
let tx_kind_write_signal = 2
let tx_kind_create_widget = 3
let tx_kind_set_property = 4
let tx_kind_add_child = 5
let tx_kind_mount = 6
let tx_kind_create_collection = 7
let tx_kind_collection_insert = 8
let tx_kind_collection_update = 9
let tx_kind_collection_remove = 10
let tx_kind_create_for = 11
let tx_kind_create_when = 12
let tx_kind_template_end = 13
let tx_kind_collection_move = 15
let tx_kind_collection_update_field = 14
let tx_kind_variant_case = 16
let tx_kind_widget_command = 17
let tx_kind_set_window_prop = 18
let tx_kind_create_window = 19
let tx_kind_destroy_window = 20
let tx_kind_show_alert = 21
let tx_kind_push_entry = 22
let tx_kind_pop_entry = 23
let tx_kind_set_entry_prop = 24
let tx_kind_add_section = 25
let tx_kind_select_section = 26
let tx_kind_set_section_prop = 27
let tx_kind_menu_item_create = 28
let tx_kind_menu_item_append = 29
let tx_kind_menubar_append = 30
let tx_kind_context_attach = 31
let tx_kind_context_attach_node = 32
let tx_kind_set_menu_prop = 33
let tx_kind_show_file_dialog = 34
let apply_kind_create = 1
let apply_kind_set_prop = 2
let apply_kind_add_child = 3
let apply_kind_mount = 4
let apply_kind_move_child = 6
let apply_kind_destroy = 5
let apply_kind_command = 7
let apply_kind_set_window_prop = 8
let apply_kind_create_window = 9
let apply_kind_destroy_window = 10
let apply_kind_present_alert = 11
let apply_kind_push_entry = 12
let apply_kind_pop_entry = 13
let apply_kind_set_entry_prop = 14
let apply_kind_add_section = 15
let apply_kind_select_section = 16
let apply_kind_set_section_prop = 17
let apply_kind_menu_item_create = 18
let apply_kind_menu_item_append = 19
let apply_kind_menubar_append = 20
let apply_kind_context_attach = 21
let apply_kind_context_attach_node = 22
let apply_kind_set_menu_prop = 23
let apply_kind_present_file_dialog = 24
let occ_kind_button_clicked = 1
let occ_kind_text_changed = 2
let occ_kind_toggled = 3
let occ_kind_value_changed = 4
let occ_kind_close_requested = 5
let occ_kind_window_closed = 6
let occ_kind_alert_result = 7
let occ_kind_entry_popped = 8
let occ_kind_back_requested = 9
let occ_kind_section_selected = 10
let occ_kind_menu_activated = 11
let occ_kind_menu_toggled = 12
let occ_kind_menu_value_changed = 13
let occ_kind_file_dialog_result = 14

let pad8 b =
  while Buffer.length b mod 8 <> 0 do
    Buffer.add_char b '\000'
  done

(* Values self-pad to 8: they concatenate inside record bodies. *)
let encode_value b v =
  (match v with
  | Bool x ->
      Buffer.add_int32_le b (Int32.of_int value_bool);
      Buffer.add_int32_le b 1l;
      Buffer.add_char b (if x then '\001' else '\000')
  | I64 x ->
      Buffer.add_int32_le b (Int32.of_int value_i64);
      Buffer.add_int32_le b 8l;
      Buffer.add_int64_le b x
  | F64 x ->
      Buffer.add_int32_le b (Int32.of_int value_f64);
      Buffer.add_int32_le b 8l;
      Buffer.add_int64_le b (Int64.bits_of_float x)
  | Str x ->
      Buffer.add_int32_le b (Int32.of_int value_str);
      Buffer.add_int32_le b (Int32.of_int (String.length x));
      Buffer.add_string b x
  | Blob x ->
      Buffer.add_int32_le b (Int32.of_int value_blob);
      Buffer.add_int32_le b 8l;
      Buffer.add_int64_le b x);
  pad8 b

(* A key path: {u32 count, u32 reserved, count values}. *)
(* A counted value sequence: a key path or a record. *)
let encode_values b vals =
  Buffer.add_int32_le b (Int32.of_int (List.length vals));
  Buffer.add_int32_le b 0l;
  List.iter (encode_value b) vals

(* A collection's element sum: per variant, counted value-type tags,
   padded to 8. A record collection is the one-variant case. *)
let encode_variant_schemas b variants =
  Buffer.add_int32_le b (Int32.of_int (List.length variants));
  Buffer.add_int32_le b 0l;
  List.iter
    (fun schema ->
      Buffer.add_int32_le b (Int32.of_int (List.length schema));
      List.iter (fun t -> Buffer.add_int32_le b (Int32.of_int t)) schema)
    variants;
  pad8 b

let finish kind fill =
  let b = Buffer.create 64 in
  Buffer.add_int32_le b 0l;
  Buffer.add_int16_le b kind;
  Buffer.add_int16_le b 0;
  fill b;
  pad8 b;
  let s = Bytes.of_string (Buffer.contents b) in
  Bytes.set_int32_le s 0 (Int32.of_int (Bytes.length s));
  Bytes.to_string s

(* Create a signal holding `initial`. *)
let tx_create_signal signal_id initial =
  finish tx_kind_create_signal (fun b ->
      Buffer.add_int64_le b signal_id;
      encode_value b initial)

(* Replace a signal's value; keep-latest per batch. *)
let tx_write_signal signal_id value =
  finish tx_kind_write_signal (fun b ->
      Buffer.add_int64_le b signal_id;
      encode_value b value)

(* Create a live widget, or declare a template node inside a scope. *)
let tx_create_widget widget_id kind =
  finish tx_kind_create_widget (fun b ->
      Buffer.add_int64_le b widget_id;
      Buffer.add_int32_le b (Int32.of_int kind);
      Buffer.add_int32_le b 0l)

(* Append `child` to `parent` (same zone only). *)
let tx_add_child parent child =
  finish tx_kind_add_child (fun b ->
      Buffer.add_int64_le b parent;
      Buffer.add_int64_le b child)

(* Mount a root into a window (0 = the default window). *)
let tx_mount window root =
  finish tx_kind_mount (fun b ->
      Buffer.add_int64_le b window;
      Buffer.add_int64_le b root)

(* Declare a collection and its schema: one ordered field-type list per variant of the element sum. A record collection is the one-variant case and a scalar collection the one-variant one-field case. Variants are indices; names never travel. A blueprint when inside a template. *)
let tx_create_collection collection_id variants =
  finish tx_kind_create_collection (fun b ->
      Buffer.add_int64_le b collection_id;
      encode_variant_schemas b variants)

(* Insert an entry into the instance at `path`; the fields match `variant`'s schema positionally. Stamps a copy from that variant's case. *)
let tx_collection_insert collection_id path key variant fields =
  finish tx_kind_collection_insert (fun b ->
      Buffer.add_int64_le b collection_id;
      encode_values b path;
      encode_value b key;
      Buffer.add_int32_le b (Int32.of_int variant);
      Buffer.add_int32_le b 0l;
      encode_values b fields)

(* Replace an entry's record; every element binding follows. A different `variant` than the entry's current one tears down its stamped copy and restamps from the new variant's case, in place. *)
let tx_collection_update collection_id path key variant fields =
  finish tx_kind_collection_update (fun b ->
      Buffer.add_int64_le b collection_id;
      encode_values b path;
      encode_value b key;
      Buffer.add_int32_le b (Int32.of_int variant);
      Buffer.add_int32_le b 0l;
      encode_values b fields)

(* Remove an entry; its stamped copy tears down. *)
let tx_collection_remove collection_id path key =
  finish tx_kind_collection_remove (fun b ->
      Buffer.add_int64_le b collection_id;
      encode_values b path;
      encode_value b key)

(* A For over a collection; opens a template scope until template_end. *)
let tx_create_for id collection_id =
  finish tx_kind_create_for (fun b ->
      Buffer.add_int64_le b id;
      Buffer.add_int64_le b collection_id)

(* A When over a Bool signal; opens a template scope until template_end. *)
let tx_create_when id signal_id =
  finish tx_kind_create_when (fun b ->
      Buffer.add_int64_le b id;
      Buffer.add_int64_le b signal_id)

(* Close the innermost template scope. *)
let tx_template_end () =
  finish tx_kind_template_end (fun b ->
      ignore b)

(* Move an entry so it sits before the entry whose key is the one value in `before`, or to the end when `before` is empty. Keys, never indices: order is data, and indices would race the very deltas that change them. *)
let tx_collection_move collection_id path key before =
  finish tx_kind_collection_move (fun b ->
      Buffer.add_int64_le b collection_id;
      encode_values b path;
      encode_value b key;
      encode_values b before)

(* Set one field of an entry's record; only bindings on that field re-resolve. `variant` is the discriminant the guest witnessed in the match that produced this write — the scene asserts it against the entry's stored variant, so a drifted model fails loudly; it never changes a constructor (update does). *)
let tx_collection_update_field collection_id path key field variant value =
  finish tx_kind_collection_update_field (fun b ->
      Buffer.add_int64_le b collection_id;
      encode_values b path;
      encode_value b key;
      Buffer.add_int32_le b (Int32.of_int field);
      Buffer.add_int32_le b (Int32.of_int variant);
      encode_value b value)

(* Inside a For over a sum: the records that follow (until the next variant_case or template_end) are the blueprint for this variant. Cases must be total at template_end; an empty case renders a constructor as nothing, explicitly. *)
let tx_variant_case variant =
  finish tx_kind_variant_case (fun b ->
      Buffer.add_int32_le b (Int32.of_int variant);
      Buffer.add_int32_le b 0l)

(* A one-shot command aimed at a live widget: momentary, fire-and-forget, never state at rest — the app's sanctioned crossing into widget-owned state (clear, focus). The widget answers through its normal occurrence path; nothing is recorded and nothing replays on rebuild. The command enum is the closed vocabulary; each verb is admitted by a real artifact, per the escalation policy. *)
let tx_widget_command widget_id command =
  finish tx_kind_widget_command (fun b ->
      Buffer.add_int64_le b widget_id;
      Buffer.add_int32_le b (Int32.of_int command);
      Buffer.add_int32_le b 0l)

(* Create an auxiliary window (capability-gated: a host without KAYA_CAP_AUX_WINDOWS rejects it at the root). Materializes hidden; mounting a root presents it. Ids are guest-allocated, below the internal bit; 0 is the primary and always exists. *)
let tx_create_window window_id =
  finish tx_kind_create_window (fun b ->
      Buffer.add_int64_le b window_id)

(* Close and forget an auxiliary window: the native window and its views are released wholesale, and the scene forgets the mounted tree (widget ids are never reused, so stale entries are inert). The primary is not destroyable: the process owns it. *)
let tx_destroy_window window_id =
  finish tx_kind_destroy_window (fun b ->
      Buffer.add_int64_le b window_id)

(* Request a modal alert over a live window (0 = primary): the request/result grammar's first client (DESIGN.md, Presentation contexts). One atomic record: title, message, `actions` action labels (0..=2 — the platform floor; ContentDialog's three slots are two actions plus close), and the always-present cancel slot, which is what EVERY platform-native dismissal (Esc, back, outside tap) resolves to. All five Values are Str; action slots beyond `actions` ride empty and are ignored. Alert ids are guest-chosen; one alert may be live per process, and the id retires when its result fires. *)
let tx_show_alert window alert actions title message action0 action1 cancel =
  finish tx_kind_show_alert (fun b ->
      Buffer.add_int64_le b window;
      Buffer.add_int64_le b alert;
      Buffer.add_int32_le b (Int32.of_int actions);
      Buffer.add_int32_le b 0l;
      encode_value b title;
      encode_value b message;
      encode_value b action0;
      encode_value b action1;
      encode_value b cancel)

(* Push a navigation entry onto `window`'s stack (0 = the primary surface; no capability gate — every host materializes a serial stack natively). Entry ids share the surface namespace with windows: one guest-side allocator, and mount's target field addresses either. Materializes covered/incoming; mounting a root into it presents it. The covered root below stays alive — retained until popped (DESIGN.md, Navigation). *)
let tx_push_entry window entry =
  finish tx_kind_push_entry (fun b ->
      Buffer.add_int64_le b window;
      Buffer.add_int64_le b entry)

(* Pop the top navigation entry from `window`'s stack and forget its mounted tree, exactly as destroy_window does (ids are never reused, so stale targets fail loudly). Popping an empty stack is a scene error. Multi-pop is binding sugar: N of these in one transaction, animated by backends as the NET stack change per batch. *)
let tx_pop_entry window =
  finish tx_kind_pop_entry (fun b ->
      Buffer.add_int64_le b window)

(* Bind a navigation-entry property (ENTRY_PROPS). Same tail convention as SET_PROPERTY_NOTE, except SOURCE_ELEMENT is rejected — entries are not collection elements. *)
let tx_set_entry_prop entry prop source =
  finish tx_kind_set_entry_prop (fun b ->
      Buffer.add_int64_le b entry;
      Buffer.add_int32_le b (Int32.of_int prop);
      Buffer.add_int32_le b (Int32.of_int source))

(* Append a section to `window`'s section set (0 = the primary surface; no capability gate — every platform has a sections idiom). Section ids share the surface namespace with windows and entries: one guest-side allocator, and mount's target field addresses any of them. The first section added becomes the selected one; the set is APPEND-ONLY — this grammar has no destruction verbs by design, and every section's root is retained while covered (DESIGN.md, Sections). *)
let tx_add_section window section =
  finish tx_kind_add_section (fun b ->
      Buffer.add_int64_le b window;
      Buffer.add_int64_le b section)

(* Select a section programmatically: configuration, not a user act — it never echoes section_selected (the echo doctrine). The section must already be added to `window`; switching is SELECTION, not lifecycle — the covered root stays alive. *)
let tx_select_section window section =
  finish tx_kind_select_section (fun b ->
      Buffer.add_int64_le b window;
      Buffer.add_int64_le b section)

(* Bind a section property (SECTION_PROPS). Same tail convention as SET_PROPERTY_NOTE, except SOURCE_ELEMENT is rejected — sections are not collection elements. *)
let tx_set_section_prop section prop source =
  finish tx_kind_set_section_prop (fun b ->
      Buffer.add_int64_le b section;
      Buffer.add_int32_le b (Int32.of_int prop);
      Buffer.add_int32_le b (Int32.of_int source))

(* Create a menu item of `kind` (menu_kind) in the menu-item id space — its own guest allocator (c_menu_item), distinct from every widget, node, and surface space. Items are live, append-only, and never removed in v1 (DESIGN.md, Menus). *)
let tx_menu_item_create item kind =
  finish tx_kind_menu_item_create (fun b ->
      Buffer.add_int64_le b item;
      Buffer.add_int32_le b (Int32.of_int kind);
      Buffer.add_int32_le b 0l)

(* Append `child` under grouping node `parent`. Single-parent: an item acquires exactly one parent or anchor and ids are never reused. The closed parent/child grammar (menu accepts menu/radio_group/action/toggle/separator; radio_group accepts only radio_option; leaves accept nothing) and the depth cap are validated at the root. *)
let tx_menu_item_append parent child =
  finish tx_kind_menu_item_append (fun b ->
      Buffer.add_int64_le b parent;
      Buffer.add_int64_le b child)

(* Append a top-level grouping node (menu or radio_group) to `window`'s command catalog — the window anchor, riding the window construct under the window-attribute unification rule (0 = the primary surface). The bar accepts only grouping nodes; duplicate shortcuts within the window's catalog are a root error. *)
let tx_menubar_append window item =
  finish tx_kind_menubar_append (fun b ->
      Buffer.add_int64_le b window;
      Buffer.add_int64_le b item)

(* Attach a context catalog rooted at `item` to a live widget — the same command vocabulary scoped to a noun. The editable text controls (entry, textarea) reject attachment (their native edit menus are dress), a context root cannot be a radio_option, and a shortcut anywhere in the subtree is a root error (shortcuts need a window catalog home). *)
let tx_context_attach widget item =
  finish tx_kind_context_attach (fun b ->
      Buffer.add_int64_le b widget;
      Buffer.add_int64_le b item)

(* Attach a context catalog to a template node (the Tpl zone): every stamped copy shows the same catalog, and an activation carries that copy's key path — the keys ARE the noun (the on_click_node encoding). Same rejections as context_attach. *)
let tx_context_attach_node node item =
  finish tx_kind_context_attach_node (fun b ->
      Buffer.add_int64_le b node;
      Buffer.add_int64_le b item)

(* Bind a menu property (MENU_PROPS). Same tail convention as SET_PROPERTY_NOTE, except SOURCE_ELEMENT is rejected — menu items are not collection elements — and icon/primary/ shortcut reject SOURCE_SIGNAL (const-only). label and enabled fan out through the signal-write path; the domain of a signal-bound value is validated on the COMPLETE coalesced value at the transaction barrier. *)
let tx_set_menu_prop item prop source =
  finish tx_kind_set_menu_prop (fun b ->
      Buffer.add_int64_le b item;
      Buffer.add_int32_le b (Int32.of_int prop);
      Buffer.add_int32_le b (Int32.of_int source))

(* Request the platform's file picker over a live window (0 = primary), on the alert's request/result grammar (DESIGN.md, File dialogs). Dialog ids are guest-chosen; one dialog may be live per process, and the id retires when its result fires. `multiple` is 0 or 1 — every backend supports both, spelled four ways (a flag on SwiftUI and AppKit, a different METHOD on GTK and WinUI, a different CONTRACT on Android). `filters` is advisory and rides as alternating Str values, a label then its space-separated extensions: every platform treats them as a default view rather than a guarantee, so the guest still validates what it got. *)
let tx_show_file_dialog window dialog multiple filters =
  finish tx_kind_show_file_dialog (fun b ->
      Buffer.add_int64_le b window;
      Buffer.add_int64_le b dialog;
      Buffer.add_int32_le b (Int32.of_int multiple);
      Buffer.add_int32_le b 0l;
      encode_values b filters)

(* set_property with a constant text value. *)
let tx_set_text widget_id text =
  finish tx_kind_set_property (fun b ->
      Buffer.add_int64_le b widget_id;
      Buffer.add_int32_le b (Int32.of_int prop_text);
      Buffer.add_int32_le b (Int32.of_int source_const);
      encode_value b (Str text))

(* set_property with a signal-bound text value. *)
let tx_bind_text widget_id signal_id =
  finish tx_kind_set_property (fun b ->
      Buffer.add_int64_le b widget_id;
      Buffer.add_int32_le b (Int32.of_int prop_text);
      Buffer.add_int32_le b (Int32.of_int source_signal);
      Buffer.add_int64_le b signal_id)

(* set_property bound to one field of the element of the enclosing
   For, `level` Fors up (0 = nearest; field 0 for a scalar). *)
let tx_bind_text_element ?(level = 0) ?(field = 0) widget_id =
  finish tx_kind_set_property (fun b ->
      Buffer.add_int64_le b widget_id;
      Buffer.add_int32_le b (Int32.of_int prop_text);
      Buffer.add_int32_le b (Int32.of_int source_element);
      Buffer.add_int32_le b (Int32.of_int level);
      Buffer.add_int32_le b (Int32.of_int field))

(* set_property with a constant checked value. *)
let tx_set_checked widget_id checked =
  finish tx_kind_set_property (fun b ->
      Buffer.add_int64_le b widget_id;
      Buffer.add_int32_le b (Int32.of_int prop_checked);
      Buffer.add_int32_le b (Int32.of_int source_const);
      encode_value b (Bool checked))

(* set_property with a signal-bound checked value. *)
let tx_bind_checked widget_id signal_id =
  finish tx_kind_set_property (fun b ->
      Buffer.add_int64_le b widget_id;
      Buffer.add_int32_le b (Int32.of_int prop_checked);
      Buffer.add_int32_le b (Int32.of_int source_signal);
      Buffer.add_int64_le b signal_id)

(* set_property bound to one field of the element of the enclosing
   For, `level` Fors up (0 = nearest; field 0 for a scalar). *)
let tx_bind_checked_element ?(level = 0) ?(field = 0) widget_id =
  finish tx_kind_set_property (fun b ->
      Buffer.add_int64_le b widget_id;
      Buffer.add_int32_le b (Int32.of_int prop_checked);
      Buffer.add_int32_le b (Int32.of_int source_element);
      Buffer.add_int32_le b (Int32.of_int level);
      Buffer.add_int32_le b (Int32.of_int field))

(* set_property with a constant value value. *)
let tx_set_value widget_id value =
  finish tx_kind_set_property (fun b ->
      Buffer.add_int64_le b widget_id;
      Buffer.add_int32_le b (Int32.of_int prop_value);
      Buffer.add_int32_le b (Int32.of_int source_const);
      encode_value b (F64 value))

(* set_property with a signal-bound value value. *)
let tx_bind_value widget_id signal_id =
  finish tx_kind_set_property (fun b ->
      Buffer.add_int64_le b widget_id;
      Buffer.add_int32_le b (Int32.of_int prop_value);
      Buffer.add_int32_le b (Int32.of_int source_signal);
      Buffer.add_int64_le b signal_id)

(* set_property bound to one field of the element of the enclosing
   For, `level` Fors up (0 = nearest; field 0 for a scalar). *)
let tx_bind_value_element ?(level = 0) ?(field = 0) widget_id =
  finish tx_kind_set_property (fun b ->
      Buffer.add_int64_le b widget_id;
      Buffer.add_int32_le b (Int32.of_int prop_value);
      Buffer.add_int32_le b (Int32.of_int source_element);
      Buffer.add_int32_le b (Int32.of_int level);
      Buffer.add_int32_le b (Int32.of_int field))

(* set_property with a constant min value. *)
let tx_set_min widget_id min =
  finish tx_kind_set_property (fun b ->
      Buffer.add_int64_le b widget_id;
      Buffer.add_int32_le b (Int32.of_int prop_min);
      Buffer.add_int32_le b (Int32.of_int source_const);
      encode_value b (F64 min))

(* set_property with a signal-bound min value. *)
let tx_bind_min widget_id signal_id =
  finish tx_kind_set_property (fun b ->
      Buffer.add_int64_le b widget_id;
      Buffer.add_int32_le b (Int32.of_int prop_min);
      Buffer.add_int32_le b (Int32.of_int source_signal);
      Buffer.add_int64_le b signal_id)

(* set_property bound to one field of the element of the enclosing
   For, `level` Fors up (0 = nearest; field 0 for a scalar). *)
let tx_bind_min_element ?(level = 0) ?(field = 0) widget_id =
  finish tx_kind_set_property (fun b ->
      Buffer.add_int64_le b widget_id;
      Buffer.add_int32_le b (Int32.of_int prop_min);
      Buffer.add_int32_le b (Int32.of_int source_element);
      Buffer.add_int32_le b (Int32.of_int level);
      Buffer.add_int32_le b (Int32.of_int field))

(* set_property with a constant max value. *)
let tx_set_max widget_id max =
  finish tx_kind_set_property (fun b ->
      Buffer.add_int64_le b widget_id;
      Buffer.add_int32_le b (Int32.of_int prop_max);
      Buffer.add_int32_le b (Int32.of_int source_const);
      encode_value b (F64 max))

(* set_property with a signal-bound max value. *)
let tx_bind_max widget_id signal_id =
  finish tx_kind_set_property (fun b ->
      Buffer.add_int64_le b widget_id;
      Buffer.add_int32_le b (Int32.of_int prop_max);
      Buffer.add_int32_le b (Int32.of_int source_signal);
      Buffer.add_int64_le b signal_id)

(* set_property bound to one field of the element of the enclosing
   For, `level` Fors up (0 = nearest; field 0 for a scalar). *)
let tx_bind_max_element ?(level = 0) ?(field = 0) widget_id =
  finish tx_kind_set_property (fun b ->
      Buffer.add_int64_le b widget_id;
      Buffer.add_int32_le b (Int32.of_int prop_max);
      Buffer.add_int32_le b (Int32.of_int source_element);
      Buffer.add_int32_le b (Int32.of_int level);
      Buffer.add_int32_le b (Int32.of_int field))

(* set_property with a constant source value. *)
let tx_set_source widget_id handle =
  finish tx_kind_set_property (fun b ->
      Buffer.add_int64_le b widget_id;
      Buffer.add_int32_le b (Int32.of_int prop_source);
      Buffer.add_int32_le b (Int32.of_int source_const);
      encode_value b (Blob handle))

(* set_property with a signal-bound source value. *)
let tx_bind_source widget_id signal_id =
  finish tx_kind_set_property (fun b ->
      Buffer.add_int64_le b widget_id;
      Buffer.add_int32_le b (Int32.of_int prop_source);
      Buffer.add_int32_le b (Int32.of_int source_signal);
      Buffer.add_int64_le b signal_id)

(* set_property bound to one field of the element of the enclosing
   For, `level` Fors up (0 = nearest; field 0 for a scalar). *)
let tx_bind_source_element ?(level = 0) ?(field = 0) widget_id =
  finish tx_kind_set_property (fun b ->
      Buffer.add_int64_le b widget_id;
      Buffer.add_int32_le b (Int32.of_int prop_source);
      Buffer.add_int32_le b (Int32.of_int source_element);
      Buffer.add_int32_le b (Int32.of_int level);
      Buffer.add_int32_le b (Int32.of_int field))

(* set_property with a constant grow value. *)
let tx_set_grow widget_id grow =
  finish tx_kind_set_property (fun b ->
      Buffer.add_int64_le b widget_id;
      Buffer.add_int32_le b (Int32.of_int prop_grow);
      Buffer.add_int32_le b (Int32.of_int source_const);
      encode_value b (F64 grow))

(* set_property with a signal-bound grow value. *)
let tx_bind_grow widget_id signal_id =
  finish tx_kind_set_property (fun b ->
      Buffer.add_int64_le b widget_id;
      Buffer.add_int32_le b (Int32.of_int prop_grow);
      Buffer.add_int32_le b (Int32.of_int source_signal);
      Buffer.add_int64_le b signal_id)

(* set_property bound to one field of the element of the enclosing
   For, `level` Fors up (0 = nearest; field 0 for a scalar). *)
let tx_bind_grow_element ?(level = 0) ?(field = 0) widget_id =
  finish tx_kind_set_property (fun b ->
      Buffer.add_int64_le b widget_id;
      Buffer.add_int32_le b (Int32.of_int prop_grow);
      Buffer.add_int32_le b (Int32.of_int source_element);
      Buffer.add_int32_le b (Int32.of_int level);
      Buffer.add_int32_le b (Int32.of_int field))

(* set_property with a constant spacing value. *)
let tx_set_spacing widget_id spacing =
  finish tx_kind_set_property (fun b ->
      Buffer.add_int64_le b widget_id;
      Buffer.add_int32_le b (Int32.of_int prop_spacing);
      Buffer.add_int32_le b (Int32.of_int source_const);
      encode_value b (F64 spacing))

(* set_property with a signal-bound spacing value. *)
let tx_bind_spacing widget_id signal_id =
  finish tx_kind_set_property (fun b ->
      Buffer.add_int64_le b widget_id;
      Buffer.add_int32_le b (Int32.of_int prop_spacing);
      Buffer.add_int32_le b (Int32.of_int source_signal);
      Buffer.add_int64_le b signal_id)

(* set_property bound to one field of the element of the enclosing
   For, `level` Fors up (0 = nearest; field 0 for a scalar). *)
let tx_bind_spacing_element ?(level = 0) ?(field = 0) widget_id =
  finish tx_kind_set_property (fun b ->
      Buffer.add_int64_le b widget_id;
      Buffer.add_int32_le b (Int32.of_int prop_spacing);
      Buffer.add_int32_le b (Int32.of_int source_element);
      Buffer.add_int32_le b (Int32.of_int level);
      Buffer.add_int32_le b (Int32.of_int field))

(* set_property with a constant align value. *)
let tx_set_align widget_id align =
  finish tx_kind_set_property (fun b ->
      Buffer.add_int64_le b widget_id;
      Buffer.add_int32_le b (Int32.of_int prop_align);
      Buffer.add_int32_le b (Int32.of_int source_const);
      encode_value b (I64 align))

(* set_property with a signal-bound align value. *)
let tx_bind_align widget_id signal_id =
  finish tx_kind_set_property (fun b ->
      Buffer.add_int64_le b widget_id;
      Buffer.add_int32_le b (Int32.of_int prop_align);
      Buffer.add_int32_le b (Int32.of_int source_signal);
      Buffer.add_int64_le b signal_id)

(* set_property bound to one field of the element of the enclosing
   For, `level` Fors up (0 = nearest; field 0 for a scalar). *)
let tx_bind_align_element ?(level = 0) ?(field = 0) widget_id =
  finish tx_kind_set_property (fun b ->
      Buffer.add_int64_le b widget_id;
      Buffer.add_int32_le b (Int32.of_int prop_align);
      Buffer.add_int32_le b (Int32.of_int source_element);
      Buffer.add_int32_le b (Int32.of_int level);
      Buffer.add_int32_le b (Int32.of_int field))

(* set_property with a constant indeterminate value. *)
let tx_set_indeterminate widget_id indeterminate =
  finish tx_kind_set_property (fun b ->
      Buffer.add_int64_le b widget_id;
      Buffer.add_int32_le b (Int32.of_int prop_indeterminate);
      Buffer.add_int32_le b (Int32.of_int source_const);
      encode_value b (Bool indeterminate))

(* set_property with a signal-bound indeterminate value. *)
let tx_bind_indeterminate widget_id signal_id =
  finish tx_kind_set_property (fun b ->
      Buffer.add_int64_le b widget_id;
      Buffer.add_int32_le b (Int32.of_int prop_indeterminate);
      Buffer.add_int32_le b (Int32.of_int source_signal);
      Buffer.add_int64_le b signal_id)

(* set_property bound to one field of the element of the enclosing
   For, `level` Fors up (0 = nearest; field 0 for a scalar). *)
let tx_bind_indeterminate_element ?(level = 0) ?(field = 0) widget_id =
  finish tx_kind_set_property (fun b ->
      Buffer.add_int64_le b widget_id;
      Buffer.add_int32_le b (Int32.of_int prop_indeterminate);
      Buffer.add_int32_le b (Int32.of_int source_element);
      Buffer.add_int32_le b (Int32.of_int level);
      Buffer.add_int32_le b (Int32.of_int field))

(* set_property with a constant columns value. *)
let tx_set_columns widget_id columns =
  finish tx_kind_set_property (fun b ->
      Buffer.add_int64_le b widget_id;
      Buffer.add_int32_le b (Int32.of_int prop_columns);
      Buffer.add_int32_le b (Int32.of_int source_const);
      encode_value b (F64 columns))

(* set_property with a signal-bound columns value. *)
let tx_bind_columns widget_id signal_id =
  finish tx_kind_set_property (fun b ->
      Buffer.add_int64_le b widget_id;
      Buffer.add_int32_le b (Int32.of_int prop_columns);
      Buffer.add_int32_le b (Int32.of_int source_signal);
      Buffer.add_int64_le b signal_id)

(* set_property bound to one field of the element of the enclosing
   For, `level` Fors up (0 = nearest; field 0 for a scalar). *)
let tx_bind_columns_element ?(level = 0) ?(field = 0) widget_id =
  finish tx_kind_set_property (fun b ->
      Buffer.add_int64_le b widget_id;
      Buffer.add_int32_le b (Int32.of_int prop_columns);
      Buffer.add_int32_le b (Int32.of_int source_element);
      Buffer.add_int32_le b (Int32.of_int level);
      Buffer.add_int32_le b (Int32.of_int field))

(* set_property with a constant a11y_id value. *)
let tx_set_a11y_id widget_id a11y_id =
  finish tx_kind_set_property (fun b ->
      Buffer.add_int64_le b widget_id;
      Buffer.add_int32_le b (Int32.of_int prop_a11y_id);
      Buffer.add_int32_le b (Int32.of_int source_const);
      encode_value b (Str a11y_id))

(* set_property with a signal-bound a11y_id value. *)
let tx_bind_a11y_id widget_id signal_id =
  finish tx_kind_set_property (fun b ->
      Buffer.add_int64_le b widget_id;
      Buffer.add_int32_le b (Int32.of_int prop_a11y_id);
      Buffer.add_int32_le b (Int32.of_int source_signal);
      Buffer.add_int64_le b signal_id)

(* set_property bound to one field of the element of the enclosing
   For, `level` Fors up (0 = nearest; field 0 for a scalar). *)
let tx_bind_a11y_id_element ?(level = 0) ?(field = 0) widget_id =
  finish tx_kind_set_property (fun b ->
      Buffer.add_int64_le b widget_id;
      Buffer.add_int32_le b (Int32.of_int prop_a11y_id);
      Buffer.add_int32_le b (Int32.of_int source_element);
      Buffer.add_int32_le b (Int32.of_int level);
      Buffer.add_int32_le b (Int32.of_int field))

(* set_property with a constant a11y_label value. *)
let tx_set_a11y_label widget_id a11y_label =
  finish tx_kind_set_property (fun b ->
      Buffer.add_int64_le b widget_id;
      Buffer.add_int32_le b (Int32.of_int prop_a11y_label);
      Buffer.add_int32_le b (Int32.of_int source_const);
      encode_value b (Str a11y_label))

(* set_property with a signal-bound a11y_label value. *)
let tx_bind_a11y_label widget_id signal_id =
  finish tx_kind_set_property (fun b ->
      Buffer.add_int64_le b widget_id;
      Buffer.add_int32_le b (Int32.of_int prop_a11y_label);
      Buffer.add_int32_le b (Int32.of_int source_signal);
      Buffer.add_int64_le b signal_id)

(* set_property bound to one field of the element of the enclosing
   For, `level` Fors up (0 = nearest; field 0 for a scalar). *)
let tx_bind_a11y_label_element ?(level = 0) ?(field = 0) widget_id =
  finish tx_kind_set_property (fun b ->
      Buffer.add_int64_le b widget_id;
      Buffer.add_int32_le b (Int32.of_int prop_a11y_label);
      Buffer.add_int32_le b (Int32.of_int source_element);
      Buffer.add_int32_le b (Int32.of_int level);
      Buffer.add_int32_le b (Int32.of_int field))

(* set_property with a constant a11y_hint value. *)
let tx_set_a11y_hint widget_id a11y_hint =
  finish tx_kind_set_property (fun b ->
      Buffer.add_int64_le b widget_id;
      Buffer.add_int32_le b (Int32.of_int prop_a11y_hint);
      Buffer.add_int32_le b (Int32.of_int source_const);
      encode_value b (Str a11y_hint))

(* set_property with a signal-bound a11y_hint value. *)
let tx_bind_a11y_hint widget_id signal_id =
  finish tx_kind_set_property (fun b ->
      Buffer.add_int64_le b widget_id;
      Buffer.add_int32_le b (Int32.of_int prop_a11y_hint);
      Buffer.add_int32_le b (Int32.of_int source_signal);
      Buffer.add_int64_le b signal_id)

(* set_property bound to one field of the element of the enclosing
   For, `level` Fors up (0 = nearest; field 0 for a scalar). *)
let tx_bind_a11y_hint_element ?(level = 0) ?(field = 0) widget_id =
  finish tx_kind_set_property (fun b ->
      Buffer.add_int64_le b widget_id;
      Buffer.add_int32_le b (Int32.of_int prop_a11y_hint);
      Buffer.add_int32_le b (Int32.of_int source_element);
      Buffer.add_int32_le b (Int32.of_int level);
      Buffer.add_int32_le b (Int32.of_int field))

(* set_window_prop with a constant title value (window 0, the primary surface). *)
let tx_set_window_title window title =
  finish tx_kind_set_window_prop (fun b ->
      Buffer.add_int64_le b window;
      Buffer.add_int32_le b (Int32.of_int wprop_title);
      Buffer.add_int32_le b (Int32.of_int source_const);
      encode_value b (Str title))

(* set_window_prop with a signal-bound title value (window 0, the primary surface). *)
let tx_bind_window_title window signal_id =
  finish tx_kind_set_window_prop (fun b ->
      Buffer.add_int64_le b window;
      Buffer.add_int32_le b (Int32.of_int wprop_title);
      Buffer.add_int32_le b (Int32.of_int source_signal);
      Buffer.add_int64_le b signal_id)

(* set_window_prop with a constant width value (window 0, the primary surface). *)
let tx_set_window_width window width =
  finish tx_kind_set_window_prop (fun b ->
      Buffer.add_int64_le b window;
      Buffer.add_int32_le b (Int32.of_int wprop_width);
      Buffer.add_int32_le b (Int32.of_int source_const);
      encode_value b (F64 width))

(* set_window_prop with a signal-bound width value (window 0, the primary surface). *)
let tx_bind_window_width window signal_id =
  finish tx_kind_set_window_prop (fun b ->
      Buffer.add_int64_le b window;
      Buffer.add_int32_le b (Int32.of_int wprop_width);
      Buffer.add_int32_le b (Int32.of_int source_signal);
      Buffer.add_int64_le b signal_id)

(* set_window_prop with a constant height value (window 0, the primary surface). *)
let tx_set_window_height window height =
  finish tx_kind_set_window_prop (fun b ->
      Buffer.add_int64_le b window;
      Buffer.add_int32_le b (Int32.of_int wprop_height);
      Buffer.add_int32_le b (Int32.of_int source_const);
      encode_value b (F64 height))

(* set_window_prop with a signal-bound height value (window 0, the primary surface). *)
let tx_bind_window_height window signal_id =
  finish tx_kind_set_window_prop (fun b ->
      Buffer.add_int64_le b window;
      Buffer.add_int32_le b (Int32.of_int wprop_height);
      Buffer.add_int32_le b (Int32.of_int source_signal);
      Buffer.add_int64_le b signal_id)

(* set_window_prop with a constant veto_close value (window 0, the primary surface). *)
let tx_set_window_veto_close window veto_close =
  finish tx_kind_set_window_prop (fun b ->
      Buffer.add_int64_le b window;
      Buffer.add_int32_le b (Int32.of_int wprop_veto_close);
      Buffer.add_int32_le b (Int32.of_int source_const);
      encode_value b (Bool veto_close))

(* set_window_prop with a signal-bound veto_close value (window 0, the primary surface). *)
let tx_bind_window_veto_close window signal_id =
  finish tx_kind_set_window_prop (fun b ->
      Buffer.add_int64_le b window;
      Buffer.add_int32_le b (Int32.of_int wprop_veto_close);
      Buffer.add_int32_le b (Int32.of_int source_signal);
      Buffer.add_int64_le b signal_id)

(* set_window_prop with a constant sections_presentation value (window 0, the primary surface). *)
let tx_set_window_sections_presentation window sections_presentation =
  finish tx_kind_set_window_prop (fun b ->
      Buffer.add_int64_le b window;
      Buffer.add_int32_le b (Int32.of_int wprop_sections_presentation);
      Buffer.add_int32_le b (Int32.of_int source_const);
      encode_value b (I64 sections_presentation))

(* set_window_prop with a signal-bound sections_presentation value (window 0, the primary surface). *)
let tx_bind_window_sections_presentation window signal_id =
  finish tx_kind_set_window_prop (fun b ->
      Buffer.add_int64_le b window;
      Buffer.add_int32_le b (Int32.of_int wprop_sections_presentation);
      Buffer.add_int32_le b (Int32.of_int source_signal);
      Buffer.add_int64_le b signal_id)

(* set_window_prop with a constant list_detail value (window 0, the primary surface). *)
let tx_set_window_list_detail window list_detail =
  finish tx_kind_set_window_prop (fun b ->
      Buffer.add_int64_le b window;
      Buffer.add_int32_le b (Int32.of_int wprop_list_detail);
      Buffer.add_int32_le b (Int32.of_int source_const);
      encode_value b (Bool list_detail))

(* set_window_prop with a signal-bound list_detail value (window 0, the primary surface). *)
let tx_bind_window_list_detail window signal_id =
  finish tx_kind_set_window_prop (fun b ->
      Buffer.add_int64_le b window;
      Buffer.add_int32_le b (Int32.of_int wprop_list_detail);
      Buffer.add_int32_le b (Int32.of_int source_signal);
      Buffer.add_int64_le b signal_id)

(* set_entry_prop with a constant title value. *)
let tx_set_entry_title entry title =
  finish tx_kind_set_entry_prop (fun b ->
      Buffer.add_int64_le b entry;
      Buffer.add_int32_le b (Int32.of_int eprop_title);
      Buffer.add_int32_le b (Int32.of_int source_const);
      encode_value b (Str title))

(* set_entry_prop with a signal-bound title value. *)
let tx_bind_entry_title entry signal_id =
  finish tx_kind_set_entry_prop (fun b ->
      Buffer.add_int64_le b entry;
      Buffer.add_int32_le b (Int32.of_int eprop_title);
      Buffer.add_int32_le b (Int32.of_int source_signal);
      Buffer.add_int64_le b signal_id)

(* set_entry_prop with a constant intercept_back value. *)
let tx_set_entry_intercept_back entry intercept_back =
  finish tx_kind_set_entry_prop (fun b ->
      Buffer.add_int64_le b entry;
      Buffer.add_int32_le b (Int32.of_int eprop_intercept_back);
      Buffer.add_int32_le b (Int32.of_int source_const);
      encode_value b (Bool intercept_back))

(* set_entry_prop with a signal-bound intercept_back value. *)
let tx_bind_entry_intercept_back entry signal_id =
  finish tx_kind_set_entry_prop (fun b ->
      Buffer.add_int64_le b entry;
      Buffer.add_int32_le b (Int32.of_int eprop_intercept_back);
      Buffer.add_int32_le b (Int32.of_int source_signal);
      Buffer.add_int64_le b signal_id)

(* set_section_prop with a constant title value. *)
let tx_set_section_title section title =
  finish tx_kind_set_section_prop (fun b ->
      Buffer.add_int64_le b section;
      Buffer.add_int32_le b (Int32.of_int sprop_title);
      Buffer.add_int32_le b (Int32.of_int source_const);
      encode_value b (Str title))

(* set_section_prop with a signal-bound title value. *)
let tx_bind_section_title section signal_id =
  finish tx_kind_set_section_prop (fun b ->
      Buffer.add_int64_le b section;
      Buffer.add_int32_le b (Int32.of_int sprop_title);
      Buffer.add_int32_le b (Int32.of_int source_signal);
      Buffer.add_int64_le b signal_id)

(* set_section_prop with a constant icon value. *)
let tx_set_section_icon section handle =
  finish tx_kind_set_section_prop (fun b ->
      Buffer.add_int64_le b section;
      Buffer.add_int32_le b (Int32.of_int sprop_icon);
      Buffer.add_int32_le b (Int32.of_int source_const);
      encode_value b (Blob handle))

(* set_section_prop with a signal-bound icon value. *)
let tx_bind_section_icon section signal_id =
  finish tx_kind_set_section_prop (fun b ->
      Buffer.add_int64_le b section;
      Buffer.add_int32_le b (Int32.of_int sprop_icon);
      Buffer.add_int32_le b (Int32.of_int source_signal);
      Buffer.add_int64_le b signal_id)

let shortcut_named_keys = [ "enter"; "escape"; "delete"; "left"; "right"; "up"; "down"; "f1"; "f2"; "f3"; "f4"; "f5"; "f6"; "f7"; "f8"; "f9"; "f10"; "f11"; "f12"; "comma"; "period"; "slash"; "backslash"; "minus"; "equal"; "leftbracket"; "rightbracket" ]

(* Canonicalize a shortcut spelling to the wire form: lowercase
   '+'-joined tokens, modifiers ordered primary, shift, alt, then one
   key (a-z, 0-9, or the closed named set). Accepts ASCII case
   variants and any modifier order; raises Invalid_argument on
   whitespace, empty tokens, repeated modifiers, aliases
   (ctrl/cmd/option), and unknown or multiple or missing keys.
   POLICY stays at the core: escape, shift-only and bare
   alphanumerics, and the reserved floor are validated there, on the
   canonical spelling, never rewritten. *)
let canonicalize_shortcut spelling =
  if String.length spelling = 0 then invalid_arg "kaya: shortcut is empty";
  String.iter
    (fun ch ->
      match ch with
      | ' ' | '\t' | '\n' | '\011' | '\012' | '\r' ->
          invalid_arg ("kaya: shortcut \"" ^ spelling ^ "\" contains whitespace")
      | _ -> ())
    spelling;
  let parts = String.split_on_char '+' (String.lowercase_ascii spelling) in
  if List.exists (fun p -> String.length p = 0) parts then
    invalid_arg ("kaya: shortcut \"" ^ spelling ^ "\" has an empty token");
  let rec split_last acc = function
    | [] -> invalid_arg "kaya: shortcut is empty"
    | [ k ] -> (List.rev acc, k)
    | m :: rest -> split_last (m :: acc) rest
  in
  let mods, key = split_last [] parts in
  let has_primary = ref false and has_shift = ref false and has_alt = ref false in
  List.iter
    (fun m ->
      let slot =
        match m with
        | "primary" -> has_primary
        | "shift" -> has_shift
        | "alt" -> has_alt
        | _ ->
            invalid_arg
              ("kaya: shortcut \"" ^ spelling ^ "\" has an unknown modifier \"" ^ m
             ^ "\" (the portable modifiers are primary, shift, alt; aliases like ctrl, cmd, and option are not accepted)")
      in
      if !slot then
        invalid_arg ("kaya: shortcut \"" ^ spelling ^ "\" repeats modifier \"" ^ m ^ "\"");
      slot := true)
    mods;
  let alnum =
    String.length key = 1
    && (match key.[0] with 'a' .. 'z' | '0' .. '9' -> true | _ -> false)
  in
  if (not alnum) && not (List.mem key shortcut_named_keys) then
    invalid_arg
      ("kaya: shortcut \"" ^ spelling ^ "\" key \"" ^ key
     ^ "\" is outside the floor (one of a-z, 0-9, or the closed named set)");
  (if !has_primary then "primary+" else "")
  ^ (if !has_shift then "shift+" else "")
  ^ (if !has_alt then "alt+" else "")
  ^ key

(* set_menu_prop with a constant label value. *)
let tx_set_menu_label item label =
  finish tx_kind_set_menu_prop (fun b ->
      Buffer.add_int64_le b item;
      Buffer.add_int32_le b (Int32.of_int mprop_label);
      Buffer.add_int32_le b (Int32.of_int source_const);
      encode_value b (Str label))

(* set_menu_prop with a signal-bound label value. *)
let tx_bind_menu_label item signal_id =
  finish tx_kind_set_menu_prop (fun b ->
      Buffer.add_int64_le b item;
      Buffer.add_int32_le b (Int32.of_int mprop_label);
      Buffer.add_int32_le b (Int32.of_int source_signal);
      Buffer.add_int64_le b signal_id)

(* set_menu_prop with a constant enabled value. *)
let tx_set_menu_enabled item enabled =
  finish tx_kind_set_menu_prop (fun b ->
      Buffer.add_int64_le b item;
      Buffer.add_int32_le b (Int32.of_int mprop_enabled);
      Buffer.add_int32_le b (Int32.of_int source_const);
      encode_value b (Bool enabled))

(* set_menu_prop with a signal-bound enabled value. *)
let tx_bind_menu_enabled item signal_id =
  finish tx_kind_set_menu_prop (fun b ->
      Buffer.add_int64_le b item;
      Buffer.add_int32_le b (Int32.of_int mprop_enabled);
      Buffer.add_int32_le b (Int32.of_int source_signal);
      Buffer.add_int64_le b signal_id)

(* set_menu_prop with a constant checked value. *)
let tx_set_menu_checked item checked =
  finish tx_kind_set_menu_prop (fun b ->
      Buffer.add_int64_le b item;
      Buffer.add_int32_le b (Int32.of_int mprop_checked);
      Buffer.add_int32_le b (Int32.of_int source_const);
      encode_value b (Bool checked))

(* set_menu_prop with a signal-bound checked value. *)
let tx_bind_menu_checked item signal_id =
  finish tx_kind_set_menu_prop (fun b ->
      Buffer.add_int64_le b item;
      Buffer.add_int32_le b (Int32.of_int mprop_checked);
      Buffer.add_int32_le b (Int32.of_int source_signal);
      Buffer.add_int64_le b signal_id)

(* set_menu_prop with a constant value value. *)
let tx_set_menu_value item value =
  finish tx_kind_set_menu_prop (fun b ->
      Buffer.add_int64_le b item;
      Buffer.add_int32_le b (Int32.of_int mprop_value);
      Buffer.add_int32_le b (Int32.of_int source_const);
      encode_value b (F64 value))

(* set_menu_prop with a signal-bound value value. *)
let tx_bind_menu_value item signal_id =
  finish tx_kind_set_menu_prop (fun b ->
      Buffer.add_int64_le b item;
      Buffer.add_int32_le b (Int32.of_int mprop_value);
      Buffer.add_int32_le b (Int32.of_int source_signal);
      Buffer.add_int64_le b signal_id)

(* set_menu_prop with a constant icon value. *)
let tx_set_menu_icon item handle =
  finish tx_kind_set_menu_prop (fun b ->
      Buffer.add_int64_le b item;
      Buffer.add_int32_le b (Int32.of_int mprop_icon);
      Buffer.add_int32_le b (Int32.of_int source_const);
      encode_value b (Blob handle))

(* set_menu_prop with a constant primary value. *)
let tx_set_menu_primary item primary =
  finish tx_kind_set_menu_prop (fun b ->
      Buffer.add_int64_le b item;
      Buffer.add_int32_le b (Int32.of_int mprop_primary);
      Buffer.add_int32_le b (Int32.of_int source_const);
      encode_value b (Bool primary))

(* set_menu_prop with a constant shortcut value, canonicalized here (the
   one binding-tier shortcut parser — no call site bypasses it). *)
let tx_set_menu_shortcut item shortcut =
  finish tx_kind_set_menu_prop (fun b ->
      Buffer.add_int64_le b item;
      Buffer.add_int32_le b (Int32.of_int mprop_shortcut);
      Buffer.add_int32_le b (Int32.of_int source_const);
      encode_value b (Str (canonicalize_shortcut shortcut)))

(* set_menu_prop with a constant role value. *)
let tx_set_menu_role item role =
  finish tx_kind_set_menu_prop (fun b ->
      Buffer.add_int64_le b item;
      Buffer.add_int32_le b (Int32.of_int mprop_role);
      Buffer.add_int32_le b (Int32.of_int source_const);
      encode_value b (Str role))

(* Reads assembled from a byte accessor (absolute offset -> byte);
   kaya v1 targets are all little-endian. *)
let u16_at byte i = byte i lor (byte (i + 1) lsl 8)
let u32_at byte i = u16_at byte i lor (u16_at byte (i + 2) lsl 16)

(* Decode one value at offset [at]; returns (value, next offset). *)
let parse_value byte at =
  let vtype = u32_at byte at in
  let vlen = u32_at byte (at + 4) in
  let next = at + 8 + ((vlen + 7) land lnot 7) in
  let v =
    if vtype = value_bool then Bool (byte (at + 8) <> 0)
    else if vtype = value_i64 || vtype = value_f64 || vtype = value_blob
    then begin
      let n = ref 0L in
      for i = 7 downto 0 do
        n := Int64.logor (Int64.shift_left !n 8)
               (Int64.of_int (byte (at + 8 + i)))
      done;
      if vtype = value_i64 then I64 !n
      else if vtype = value_blob then Blob !n
      else F64 (Int64.float_of_bits !n)
    end
    else Str (String.init vlen (fun i -> Char.chr (byte (at + 8 + i))))
  in
  (v, next)

(* Decode one occurrence record (header included) through the byte
   accessor. Some (kind, id, keys, payload) — keys is [] when id is
   a widget id, else id is a template node id and keys is the copy's
   key path; payload is Some for text_changed/toggled/value_changed
   (a Str, Bool, or F64
   value), None for clicks. None for pad/unknown kinds. *)
let parse_occurrence byte =
  let kind = u16_at byte 4 in
  if kind <> occ_kind_button_clicked && kind <> occ_kind_text_changed && kind <> occ_kind_toggled && kind <> occ_kind_value_changed && kind <> occ_kind_close_requested && kind <> occ_kind_window_closed && kind <> occ_kind_alert_result && kind <> occ_kind_entry_popped && kind <> occ_kind_back_requested && kind <> occ_kind_section_selected && kind <> occ_kind_menu_activated && kind <> occ_kind_menu_toggled && kind <> occ_kind_menu_value_changed && kind <> occ_kind_file_dialog_result then None
  else begin
    (* ids are guest-allocated and small; the low u32 is the story. *)
    let id = u32_at byte 8 in
    if kind = occ_kind_alert_result
    then
      (* The alert's one answer: id + u32 choice (the alert_choice values). *)
      Some (kind, Int64.of_int id, [], Some (I64 (Int64.of_int (u32_at byte 16))))
    else if kind = occ_kind_file_dialog_result
    then begin
      (* id, a count, then three Values per file (handle, name,
         local_path), FLATTENED into the values slot; the app
         layer regroups them. EMPTY IS CANCEL. *)
      let count = u32_at byte 16 in
      let at = ref 32 in
      let out = ref [] in
      for _ = 1 to count * 3 do
        let v, next = parse_value byte !at in
        out := v :: !out;
        at := next
      done;
      Some (kind, Int64.of_int id, List.rev !out, None)
    end
    (* Surface lifecycle records carry the surface id alone
       ( derived from the record shapes ). *)
    else if kind = occ_kind_close_requested || kind = occ_kind_window_closed || kind = occ_kind_entry_popped || kind = occ_kind_back_requested
    then Some (kind, Int64.of_int id, [], None)
    (* Surface-pair records (window, section): the SECOND id
       keys the handler; the first rides as the payload. *)
    else if kind = occ_kind_section_selected
    then
      Some
        ( kind,
          Int64.of_int (u32_at byte 16),
          [],
          Some (I64 (Int64.of_int id)) )
    else begin
    let path_len = u32_at byte 16 in
    let keys = ref [] in
    let at = ref 24 in
    for _ = 1 to path_len do
      let v, next = parse_value byte !at in
      keys := v :: !keys;
      at := next
    done;
    let payload =
      if kind = occ_kind_text_changed || kind = occ_kind_toggled || kind = occ_kind_value_changed || kind = occ_kind_menu_toggled || kind = occ_kind_menu_value_changed then
        Some (fst (parse_value byte !at))
      else None
    in
    Some (kind, Int64.of_int id, List.rev !keys, payload)
    end
  end
