// Code generated by kaya-gen; DO NOT EDIT.
// Regenerate with `go generate ./...` (tools/gen-guests.sh checks freshness).

package main

import kaya "dev.kaya/bindings/go"

// PostCollection declares the sum collection: one variant per
// constructor, in declaration order — this call is the one
// spelling of that order.
func PostCollection(tx *kaya.Tx) kaya.SumCollection[string, Post] {
	return kaya.SumOf[string, Post](tx, Note{}, Todo{})
}

// PostEachSum is the template eliminator: one required arm per
// constructor — a call must supply every argument, so totality is
// a compile error here, and the scene checks it again. An arm of
// `func(_ kaya.SumCase[...]) {}` renders its constructor as
// nothing, explicitly.
func PostEachSum(
	tx *kaya.Tx,
	c kaya.SumCollection[string, Post],
	note func(kaya.SumCase[string, Note]),
	todo func(kaya.SumCase[string, Todo]),
) kaya.Widget {
	return tx.ForEach(c.Collection, func(t *kaya.Tpl) {
		c.Case[Note](t, note)
		c.Case[Todo](t, todo)
	})
}
