// Code generated by kaya-gen; DO NOT EDIT.
// Regenerate with `go generate ./...` (tools/gen-guests.py checks freshness).

package sliders

import (
	"iter"

	kaya "dev.kaya/bindings/go"
)

// TrackCollection declares the record collection; the struct is the
// schema.
func TrackCollection(tx *kaya.Tx) kaya.RecordCollection[string, Track] {
	return kaya.CollectionOf[string, Track](tx)
}

// TrackPatch opens a named-setter patch on one entry; each setter
// records one update_field — a patch is recorded writes, never a
// diff.
func TrackPatch(c kaya.RecordCollection[string, Track], tx *kaya.Tx, key string) trackPatchBuilder {
	return trackPatchBuilder{c.Patch(tx, key)}
}

type trackPatchBuilder struct {
	p kaya.RecordPatch[string, Track]
}

func (p trackPatchBuilder) Name(v string) trackPatchBuilder {
	p.p.Set(func(t *Track) *string { return &t.Name }, v)
	return p
}

func (p trackPatchBuilder) Level(v float64) trackPatchBuilder {
	p.p.Set(func(t *Track) *float64 { return &t.Level }, v)
	return p
}

// The row surface: one token per wire field, and the template
// constructors that consume them.
type trackRow struct {
	t *kaya.Tpl
	c kaya.RecordCollection[string, Track]
}

func (r trackRow) Name() kaya.Field[string] { return kaya.FieldAt[string](0) }

func (r trackRow) Level() kaya.Field[float64] { return kaya.FieldAt[float64](1) }

func (r trackRow) Row(body func()) kaya.Node { return r.t.Row(body) }

func (r trackRow) Column(body func()) kaya.Node { return r.t.Column(body) }

func (r trackRow) Label(f kaya.Field[string]) kaya.Node { return r.c.Label(r.t, f) }

func (r trackRow) Heading(f kaya.Field[string]) kaya.Node { return r.c.Heading(r.t, f) }

func (r trackRow) Caption(f kaya.Field[string]) kaya.Node { return r.c.Caption(r.t, f) }

func (r trackRow) Image(f kaya.Field[[]byte]) kaya.Node { return r.c.Image(r.t, f) }

func (r trackRow) Checkbox(f kaya.Field[bool], onToggle func(*kaya.Tx, string, bool)) kaya.Node {
	return r.c.Checkbox(r.t, f, onToggle)
}

func (r trackRow) DatePicker(f kaya.Field[kaya.Date], onDate func(*kaya.Tx, string, kaya.Date)) kaya.Node {
	return r.c.DatePicker(r.t, f, onDate)
}

func (r trackRow) TimePicker(f kaya.Field[kaya.Time], onTime func(*kaya.Tx, string, kaya.Time)) kaya.Node {
	return r.c.TimePicker(r.t, f, onTime)
}

func (r trackRow) Slider(min, max float64, f kaya.Field[float64], onChange func(*kaya.Tx, string, float64)) kaya.Node {
	return r.c.Slider(r.t, min, max, f, onChange)
}

// The template props: the const flavors write through the recorder,
// the sourced ones through the typed collection, as the constructors
// above do.
func (r trackRow) SetGrow(n kaya.Node, weight float64) { r.t.SetGrow(n, weight) }

func (r trackRow) SetStep(n kaya.Node, step float64) { r.t.SetStep(n, step) }

func (r trackRow) SetTickSpacing(n kaya.Node, spacing float64) { r.t.SetTickSpacing(n, spacing) }

func (r trackRow) SetA11yID(n kaya.Node, id string) { r.t.SetA11yID(n, id) }

func (r trackRow) A11yID(n kaya.Node, f kaya.Field[string]) { r.c.A11yID(r.t, n, f) }

func (r trackRow) SetA11yLabel(n kaya.Node, label string) { r.t.SetA11yLabel(n, label) }

func (r trackRow) A11yLabel(n kaya.Node, f kaya.Field[string]) { r.c.A11yLabel(r.t, n, f) }

func (r trackRow) SetA11yHint(n kaya.Node, hint string) { r.t.SetA11yHint(n, hint) }

func (r trackRow) A11yHint(n kaya.Node, f kaya.Field[string]) { r.c.A11yHint(r.t, n, f) }

func (r trackRow) SetHelp(n kaya.Node, text string) { r.t.SetHelp(n, text) }

func (r trackRow) Help(n kaya.Node, f kaya.Field[string]) { r.c.Help(r.t, n, f) }

func (r trackRow) SetAccepts(n kaya.Node, kinds ...string) { r.t.SetAccepts(n, kinds...) }

func (r trackRow) SetFill(n kaya.Node, on bool) { r.t.SetFill(n, on) }

func (r trackRow) SetColumnsAuto(n kaya.Node, minWidth float64) { r.t.SetColumnsAuto(n, minWidth) }

func (r trackRow) SetWrap(n kaya.Node, on bool) { r.t.SetWrap(n, on) }

func (r trackRow) Draggable(n kaya.Node) kaya.TplDragRef { return r.t.Draggable(n) }

func (r trackRow) SetDropTarget(n kaya.Node, ops ...kaya.Op) { r.t.SetDropTarget(n, ops...) }

func (r trackRow) SetRole(n kaya.Node, role int64) { r.t.SetRole(n, role) }

func (r trackRow) SetInset(n kaya.Node, pad float64) { r.t.SetInset(n, pad) }

// TrackRows opens the record template as a for statement: the For is
// minted here, the chain declares the table, and the loop body runs
// once with the typed row surface (exact-index tokens, no probes);
// stamping is the core's replay.
func TrackRows(tx *kaya.Tx, c kaya.RecordCollection[string, Track]) *trackRowsFor {
	return &trackRowsFor{tx.Rows(c.Collection), c}
}

// The embedded *kaya.Rows carries Widget(); the two chain methods
// are re-spelled only to keep the typed All() reachable through them.
type trackRowsFor struct {
	*kaya.Rows
	c kaya.RecordCollection[string, Track]
}

func (f *trackRowsFor) Columns(titles []string, sort kaya.Sort) *trackRowsFor {
	f.Rows.Columns(titles, sort)
	return f
}

func (f *trackRowsFor) OnSort(fn func(*kaya.Tx, uint32)) *trackRowsFor {
	f.Rows.OnSort(fn)
	return f
}

func (f *trackRowsFor) All() iter.Seq[trackRow] {
	return func(yield func(trackRow) bool) {
		for row := range f.Rows.All() {
			if !yield(trackRow{t: row.Tpl, c: f.c}) {
				return
			}
		}
	}
}
