#ifndef KAYA_H
#define KAYA_H

/* Generated by cbindgen. Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define REC_PAD 0

#define REC_BUTTON_CLICKED 1

#define HEADER_SIZE 8

#define TX_CREATE_SIGNAL 1

#define TX_WRITE_SIGNAL 2

#define TX_CREATE_WIDGET 3

#define TX_SET_PROPERTY 4

#define TX_ADD_CHILD 5

#define TX_MOUNT 6

#define APPLY_CREATE 1

#define APPLY_SET_PROP 2

#define APPLY_ADD_CHILD 3

#define APPLY_MOUNT 4

#define VALUE_BOOL 1

#define VALUE_I64 2

#define VALUE_F64 3

#define VALUE_STR 4

#define KIND_COLUMN 1

#define KIND_BUTTON 2

#define KIND_LABEL 3

#define PROP_TEXT 1

#define SOURCE_CONST 0

#define SOURCE_SIGNAL 1

/**
 * Occurrence record kinds (the ring, core -> guest).
 */
#define KAYA_OCCURRENCE_PAD 0

#define KAYA_OCCURRENCE_BUTTON_CLICKED 1

/**
 * Transaction record kinds (guest -> core, via kaya_submit). Layouts,
 * after the common 8-byte header, little-endian, 8-aligned:
 *   CREATE_SIGNAL: u64 signal_id, value
 *   WRITE_SIGNAL:  u64 signal_id, value
 *   CREATE_WIDGET: u64 widget_id, u32 kind, u32 pad
 *   SET_PROPERTY:  u64 widget_id, u32 prop, u32 source,
 *                  then value (SOURCE_CONST) or u64 signal_id (SOURCE_SIGNAL)
 *   ADD_CHILD:     u64 parent, u64 child
 *   MOUNT:         u64 window (0 = the default window), u64 root
 * where value is { u32 type, u32 len, payload padded to 8 }.
 */
#define KAYA_TX_CREATE_SIGNAL 1

#define KAYA_TX_WRITE_SIGNAL 2

#define KAYA_TX_CREATE_WIDGET 3

#define KAYA_TX_SET_PROPERTY 4

#define KAYA_TX_ADD_CHILD 5

#define KAYA_TX_MOUNT 6

/**
 * Apply record kinds (core -> presentation pump, via kaya_next_commands).
 * Layouts after the header:
 *   CREATE:    u64 widget_id, u32 kind, u32 pad
 *   SET_PROP:  u64 widget_id, u32 prop, u32 pad, value (always resolved)
 *   ADD_CHILD: u64 parent, u64 child
 *   MOUNT:     u64 window, u64 root
 */
#define KAYA_APPLY_CREATE 1

#define KAYA_APPLY_SET_PROP 2

#define KAYA_APPLY_ADD_CHILD 3

#define KAYA_APPLY_MOUNT 4

/**
 * Value types.
 */
#define KAYA_VALUE_BOOL 1

#define KAYA_VALUE_I64 2

#define KAYA_VALUE_F64 3

#define KAYA_VALUE_STR 4

/**
 * Widget kinds.
 */
#define KAYA_KIND_COLUMN 1

#define KAYA_KIND_BUTTON 2

#define KAYA_KIND_LABEL 3

/**
 * Property keys.
 */
#define KAYA_PROP_TEXT 1

/**
 * set_property sources.
 */
#define KAYA_SOURCE_CONST 0

#define KAYA_SOURCE_SIGNAL 1

typedef struct WindowId WindowId;

typedef struct KayaOccurrence {
  uint16_t kind;
  uint64_t widget_id;
} KayaOccurrence;

/**
 * The occurrence ring's layout, for direct consumers.
 */
typedef struct KayaRingInfo {
  uint8_t *data;
  uint32_t capacity;
  uint32_t *head;
  uint32_t *tail;
} KayaRingInfo;

/**
 * Wire framing of every record, exported through the C header so direct
 * consumers cast a pointer instead of bit-twiddling. Little-endian
 * layout; records are 8-byte aligned, so the payload follows the header
 * at natural alignment.
 */
typedef struct KayaRecordHeader {
  uint32_t size;
  uint16_t kind;
  uint16_t flags;
} KayaRecordHeader;

/**
 * The button-clicked record as it appears on the wire. Constructed by
 * direct consumers casting into the ring, not by Rust code.
 */
typedef struct KayaRecordButtonClicked {
  struct KayaRecordHeader header;
  uint64_t widget_id;
} KayaRecordButtonClicked;

/**
 * The presentation-side functions handed to a guest-language backend.
 * next_commands blocks until a transaction is resolved and fills the
 * buffer with apply-op records (KAYA_APPLY_*); returns the byte length,
 * 0 on shutdown.
 */
typedef struct KayaHostApi {
  void (*emit_button_clicked)(uint64_t);
  uintptr_t (*next_commands)(uint8_t*, uintptr_t);
} KayaHostApi;



extern void *dlopen(const char *path, int flag);

extern void *dlsym(void *handle, const char *symbol);

/**
 * Take over the calling thread, which must be the process main thread,
 * and run the core. Returns when the app exits, with the exit code; the
 * host decides how to terminate its own process.
 */
int32_t kaya_run(void);

/**
 * Submit one transaction: `len` bytes of records at `records`, applied
 * atomically on the UI thread. The buffer is copied before this call
 * returns. Malformed records are a broken binding and fail loudly.
 */
void kaya_submit(const uint8_t *records, uintptr_t len);

/**
 * Function-floor consumption: block until the next occurrence and write
 * it to `out`. Returns false when the core has shut down. Call from a
 * single app thread, and do not mix with direct ring access.
 */
bool kaya_next_occurrence(struct KayaOccurrence *out);

/**
 * Direct-access setup: the occurrence ring's memory layout. Pointers
 * remain valid for the life of the process.
 */
void kaya_occurrence_ring(struct KayaRingInfo *out);

/**
 * Direct-access waiting: block until the ring is non-empty. Returns
 * false when the core has shut down and the ring is drained.
 */
bool kaya_wait_occurrences(void);

/**
 * Presentation side: emit a button-clicked occurrence, exactly as a
 * backend's action handler would. Do not combine with kaya_run.
 */
void kaya_emit_button_clicked(uint64_t widget_id);

/**
 * Presentation side: block until the next transaction, resolve it
 * through the scene, and write the apply-op records into `buf`.
 * Returns the byte length written, or 0 when the core has shut down.
 * Call from a single pump thread with a buffer of at least 64 KiB;
 * an overflowing batch fails loudly.
 */
uintptr_t kaya_next_commands(uint8_t *buf, uintptr_t cap);

#endif  /* KAYA_H */
